import {readFile} from 'node:fs/promises';
import {isDeepStrictEqual} from 'node:util';
import {plan,evidence,clean,val,fval,fixed,pn,attr,op,add,mul,behavior,life,begin,parameter,data,literal,coefficient,formula,result,effect,damage,manaEffect,castProcess,hit,pending,exclude,attributeEffect,common,runtime,activeBuff,rule,champion,cooldown} from './英雄候选.mjs';
export {plan};
function interpolation(x,key,name,part){if(!Number.isFinite(part.mStartValue)||!Number.isFinite(part.mEndValue))throw Error('插值端点缺失');const a=Array.from({length:18},(_,i)=>Math.round((clean(part.mStartValue)+(clean(part.mEndValue)-clean(part.mStartValue))*i/17)*1e9)/1e9);parameter(x,key,name,a,'当前完整计算树的1至18级线性插值，端点均明确。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,raw:part,values:a,source:'完整计算树等级插值'});}
function growth(x,key,name,part){if(!Number.isFinite(part.mLevel1Value)||!Number.isFinite(part.mInitialBonusPerLevel))throw Error('逐级增长缺失');let value=part.mLevel1Value,step=part.mInitialBonusPerLevel;const a=[clean(value)];for(let level=2;level<=18;level++){for(const b of part.mBreakpoints??[])if(b.mLevel===level){if(b.mBonusPerLevelAtAndAfter!=null)step=b.mBonusPerLevelAtAndAfter;value+=b.mAdditionalBonusAtThisLevel??0;}value+=step;a.push(clean(value));}parameter(x,key,name,a,'当前完整计算树按初始每级增量和各等级起新增量展开1至18级。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,raw:part,values:a,source:'完整计算树逐级增长断点'});}
function apDamage(x,base='BaseDamage',ap='APRatio',calc='TotalDamage'){data(x,base,'base_damage','基础伤害');if(ap)data(x,ap,'ap_ratio','法强倍率');else coefficient(x,calc,1,'ap_ratio','法强倍率');const expression=add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power')));formula(x,'damage',x.c.name+'基础伤害',expression,'当前根'+calc+'：基础伤害+法强倍率×总法强。');return expression;}
function sourceShield(x,key,name,formulaKey,duration){effect(x,key,name,[result('shield','自身护盾','NORMAL_SHIELD','SOURCE',fval(formulaKey),{absorbedDamageTypeKey:null,decayMode:'NONE'},behavior)],life(val(duration)),'自身普通护盾；仅本效果来源实例刷新，不代替额外护盾的叠加语义。');}
function ownDamageHeal(x,key,name,formulaKey){effect(x,key,name,[result('heal','回复自身生命','DIRECT_HEAL','SOURCE',fval(formulaKey),{})]);}

{
 const x=begin('ahri_p');interpolation(x,'champion_base_heal','吞噬英雄魂魄基础治疗',x.p.mSpellCalculations.ChampionHeal.mFormulaParts[0]);coefficient(x,'ChampionHeal',1,'ap_ratio','英雄魂魄治疗法强倍率');data(x,'TakedownWindow','recent_damage_window_ms','近期伤害英雄魂魄窗口（毫秒）',{scale:1000});formula(x,'champion_heal','英雄魂魄治疗',add(pn('champion_base_heal'),mul(pn('ap_ratio'),attr('ability_power'))),'ChampionHeal：等级75至165+0.3AP。');ownDamageHeal(x,'champion_soul_heal','吞噬英雄魂魄治疗','champion_heal');pending(x,'英雄魂魄死亡因果与R续用','目标是近期3秒本人伤害过的英雄死亡；不能任意KILL或任何英雄死亡即治疗。还须向R发送合法吞噬事件。');exclude(x,'击杀小兵野怪9层回血','本轮单英雄对手不含小兵野怪来源支路；英雄魂魄治疗保留。');
}
{
 const x=begin('ahri_q');common(x,{cast:true});apDamage(x,'BaseDamage',null);damage(x,'outgoing_orb','宝珠去程魔法伤害','damage');damage(x,'returning_orb','宝珠返程真实伤害','damage','real');castProcess(x);pending(x,'方向与实际命中事件','去程和返程分别判定，HIT_INDEX是命中序号，不能拿1/2冒充方向：去程未中而返程首次命中时仍应真实伤害。等待可证明的阶段来源再接两效果。');exclude(x,'多目标和回程空间路径','仅后置空间搜索，不排除返程当前目标真实伤害。');
}
{
 const x=begin('ahri_w');common(x,{cast:true});const base=apDamage(x,'BaseDamage','APRatio','SingleFireDamage');data(x,'RepeatDamageMod','repeat_damage_ratio','同目标后续狐火伤害倍率');data(x,'MovementSpeed','initial_speed_ratio','狐火初始移动速度比例');data(x,'MovementSpeedDuration','speed_decay_duration_ms','移速衰减时长（毫秒）',{scale:1000});data(x,'InitialDelay','initial_fire_delay_ms','首团狐火延迟（毫秒）',{scale:1000});data(x,'SecondaryDelay','secondary_fire_delay_ms','后续狐火延迟原值（毫秒）',{scale:1000});data(x,'FlameDuration','fire_duration_ms','狐火存留时长（毫秒）',{scale:1000});literal(x,'fire_count','狐火数量',3,'当前官方与根AhriFoxFire文本明确3团狐火。','official.tooltip + Spell_AhriFoxFire_Tooltip');formula(x,'repeat_damage','同目标后续狐火伤害',mul(base,pn('repeat_damage_ratio')),'MultiFireDamage完整修改树为首团×0.4；不使用旧别名文本的30%。');damage(x,'first_fox_fire','同目标首团狐火伤害','damage');damage(x,'repeat_fox_fire','同目标后续狐火伤害','repeat_damage');castProcess(x);pending(x,'狐火命中计数与移速衰减','需本次施放对当前目标首个/后续命中及火焰实际命中，不将施放必定打满3团。40%移速在2秒衰减，不能写恒定效果。');exclude(x,'目标优先级、小兵低血量增伤','多对象选择与小兵特供跳过，单英雄伤害分支保留。');
}
{
 const x=begin('ahri_e');common(x,{cast:true});apDamage(x);data(x,'CharmDuration','charm_duration_ms','魅惑时长（毫秒）',{scale:1000});data(x,'SlowPercent','charm_slow_ratio','魅惑期间移速降低比例',{scale:-1});damage(x,'charm_hit','魅惑命中魔法伤害','damage');castProcess(x);hit(x,'charm_hit');pending(x,'魅惑与中断位移','当前仅眩晕目录，不能用眩晕代替向来源移动的魅惑；需要中断位移及魅惑行为和65%减速正确组合。');
}
{
 const x=begin('ahri_r');common(x);apDamage(x,'RBaseDamage','RAPCoefficient','RCalculatedDamage');data(x,'RRecastWindow','recast_window_ms','首次再次施放窗口（毫秒）',{scale:1000});data(x,'RMaxCasts','maximum_stored_casts','最多储存施放次数');data(x,'RDashCooldown','between_dash_lockout_ms','连续突袭间隔锁定（毫秒）',{scale:1000});data(x,'RResetCasts','soul_granted_casts','吞噬英雄魂魄补充次数');data(x,'PDurationExtension','soul_window_extension_ms','吞噬魂魄续用窗口上限（毫秒）',{scale:1000});damage(x,'spirit_bolt_hit','一次突袭命中灵魄弹','damage');hit(x,'spirit_bolt_hit');pending(x,'首施放成本冷却与限次重施放','现RECAST支持窗口/次数，但还需每次1秒间隔、P补1次且储存最多3次及窗口延长至10秒的组合；不直接重施放付100法力或每次启动基础冷却。');exclude(x,'三目标发射与突袭空间路径','每次最多打三个对象不等于同一目标三发；单英雄每次只保留一颗灵魄弹。');
}
{
 const x=begin('darius_p');interpolation(x,'bleed_base_total','每层完整出血基础伤害',x.p.mSpellCalculations.BleedDamagePerStack.mFormulaParts[0]);literal(x,'bonus_ad_ratio','每层出血额外攻击力倍率',clean(x.p.mSpellCalculations.BleedDamagePerStack.mFormulaParts[1].mCoefficient),'BleedDamagePerStack mStat=2、mStatFormula=2，额外AD系数0.3。','mSpellCalculations.BleedDamagePerStack');data(x,'BleedDuration','bleed_duration_ms','出血与血怒持续（毫秒）',{scale:1000});data(x,'SecondsPerTick','raw_bleed_tick_interval_ms','客户端出血周期原值（毫秒）',{scale:1000});data(x,'MaxStacks','max_stacks','出血层数上限');growth(x,'noxian_might_bonus_ad','血怒额外攻击力',x.p.mSpellCalculations.NoxianMightBonusAD.mFormulaParts[0]);formula(x,'bleed_total_per_stack','每层5秒出血总量',add(pn('bleed_base_total'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'完整BleedDamagePerStack是5秒总伤害，不是每次周期伤害。');attributeEffect(x,'noxian_might','血怒攻击力','noxian_might_bonus_ad','attack_damage',val('bleed_duration_ms'));pending(x,'出血周期、血怒与跨技能应用','5秒总量与周期原值1.26秒不能推成每次总量或猜4次均分。满5层/被R击杀获得血怒，后续攻击和伤害技能施加5层；Q斧柄不叠，R取命中前层数，均待合法事件及顺序。');exclude(x,'野怪2.5倍出血','固定英雄对手不使用MonsterMod。');
}
{
 const x=begin('darius_q');common(x);data(x,'BaseDamage','base_damage','斧刃基础伤害');data(x,'TotalADRatio','total_ad_ratio','斧刃总攻击力倍率',{scale:.01});data(x,'InnerCircleDamagePercent','handle_ratio','斧柄伤害倍率',{scale:.01});data(x,'MissingHealthHeal','missing_hp_heal_ratio','每个英雄斧刃命中回复比例',{scale:.01});formula(x,'blade_damage','斧刃伤害',add(pn('base_damage'),mul(pn('total_ad_ratio'),attr('attack_damage'))),'BladeDamage当前总AD倍率100/110/120/130/140%。');formula(x,'handle_damage','斧柄伤害',mul(add(pn('base_damage'),mul(pn('total_ad_ratio'),attr('attack_damage'))),pn('handle_ratio')),'斧柄是斧刃35%，不能施加出血。');formula(x,'blade_heal','单英雄斧刃命中治疗',mul(pn('missing_hp_heal_ratio'),attr('hp','SOURCE','MISSING')),'单英雄命中回复来源已损失生命17%；不固定使用最大生命或多对象51%上限。');damage(x,'blade_hit','斧刃命中物理伤害','blade_damage','physics');damage(x,'handle_hit','斧柄命中物理伤害','handle_damage','physics');ownDamageHeal(x,'blade_heal','斧刃命中自身治疗','blade_heal');pending(x,'内外圈命中与施放延迟','需真实斧刃/斧柄来源分支，斧刃才治疗和出血；mCastTime0.2344与spellCastTime0.25不构成完整挥斧延迟证据，不能假定施法结束命中。');exclude(x,'野怪与多对象治疗','保留当前一名英雄17%已损失生命治疗，多对象51%不套给单人。');
}
{
 const x=begin('darius_w');common(x);data(x,'ADRatio','empowered_total_ad_ratio','强化攻击总伤害倍率');data(x,'SlowPercent','slow_ratio','强化攻击减速比例',{scale:.01});data(x,'SlowDuration','slow_duration_ms','减速持续（毫秒）',{scale:1000});data(x,'PercentCDRefund','kill_cooldown_refund_ratio','本技能击杀冷却返还比例',{scale:.01});literal(x,'normal_attack_ratio','普通攻击基础倍率',1,'强化攻击是总攻击伤害1.4至1.6倍，独立额外部分要扣除普通攻击1倍。','EmpoweredAttackDamage + 普攻基础部分');formula(x,'empowered_attack_damage','强化攻击未暴击总伤害',mul(pn('empowered_total_ad_ratio'),attr('attack_damage')),'完整EmpoweredAttackDamage，不在普通攻击伤害之外再附加整份。');formula(x,'bonus_attack_damage','强化攻击未暴击额外部分',mul(op('SUBTRACT',pn('empowered_total_ad_ratio'),pn('normal_attack_ratio')),attr('attack_damage')),'只表达未暴击额外0.4/0.45/0.5/0.55/0.6总AD。暴击组合待核，不作为完整强化攻击链。');damage(x,'noncritical_bonus','强化攻击未暴击额外伤害','bonus_attack_damage','physics',{delivery:'BASIC_ATTACK',block:null});effect(x,'kill_mana_refund','致残打击击杀返还法力',[result('refund','返还本次消耗','RESOURCE_CHANGE','SOURCE',val('mana_cost'),{attributeKey:'mana',operation:'REFUND'})]);pending(x,'强化普攻过程、暴击及击杀因果','现有EMPOWERED_BASIC_ATTACK可以消费下一次攻击，但当前根没有明确等待窗口；不能猜时限。还需普攻重置、未暴击/暴击额外部分组合、伤害时技能特效与本次W导致击杀才退款/减50%冷却。');
}
{
 const x=begin('darius_e');common(x,{cast:true});data(x,'PassivePercentArmorPen','armor_penetration_ratio','被动百分比护甲穿透',{scale:.01});data(x,'SlowPercent','slow_ratio','拖拽后减速比例',{scale:.01});data(x,'SlowDuration','slow_duration_ms','减速持续（毫秒）',{scale:1000});castProcess(x);pending(x,'百分比穿透组合','当前20/25/30/35/40%穿透来源应按正确剩余护甲组合，已有40%与本技能20%为52%，不能固定加为60%。现目录仅固定加算和比例加成，先不写错误效果。','系统');pending(x,'拖拽/击飞与减速','不能用已有眩晕代替拖拽击飞；不把施法结束当必定拉中。');
}
{
 const x=begin('darius_r');common(x);data(x,'RBaseDamage','base_damage','断头台基础真实伤害');literal(x,'bonus_ad_ratio','断头台额外攻击力倍率',.75,'Damage计算树额外攻击力系数0.75。','mSpellCalculations.Damage');data(x,'RDamagePercentPerHemoStack','per_bleed_stack_ratio','每层出血伤害增幅');data(x,'RRecastDuration','kill_recast_window_ms','1至2级击杀重施放窗口（毫秒）',{scale:1000});literal(x,'max_bleed_stacks','读取出血层数上限',5,'当前P MaxStacks=5，R MaximumDamage=基础量2倍，与每层20%一致。','DariusP.MaxStacks + MaximumDamage');literal(x,'zero_stacks','无出血层数',0,'无出血目标使用基础伤害。','official.tooltip每层额外');literal(x,'one','基础倍率单位值',1,'基础伤害本身1倍，加每层20%。','Damage + RDamagePercentPerHemoStack');runtime(x,'bleed_stacks','命中前实际出血层数','读取当前目标由本来源施加的命中前出血层数0至5；不默认满层，R伤害后的P应用不能提前计入。');const base=add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),stacks=op('MIN',pn('max_bleed_stacks'),op('MAX',pn('zero_stacks'),pn('bleed_stacks')));formula(x,'base_damage','无出血断头台伤害',base,'当前Damage基础125/250/375+0.75额外AD。');formula(x,'damage','按实际出血层数断头台伤害',mul(base,add(pn('one'),mul(pn('per_bleed_stack_ratio'),stacks))),'实际层数限定0至5，最多基础2倍真实伤害；这是伤害，不是按生命阈值直接处决。');damage(x,'guillotine_damage','诺克萨斯断头台真实伤害','damage','real');cooldown(x,'rank_three_kill_reset','3级断头台本次击杀完全重置',['darius_r'],'RESET');pending(x,'真实取层、R击杀和分等级刷新','0至5层公式及3级真实0法力已录。命中取P旧层、本次R造成击杀才触发：1/2级20秒重施放、3级完全刷新，还要联动血怒；未建任意KILL退款。施法时长0.25/0.3667冲突暂不固定。');
}
{
 const x=begin('diana_p');growth(x,'cleave_base_damage','第三次攻击基础魔法伤害',x.p.mSpellCalculations.CleaveDamage.mFormulaParts[0]);data(x,'APRatio','ap_ratio','第三次攻击法强倍率');interpolation(x,'passive_attack_speed_ratio','常态额外攻击速度',x.p.mSpellCalculations.BonusAS.mFormulaParts[0]);data(x,'BuffDuration','empowered_duration_ms','施法后强化攻速持续（毫秒）',{scale:1000});data(x,'AttackCount','cleave_attack_count','顺劈所需攻击次数');literal(x,'additional_as_multiplier','施法后额外攻速份数',2,'EmpoweredAS=常态3倍；常态仍存在，因此临时只额外加2倍。','mSpellCalculations.EmpoweredAS.mMultiplier=3');formula(x,'cleave_damage','第三次攻击顺劈额外伤害',add(pn('cleave_base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),'完整CleaveDamage，等级基础20至220+0.5AP。');formula(x,'additional_attack_speed','施法后临时额外攻速',mul(pn('passive_attack_speed_ratio'),pn('additional_as_multiplier')),'常态+临时=1倍+2倍=3倍。');attributeEffect(x,'passive_attack_speed','月银之刃常态攻速','passive_attack_speed_ratio','bonus_attack_speed_percent',null);effect(x,'cast_attack_speed','施法后月银攻速',[result('attack_speed','临时额外攻速','ATTRIBUTE_CHANGE','SOURCE',fval('additional_attack_speed'),{attributeKey:'bonus_attack_speed_percent',operation:'INCREASE',modifierZoneKey:'attribute_flat_add'},behavior)],life(val('empowered_duration_ms')));damage(x,'cleave_damage','第三次攻击顺劈魔法伤害','cleave_damage','magic',{delivery:'BASIC_ATTACK',block:null});rule(x,'initialize_passive_attack_speed','初始化月银之刃常态攻速',{eventType:'SOURCE_INITIALIZED',detail:{}},['passive_attack_speed']);x.c.write.triggerRules.at(-1).actions[0].targetContext='EVENT_SOURCE';for(const s of ['q','w','e','r'])rule(x,'after_'+s+'_attack_speed','施放'+s.toUpperCase()+'后强化攻速',{eventType:'SKILL_USED',detail:{sourceSkillKey:'diana_'+s,useKind:'ACTIVE'}},['cast_attack_speed']);pending(x,'每第三次攻击计数','现COUNTER/过程状态操作可表示基本计数，仍需核计数持续/重置、攻击开始还是命中、攻击取消或闪避处理，不构造永久计数假定。常态与施法强化攻速规则已独立完成。');exclude(x,'野怪2.7倍和扇形空间搜索','当前英雄顺劈伤害保留。');
}
{
 const x=begin('diana_q');common(x,{cast:true});apDamage(x);data(x,'MoonlightDuration','moonlight_duration_ms','月光标记持续（毫秒）',{scale:1000});damage(x,'moon_arc_hit','月能圆弧命中','damage');castProcess(x);hit(x,'moon_arc_hit');pending(x,'月光与E刷新','月光不是纯视野：同来源目标标记要供E命中前判断和正确消耗/清除，需要真实标记生命周期。');exclude(x,'显形和月弧多目标路径','纯视野与空间搜索后置，E所需月光标记留范围。');
}
{
 const x=begin('diana_w');common(x,{cast:true});apDamage(x,'OrbDamage','OrbAPRatio');data(x,'ShieldBase','base_shield','基础自护盾');data(x,'ShieldAPRatio','shield_ap_ratio','自护盾法强倍率');data(x,'ShieldBHPRatio','shield_bonus_hp_ratio','自护盾额外生命倍率');data(x,'ShieldDuration','shield_duration_ms','护盾和法球持续（毫秒）',{scale:1000});literal(x,'orb_count','护体法球数',3,'官方及当前TotalMaxDamage乘3一致。','official.tooltip + mSpellCalculations.TotalMaxDamage');formula(x,'shield','一次苍白之瀑护盾量',add(pn('base_shield'),mul(pn('shield_ap_ratio'),attr('ability_power')),mul(pn('shield_bonus_hp_ratio'),attr('hp','SOURCE','BONUS'))),'ShieldValue明确额外生命0.11，非总生命；基础45/60/75/90/105+0.3AP+0.11额外HP。');sourceShield(x,'pale_cascade_shield','施放苍白之瀑自护盾','shield','shield_duration_ms');damage(x,'orb_collision','一颗护体法球接触爆炸','damage');activeBuff(x,['pale_cascade_shield'],{delay:true});pending(x,'法球实际爆炸与最后一颗额外护盾','三球接触才造成伤害，最后一颗再加同额护盾并刷新持续；不能首次施放直接给双盾，不能把普通刷新覆盖当剩余护盾加新盾。需同次法球计数和额外护盾合并确认。');
}
{
 const x=begin('diana_e');common(x,{cast:true});apDamage(x);data(x,'CDResetTime','moonlight_reset_delay_ms','月光冷却刷新延迟原值（毫秒）',{scale:1000});damage(x,'lunar_rush_hit','月神冲刺命中','damage');cooldown(x,'moonlight_cooldown_reset','命中已有月光目标重置冲刺',['diana_e'],'RESET');castProcess(x);hit(x,'lunar_rush_hit');pending(x,'月光旧状态判断、消耗与0.25秒刷新','判定目标先前已有本来源月光，核CDResetTime原字段实际时点；不对每次冲刺都重置，也不能因E施放后新标记误判。');exclude(x,'冲刺空间路径','保留当前目标伤害和重置所需组成。');
}
{
 const x=begin('diana_r');common(x,{cast:true});apDamage(x,'Damage',null,'RExplosionDamage');data(x,'Delay','explosion_delay_ms','拉入后爆炸等待（毫秒）',{scale:1000});data(x,'SlowTooltip','slow_ratio','拉入减速比例',{scale:.01});data(x,'SlowDuration','slow_duration_ms','减速持续（毫秒）',{scale:1000});damage(x,'moonfall_explosion','单英雄新月爆炸','damage');castProcess(x);pending(x,'初始拉入与延迟爆炸实际命中','至少拉中一个英雄才生成1秒后爆炸；初始拉入命中不能直接执行后续伤害，等待阶段与实际命中来源。拖拽和减速不由眩晕替代。');exclude(x,'第二名以后英雄增伤和显形','单英雄不加35/60/85+0.15AP的额外多英雄增幅，空间搜索与视野后置。');
}
{
 const x=begin('veigar_p');data(x,'dAbilityStacks','ability_hit_stacks','技能命中英雄所得层数');data(x,'dTakedownStacks','champion_takedown_stacks','参与击杀英雄额外层数');data(x,'dQKillStacks','q_kill_stacks','Q击杀普通单位所得层数');data(x,'PStacksPerDarkMatterCDR','stacks_per_w_cdr','W每档缩冷却所需层数');data(x,'DarkMatterCDRIncrement','w_cdr_increment','W每档冷却缩短比例');literal(x,'ap_per_stack','每层额外法强',1,'APPerStack完整树常数1。','mSpellCalculations.APPerStack');runtime(x,'phenomenal_evil_stacks','已累计超凡邪力层数','真实技能命中、参与击杀和Q击杀累计的非负整数；来源没有上限，不编造最大值。');formula(x,'stack_ability_power','实际超凡邪力层数提供法强',mul(pn('phenomenal_evil_stacks'),pn('ap_per_stack')),'1层=1AP；只表示本被动贡献，不用总法强反推层数。');pending(x,'永久无上限层数及W共享读取','已有COUNTER需填写最大值，当前无法直接无上限。不可任意填999999上限；共享值ADD可累计法强但不能直接当W读取的真实层数来源。需命中英雄与击杀因果规则、逻辑层数可读表达一起补齐。','系统');exclude(x,'大型小兵野怪额外Q层数','Q击杀英雄仍可能包含常规击杀层，保留常规dQKillStacks；大型小兵野怪3层支路不录。');
}
{
 const x=begin('veigar_q');common(x,{cast:true});apDamage(x);damage(x,'baleful_strike_hit','黑暗能量命中','damage');castProcess(x);hit(x,'baleful_strike_hit');pending(x,'P命中与Q击杀额外层数','命中英雄P一层，与本次Q击杀的额外一层、参与击杀五层应按源规则组合，不能重复或漏记；不得用任意击杀判定本次Q。');exclude(x,'第二对象和大型小兵野怪层数','只保留当前敌方英雄。');
}
{
 const x=begin('veigar_w');common(x,{cast:true});apDamage(x);data(x,'BaseCooldown','base_cooldown_ms','零被动层数基础冷却（毫秒）',{scale:1000});data(x,'ImpactDelay','impact_delay_ms','黑暗物质落下延迟（毫秒）',{scale:1000});damage(x,'dark_matter_hit','黑暗物质实际命中','damage');hit(x,'dark_matter_hit');pending(x,'P层数冷却与施法过程接线','官方/主cooldown=0是动态占位，BaseCooldown=8秒才是基础。每50层减少10%的具体档位/叠加关系及P真实层数读取待证；不能建0冷却过程，也不能把固定8秒当有层数时最终冷却。250毫秒施法与成本已存，落下1.2秒不能当必定命中。');
}
{
 const x=begin('veigar_e');common(x,{cast:true});data(x,'StunDuration','stun_duration_ms','事件视界眩晕时长（毫秒）',{scale:1000});data(x,'CageDelay','cage_delay_ms','牢笼生成延迟（毫秒）',{scale:1000});literal(x,'cage_duration_ms','牢笼持续（毫秒）',3000,'当前根Spell_VeigarEventHorizon_Tooltip明确持续3秒。','official.tooltip + Spell_VeigarEventHorizon_Tooltip');castProcess(x);pending(x,'牢笼存在与中断位移','真实页面已确认持续目标状态的法术护盾粒度被拒绝：PERSISTENT+TARGET+非空阻挡粒度不可存，null会绕过护盾。APPLICATION+EFFECT没有本次状态归属/期限，用statusKey结束移除会误删别的来源。同一牢笼重复触发来源亦未证；两项未保存，待结构修正后补，不在本轮排除。0.5秒生成和3秒牢笼参数保留。');exclude(x,'牢笼空间路径与多对象搜索','空间生成/搜索后置，单对手真实边缘接触的眩晕保留。');
}
{
 const x=begin('veigar_r');common(x,{cast:true});const base=apDamage(x,'BaseDamage','APRatio','MinDamage');data(x,'MaxExecuteMult','maximum_damage_multiplier','低生命最大伤害倍率');literal(x,'maximum_damage_health_threshold','说明最大伤害当前生命比例',.33,'当前官方/客户端文字为生命33%以下最大伤害，只记录说明阈值；未据此猜连续斜率或精确2/3断点。','official.tooltip + Spell_VeigarR_Tooltip');formula(x,'max_damage','能量爆裂最大伤害',mul(base,pn('maximum_damage_multiplier')),'MaxDamage完整修改树为MinDamage×2。');damage(x,'minimum_burst','满生命基础魔法伤害组成','damage');damage(x,'maximum_burst','低生命上限魔法伤害组成','max_damage');castProcess(x);pending(x,'连续生命值伤害倍率','完整根只包含MinDamage/MaxDamage，33%说明不能单独证明连续关系1+1.5已损生命比例或精确阈值；需冻源补证后接当前生命完整伤害，不把上下限同时执行或永远用最大值。');
}

// 页面生成动作标识，沿用真实表单形状；此规则仍由主负责人页面保存。
// 两个攻速来源均随当前角色等级读取，防止初始化或施放时快照锁住旧等级。
for(const key of ['passive_attack_speed','cast_attack_speed'])plan.skills.diana_p.write.effects.find(e=>e.effectKey===key).results[0].lifecycleBehavior={moment:'PERSISTENT',valueReadMode:'MOMENT_EVALUATION',stackValueMode:'SHARED',reapplicationValueMode:null,periodicExecutionMode:null};
plan.skills.darius_q.pending[0].reason+=' 当前根还标记SpecialCase_DelayedCooldown，基础冷却时长不能证明应从施放开始计时；过程需连同时点一起补证。';
plan.skills.veigar_e.pending.push({kind:'系统',component:'眩晕的行动限制语义',reason:'独立GET /statuses/vertigo 仅含名称、启停和说明，无眩晕类别/行动限制字段；当前状态操作只能据此确认状态标识及持续时间，不能声称已具备禁止移动、攻击、施法的完整控制语义。'});

// 数值一致时复用既有公共参数的完整业务字段，保护名称、说明、顺序。
const before=JSON.parse(await readFile(new URL('./写前现值.json',import.meta.url),'utf8'));
const body=p=>Object.fromEntries(Object.entries(p).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)));
for(const s of Object.values(plan.skills)){
 s.reusedParameters=[];const existing=before.skills[s.skillKey].components.parameters;
 s.write.parameters=s.write.parameters.map(p=>{const prev=existing.find(v=>v.parameterKey===p.parameterKey);if(!prev)return p;const fields=['valueType','valueMode','fixedValue','levelValues'];if(fields.some(k=>!isDeepStrictEqual(p[k],prev[k])))throw Error('公共参数数值不同需单项处置 '+s.skillKey+'/'+p.parameterKey);s.reusedParameters.push(p.parameterKey);return body(prev);});
 s.status='部分范围组成，保存以独立GET为准；待配不是机制完成';
 for(const a of Object.values(s.write)){const keys=a.map(v=>v.parameterKey??v.formulaKey??v.effectKey??v.processKey??v.stateKey??v.ruleKey);if(new Set(keys).size!==keys.length)throw Error('重复键 '+s.skillKey);}
}
