import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import{fileURLToPath}from'node:url';import{verifyMath}from'./独立实值核算.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)),read=n=>JSON.parse(fs.readFileSync(dir+'/'+n)),sha=n=>crypto.createHash('sha256').update(fs.readFileSync(dir+'/'+n)).digest('hex');
assert.equal(sha('最终候选.json'),'71e82f521f48fdb76e16d124f378cc7adc427b9be10c7e166068e079c98d6fc3');assert.equal(sha('最终写入计划.json'),'dead20e1e882ca6c72bced9b3944951d0773684f0c3d063bd0684b5e6316462c');assert.equal(sha('主负责人写前保护.json'),'e9c8efa94bb7c6cfbf56c6a409f846b008480af025882cdd723ae95fb557991e');
const candidate=read('最终候选.json'),plan=read('最终写入计划.json'),before=read('主负责人写前保护.json'),source=read('冻结根绑定与当前文本.json');assert.equal(sha('冻结根绑定与当前文本.json'),'3147c351e63770e1ba828d9887c305226ee451b8ffc4da140187d4e666d07769');assert.equal(plan.requests.length,29);
const mode=process.argv[2]??'--preflight';assert(['--preflight','--apply','--verify'].includes(mode));
const stamp=new Date().toISOString().replaceAll(':','-'),out=dir+'/'+({'--apply':'实际写入','--verify':'独立回读','--preflight':'只读预检'}[mode])+'-'+stamp+'.json',lock=dir+'/写入锁.json',events=[],writes=[];let ownedLock=false;
const clean=x=>{if(Array.isArray(x))return x.map(clean);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)).map(([k,v])=>[k,clean(v)]));return x;};
async function http(method,route,body){let record;try{const response=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer local-entry','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});record={at:new Date().toISOString(),method,route,status:response.status,data:await response.json()};}catch(e){record={at:new Date().toISOString(),method,route,status:'UNKNOWN',error:String(e)};}events.push(record);fs.appendFileSync(out+'.jsonl',JSON.stringify(record)+'\n');return record;}
const kinds=[['parameters','parameters','parameterKey'],['formulas','formulas','formulaKey'],['effects','effects','effectKey'],['processes','processes','processKey'],['internal-states','internalStates','stateKey'],['trigger-rules','triggerRules','ruleKey']];
function listEqual(route,data){const m=route.match(/^\/skills\/(zoe_[pqwer])\/([^/]+)$/);assert(m);const[kind,writeKey,key]=kinds.find(x=>x[0]===m[2]);const expected=candidate.skills[m[1]].write[writeKey],actual=Array.isArray(data)?data:data.items;assert.equal(actual.length,expected.length,route);assert.deepEqual(actual.map(x=>x[key]).sort(),expected.map(x=>x[key]).sort());for(const row of actual){const want=expected.find(x=>x[key]===row[key]);for(const[k,v]of Object.entries(clean(row))){if(k==='lifecycleEnabled')assert.equal(v,!!want.lifecycle);else if(k==='resultCount')assert.equal(v,want.results.length);else assert.deepEqual(v,want[k],route+'/'+k);}}}
async function protect(after){for(const old of before.requests){const got=await http('GET',old.route);assert.equal(got.status,old.status,old.route);if(after&&/^\/skills\/zoe_[pqwer]\/(parameters|formulas|effects|processes|internal-states|trigger-rules)$/.test(old.route))listEqual(old.route,got.data);else assert.deepEqual(got.data,old.data,old.route);}}
let error=null,math=null;try{
 math=verifyMath(candidate.skills,source);
 if(mode==='--apply'){
  fs.writeFileSync(lock,JSON.stringify({state:'STARTED',at:new Date().toISOString(),planSha256:sha('最终写入计划.json')},null,2)+'\n',{flag:'wx'});ownedLock=true;await protect(false);
  for(const req of plan.requests){const absent=await http('GET',req.readRoute);assert.equal(absent.status,404,req.readRoute);const changed=await http('POST',req.route,req.body),fresh=await http('GET',req.readRoute);writes.push({route:req.readRoute,status:changed.status});assert.equal(changed.status,201,req.readRoute);assert.equal(fresh.status,200);assert.deepEqual(clean(fresh.data),clean(req.body),req.readRoute);}
  fs.writeFileSync(lock,JSON.stringify({state:'COMPLETED',at:new Date().toISOString(),writes:writes.length,planSha256:sha('最终写入计划.json')},null,2)+'\n');
 }else if(mode==='--verify'){
  await protect(true);const actual=structuredClone(candidate.skills);
  for(const[skillKey,s]of Object.entries(candidate.skills))for(const[routeKind,writeKey,key]of kinds){actual[skillKey].write[writeKey]=[];for(const row of s.write[writeKey]){const got=await http('GET','/skills/'+skillKey+'/'+routeKind+'/'+row[key]);assert.equal(got.status,200);const expected=structuredClone(row);delete expected.reuse;assert.deepEqual(clean(got.data),clean(expected));actual[skillKey].write[writeKey].push(got.data);}}
  math=verifyMath(actual,source);
 }else await protect(false);
}catch(e){error=String(e);if(ownedLock)fs.writeFileSync(lock,JSON.stringify({state:'ABORTED',at:new Date().toISOString(),writes,error},null,2)+'\n');}
const report={at:new Date().toISOString(),mode,passed:!error,candidateSha256:sha('最终候选.json'),planSha256:sha('最终写入计划.json'),GETs:events.filter(x=>x.method==='GET').length,writes,math,error,events};fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({out,passed:!error,GETs:report.GETs,writes:writes.length,math:math?{checks:math.checks,formulaCases:math.formulaCases,rejections:math.missingInputRejections}:null,error}));if(error)process.exitCode=1;
