import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url)),mode=process.argv[2];assert([undefined,'--apply','--verify'].includes(mode));const read=n=>JSON.parse(fs.readFileSync(dir+'/'+n)),sha=n=>crypto.createHash('sha256').update(fs.readFileSync(dir+'/'+n)).digest('hex'),candidate=read('最终候选.json'),plan=read('最终计划.json'),before=read('写前保护.json');assert.equal(sha('最终候选.json'),'abbb05267a91cc4d22b44cc883cf077bc76d68eb48072cb98ed0c40ecb24f2ac');assert.equal(sha('最终计划.json'),'e6a6b12e4d3152932516a8a662d6c81ea8dea76a2daca97802ba56fc312e82b6');assert.equal(plan.requests.length,5);assert.equal(sha('冻结来源.json'),'7f7c23e756fb1b9297a468fb63bd89ce3cf3fa85c9f2e6d56da5d18fb5982f57');assert.equal(sha('写前保护.json'),'2e204137122a311ea867a1efeaa16cdccde2cb8cc5373a1b15ecbd7372a92732');
const run=new Date().toISOString().replaceAll(':','-'),file=dir+'/'+(mode==='--apply'?'实际写入':mode==='--verify'?'独立回读':'只读预检')+'-'+run+'.json',events=[],written=[];let ownedLock=false;const lock=dir+'/写入锁.json';const api='http://127.0.0.1:8080/api/admin/games/lol';
async function http(method,route,body){let x;try{const r=await fetch(api+route,{method,headers:{Authorization:'Bearer local-entry','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});x={at:new Date().toISOString(),method,route,status:r.status,data:await r.json()};}catch(e){x={at:new Date().toISOString(),method,route,status:'UNKNOWN',error:String(e)};}events.push(x);fs.appendFileSync(file+'.jsonl',JSON.stringify(x)+'\n');return x;}
const strip=x=>{if(Array.isArray(x))return x.map(strip);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).filter(([k])=>!['gameId','createdAt','updatedAt','skillKey'].includes(k)).map(([k,v])=>[k,strip(v)]));return x;};const arr=x=>Array.isArray(x)?x:x.items;
function targetEqual(req,got){assert.equal(got.status,200,req.readRoute);if(req.kind==='image'){assert.equal(got.data.image.imageKey,req.body.imageKey);return;}if(req.kind==='relation'){const a=arr(got.data);assert.equal(a.length,1);for(const[k,v]of Object.entries(req.body))assert.equal(a[0][k],v);const owner=candidate.objects.find(o=>o.skillKey===req.body.skillKey),equipment=before.find(r=>r.route==='/equipment/'+owner.equipmentKey).data;assert.equal(a[0].skillName,owner.apiPayload.skill.name);assert.equal(a[0].equipmentName,equipment.name);assert.equal(a[0].skillStatus,'ENABLED');return;}assert.deepEqual(strip(got.data),strip(req.body),req.readRoute);}
async function protect(after){for(const old of before){const got=await http('GET',old.route);const req=plan.requests.find(r=>r.readRoute===old.route);if(after&&req)targetEqual(req,got);else{assert.equal(got.status,old.status,old.route);assert.deepEqual(strip(got.data),strip(old.data),old.route);}}}
async function independent(){await protect(true);const targets=[];for(const req of plan.requests){const got=await http('GET',req.readRoute);targetEqual(req,got);targets.push({request:req,response:got});}for(const o of candidate.objects)for(const [kind,key,apiKind]of [['parameters','parameterKey','parameters'],['formulas','formulaKey','formulas'],['effects','effectKey','effects'],['processes','processKey','processes'],['internalStates','stateKey','internal-states'],['triggerRules','ruleKey','trigger-rules']]){const got=await http('GET','/skills/'+o.skillKey+'/'+apiKind);assert.equal(got.status,200);const actual=arr(got.data);assert.deepEqual(actual.map(x=>x[key]).sort(),o.apiPayload[kind].map(x=>x[key]).sort());for(const row of actual){const expected=o.apiPayload[kind].find(p=>p[key]===row[key]);for(const k of Object.keys(row).filter(k=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)))assert.deepEqual(row[k],expected[k]);}}
 const p=targets.filter(t=>t.request.kind==='parameters').map(t=>t.response.data);assert.equal(p.length,2);assert.equal(p.find(x=>x.parameterKey==='synchrony_move_speed').fixedValue,45);assert.equal(p.find(x=>x.parameterKey==='out_of_combat_total_move_speed_ratio').fixedValue,.08);return {targetGETs:targets.length,componentLists:6,parameterCount:2,formulaCount:0,sourceValueChecks:2,allPass:true};}

let error=null,result=null;try{if(mode==='--apply'){fs.writeFileSync(lock,JSON.stringify({at:new Date().toISOString(),state:'STARTED',planSha256:sha('最终计划.json')},null,2)+'\n',{flag:'wx'});ownedLock=true;await protect(false);for(const req of plan.requests){const old=await http('GET',req.readRoute);if(req.kind==='relation')assert.deepEqual(arr(old.data),[]);else if(req.kind==='image')assert(old.status===404||(old.status===200&&old.data.image===null));else assert.equal(old.status,404,req.readRoute);const changed=await http(req.method,req.route,req.body),actual=await http('GET',req.readRoute);written.push({method:req.method,route:req.route,status:changed.status});assert(typeof changed.status==='number'&&changed.status>=200&&changed.status<300,JSON.stringify(written.at(-1)));targetEqual(req,actual);}fs.writeFileSync(lock,JSON.stringify({state:'COMPLETED',at:new Date().toISOString(),writes:written.length,planSha256:sha('最终计划.json')},null,2)+'\n');}else if(mode==='--verify')result=await independent();else await protect(false);}catch(e){error=String(e);if(ownedLock)fs.writeFileSync(lock,JSON.stringify({state:'ABORTED',at:new Date().toISOString(),writes:written,error,planSha256:sha('最终计划.json')},null,2)+'\n');}
const report={at:new Date().toISOString(),mode:mode??'--preflight',passed:error===null,candidateSha256:sha('最终候选.json'),planSha256:sha('最终计划.json'),GETs:events.filter(x=>x.method==='GET').length,writes:written,result,error,events};fs.writeFileSync(file,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({file,passed:report.passed,GETs:report.GETs,writes:written.length,error,result}));if(error)process.exitCode=1;
