// 离线模拟完整字段冲突、兰顿两个槽及写响应中断；不会调用业务 API。
import {writeFile} from 'node:fs/promises';
import {load,entries,compareEntry,applyMissing,makeRequest,here} from './接口工具.mjs';
const {plan}=await load(),checks=[],check=(name,match)=>checks.push({name,match}),passive=plan.objects.find(o=>o.skillKey==='item_3143_passive'),active=plan.objects.find(o=>o.skillKey==='item_3143_active'),skill=entries(active).find(e=>e.kind==='skill'),relation=entries(active).find(e=>e.kind==='relation');
const fullSkill={...skill.expected,gameId:'lol',createdAt:'kept',updatedAt:'kept'},relationData=o=>({...o.apiPayload.relation,equipmentName:o.equipmentName,skillName:o.apiPayload.skill.name,skillStatus:'ENABLED',gameId:'lol',createdAt:'kept',updatedAt:'kept'}),response=data=>({status:200,ok:true,data});
check('兰顿主动被动关系同时存在时按自身键比较',compareEntry(active,relation,response([relationData(passive),relationData(active)])).state==='same');check('只缺主动挂载时仍保留已有被动',compareEntry(active,relation,response([relationData(passive)])).state==='missing');check('拒绝计划外关系',compareEntry(active,relation,response([relationData(active),{skillKey:'item_3143_unrelated'}])).state==='conflict');check('拒绝重复关系',compareEntry(active,relation,response([relationData(active),relationData(active)])).state==='conflict');check('完整技能业务字段同值可复用且忽略创建更新时间',compareEntry(active,skill,response(fullSkill)).state==='same');check('不同说明不允许覆盖',compareEntry(active,skill,response({...fullSkill,description:'后来录入的有效说明'})).state==='conflict');check('额外未知业务字段不会静默忽略',compareEntry(active,skill,response({...fullSkill,unknownBusinessField:1})).state==='conflict');
let denied=false;try{await makeRequest()('/skills',{method:'POST',body:skill.expected});}catch{denied=true;}check('默认只读拒绝写请求',denied);
let calls=0;try{await applyMissing(plan,{conflicts:[{}],missing:[skill]},{request:async()=>{calls++;}});}catch{}check('全局冲突时零请求',calls===0);
let posts=0,gets=0,saved=false;const events=await applyMissing(plan,{conflicts:[],missing:[skill]},{request:async(route,{method='GET'}={})=>{if(method==='POST'){posts++;saved=true;throw Error('模拟服务端保存成功后响应中断');}gets++;return saved?response(fullSkill):{status:404,ok:false,data:null};}});check('响应中断后独立GET同值，不重放POST',posts===1&&gets===2&&events.failed.length===0&&events.events.some(e=>e.action==='写后独立GET'&&e.match));
let writes=0,stopped=false;try{await applyMissing(plan,{conflicts:[],missing:[skill]},{request:async(route,{method='GET'}={})=>{if(method!=='GET')writes++;return response({...fullSkill,description:'预检后对象变化'});}});}catch{stopped=true;}check('写前现值变化立即停止且零覆盖请求',stopped&&writes===0);
const out={at:new Date().toISOString(),boundary:'纯本地模拟，无业务写入',checks,failures:checks.filter(c=>!c.match)};await writeFile(new URL('入口安全核对.json',here),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,failures:out.failures}));if(out.failures.length)process.exitCode=1;
