// 独立读取最终候选或全量 GET 内容，不引用生成器或写响应。
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {isDeepStrictEqual as equal} from 'node:util';
export function arithmetic(objects){const tests=[],find=k=>objects.find(o=>o.skillKey===k)?.apiPayload,number=(k,p)=>find(k)?.parameters.find(n=>n.parameterKey===p)?.fixedValue,check=(skillKey,name,expected,actual)=>tests.push({skillKey,name,expected,actual,match:Math.abs(expected-actual)<1e-9});
 const cases={item_3145_passive:{proc_damage:65,proc_cooldown_ms:40000},item_3146_active:{damage_interpolation_start:175,damage_interpolation_end:253,damage_stat_coefficient:.3,slow_ratio:.25,slow_duration_ms:1500,active_cooldown_ms:60000},item_4629_passive:{move_speed_bonus:20,move_speed_duration_ms:4000},item_3082_passive:{flat_block:15,block_cap_ratio:.2},item_3110_passive:{attack_speed_reduction_ratio:.2},item_3143_passive:{critical_damage_reduction_ratio:.3},item_3143_active:{slow_ratio:.7,slow_duration_ms:2000,active_cooldown_ms:90000}};
 for(const [key,values]of Object.entries(cases))if(find(key))for(const [p,v]of Object.entries(values))check(key,'独立确定值 '+p,v,number(key,p));
 if(find('item_3145_passive')){check('item_3145_passive','40秒毫秒换算',40,number('item_3145_passive','proc_cooldown_ms')/1000);check('item_3145_passive','固定附伤65不随输入攻击力200变化',65,number('item_3145_passive','proc_damage'));}
 if(find('item_3146_active')){check('item_3146_active','插值值域两端差额，未映射到等级',78,number('item_3146_active','damage_interpolation_end')-number('item_3146_active','damage_interpolation_start'));check('item_3146_active','0.3乘100未定属性点，仅系数算术',30,number('item_3146_active','damage_stat_coefficient')*100);check('item_3146_active','25%减速幅度显示',25,number('item_3146_active','slow_ratio')*100);}
 if(find('item_4629_passive')){const e=find('item_4629_passive').effects.find(e=>e.effectKey==='spelldance_move_speed'),r=e?.results[0];check('item_4629_passive','效果引用固定20点',20,number('item_4629_passive',r?.valueRule.value.parameterKey));check('item_4629_passive','效果引用持续4000毫秒',4000,number('item_4629_passive',e?.lifecycle.durationValue.parameterKey));check('item_4629_passive','上限仅1层，不读取旧3层',1,e?.lifecycle.maxStacksValue.value);}
 if(find('item_3082_passive')){const expression=find('item_3082_passive').formulas.find(f=>f.formulaKey==='block_amount')?.expression;const evalNode=(n,input)=>{if(n.nodeType==='PARAMETER')return n.parameterKey==='attack_damage_for_block_cap'?input:number('item_3082_passive',n.parameterKey);if(n.nodeType==='OPERATION'){const a=n.operands.map(v=>evalNode(v,input));if(n.operation==='MIN')return Math.min(...a);if(n.operation==='MULTIPLY')return a.reduce((x,y)=>x*y,1);}throw Error('独立算例遇到未知表达式');};for(const [input,expected]of [[0,0],[1,0.2],[7.5,1.5],[10,2],[50,10],[74.5,14.9],[75,15],[75.5,15],[100,15],[1000,15]])check('item_3082_passive','独立公式输入D='+input+'（阶段待绑定）',expected,evalNode(expression,input));}
 if(find('item_3110_passive')){check('item_3110_passive','降低20%按比例显示',20,number('item_3110_passive','attack_speed_reduction_ratio')*100);check('item_3110_passive','仅数学示例：1.25的20%为0.25，非20百分点额外攻速',.25,1.25*number('item_3110_passive','attack_speed_reduction_ratio'));}
 if(find('item_3143_passive'))check('item_3143_passive','仅比例算术：100暴击伤害的30%为30',30,100*number('item_3143_passive','critical_damage_reduction_ratio'));
 if(find('item_3143_active'))check('item_3143_active','70%减速幅度显示',70,number('item_3143_active','slow_ratio')*100);return tests;
}
const here=new URL('./',import.meta.url);
if(process.argv[1]&&new URL('file:///'+process.argv[1].replaceAll('\\','/')).href===import.meta.url){
 if(process.argv.length>2)throw Error('只允许本地最终候选核算');const read=n=>readFile(new URL(n,here),'utf8').then(JSON.parse),bytes=await readFile(new URL('完整候选.json',here)),plan=JSON.parse(bytes),source=await read('冻结来源.json'),before=await read('当前只读核对.json'),checks=[];const check=(name,match,detail=null)=>checks.push({name,match,detail}),sha=b=>createHash('sha256').update(b).digest('hex');
 const root=new URL('../../',here);for(const s of source.sources){if(s.文件){const b=await readFile(new URL('装备效果补证/'+s.文件,root)),raw=gunzipSync(b);check('压缩摘要 '+s.文件,sha(b)===s.压缩SHA256);check('展开摘要 '+s.文件,sha(raw)===s.原始SHA256);}else{const b=await readFile(new URL('装备符文/'+s.file,root));check('官方摘要 '+s.file,sha(b)===s.sha256);}}
 const expectedKeys=['item_3145_passive','item_3146_active','item_4629_passive','item_3082_passive','item_3110_passive','item_3143_passive','item_3143_active'];check('严格限定七技能',equal(plan.objects.map(o=>o.skillKey),expectedKeys));
 for(const o of plan.objects){const p=o.apiPayload,params=new Set(p.parameters.map(p=>p.parameterKey)),formulas=new Set(p.formulas.map(f=>f.formulaKey)),missing=[];function walk(v){if(!v||typeof v!=='object')return;if((v.kind==='PARAMETER'||v.nodeType==='PARAMETER')&&!params.has(v.parameterKey))missing.push(v.parameterKey);if(v.kind==='FORMULA'&&!formulas.has(v.formulaKey))missing.push(v.formulaKey);for(const x of Object.values(v))walk(x);}walk(p);check(o.skillKey+'本地引用完整',!missing.length,missing);check(o.skillKey+'没有空过程、假状态或事件',p.processes.length+p.internalStates.length+p.triggerRules.length===0);check(o.skillKey+'无猜测角色等级曲线',p.parameters.every(v=>v.levelValues===null&&v.valueMode!=='CHARACTER_LEVEL'));check(o.skillKey+'关系归属完整',p.skill.skillKey===o.skillKey&&p.relation.skillKey===o.skillKey&&p.relation.equipmentKey===o.equipmentKey);const live=before.objects.find(v=>v.equipmentKey===o.equipmentKey),image=live.records.find(r=>r.route.endsWith('/representative-image')).data;check(o.skillKey+'原代表图仅复用',p.representativeImage.imageKey===image.image.imageKey);check(o.skillKey+'原属性与主体元数据完整保护',equal(o.safeguards.equipment,live.records.find(r=>r.route==='/equipment/'+o.equipmentKey).data)&&equal(o.safeguards.attributes,live.records.find(r=>r.route.endsWith('/attributes')).data));check(o.skillKey+'别名为空且现有主体404',live.possibleAliases.length===0&&live.skills.find(s=>s.skillKey===o.skillKey).records[0].status===404);}
 const get=k=>plan.objects.find(o=>o.skillKey===k).apiPayload,cosmic=get('item_4629_passive'),e=cosmic.effects[0],r=e.results[0];check('发电机未知护盾效果已撤出',get('item_3145_passive').effects.length===0);check('枪刃没有默认解码未证伤害公式或效果',get('item_3146_active').formulas.length+get('item_3146_active').effects.length===0);check('星界固定加算单层刷新且仅来源自身',r.resultType==='ATTRIBUTE_CHANGE'&&r.target==='SOURCE'&&r.detail.attributeKey==='move_speed'&&r.detail.operation==='INCREASE'&&r.detail.modifierZoneKey==='attribute_flat_add'&&r.lifecycleBehavior.valueReadMode==='APPLICATION_SNAPSHOT'&&e.lifecycle.instanceScope==='SOURCE'&&e.lifecycle.reapplicationDurationMode==='REFRESH_ALL'&&e.lifecycle.reapplicationStackMode==='KEEP');check('星界不借旧叠层/比例/冷却字段',equal(cosmic.parameters.map(p=>p.parameterKey),['move_speed_bonus','move_speed_duration_ms']));check('守望者保留小数输入且无减伤结果',get('item_3082_passive').parameters.some(p=>p.parameterKey==='attack_damage_for_block_cap'&&p.valueMode==='RUNTIME_INPUT'&&p.valueType==='DECIMAL'&&p.fixedValue===null)&&get('item_3082_passive').effects.length===0);check('冰心没有减额外攻速20百分点效果',get('item_3110_passive').effects.length===0);check('兰顿两槽无借用区或控制状态',get('item_3143_passive').effects.length+get('item_3143_active').effects.length===0);
 const zones=before.catalogs['modifier-zones'].data.items,attrs=before.catalogs.attributes.data.items;check('已用属性与计算区真实目录兼容',attrs.some(a=>a.attributeKey==='move_speed'&&a.status==='ENABLED')&&zones.some(z=>z.modifierZoneKey==='attribute_flat_add'&&z.domain==='ATTRIBUTE'&&z.applicationStage==='ATTRIBUTE_FLAT'&&z.calculationMode==='FLAT_ADD'&&z.status==='ENABLED'));check('未使用不存在伤害区或减速状态',zones.every(z=>z.domain!=='DAMAGE')&&(before.catalogs.statuses.data.items??before.catalogs.statuses.data).every(s=>s.statusKey!=='slow'));
 const tests=arithmetic(plan.objects),out={at:new Date().toISOString(),candidateSha256:sha(bytes),boundary:'独立读取本地最终载荷及真实GET目录；算例不代表伤害管线或战斗运行。缺口公式输入阶段仍待绑定。',checks,tests,failures:[...checks,...tests].filter(t=>!t.match)};await writeFile(new URL('完整独立核算.json',here),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({sha256:out.candidateSha256,checks:checks.length,samples:tests.length,failures:out.failures}));if(out.failures.length)process.exitCode=1;
}
