import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const here=new URL('./',import.meta.url),root='C:/project/damage_web_dev/数据参考/全量录入-2026-09/交叉试录/历史等级曲线修正/',back='C:/project/damage_backend_dev/',sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const raw=fs.readFileSync(root+'补充可审查请求.json');assert.equal(sha(raw),'50342518c542cc96aac3af2d78e1e27b3c1953a98577d64225562cf154443d45');const plan=JSON.parse(raw),snapshot=read(new URL('独立实时148GET.json',here)),validator=read(new URL('实际后端校验反例.json',here)),extra=read(new URL('字典与效果图片7GET.json',here));
assert.equal(snapshot.errors.length,0);assert.equal(extra.errors.length,0);assert.equal(validator.checks.length,15);assert(validator.checks.every(c=>c.passed));const live=new Map(snapshot.reads.map(r=>[r.route,r]));
for(const r of plan.requests){assert.equal(live.get(r.route).status,200);assert.deepEqual(live.get(r.route).data,r.before);if(r.method==='PUT'){assert(!Object.hasOwn(r.body,'parameterKey'));for(const k of ['parameterKey','skillKey','name','valueType','sortOrder','createdAt','gameId'])assert.deepEqual(r.before[k],r.after[k]);assert.equal(r.body.valueMode,'RUNTIME_INPUT');assert.equal(r.body.fixedValue,null);assert.equal(r.body.levelValues,null);}}
const g=live.get('/skills/garen_p/effects/perseverance_regen').data;const proposal={method:'DELETE',route:'/skills/garen_p/effects/perseverance_regen',before:g,reason:'原MOMENT_EVALUATION持续效果经regen_per_5s引用待转RUNTIME_INPUT参数，必须保持原语义并撤除未证动态效果，不能改快照绕过。',currentIncomingReferences:[],currentProcesses:live.get('/skills/garen_p/processes').data,currentTriggerRules:live.get('/skills/garen_p/trigger-rules').data,representativeImage:extra.reads.find(r=>r.route==='/skills/garen_p/effects/perseverance_regen/representative-image').data,chain:[{kind:'EFFECT',key:'perseverance_regen',field:'results[0].valueRule.value',mode:'PERSISTENT + MOMENT_EVALUATION'},{kind:'FORMULA',key:'regen_per_5s',fullObject:live.get('/skills/garen_p/formulas/regen_per_5s').data},{kind:'PARAMETER',key:'regen_ratio_per_5s',fullObject:live.get('/skills/garen_p/parameters/regen_ratio_per_5s').data}]};
fs.writeFileSync(new URL('Garen补充删除精确对象.json',here),JSON.stringify(proposal,null,2)+'\n',{flag:'wx'});
const sources=['server/data_manage/src/main/java/xyz/game/datamanage/support/authoring/SkillNumericSemantics.java','server/data_manage/src/main/java/xyz/game/datamanage/support/authoring/SkillObjectReferences.java','server/data_manage/src/main/java/xyz/game/datamanage/support/authoring/GameConfigurationWriteGuard.java','server/data_manage/src/main/java/xyz/game/datamanage/service/skilleffect/SkillEffectService.java','server/data_manage/src/main/resources/mapper/skilleffect/SkillEffectMapper.xml','server/data_manage/src/main/java/xyz/game/datamanage/service/skilltrigger/SkillTriggerRuleService.java'];
const out={at:new Date().toISOString(),verdict:'REVISE',reviewedPlanSha256:sha(raw),businessWrites:0,gets:155,statusCounts:{200:149,404:6},actualBaselineAllFieldsMatched:true,blocking:[{route:proposal.route,reason:proposal.reason,preciseFix:'补充1个DELETE，排在4个参数PUT之前。先逐GET比完整before，无引用才删除，随后参数更新；保留现已确认12项，不重放。'}],proposedFinal:{requests:7,additionalDeletes:3,remainingParameterUpdates:4,originalComponents:76,alreadyDeletedRules:6,finalComponents:67,changedParameters:10,otherComponentsUnchanged:57},remainingChecks:[{parameter:'diana_p/passive_attack_speed_ratio',verdict:'两个动态效果都删除后通过；任留一个均失败'},{parameter:'trundle_p/dead_enemy_hp_heal_ratio',verdict:'独立即时效果允许实际输入，无过程/自动规则，实际校验通过'},{parameter:'warwick_p/on_hit_base',verdict:'独立伤害结果允许实际输入，旧命中规则已404，实际校验通过'},{parameter:'garen_p/regen_ratio_per_5s',verdict:'当前仍被动态持续效果间接引用，原补充计划必拒绝；撤效果后通过'}],validator:{realCurrentSourcesCompiled:true,offlineOnly:true,checks:15,assertionsPassed:true,allEightSkillAggregatesChecked:true,originalSixRequestCounterexample:true,correctedSevenRequestPass:true},deletionProtection:{currentEightSkillsExternalEffectReferences:0,scope:'现行效果/结果/生命周期引用由local/child强制当前技能；跨技能SKILL事件不构成跨技能EFFECT引用。未扫855技能；服务最终按同游戏全量引用守卫复核。',threeImagesNull:true,behavior:'服务检查过程、触发规则和生命周期操作引用，提交前再次全游戏引用/数值检查，异常回滚；效果删除会清其图片关系但不删图字节。'},files:{snapshotSha256:sha(fs.readFileSync(new URL('独立实时148GET.json',here))),additionalGETSha256:sha(fs.readFileSync(new URL('字典与效果图片7GET.json',here))),backendCounterexamplesSha256:sha(fs.readFileSync(new URL('实际后端校验反例.json',here))),garenObjectSha256:sha(fs.readFileSync(new URL('Garen补充删除精确对象.json',here)))},sourceSha256:Object.fromEntries(sources.map(p=>[p,sha(fs.readFileSync(back+p))])),notes:['审查未执行业务写。原计划SHA不修改；主负责人应冻结7请求新文件后核对最终SHA。','原始参数/公式说明仍提旧18级表或已删除规则，属于保留元数据文字；本次只按授权数值字段与最小撤除执行，不能把文字误认为自动动作仍存在。']};
fs.writeFileSync(new URL('独立审查.json',here),JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({verdict:out.verdict,gets:out.gets,checks:15,finalComponents:67,reportSha256:sha(fs.readFileSync(new URL('独立审查.json',here))),garenObjectSha256:out.files.garenObjectSha256}));
