// 只允许GET；不创建技能、挂载或图片。
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
if(process.argv.length!==2)throw Error('只读预检不接受写参数');const here=path.dirname(fileURLToPath(import.meta.url)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),raw=fs.readFileSync(path.join(here,'冻结来源.json'));assert.equal(sha(raw),'878fd1147a277282f6bacd04ecddafe55e980e729a67d4469b31b2ff93d492a7');const source=JSON.parse(raw),token=process.env.RUNE5_API_TOKEN;assert.ok(token,'通过进程环境提供开发认证占位值');
const artifact='C:/project/damage_web_dev/.agents/artifacts/rune5-candidate';fs.mkdirSync(artifact,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,'-'),events=[],report={at:new Date().toISOString(),sourceFrozenSha256:sha(raw),apiWrites:0,identities:null,layouts:null,catalogs:{},owners:[],errors:[],pass:false};
async function get(route){let result;try{const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method:'GET',headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)});result={route,status:r.status,data:await r.json()};}catch(e){result={route,status:null,data:null,error:e.name+': '+e.message};}events.push({route,status:result.status});fs.appendFileSync(path.join(artifact,'GET-'+stamp+'.jsonl'),JSON.stringify({at:new Date().toISOString(),route,status:result.status,error:result.error})+'\n');return result;}
const rows=r=>Array.isArray(r.data)?r.data:r.data?.items;
try{
 report.identities=await get('/runes');report.layouts=await get('/rune-paths');assert.equal(report.identities.status,200);assert.equal(report.layouts.status,200);
 for(const key of ['attributes','modifier-zones','skill-categories','statuses','damage-types']){const r=await get('/'+key);assert.equal(r.status,200);report.catalogs[key]=r;}
 for(const e of source.entries){const runeKey='rune_'+e.id,skillKey=runeKey+'_passive',rune=await get('/runes/'+runeKey),skill=await get('/skills/'+skillKey),representative=await get('/runes/'+runeKey+'/representative-image'),relations=await get('/rune-skill-relations?runeKey='+runeKey);assert.equal(rune.status,200);assert.equal(representative.status,200);assert.equal(relations.status,200);assert.ok([200,404].includes(skill.status));const imageKey=representative.data.image?.imageKey;assert.ok(imageKey);const image=await get('/images/'+imageKey),usage=await get('/images/'+imageKey+'/usages');assert.equal(image.status,200);assert.equal(usage.status,200);assert.ok(usage.data.runes.some(x=>x.runeKey===runeKey));
  const bytes=Buffer.from(image.data.imageBase64.includes(',')?image.data.imageBase64.split(',').at(-1):image.data.imageBase64,'base64');assert.equal(bytes.subarray(0,8).toString('hex'),'89504e470d0a1a0a');const width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20);assert.ok(width<=64&&height<=64&&width>0&&height>0);const metadata={...image.data};delete metadata.imageBase64;
  const owner={id:e.id,runeKey,skillKey,rune:rune.data,skillStatus:skill.status,skill:skill.status===200?skill.data:null,representative:representative.data,relations:relations.data,image:{metadata,contentSha256:sha(bytes),byteLength:bytes.length,width,height},usage:usage.data,components:{}};
  if(skill.status===200)for(const[k,id]of [['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey'],['processes','processKey'],['internal-states','stateKey'],['trigger-rules','ruleKey']]){const list=await get('/skills/'+skillKey+'/'+k);assert.equal(list.status,200);owner.components[k]=[];for(const row of rows(list)){const detail=await get('/skills/'+skillKey+'/'+k+'/'+row[id]);assert.equal(detail.status,200);owner.components[k].push(detail.data);}}
  report.owners.push(owner);
 }
 report.pass=report.owners.length===12;
}catch(e){report.errors.push({name:e.name,message:e.message});}
report.requests=events;report.statusCounts=events.reduce((m,x)=>(m[x.status]=(m[x.status]??0)+1,m),{});report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(here,'保护基线.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});
if(report.pass){const proposals=report.owners.map(x=>({id:x.id,skillKey:x.skillKey,kind:'image',method:'PUT',route:'/skills/'+x.skillKey+'/representative-image',readRoute:'/skills/'+x.skillKey+'/representative-image',body:{imageKey:x.image.metadata.imageKey},sourceContentSha256:x.image.contentSha256}));fs.writeFileSync(path.join(here,'代表图复用候选.json'),JSON.stringify({at:new Date().toISOString(),apiWrites:0,boundary:'仅将现有符文代表图关联到未来技能，不上传图、不修改原符文图；此处只有可审查请求。',requests:proposals},null,2)+'\n',{flag:'wx'});}
console.log(JSON.stringify({pass:report.pass,apiWrites:0,requests:events.length,statusCounts:report.statusCounts,owners:report.owners.length,newSkills:report.owners.filter(x=>x.skillStatus===404).length,identityCount:rows(report.identities)?.length,layoutCount:rows(report.layouts)?.length,errors:report.errors}));if(!report.pass)process.exitCode=1;
