import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),bytes=fs.readFileSync(path.join(here,'最终修正请求.json'));assert.equal(sha(bytes),'922f213e781fea8ab8cec893f8cec096382cfaca2cd2e7518958a8e7df636599');
const plan=JSON.parse(bytes),baseBytes=fs.readFileSync(path.join(here,'写前保护.json'));assert.equal(sha(baseBytes),plan.baselineSha256);const baseline=JSON.parse(baseBytes);assert.equal(plan.requests.length,7);
const apply=process.argv[2]==='--apply';assert(process.argv.length===(apply?3:2));const token=process.env.HERO11_API_TOKEN;assert(token);
const journal=path.join(here,'实际修正流水.jsonl'),resultFile=path.join(here,'实际修正结果.json');if(apply)assert(!fs.existsSync(journal)&&!fs.existsSync(resultFile),'已有实际流水，请先只读对账，禁止重放');
const reads=[],writes=[],changed=new Map();const match=(a,b)=>{for(const[k,v]of Object.entries(b))assert.deepEqual(a[k],v,k);};
async function call(method,route,body){if(method!=='GET'){assert(apply);const p=plan.requests.find(p=>p.route===route);assert(p&&method==='PUT');assert.deepEqual(body,p.body);}if(apply)fs.appendFileSync(journal,JSON.stringify({at:new Date().toISOString(),phase:'before',method,route,body})+'\n');const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const data=await r.json();if(apply)fs.appendFileSync(journal,JSON.stringify({at:new Date().toISOString(),phase:'after',method,route,status:r.status,data})+'\n');assert.equal(r.status,200,route);const value={method,route,status:r.status,data};if(method==='GET')reads.push(value);return data;}
for(const p of plan.requests)assert.deepEqual(await call('GET',p.route),p.before,p.route+'写前全值');
if(!apply){console.log(JSON.stringify({preview:true,gets:reads.length,writes:0}));process.exit(0);}
for(const p of plan.requests){assert.deepEqual(await call('GET',p.route),p.before);await call('PUT',p.route,p.body);const after=await call('GET',p.route);match(after,p.body);for(const[k,v]of Object.entries(p.before))if(k!=='updatedAt'&&!Object.hasOwn(p.body,k))assert.deepEqual(after[k],v);writes.push({route:p.route,method:'PUT',status:200,after});changed.set(p.route,after);}
function corrected(x){if(!x||typeof x!=='object')return x;if(Array.isArray(x))return x.map(corrected);const kind=x.parameterKey?'parameters':x.formulaKey?'formulas':null,key=x.parameterKey??x.formulaKey,live=kind&&changed.get(`/skills/${x.skillKey}/${kind}/${key}`);return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,live&&Object.hasOwn(live,k)?live[k]:corrected(v)]));}
const queue=baseline.reads;let index=0;await Promise.all(Array.from({length:4},async()=>{while(index<queue.length){const old=queue[index++],actual=await call('GET',old.route);assert.deepEqual(actual,corrected(old.data),old.route+'完整保护');}}));
const f=changed.get('/skills/gwen_p/formulas/passive_heal_amount');function evalNode(n,input){if(n.nodeType==='PARAMETER'){if(!Object.hasOwn(input,n.parameterKey))throw Error('缺输入 '+n.parameterKey);return input[n.parameterKey];}if(n.nodeType==='ATTRIBUTE')return input[n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind];const [a,b]=n.operands.map(o=>evalNode(o,input));if(n.operation==='ADD')return a+b;if(n.operation==='MULTIPLY')return a*b;if(n.operation==='MIN')return Math.min(a,b);throw Error('不支持');}
const cases=[];for(const [damage,cap,ap,expected]of [[10,30,100,6.7],[100,30,100,37],[100,70,100,67]]){const inputs={healing_ratio:.67,actual_passive_hero_damage:damage,heal_cap_level:cap,heal_cap_ap_ratio:.07,'SOURCE.ability_power.TOTAL':ap},actual=evalNode(f.expression,inputs);assert(Math.abs(actual-expected)<1e-9);cases.push({inputs,expected,actual,pass:true});}assert.throws(()=>evalNode(f.expression,{healing_ratio:.67,actual_passive_hero_damage:100,heal_cap_ap_ratio:.07,'SOURCE.ability_power.TOTAL':100}),/缺输入 heal_cap_level/);
for(const p of plan.requests.filter(p=>p.route.includes('/parameters/'))){const now=changed.get(p.route);assert.equal(now.valueMode,'RUNTIME_INPUT');assert.equal(now.fixedValue,null);assert.equal(now.levelValues,null);}
const result={at:new Date().toISOString(),requestSha256:sha(bytes),writes,reads,summary:{success:true,updates:writes.length,gets:reads.length,fullProtectionGets:queue.length,parametersToRuntime:6,formulasCorrected:1,otherComponentsProtected:228,mathCases:cases.length,missingInputRejected:true},mathCases:cases,boundary:'算例中的等级基础输入是人为指定的已知值，不证明任何真实等级曲线；未执行战斗引擎。'};fs.writeFileSync(resultFile,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result.summary));
