import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = path.dirname(fileURLToPath(import.meta.url));
const INPUT = process.env.HERO49_INPUT ? path.resolve(process.env.HERO49_INPUT) : path.resolve(ROOT, '..', 'hero49-root-entry-20260910');
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const candidate = readJson(path.join(ROOT, '完整候选.json'));
const binding = readJson(path.join(INPUT, '来源绑定与当前文本.json'));
const protection = readJson(path.join(INPUT, '参考资料', '当前20槽保护快照.json'));
const sourceByKey = Object.fromEntries(binding.heroes.flatMap(hero => hero.skills.map(skill => [skill.skillKey, { hero, skill }])));
const attrs = new Set((protection.dictionaries?.['/attributes']?.items || []).map(item => item.attributeKey));
const reuse = new Set((candidate.reusedPublicParameters || []).map(item => item.skillKey + '/' + item.parameterKey));
const finite = value => typeof value === 'number' && Number.isFinite(value);
const fail = (list, message) => list.push(message);
const dataAt = (key, name, rank) => { const sp = sourceByKey[key].skill.sourceObject.mSpell; const row = (sp.DataValues || []).find(item => item.name === name); if (!row || !Array.isArray(row.values) || row.values[rank] === undefined) throw new Error('source data missing ' + key + '/' + name + '/' + rank); return row.values[rank]; };
const evalNode = (node, ctx, sourceMode = false) => {
  if (!node) throw new Error('空表达式节点');
  if (node.nodeType === 'PARAMETER') { const p = ctx.def.write.parameters.find(item => item.parameterKey === node.parameterKey); if (!p) { if (reuse.has(ctx.key + '/' + node.parameterKey)) throw new Error('复用参数未注入数学快照：' + node.parameterKey); throw new Error('参数引用不存在：' + ctx.key + '/' + node.parameterKey); } if (p.valueMode === 'RUNTIME_INPUT') { if (!(node.parameterKey in ctx.runtime)) throw new Error('缺少运行输入：' + ctx.key + '/' + node.parameterKey); return ctx.runtime[node.parameterKey]; } if (p.valueMode === 'FIXED') return p.fixedValue; return p.levelValues[String(ctx.rank)]; }
  if (node.nodeType === 'ATTRIBUTE' || node.nodeType === 'SOURCE_ATTRIBUTE') { const a = ctx.values[node.attributeOwner]?.[node.attributeKey]?.[node.attributeValueKind]; if (!finite(a)) throw new Error('缺少属性场景：' + node.attributeOwner + '/' + node.attributeKey + '/' + node.attributeValueKind); return a; }
  if (node.nodeType === 'SOURCE_DATA') return dataAt(ctx.key, node.dataName, ctx.rank) * node.transform;
  if (node.nodeType === 'SOURCE_RUNTIME') { if (!(node.runtimeKey in ctx.runtime)) throw new Error('缺少来源运行输入：' + ctx.key + '/' + node.runtimeKey); return ctx.runtime[node.runtimeKey]; }
  if (node.nodeType === 'SOURCE_CONSTANT') return node.value;
  if (node.nodeType === 'OPERATION') { if (!Array.isArray(node.operands) || node.operands.length !== 2) throw new Error('操作数不是2'); const left = evalNode(node.operands[0], ctx, sourceMode); const right = evalNode(node.operands[1], ctx, sourceMode); if (node.operation === 'ADD') return left + right; if (node.operation === 'MULTIPLY') return left * right; throw new Error('未知运算：' + node.operation); }
  throw new Error('未知节点类型：' + node.nodeType);
};
const runtimeValue = (p, rank) => { if (p.valueType === 'INTEGER' || p.parameterKey.endsWith('_ms')) return p.parameterKey.includes('count') || p.parameterKey.includes('stacks') ? 3 : 1500 + rank * 100; if (p.parameterKey.includes('ratio')) return 0.25 + rank * 0.01; if (p.parameterKey.includes('health')) return 900 + rank * 100; return 1 + rank * 0.1; };
const scenariosFor = (key, def, rank) => { const runtime = {}; for (const p of def.write.parameters) if (p.valueMode === 'RUNTIME_INPUT') runtime[p.parameterKey] = runtimeValue(p, rank); return { key, def, rank, runtime, values: { SOURCE: { attack_damage: { TOTAL: rank === 1 ? 220 : 420, BONUS: rank === 1 ? 110 : 210 }, ability_power: { TOTAL: rank === 1 ? 300 : 500 }, hp: { TOTAL: rank === 1 ? 1800 : 2600, BONUS: rank === 1 ? 400 : 700 } }, TARGET: { hp: { TOTAL: rank === 1 ? 2400 : 3600 } } } }; };
const refs = (node, callback) => { if (!node || typeof node !== 'object') return; callback(node); if (node.nodeType === 'OPERATION') for (const operand of node.operands || []) refs(operand, callback); };
const checkTypes = (report, key, def) => { const own = new Set(def.write.parameters.map(item => item.parameterKey)); const formulas = new Set(def.write.formulas.map(item => item.formulaKey)); const checkExpr = (expr, where) => refs(expr, node => { if (node.nodeType === 'PARAMETER' && !own.has(node.parameterKey) && !reuse.has(key + '/' + node.parameterKey)) fail(report.failures, '悬空参数引用 ' + where + '/' + node.parameterKey); if (node.nodeType === 'ATTRIBUTE' && !attrs.has(node.attributeKey)) fail(report.failures, '属性不存在 ' + where + '/' + node.attributeKey); if (node.nodeType === 'OPERATION' && (!Array.isArray(node.operands) || node.operands.length !== 2)) fail(report.failures, '非二元运算 ' + where); }); for (const formula of def.write.formulas) checkExpr(formula.expression, key + '/formula/' + formula.formulaKey); for (const effect of def.write.effects) for (const result of effect.results || []) { if (result.valueRule?.value?.kind === 'PARAMETER' && !own.has(result.valueRule.value.parameterKey) && !reuse.has(key + '/' + result.valueRule.value.parameterKey)) fail(report.failures, '效果参数引用不存在 ' + key + '/' + result.valueRule.value.parameterKey); if (result.valueRule?.value?.kind === 'FORMULA' && !formulas.has(result.valueRule.value.formulaKey)) fail(report.failures, '效果公式引用不存在 ' + key + '/' + result.valueRule.value.formulaKey); if (result.detail?.attributeKey && !attrs.has(result.detail.attributeKey)) fail(report.failures, '效果属性不存在 ' + key + '/' + result.detail.attributeKey); if (result.detail?.attributeKey === 'move_speed_percent' || result.detail?.attributeKey === 'bonus_attack_speed_percent') { report.effectUnits.push({ key, effectKey: effect.effectKey, attributeKey: result.detail.attributeKey, modifierZoneKey: result.detail.modifierZoneKey, unit: '1=100%' }); if (result.detail.modifierZoneKey !== 'attribute_flat_add') fail(report.failures, '比例属性未使用attribute_flat_add ' + key + '/' + effect.effectKey); } if (result.valueRule && !finite(result.valueRule.fixedMultiplier)) fail(report.failures, '效果最终倍率非有限数字 ' + key + '/' + effect.effectKey); } };
const checkArrays = (report, key, def) => { for (const p of def.write.parameters) { if (p.valueMode === 'RUNTIME_INPUT') { if (p.fixedValue !== null || p.levelValues !== null) fail(report.failures, '运行输入含默认值 ' + key + '/' + p.parameterKey); continue; } const values = p.levelValues; if (p.valueMode === 'SKILL_LEVEL') { const expected = Array.from({ length: def.maxLevel }, (_, i) => String(i + 1)); if (!values || JSON.stringify(Object.keys(values)) !== JSON.stringify(expected)) fail(report.failures, '技能等级数组不完整 ' + key + '/' + p.parameterKey); } if (p.valueMode === 'CHARACTER_LEVEL') { const expected = Array.from({ length: 18 }, (_, i) => String(i + 1)); if (!values || JSON.stringify(Object.keys(values)) !== JSON.stringify(expected)) fail(report.failures, '角色等级数组不完整 ' + key + '/' + p.parameterKey); } const all = p.valueMode === 'FIXED' ? [p.fixedValue] : Object.values(values || {}); for (const value of all) { if (!finite(value)) fail(report.failures, '参数非有限数字 ' + key + '/' + p.parameterKey); if (p.valueType === 'INTEGER' && !Number.isInteger(value)) fail(report.failures, '整数参数含小数 ' + key + '/' + p.parameterKey); if (p.parameterKey.endsWith('_ms') && !Number.isInteger(value)) fail(report.failures, '毫秒参数非整数 ' + key + '/' + p.parameterKey); } } };
const report = { generatedAt: new Date().toISOString(), batch: candidate.meta.batch, revision: candidate.meta.revision, status: '独立数学核算', tolerance: 0.00001, failures: [], formulas: [], effectUnits: [], sourceMatches: 0, formulaScenarios: 0, missingRuntimeRejected: 0, typeReferencesChecked: 0, parameterArraysChecked: 0, finalEffectMultipliers: [] };
for (const key of candidate.order) { const def = candidate.skills[key]; checkTypes(report, key, def); checkArrays(report, key, def); report.parameterArraysChecked += def.write.parameters.length; for (const formula of def.write.formulas) { const evidence = def.formulaEvidence?.[formula.formulaKey]; if (!evidence?.sourceRule) { fail(report.failures, '缺少原始来源公式规则 ' + key + '/' + formula.formulaKey); continue; } for (const rank of [1, def.maxLevel]) { const ctx = scenariosFor(key, def, rank); report.formulaScenarios += 1; let candidateValue; let sourceValue; try { candidateValue = evalNode(formula.expression, ctx); sourceValue = evalNode(evidence.sourceRule, ctx, true); } catch (error) { fail(report.failures, '公式求值失败 ' + key + '/' + formula.formulaKey + '/rank' + rank + ': ' + error.message); continue; } const delta = Math.abs(candidateValue - sourceValue); const check = { key, formulaKey: formula.formulaKey, rank, sourceCalculation: evidence.sourceCalculation, candidateValue, sourceValue, delta, matched: delta < report.tolerance }; report.formulas.push(check); if (check.matched) report.sourceMatches += 1; else fail(report.failures, '候选与源值不一致 ' + key + '/' + formula.formulaKey + '/rank' + rank); const runtimeParams = def.write.parameters.filter(item => item.valueMode === 'RUNTIME_INPUT' && JSON.stringify(formula.expression).includes(item.parameterKey)); if (runtimeParams.length) { const missing = { ...ctx, runtime: {} }; let rejected = false; try { evalNode(formula.expression, missing); } catch { rejected = true; } if (rejected) report.missingRuntimeRejected += 1; else fail(report.failures, '缺运行输入未拒绝 ' + key + '/' + formula.formulaKey + '/rank' + rank); } } } for (const effect of def.write.effects) for (const result of effect.results || []) if (result.valueRule) report.finalEffectMultipliers.push({ key, effectKey: effect.effectKey, resultKey: result.resultKey, fixedMultiplier: result.valueRule.fixedMultiplier, attributeKey: result.detail?.attributeKey || null, modifierZoneKey: result.detail?.modifierZoneKey || null }); }
report.typeReferencesChecked = report.formulaScenarios + report.parameterArraysChecked;
report.status = report.failures.length ? '失败' : '通过';
fs.writeFileSync(path.join(ROOT, '独立数学报告.json'), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify({ status: report.status, formulaScenarios: report.formulaScenarios, sourceMatches: report.sourceMatches, missingRuntimeRejected: report.missingRuntimeRejected, failures: report.failures.length, report: path.join(ROOT, '独立数学报告.json') }, null, 2));
if (report.failures.length) process.exitCode = 1;
