import assert from'node:assert/strict';
export function verifyMath(skills,binding){
 const sources=new Map(binding.heroes.flatMap(h=>h.skills).map(s=>[s.skillKey,s])),reports=[];
 const mapping={ekko_p:{three_hit_damage:'ThreeHitDamage'},ekko_q:{initial_damage:'InitialDamage',recall_damage:'RecallDamage'},ekko_w:{missing_health_damage_ratio:'MissingHealthPercent',total_shield:'TotalShield'},ekko_e:{damage:'TotalDamage'},ekko_r:{damage:'TotalDamage',total_base_heal:'TotalBaseHeal'},fizz_p:{damage_reduction:'DamageReductionCalc'},fizz_q:{magic_damage:'QDamage',physical_damage:'TotalDamage'},fizz_w:{dot_damage:'DoTDamage',active_damage:'ActiveDamage',on_hit_buff_damage:'OnHitBuffDamage'},fizz_e:{damage:'EDamage'},fizz_r:{small_shark_damage:'SmallSharkDamage',mid_shark_damage:'{262c3c02}',big_shark_damage:'BigSharkDamage'}};
 const sourceData=(key,name,rank)=>{const m=sources.get(key).object.mSpell,p=m.DataValues.find(p=>p.name===name);assert(p&&Array.isArray(p.values),'source data '+key+'/'+name);assert(Number.isFinite(p.values[rank]));return p.values[rank];};
 const required=(c,key)=>{assert(Object.hasOwn(c,key),'missing '+key);const v=c[key];assert(Number.isFinite(v)&&v>=0,'invalid '+key);return v;};
 function sourcePart(key,n,c){const m=sources.get(key).object.mSpell;switch(n.__type){case'NamedDataValueCalculationPart':return sourceData(key,n.mDataValue,c.rank);case'NumberCalculationPart':assert(Number.isFinite(n.mNumber));return n.mNumber;case'EffectValueCalculationPart':{const v=m.mEffectAmount[n.mEffectIndex-1].value[c.rank];assert(Number.isFinite(v));return v;}case'StatByCoefficientCalculationPart':case'StatByNamedDataValueCalculationPart':{assert(!n.UseNewStats);assert.equal(n.mStatFormula??0,0);const stat=n.mStat??0;assert([0,2].includes(stat));const value=required(c,stat===0?'AP':'totalAD');return value*(n.__type==='StatByCoefficientCalculationPart'?n.mCoefficient:sourceData(key,n.mDataValue,c.rank));}case'ByCharLevelBreakpointsCalculationPart':assert.equal(key,'ekko_p');return required(c,'char_level_base_damage');default:throw Error('Unsupported source node '+n.__type);}}
 function sourceCalc(key,calcKey,c){const n=sources.get(key).object.mSpell.mSpellCalculations[calcKey];assert(n,'source calc '+key+'/'+calcKey);assert(n.ResultModifier===undefined,'unresolved modifier');const mult=n.mMultiplier?sourcePart(key,n.mMultiplier,c):1;if(n.__type==='GameCalculationModified')return mult*sourceCalc(key,n.mModifiedGameCalculation,c);assert.equal(n.__type,'GameCalculation');return mult*n.mFormulaParts.reduce((sum,p)=>sum+sourcePart(key,p,c),0);}
 function evaluate(key,n,c){if(n.nodeType==='PARAMETER'){const p=skills[key].parameters.find(p=>p.parameterKey===n.parameterKey);assert(p);if(p.valueMode==='FIXED'){assert(Number.isFinite(p.fixedValue));return p.fixedValue;}if(p.valueMode==='SKILL_LEVEL'){assert(Object.hasOwn(p.levelValues,c.rank));return p.levelValues[c.rank];}assert.equal(p.valueMode,'RUNTIME_INPUT');assert.equal(p.fixedValue,null);assert.equal(p.levelValues,null);const v=required(c,p.parameterKey);if(p.valueType==='INTEGER')assert(Number.isInteger(v));return v;}if(n.nodeType==='ATTRIBUTE'){assert.equal(n.attributeOwner,'SOURCE');assert.equal(n.attributeValueKind,'TOTAL');assert(['ability_power','attack_damage'].includes(n.attributeKey));return required(c,n.attributeKey==='ability_power'?'AP':'totalAD');}assert.equal(n.nodeType,'OPERATION');const v=n.operands.map(x=>evaluate(key,x,c));assert(v.length>=2);switch(n.operation){case'ADD':return v.reduce((a,b)=>a+b,0);case'MULTIPLY':return v.reduce((a,b)=>a*b,1);case'MIN':return Math.min(...v);case'MAX':return Math.max(...v);default:throw Error('Unexpected operation '+n.operation);}}
 function expected(key,f,c){if(mapping[key]?.[f])return sourceCalc(key,mapping[key][f],c);if(key==='fizz_p'&&f==='capped_damage_reduction')return Math.min(sourceCalc(key,'DamageReductionCalc',c),sourceData(key,'DamageReductionMax',c.rank)*required(c,'damage_before_this_reduction'));if(key==='ekko_w'&&f==='eligible_on_hit_damage'){const text=sources.get(key).currentTexts.keyTooltipExtendedBelowLine.text;assert(text.includes('最少造成')&&text.includes('对小兵和野怪最多'));return Math.max(sourceData(key,'OnHitMinMinionDamage',c.rank),sourceCalc(key,'MissingHealthPercent',c)*required(c,'target_missing_health_for_on_hit'));}if(key==='ekko_r'&&f==='history_amplified_heal'){assert(sources.get(key).currentTexts.keyTooltip.text.includes('最近4秒里每损失1%生命值'));return sourceCalc(key,'TotalBaseHeal',c)*(1+sourceData(key,'PercentHealAmpPerPercentMissingHealth',c.rank)/100*required(c,'past_missing_health_percent_points'));}throw Error('Unmapped formula '+key+'/'+f);}
 function dependencies(key,n,set=new Set()){if(n.nodeType==='ATTRIBUTE')set.add(n.attributeKey==='ability_power'?'AP':'totalAD');if(n.nodeType==='PARAMETER'&&skills[key].parameters.find(p=>p.parameterKey===n.parameterKey).valueMode==='RUNTIME_INPUT')set.add(n.parameterKey);for(const o of n.operands??[])dependencies(key,o,set);return set;}
 let formulaCount=0,positive=0,rejections=0,resourceEffects=0;for(const[key,s]of Object.entries(skills)){for(const p of s.parameters){assert(!Object.hasOwn(p,'reuse'));if(p.valueMode==='RUNTIME_INPUT'){assert.equal(p.fixedValue,null);assert.equal(p.levelValues,null);}}for(const effect of s.effects){assert.equal(effect.results.length,1);const result=effect.results[0];assert.equal(result.resultType,'RESOURCE_CHANGE');assert.equal(result.target,'SOURCE');assert.equal(result.detail.attributeKey,'mana');assert.equal(result.detail.operation,'CONSUME');assert.equal(result.valueRule.value.kind,'PARAMETER');assert.equal(result.valueRule.value.parameterKey,'mana_cost');resourceEffects++;}for(const f of s.formulas){formulaCount++;const rankMax=key.endsWith('_p')?1:key.endsWith('_r')?3:5;for(const c of [{rank:1,AP:100,totalAD:200,bonusAD:100,char_level_base_damage:30,damage_before_this_reduction:8,target_missing_health_for_on_hit:50,past_missing_health_percent_points:30},{rank:rankMax,AP:173,totalAD:287,bonusAD:91,char_level_base_damage:121,damage_before_this_reduction:100,target_missing_health_for_on_hit:1000,past_missing_health_percent_points:100}]){const actual=evaluate(key,f.expression,c),want=expected(key,f.formulaKey,c);assert(Math.abs(actual-want)<1e-4,`${key}/${f.formulaKey}: ${actual} versus ${want}`);reports.push({skillKey:key,formulaKey:f.formulaKey,inputs:c,actual,sourceExpected:want,passed:true});positive++;}for(const dep of dependencies(key,f.expression)){const c={rank:1,AP:100,totalAD:200,bonusAD:100,char_level_base_damage:30,damage_before_this_reduction:8,target_missing_health_for_on_hit:50,past_missing_health_percent_points:30};delete c[dep];assert.throws(()=>evaluate(key,f.expression,c),/missing/);rejections++;reports.push({skillKey:key,formulaKey:f.formulaKey,missingInput:dep,rejected:true});}}}
 const boundaryChecks=[];for(const[key,f,field,values,wants]of [['fizz_p','capped_damage_reduction','damage_before_this_reduction',[0,8,10,100],[0,4,5,5]],['ekko_w','eligible_on_hit_damage','target_missing_health_for_on_hit',[0,200,250,300],[15,15,15,18]],['ekko_r','history_amplified_heal','past_missing_health_percent_points',[0,30,100],[160,304,640]]])for(let i=0;i<values.length;i++){const formula=skills[key].formulas.find(x=>x.formulaKey===f),context={rank:1,AP:100,[field]:values[i]},actual=evaluate(key,formula.expression,context);assert(Math.abs(actual-wants[i])<1e-8);boundaryChecks.push({skillKey:key,formulaKey:f,input:values[i],actual,expected:wants[i],passed:true});}
 assert.equal(formulaCount,21);assert.equal(resourceEffects,8);return{formulaCount,positiveCases:positive,missingInputRejections:rejections,boundaryCases:boundaryChecks.length,totalChecks:positive+rejections+boundaryChecks.length,resourceEffects,passed:true,reports,boundaryChecks,sourceBoundary:'等级基础实值为明确外供输入，未展开未知曲线；基于当前根树和文字的数学核对，不表示游戏执行。'};
}
