import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
assert.deepEqual(process.argv.slice(2),['--browser-verified']);const d='C:/project/damage_web_dev/.agents/artifacts/hero31-luna-candidate/修订三',calls=[],cases=[],p={},f={};assert.equal(JSON.parse(fs.readFileSync(d+'/实际写入锁.json')).status,'COMPLETED');
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer local-entry'},signal:AbortSignal.timeout(30000)});assert.equal(r.status,200,route);const data=await r.json();calls.push({route,status:200,data});return data;}
for(const k of ['janna_w','lulu_w','nami_w','morgana_e']){await get('/skills/'+k);assert((await get('/skills/'+k+'/representative-image')).image);p[k]=await get('/skills/'+k+'/parameters');}
for(const[k,keys]of Object.entries({janna_w:['total_move_speed_ratio','total_magic_damage','total_slow_ratio'],lulu_w:['ally_move_speed_ratio'],nami_w:['first_damage','first_heal','bounce_scaling_ratio','bounced_damage','bounced_heal'],morgana_e:['magic_shield_value']}))for(const key of keys)f[k+'/'+key]=await get('/skills/'+k+'/formulas/'+key);
const as=await get('/skills/lulu_w/effects/self_attack_speed'),shield=await get('/skills/morgana_e/effects/magic_shield');
function val(k,key,l,runtime){const x=p[k].find(x=>x.parameterKey===key);assert(x,key);const v=x.valueMode==='FIXED'?x.fixedValue:x.valueMode==='SKILL_LEVEL'?x.levelValues?.[l]:runtime[key];if(x.valueMode==='RUNTIME_INPUT'){assert.equal(x.fixedValue,null);assert.equal(x.levelValues,null);}assert(Number.isFinite(v),'缺值 '+key);if(x.valueType==='INTEGER')assert(Number.isInteger(v));return v;}
function ev(n,k,l,ap,runtime){if(n.nodeType==='PARAMETER')return val(k,n.parameterKey,l,runtime);if(n.nodeType==='ATTRIBUTE'){assert.equal(n.attributeOwner,'SOURCE');assert.equal(n.attributeKey,'ability_power');assert.equal(n.attributeValueKind,'TOTAL');return ap;}assert(n.nodeType==='OPERATION'&&n.operands.length===2);const[a,b]=n.operands.map(x=>ev(x,k,l,ap,runtime));switch(n.operation){case'ADD':return a+b;case'SUBTRACT':return a-b;case'MULTIPLY':return a*b;case'DIVIDE':return a/b;case'MIN':return Math.min(a,b);case'MAX':return Math.max(a,b);default:throw Error(n.operation);}}
function check(k,key,l,ap,runtime,expected){const actual=ev(f[k+'/'+key].expression,k,l,ap,runtime);assert(Math.abs(actual-expected)<=1e-6*Math.max(1,Math.abs(expected)),`${key}: ${actual} != ${expected}`);cases.push({skillKey:k,formulaKey:key,skillLevel:l,abilityPower:ap,runtime,actual,expected,passed:true});}
for(const[l,ap,ms,speed,damage,slow]of [[1,100,50,.08,120,.26],[5,300,180,.16,379,.54]])for(const[key,value]of [['total_move_speed_ratio',speed],['total_magic_damage',damage],['total_slow_ratio',slow]])check('janna_w',key,l,ap,{actual_bonus_move_speed:ms},value);
check('lulu_w','ally_move_speed_ratio',1,100,{},.3);check('lulu_w','ally_move_speed_ratio',5,300,{},.4);
for(const[l,ap,damage,heal,bounce,secondDamage,secondHeal]of [[1,100,110,95,-.05,104.5,90.25],[5,300,350,275,.25,437.5,343.75]])for(const[key,value]of [['first_damage',damage],['first_heal',heal],['bounce_scaling_ratio',bounce],['bounced_damage',secondDamage],['bounced_heal',secondHeal]])check('nami_w',key,l,ap,{},value);
check('morgana_e','magic_shield_value',1,100,{},170);check('morgana_e','magic_shield_value',5,300,{},530);
assert.deepEqual(as.results[0].valueRule.value,{kind:'PARAMETER',parameterKey:'attack_speed_bonus_ratio'});assert.equal(as.results[0].detail.attributeKey,'bonus_attack_speed_percent');assert.equal(val('lulu_w','attack_speed_bonus_ratio',1,{}),.2);assert.equal(val('lulu_w','attack_speed_bonus_ratio',5,{}),.3);assert.equal(val('lulu_w','ally_buff_duration_ms',1,{}),3000);assert.equal(val('lulu_w','ally_buff_duration_ms',5,{}),4000);assert(!p.lulu_w.some(x=>x.parameterKey==='slow_percent_points'));assert.equal(val('lulu_w','polymorph_slow_amount',1,{}),-60);assert.equal(shield.results[0].resultType,'NORMAL_SHIELD');assert.equal(shield.results[0].detail.absorbedDamageTypeKey,'magic');assert.equal(val('morgana_e','shield_duration_ms',1,{}),5000);assert.equal(calls.length,24);assert.equal(cases.length,20);
fs.writeFileSync(d+'/页面验收.json',JSON.stringify({at:new Date().toISOString(),passed:true,browser:'Codex内置浏览器tab2，实际查询4技能并打开参数、公式、效果及结果详情，http://127.0.0.1:5173/#/skills',representativePages:4,observations:[{skillKey:'janna_w',ui:'额外移动速度点数为无默认实际输入，W完整式只加一次P的0.3项。'},{skillKey:'lulu_w',ui:'攻速效果当前选择技能参数并显示attack_speed_bonus_ratio，持久生效、施加快照、属性增加；变形原始减速量的单位修正另有实际回读。'},{skillKey:'nami_w',ui:'第二目标伤害=首个完整伤害×(1+弹跳修正)，一对一只允许敌人和自身各一次。'},{skillKey:'morgana_e',ui:'结果为普通护盾，只吸收魔法伤害；不是抵消一次技能的法术护盾，控制免疫接线另记。'}],GETs:24,mathCases:20,calls,cases,apiWrites:0,runtimeValidation:'未执行',scriptSha256:crypto.createHash('sha256').update(fs.readFileSync(new URL(import.meta.url))).digest('hex')},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,GETs:24,mathCases:20,pages:4}));

