import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {makeRequest,compareEntry,applyMissing,entries,same,here} from './接口工具.mjs';
const checks=[];async function check(name,fn){await fn();checks.push({name,match:true});}
const body={skillKey:'item_3033_passive',name:'凡性的提醒·重伤',description:'当前说明',maxLevel:1,status:'ENABLED',sortOrder:0,skillCategoryKeys:['passive']},o={equipmentKey:'item_3033',skillKey:body.skillKey,equipmentName:'凡性的提醒',apiPayload:{skill:body},safeguards:{representativeImage:{image:{imageKey:'item_3033',enabled:true,name:'item_3033'}}}},e={equipmentKey:o.equipmentKey,skillKey:o.skillKey,kind:'skill',route:'/skills/'+o.skillKey,createRoute:'/skills',method:'POST',expected:body},missing={status:404,ok:false,data:null},ok=data=>({status:200,ok:true,data});
await check('默认只读且批次外写入禁止',async()=>{await assert.rejects(makeRequest()('/skills',{method:'POST',body}));await assert.rejects(makeRequest(true)('/skills',{method:'POST',body:{...body,skillKey:'item_9999_passive'}}));await assert.rejects(makeRequest(true)('/skills/item_3033_passive',{method:'PUT',body}));await assert.rejects(makeRequest(true)('/equipment/item_3033',{method:'DELETE'}));});
await check('全部业务字段参与比较，服务器时间不混入载荷',()=>{assert.equal(compareEntry(o,e,ok({...body,gameId:'lol',createdAt:'now'})).state,'same');assert.equal(compareEntry(o,e,ok({...body,description:'其他修改'})).state,'conflict');assert.equal(compareEntry(o,e,ok({...body,unexpected:true})).state,'conflict');});
await check('已有不同图片或其他关联均为冲突',()=>{assert.equal(compareEntry(o,{kind:'image',expected:{imageKey:'item_3033'}},ok({image:{imageKey:'another',enabled:true,name:'another'}})).state,'conflict');assert.equal(compareEntry(o,{kind:'relation',expected:{equipmentKey:o.equipmentKey,skillKey:o.skillKey,sortOrder:10}},ok({items:[{skillKey:'other'}],total:1})).state,'conflict');});
await check('全局冲突时业务请求零次',async()=>{let n=0;await assert.rejects(applyMissing({objects:[o]},{conflicts:[{}],missing:[e]},{request:async()=>{n++;}}));assert.equal(n,0);});
await check('写前同值跳过，不发写请求',async()=>{let n=0;const r=await applyMissing({objects:[o]},{conflicts:[],missing:[e]},{request:async(_r,opt={})=>{if(opt.method)n++;return ok(body);}});assert.equal(n,0);assert.equal(r.events[0].action,'写前同值跳过');});
await check('写响应断线后GET确认一次落地，不重发',async()=>{let posted=false,n=0;const r=await applyMissing({objects:[o]},{conflicts:[],missing:[e]},{request:async(_r,opt={})=>{if(opt.method){n++;posted=true;throw Error('模拟断线');}return posted?ok(body):missing;}});assert.equal(n,1);assert.equal(r.events.at(-1).match,true);});
await check('图片写前出现不同值时不覆盖',async()=>{let n=0;await assert.rejects(applyMissing({objects:[o]},{conflicts:[],missing:[{...e,kind:'image',route:e.route+'/representative-image',method:'PUT',expected:{imageKey:'item_3033'}}]},{request:async()=>{n++;return ok({image:{imageKey:'other',name:'other',enabled:true}});}}));assert.equal(n,1);});
await check('候选变化在请求前停止',async()=>{let n=0;await assert.rejects(applyMissing({objects:[o]},{conflicts:[],missing:[e]},{assertUnchanged:async()=>{throw Error('候选改变');},request:async()=>{n++;}}));assert.equal(n,0);});
await check('公式操作数顺序保持',()=>{assert.equal(same({operands:[1,2]},{operands:[2,1]}),false);});
await writeFile(new URL('入口安全核对.json',here),JSON.stringify({at:new Date().toISOString(),boundary:'离线模拟，业务网络请求0次',checks},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,failures:0,businessRequests:0}));
