// 此入口只有GET。候选阶段显式拒绝--apply及其他参数。
import {readFile,writeFile,access} from 'node:fs/promises';
import assert from 'node:assert/strict';
if(process.argv.length>2)throw Error('第十二批当前仅允许无参数只读前检，未授权写业务接口');
const here=new URL('./',import.meta.url),source=JSON.parse(await readFile(new URL('冻结来源.json',here),'utf8')),out={at:new Date().toISOString(),boundary:'仅GET；不创建技能、装备关联、图片或组成。',catalogs:{},skillInventory:[],objects:[],references:[]};
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer local-entry',Accept:'application/json'},signal:AbortSignal.timeout(15000)});return {route,status:r.status,data:await r.json()};}
const items=r=>Array.isArray(r.data)?r.data:r.data?.items;
for(const key of ['attributes','modifier-zones','statuses','skill-categories']){const r=await get('/'+key+'?page=1&pageSize=200');assert.equal(r.status,200,key);assert.ok(Array.isArray(items(r)));if(r.data.total!=null)assert.equal(items(r).length,r.data.total,key+'必须完整');out.catalogs[key]=r;}
let total=null;for(let page=1;total===null||out.skillInventory.length<total;page++){const r=await get('/skills?page='+page+'&pageSize=200');assert.equal(r.status,200);assert.ok(Array.isArray(items(r)));if(total===null)total=r.data.total??items(r).length;if(!items(r).length&&out.skillInventory.length<total)throw Error('技能清单提前结束');out.skillInventory.push(...items(r).map(s=>({skillKey:s.skillKey,name:s.name})));if(Array.isArray(r.data))break;}
assert.equal(new Set(out.skillInventory.map(s=>s.skillKey)).size,out.skillInventory.length);assert.equal(out.skillInventory.length,total);
for(const o of source.objects){const skillKey=o.equipmentKey+([2420,3139].includes(o.id)?'_active':'_passive'),records=[];for(const route of ['/equipment/'+o.equipmentKey,'/equipment/'+o.equipmentKey+'/attributes','/equipment/'+o.equipmentKey+'/representative-image','/equipment-skill-relations?equipmentKey='+o.equipmentKey,'/skills/'+skillKey]){const r=await get(route);assert.ok([200,404].includes(r.status),route);records.push(r);}out.objects.push({equipmentKey:o.equipmentKey,name:o.name,skillKey,possibleAliases:out.skillInventory.filter(s=>s.skillKey.startsWith(o.equipmentKey+'_')||s.skillKey===o.equipmentKey||s.name===o.name||s.name.startsWith(o.name+'·')),records});}
for(const key of ['item_3123_passive','item_3916_passive','item_3157_active','item_3140_active','item_3078_passive']){const r={skillKey:key,records:[]};for(const part of ['', '/parameters','/formulas','/effects','/processes','/internal-states','/trigger-rules']){const x=await get('/skills/'+key+part);assert.equal(x.status,200,key+part);r.records.push(x);if(['/effects','/processes','/trigger-rules'].includes(part))for(const i of items(x)){const id=i.effectKey??i.processKey??i.ruleKey;const d=await get('/skills/'+key+part+'/'+id);assert.equal(d.status,200);r.records.push(d);}}out.references.push(r);}
const original=new URL('写前现值.json',here);if(!await access(original).then(()=>true,()=>false))await writeFile(original,JSON.stringify(out,null,2)+'\n',{flag:'wx'});await writeFile(new URL('当前只读核对.json',here),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({skills:out.skillInventory.length,equipment:out.objects.length,aliases:out.objects.flatMap(o=>o.possibleAliases),references:out.references.length}));
