// 只读本地候选和最新GET证据，不调用写接口。
import {readFile,writeFile} from 'node:fs/promises';
import {isDeepStrictEqual} from 'node:util';
const here=new URL('./',import.meta.url),read=n=>readFile(new URL(n,here),'utf8').then(JSON.parse),p=await read('完整候选.json'),before=await read('当前只读核对.json'),source=await read('冻结来源.json'),checks=[];
function check(equipmentKey,name,match,detail=null){checks.push({equipmentKey,name,match,detail});}
const strip=o=>Object.fromEntries(Object.entries(o).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)));
for(const o of p.objects){const b=o.apiPayload,s=source.objects.find(x=>x.equipmentKey===o.equipmentKey),live=before.objects.find(x=>x.equipmentKey===o.equipmentKey),keys=new Set(b.parameters.map(x=>x.parameterKey)),forms=new Set(b.formulas.map(x=>x.formulaKey)),missing=[];
 function walk(n){if(!n||typeof n!=='object')return;if((n.kind==='PARAMETER'||n.nodeType==='PARAMETER')&&!keys.has(n.parameterKey))missing.push(n.parameterKey);if(n.kind==='FORMULA'&&!forms.has(n.formulaKey))missing.push(n.formulaKey);for(const v of Object.values(n))if(v&&typeof v==='object')walk(v);}
 walk(b);check(o.equipmentKey,'数值与公式引用完整',!missing.length,missing);check(o.equipmentKey,'技能键和装备关联不越界',b.skill.skillKey===o.skillKey&&b.relation.equipmentKey===o.equipmentKey&&b.relation.skillKey===o.skillKey);check(o.equipmentKey,'不重复施加装备直接属性',b.effects.every(e=>e.results.every(r=>r.resultType!=='ATTRIBUTE_CHANGE'||r.detail.attributeKey==='move_speed'||r.detail.attributeKey==='move_speed_percent')));check(o.equipmentKey,'原装备代表图仅复用',b.representativeImage.imageKey===live.records.find(r=>r.route.endsWith('/representative-image')).data.image.imageKey);check(o.equipmentKey,'来源对象当前编号一致',s.object.itemID===Number(o.equipmentKey.slice(5)));
 const attrItems=before.catalogs.attributes.data.items,zoneItems=before.catalogs['modifier-zones'].data.items;for(const e of b.effects)for(const r of e.results){if(r.resultType==='ATTRIBUTE_CHANGE')check(o.equipmentKey,'持续属性使用已有有效目录',attrItems.some(a=>a.attributeKey===r.detail.attributeKey&&a.status==='ENABLED')&&zoneItems.some(z=>z.modifierZoneKey===r.detail.modifierZoneKey&&z.domain==='ATTRIBUTE'&&z.status==='ENABLED'));check(o.equipmentKey,'持续效果为自身且期限有明确参数',r.target==='SOURCE'&&e.lifecycle.instanceScope==='SOURCE'&&e.lifecycle.durationValue.kind==='PARAMETER'&&keys.has(e.lifecycle.durationValue.parameterKey));}
}
const get=id=>p.objects.find(o=>o.equipmentKey==='item_'+id),pv=(id,key)=>get(id).apiPayload.parameters.find(p=>p.parameterKey===key)?.fixedValue;
for(const id of [3033,3165,6609]){check('item_'+id,'40%重伤3秒且无伪效果规则',pv(id,'grievous_amount')===.4&&pv(id,'grievous_duration_ms')===3000&&get(id).apiPayload.effects.length===0&&get(id).apiPayload.triggerRules.length===0);check('item_'+id,'重伤影响生命回复属于已确证来源',source.boundDefinitions.Item_KeywordDefinition_Wounds.text.includes('生命回复')&&get(id).disposition.来源待核.length===0);}
check('item_2420','单次凝滞2500毫秒，无沙漏冷却或重复过程',pv(2420,'stasis_duration_ms')===2500&&pv(2420,'maximum_uses')===1&&!get(2420).apiPayload.parameters.some(p=>p.parameterKey.includes('cooldown'))&&get(2420).apiPayload.processes.length===0);
const ref=before.references.find(r=>r.skillKey==='item_3157_active').records.find(r=>r.route.endsWith('/effects/stasis_damage_immunity')).data,stasis=get(2420).apiPayload.effects[0];check('item_2420','独立免伤结构复用已保存3157而非伪造凝滞',isDeepStrictEqual(stasis.lifecycle,ref.lifecycle)&&isDeepStrictEqual(stasis.results,ref.results)&&stasis.results[0].resultType==='DAMAGE_IMMUNITY');
check('item_3139','水银90秒、50%自身移速2秒',pv(3139,'active_cooldown_ms')===90000&&pv(3139,'move_speed_ratio')===.5&&pv(3139,'move_speed_duration_ms')===2000);
check('item_3139','未用只解眩晕或清空全部状态替代水银',get(3139).apiPayload.effects.every(e=>e.results.every(r=>r.resultType!=='STATUS_OPERATION'))&&get(3139).apiPayload.processes.length===0);
const ranged=get(3044).apiPayload.formulas.find(f=>f.formulaKey==='ranged_move_speed_bonus'),val=n=>pv(3044,n.parameterKey),actual=val(ranged.expression.operands[0])*val(ranged.expression.operands[1]);check('item_3044','独立读取保存候选公式得远程10点',ranged.expression.operation==='MULTIPLY'&&actual===10,{expected:10,actual});check('item_3044','近战20、远程10且无无条件20点规则',pv(3044,'melee_move_speed_bonus')===20&&get(3044).apiPayload.effects.length===2&&get(3044).apiPayload.triggerRules.length===0);
const out={at:new Date().toISOString(),boundary:'本地冻结来源、候选结构与最新只读目录核对；没有业务写入，没有战斗或浏览器验证。',checks,failures:checks.filter(x=>!x.match)};await writeFile(new URL('独立候选核对.json',here),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,failures:out.failures}));if(out.failures.length)process.exitCode=1;
