// 默认生成前三件；--full纳入另外三件。只写本目录候选，不调用业务接口。
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const here=new URL('./',import.meta.url),read=p=>readFile(new URL(p,here),'utf8').then(JSON.parse),source=await read('冻结来源.json'),before=await read('当前只读核对.json'),full=process.argv.includes('--full');
if(process.argv.slice(2).some(a=>a!=='--full'))throw Error('只允许默认前三件或--full');
export const clean=n=>Math.round(n*1e6)/1e6,parameterValue=parameterKey=>({kind:'PARAMETER',parameterKey}),fixed=value=>({kind:'FIXED',value});
export function parameter(key,name,value,description,sortOrder){assert.ok(Number.isFinite(value));return {parameterKey:key,name,valueType:Number.isInteger(value)?'INTEGER':'DECIMAL',valueMode:'FIXED',fixedValue:value,levelValues:null,description,sortOrder};}
export function data(o,key){const v=o.object.mDataValues.find(v=>v.mName===key)?.mValue;assert.ok(Number.isFinite(v),o.equipmentKey+'/'+key);return clean(v);}
export function base(o,suffix,skillName,description){const skillKey=o.equipmentKey+'_'+suffix,current=before.objects.find(x=>x.equipmentKey===o.equipmentKey),equipment=current.records.find(r=>r.route==='/equipment/'+o.equipmentKey),relations=current.records.find(r=>r.route.startsWith('/equipment-skill-relations')),image=current.records.find(r=>r.route.endsWith('/representative-image'));assert.equal(equipment.status,200);assert.deepEqual(current.possibleAliases,[]);assert.equal((Array.isArray(relations.data)?relations.data:relations.data.items).length,0);assert.ok(image.data?.image?.imageKey,'装备原代表图缺失');return {equipmentKey:o.equipmentKey,equipmentName:o.name,skillKey,source:{path:o.path,bindings:o.bound,official:o.official,sourceFiles:source.sources},apiPayload:{skill:{skillKey,name:skillName,description,maxLevel:1,status:'ENABLED',sortOrder:0,skillCategoryKeys:suffix==='passive'?['passive']:[]},parameters:[],formulas:[],effects:[],processes:[],internalStates:[],triggerRules:[],relation:{equipmentKey:o.equipmentKey,skillKey,sortOrder:10},representativeImage:{imageKey:image.data.image.imageKey}},disposition:{范围外:[],来源待核:[],系统缺口:[],尚未接线:[]},proofs:[],arithmetic:[],safeguards:{equipment:equipment.data,attributes:current.records.find(r=>r.route.endsWith('/attributes')).data,representativeImage:image.data,relations:relations.data}};}
const objects=[];
for(const id of [3033,3165,6609]){const o=source.objects.find(o=>o.id===id),type=id===3165?'魔法':'物理',name=id===6609?'劈削':'重伤',x=base(o,'passive',o.name+'·'+name,`当前绑定说明：对敌方英雄造成${type}伤害时施加40%重伤，持续3秒。本候选记录确证参数；重伤跨来源取强、治疗和生命回复覆盖、伤害事件英雄门槛仍待配。装备直接属性由装备自身提供，不重复施加。`),amount=data(o,'GrievousAmount'),duration=data(o,'GrievousDuration');assert.equal(amount,.4);assert.equal(duration,3);assert.ok(o.bound.keyTooltip.text.includes(type));
 x.apiPayload.parameters=[parameter('grievous_amount','重伤减疗比例',amount,'当前根GrievousAmount与绑定主说明共同确证，0.4表示40%。',10),parameter('grievous_duration_ms','重伤持续时间',duration*1000,'当前根GrievousDuration=3秒，换算3000毫秒。',20)];
 x.proofs.push({source:o.path+'/mDataValues',raw:o.object.mDataValues,accepted:{grievous_amount:amount,grievous_duration_ms:duration*1000},trigger:`对敌方英雄造成${type}伤害`,damageTypeKey:id===3165?'magic':'physics'});
 x.disposition.系统缺口.push({component:'多个重伤来源只取最强',reason:'沿用3123/3916既有实录结论：普通比例加算会将两份40%叠成80%，不能仅新增治疗乘区就提交。跨来源取强方式待补。'},{component:'伤害事件与英雄类别门槛',reason:`当前要求对敌方英雄造成${type}伤害，不是任意命中。既有实录发现DAMAGE_DEALT与英雄类别条件尚不能完整组合，未新造事件或放宽目标。`});
 x.disposition.系统缺口.push({component:'重伤对生命回复的完整覆盖',reason:'当前绑定重伤定义已明确同时降低治疗与生命回复，游戏文字来源已确证；当前配置到运行的hp_regen覆盖路径尚未验证，不能把单个治疗修正结果当作完整覆盖。'});
 x.disposition.尚未接线.push({component:'3秒重伤实例与刷新',reason:'待跨来源取强、作用范围及输入组合明确后，按来源目标期限配置重伤效果和刷新；本阶段效果、过程、状态、规则均为空。'});
 x.arithmetic.push({sample:'单份40%重伤作用于100治疗点，仅算术',expected:40,actual:100*amount,match:100*amount===40},{sample:'持续3秒换算毫秒',expected:3000,actual:duration*1000,match:duration*1000===3000},{sample:'同强度两份重伤仍为40%，禁止直接相加',expected:.4,actual:Math.max(amount,amount),match:Math.max(amount,amount)===.4,boundary:'机制要求算例，尚无已保存效果实现该行为'});objects.push(x);
}
if(full){const {extra}=await import('./其余三件组成.mjs');objects.push(...extra({source,before,base,data,parameter,parameterValue,fixed}));}
const totals={skills:objects.length,parameters:objects.reduce((n,o)=>n+o.apiPayload.parameters.length,0),formulas:objects.reduce((n,o)=>n+o.apiPayload.formulas.length,0),effects:objects.reduce((n,o)=>n+o.apiPayload.effects.length,0),processes:objects.reduce((n,o)=>n+o.apiPayload.processes.length,0),internalStates:objects.reduce((n,o)=>n+o.apiPayload.internalStates.length,0),triggerRules:objects.reduce((n,o)=>n+o.apiPayload.triggerRules.length,0),relations:objects.length,representativeImages:objects.length};
const out={generatedAt:new Date().toISOString(),stage:'仅来源和候选，未授权业务写入',clientVersion:'16.17',officialVersion:'16.17.1',objects,totals,entryBoundary:'只读前检.mjs仅GET且拒绝--apply；当前没有创建入口。'};
const prefix=full?'完整':'前三件';await writeFile(new URL(prefix+'候选.json',here),JSON.stringify(out,null,2)+'\n');
const tests=objects.flatMap(o=>o.arithmetic.map(a=>({equipmentKey:o.equipmentKey,...a})));assert.ok(tests.every(t=>t.match));await writeFile(new URL(prefix+'独立算术.json',here),JSON.stringify({boundary:'冻结来源及候选算术，不表示数据库保存或战斗运行',tests},null,2)+'\n');
const lines=['# 第十二批常规装备效果候选','',`本文件记录${objects.length}件装备候选，未调用业务写接口。原装备、直接属性、原代表图和现有关系保持只读。`,'',`候选数量：${JSON.stringify(totals)}；独立算术与机制约束样例${tests.length}项通过。`,''];for(const o of objects){lines.push(`## ${o.equipmentName} ${o.equipmentKey}`,'');for(const [kind,list]of Object.entries(o.disposition))lines.push(`**${kind}**：${list.length?list.map(v=>v.component+'：'+v.reason).join('；'):'无新增记录。'}`,'');}await writeFile(new URL(prefix+'审查说明.md',here),lines.join('\n')+'\n');console.log(JSON.stringify({objects:objects.length,totals,samples:tests.length}));
