package xyz.game.datamanage.model.skilleffect;

public enum SkillEffectResultType {
    DAMAGE,
    DIRECT_HEAL,
    NORMAL_SHIELD,
    ATTRIBUTE_CHANGE,
    RESOURCE_CHANGE,
    COOLDOWN_CHANGE,
    STATUS_OPERATION,
    LIFECYCLE_OPERATION,
    DAMAGE_MODIFIER,
    HEALING_MODIFIER,
    DAMAGE_IMMUNITY,
    HEALTH_FLOOR,
    SPELL_SHIELD,
    EXECUTE,
    HIT_LINK_APPLICATION,
    ATTACK_LINK_APPLICATION
}
