import {readFile,writeFile,appendFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {objects} from './录入装备技能.mjs';
export const here=path.dirname(fileURLToPath(import.meta.url));
export const kinds=[['parameters','parameterKey','parameters'],['formulas','formulaKey','formulas'],['effects','effectKey','effects'],['triggerRules','ruleKey','trigger-rules'],['processes','processKey','processes'],['internalStates','stateKey','internal-states']];
export async function request(route,method='GET',body){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer local-entry',Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});const raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null;}catch{throw Error('响应非JSON '+route);}return{status:r.status,ok:r.ok,data};}
export function compare(expected,actual,p=''){if(expected===actual)return [];if(expected===null||typeof expected!=='object')return[{path:p,expected,actual}];if(actual===null||typeof actual!=='object')return[{path:p,expected,actual}];if(Array.isArray(expected)){if(!Array.isArray(actual)||actual.length!==expected.length)return[{path:p,expected,actual}];return expected.flatMap((v,i)=>compare(v,actual[i],p+'['+i+']'));}return Object.entries(expected).flatMap(([k,v])=>compare(v,actual[k],p?(p+'.'+k):k));}
const strip=(v,id)=>Object.fromEntries(Object.entries(v).filter(([k])=>k!==id&&!['gameId','createdAt','updatedAt'].includes(k)));
export const original=(JSON.parse(await readFile(path.join(here,'修正前证据/录入候选.json'),'utf8'))).objects;
export async function getEzBaseline(){const file=path.join(here,'ez_r修正前.json');try{return JSON.parse(await readFile(file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;const got=await request('/skills/ez_r');if(!got.ok||JSON.stringify(got.data.skillCategoryKeys)!=='["common"]')throw Error('旧ez_r首次分类与已审现值不符');await writeFile(file,JSON.stringify(got.data,null,2)+'\n');return got.data;}}
export async function buildMutations(){const find=(set,id,kind,key,keyField)=>set.find(o=>o.skill.skillKey===id)[kind].find(v=>v[keyField]===key);const defs=[['item_3065_passive','triggerRules','trigger-rules','ruleKey','initialize_heal_shield_power_bonus','DELETE'],['item_3065_passive','effects','effects','effectKey','heal_shield_power_bonus','DELETE'],['item_3065_passive','parameters','parameters','parameterKey','heal_shield_power_bonus','PUT'],['item_6621_passive','effects','effects','effectKey','ap_from_base_mana_regen','PUT'],['item_6621_passive','effects','effects','effectKey','heal_shield_from_base_mana_regen','PUT'],['item_3124_passive','effects','effects','effectKey','attack_speed_stack','PUT'],['item_3008_passive','effects','effects','effectKey','omnivamp_kill_stack','PUT']];const list=defs.map(([skill,kind,apiKind,keyField,key,method])=>({route:'/skills/'+skill+'/'+apiKind+'/'+key,skill,kind,key,keyField,method,original:find(original,skill,kind,key,keyField),target:method==='DELETE'?null:find(objects,skill,kind,key,keyField)}));const ez=await getEzBaseline(),ezBody=strip(ez,'skillKey');list.push({route:'/skills/ez_r',skill:'ez_r',kind:'skill',key:'ez_r',keyField:'skillKey',method:'PUT',original:ezBody,target:{...ezBody,skillCategoryKeys:ezBody.skillCategoryKeys.filter(v=>v!=='common')}});return list;}
async function main(){const apply=process.argv.includes('--apply'),mutations=await buildMutations();const out={at:new Date().toISOString(),mode:apply?'explicit-apply':'read-only',preflight:[],conflicts:[],writes:[],note:'全批旧值或精确目标检查后，仅执行8项已审纠错；不改共享目录。'};
 for(const obj of objects){const key=obj.skill.skillKey,old=original.find(o=>o.skill.skillKey===key);const skill=await request('/skills/'+key);const sd=skill.ok?compare(obj.skill,skill.data):[{status:skill.status}];out.preflight.push({route:'/skills/'+key,status:skill.status,differences:sd});if(sd.length)out.conflicts.push(...sd.map(d=>({skill:key,...d})));
  for(const[kind,idField,apiKind]of kinds){const base='/skills/'+key+'/'+apiKind,got=await request(base);if(!got.ok||!Array.isArray(got.data))throw Error('列表读取失败 '+base);const oldItems=old[kind]??[],targets=obj[kind]??[],ids=new Set([...oldItems,...targets].map(v=>v[idField]));for(const item of got.data)if(!ids.has(item[idField]))out.conflicts.push({route:base,unexpected:item[idField]});for(const id of ids){const route=base+'/'+encodeURIComponent(id),r=await request(route),before=oldItems.find(v=>v[idField]===id),target=targets.find(v=>v[idField]===id),originalMatch=before&&r.ok&&!compare(before,r.data).length,targetMatch=target?r.ok&&!compare(target,r.data).length:r.status===404;out.preflight.push({route,status:r.status,originalMatch:!!originalMatch,targetMatch,actual:r.data});if(!originalMatch&&!targetMatch)out.conflicts.push({route,status:r.status,targetDifference:target?compare(target,r.data):null});}}
 }
 const ez=mutations.at(-1),er=await request(ez.route),ezOldMatch=er.ok&&!compare(ez.original,er.data).length,ezTargetMatch=er.ok&&!compare(ez.target,er.data).length;out.preflight.push({route:ez.route,status:er.status,originalMatch:ezOldMatch,targetMatch:ezTargetMatch,actual:er.data});if(!ezOldMatch&&!ezTargetMatch)out.conflicts.push({route:ez.route,difference:compare(ez.original,er.data)});
 await writeFile(path.join(here,apply?'纠错写前检查.json':'纠错只读检查.json'),JSON.stringify(out,null,2)+'\n');if(out.conflicts.length)throw Error('整批预检存在其他现值差异；停止所有纠错');
 for(const m of mutations){if(!apply)continue;const before=await request(m.route),same=m.target?before.ok&&!compare(m.target,before.data).length:before.status===404;if(same){out.writes.push({route:m.route,action:'same-target-skip'});continue;}if(!before.ok||compare(m.original,before.data).length)throw Error('写前值改变，停止 '+m.route);const written=await request(m.route,m.method,m.target?strip(m.target,m.keyField):undefined);if(!written.ok)throw Error(m.method+'失败 '+m.route+' '+written.status+' '+JSON.stringify(written.data));const after=await request(m.route);const match=m.target?after.ok&&!compare(m.target,after.data).length:after.status===404;const row={at:new Date().toISOString(),route:m.route,method:m.method,writeStatus:written.status,readbackStatus:after.status,match,before:before.data,after:after.data};await appendFile(path.join(here,'纠错流水.jsonl'),JSON.stringify(row)+'\n');out.writes.push(row);if(!match)throw Error('写后GET不符 '+m.route);}
 out.finishedAt=new Date().toISOString();await writeFile(path.join(here,apply?'纠错结果.json':'纠错只读检查.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({mode:out.mode,preflight:out.preflight.length,conflicts:out.conflicts.length,writes:out.writes.filter(w=>w.method).length,skips:out.writes.filter(w=>w.action).length}));
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))await main();
