import {writeFile} from 'node:fs/promises';
import {objects} from './录入装备技能.mjs';
import {request,compare,kinds,getEzBaseline} from './有界纠错.mjs';
const out={startedAt:new Date().toISOString(),boundary:'独立GET、字段和配置语义算例；不是实际战斗、Wasm或浏览器运行。',checks:[],arithmetic:[],invariants:[],failures:[],counts:{skills:0,parameters:0,formulas:0,effects:0,triggerRules:0,processes:0,internalStates:0,relations:0,images:0},live:{}};
function check(route,expected,r){const differences=r.ok?compare(expected,r.data):[{status:r.status}];out.checks.push({route,status:r.status,expected,actual:r.data,differences});if(differences.length)out.failures.push({route,differences});}
for(const o of objects){const key=o.skill.skillKey,base='/skills/'+key;out.live[key]={};const skill=await request(base);check(base,o.skill,skill);out.counts.skills++;
 for(const[kind,idField,apiKind]of kinds){const expected=o[kind]??[],route=base+'/'+apiKind,list=await request(route);if(!list.ok||!Array.isArray(list.data))throw Error('GET列表失败 '+route);out.counts[kind]+=list.data.length;out.live[key][kind]={};const expectedKeys=expected.map(v=>v[idField]).sort(),actualKeys=list.data.map(v=>v[idField]).sort();if(JSON.stringify(expectedKeys)!==JSON.stringify(actualKeys))out.failures.push({route,expectedKeys,actualKeys});for(const item of list.data){const id=item[idField],r=await request(route+'/'+encodeURIComponent(id));out.live[key][kind][id]=r.data;const exp=expected.find(v=>v[idField]===id);if(exp)check(route+'/'+id,exp,r);}}
 const direct=await request('/equipment/'+o.equipmentKey+'/attributes');check('/equipment/'+o.equipmentKey+'/attributes',o.directAttributes,{...direct,data:direct.data?.attributeValues??direct.data});
 const rr='/equipment-skill-relations?equipmentKey='+o.equipmentKey,rels=await request(rr),related=(rels.data?.items??rels.data??[]).find(v=>v.skillKey===key);check(rr,o.relation,{...rels,data:related});if(related)out.counts.relations++;
 const image=await request('/equipment/'+o.equipmentKey+'/representative-image'),skillImage=await request(base+'/representative-image');const imageKey=image.data?.image?.imageKey;if(!image.ok||!imageKey)out.failures.push({route:'/equipment/'+o.equipmentKey+'/representative-image',status:image.status});check(base+'/representative-image',{image:{imageKey}},skillImage);if(skillImage.data?.image?.imageKey===imageKey)out.counts.images++;
}
const ezBefore=await getEzBaseline(),ez=await request('/skills/ez_r'),ezTarget={...ezBefore,skillCategoryKeys:ezBefore.skillCategoryKeys.filter(v=>v!=='common')};delete ezTarget.updatedAt;check('/skills/ez_r',ezTarget,ez);out.ez_r={before:ezBefore,after:ez.data};
function invariant(name,match,details=null){out.invariants.push({name,match,details});if(!match)out.failures.push({name,details});}
function sample(name,actual,expected,inputs){const match=Math.abs(actual-expected)<1e-9;out.arithmetic.push({name,inputs,actual,expected,match});if(!match)out.failures.push({name,actual,expected});}
function parameter(skill,key){const p=out.live[skill].parameters[key];if(p.valueMode!=='FIXED')throw Error('非固定参数');return p.fixedValue;}
function evalFormula(skill,key,attrs){const ev=n=>n.nodeType==='PARAMETER'?parameter(skill,n.parameterKey):n.nodeType==='ATTRIBUTE'?attrs[n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind]:({MULTIPLY:()=>ev(n.operands[0])*ev(n.operands[1]),ADD:()=>ev(n.operands[0])+ev(n.operands[1])}[n.operation])();return ev(out.live[skill].formulas[key].expression);}
const spirit='item_3065_passive',sp=parameter(spirit,'heal_shield_power_bonus');
sample('收到100治疗应按收到量增加25%，施放强度初值0不影响此期望',100*(1+sp),125,{receivedHealing:100,outgoingHealShieldPower:0,storedImplementation:'仅保留增幅参数，收到治疗效果尚待配置'});
sample('收到100护盾的来源期望',100*(1+sp),125,{receivedShield:100,outgoingHealShieldPower:0,storedImplementation:'收到护盾增幅结构待补'});
sample('旧错误的0强度乘1.25仍为0',0*(1+sp),0,{wrongAttribute:'heal_shield_power_percent'});
invariant('振奋已撤属性效果与其初始化规则',!out.live[spirit].effects.heal_shield_power_bonus&&!out.live[spirit].triggerRules.initialize_heal_shield_power_bonus);
const dawn='item_6621_passive';for(const [regen,expectedAP,expectedHSP]of [[1,10,.18],[2,20,.2],[3,30,.22]]){const attrs={'SOURCE.base_mana_regen_percent.TOTAL':regen};sample('黎明回蓝'+regen+'时额外AP',evalFormula(dawn,'ap_from_base_mana_regen',attrs),expectedAP,attrs);sample('黎明回蓝'+regen+'时总治疗护盾强度',.16+evalFormula(dawn,'heal_shield_from_base_mana_regen',attrs),expectedHSP,{...attrs,baseStrength:.16});}
for(const key of ['ap_from_base_mana_regen','heal_shield_from_base_mana_regen']){const r=out.live[dawn].effects[key].results[0];invariant('黎明'+key+'按当前值固定加算',r.detail.modifierZoneKey==='attribute_flat_add'&&r.lifecycleBehavior.valueReadMode==='MOMENT_EVALUATION'&&r.lifecycleBehavior.stackValueMode==='SHARED'&&r.lifecycleBehavior.reapplicationValueMode===null);}
for(const[skill,effectKey,param,maxParam,repetitions,expected]of [['item_3124_passive','attack_speed_stack','attack_speed_per_stack','attack_speed_max_stacks',[4,5],.32],['item_3008_passive','omnivamp_kill_stack','omnivamp_per_kill_stack','omnivamp_max_stacks',[10,11],.06]]){const e=out.live[skill].effects[effectKey],r=e.results[0],max=parameter(skill,maxParam),value=parameter(skill,param);invariant(skill+'按层值且满层不继续追加共享值',r.lifecycleBehavior.stackValueMode==='PER_STACK'&&r.lifecycleBehavior.valueReadMode==='APPLICATION_SNAPSHOT'&&r.lifecycleBehavior.reapplicationValueMode===null&&e.lifecycle.reapplicationStackMode==='INCREASE'&&r.detail.modifierZoneKey==='attribute_flat_add');for(const times of repetitions)sample(skill+'第'+times+'次应用仍受层数上限限制',Math.min(times,max)*value,expected,{applications:times,maxStacks:max,perStackValue:value,method:'按层上限与单层值的配置语义算例，未执行战斗'});}
invariant('暴食没有过宽击杀触发',!Object.keys(out.live.item_3008_passive.triggerRules).length);
invariant('暴食效果增加全能吸血而非移动速度',out.live.item_3008_passive.effects.omnivamp_kill_stack.results[0].detail.attributeKey==='omnivamp_percent');
const skills=await request('/skills');if(!skills.ok)throw Error('读取分类集合失败');const all=skills.data?.items??skills.data;if(!Array.isArray(all))throw Error('分类列表非数组');const basic=all.filter(s=>s.skillCategoryKeys.includes('common')),rSkills=all.filter(s=>s.skillKey.endsWith('_r'));out.classifications={totalSkills:all.length,basicCategory:basic.map(s=>s.skillKey),rSkills:rSkills.map(s=>({skillKey:s.skillKey,categories:s.skillCategoryKeys})),basicR:basic.filter(s=>s.skillKey.endsWith('_r')).map(s=>s.skillKey)};invariant('common类别集合已不含R',out.classifications.basicR.length===0,out.classifications.basicR);invariant('ez_r其它字段不变',compare(ezTarget,ez.data).length===0);
out.finishedAt=new Date().toISOString();await writeFile(new URL('./纠错后独立回读.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({counts:out.counts,checks:out.checks.length,arithmetic:out.arithmetic.length,invariants:out.invariants.length,failures:out.failures}));if(out.failures.length)process.exitCode=1;
