import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import{isDeepStrictEqual as equal}from'node:util';import{fileURLToPath}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),input=path.resolve(here,'../../hero29-root-entry-20260909'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const wanted={candidate:'3837264e96ce61ca1cb420a0d37cdadb19d5d3082240f92cff29baff335875b1',plan:'162f1637ac59183d198265a5c152d245c7a1b619efef742256f094bd98344eb0',input:'85459db3db119841a7950124c3661b7cc5625b7be3b2283fe5e31fc61d66349f'};
assert.equal(sha(here+'/完整候选.json'),wanted.candidate);assert.equal(sha(here+'/请求计划.json'),wanted.plan);assert.equal(sha(input+'/输入版本.json'),wanted.input);
const candidate=read(here+'/完整候选.json'),plan=read(here+'/请求计划.json'),version=read(input+'/输入版本.json'),baseline=read(input+'/参考资料/当前10槽保护快照.json');for(const x of version.sourceFiles)assert.equal(sha(input+'/'+x.path),x.sha256);

assert.equal(sha(input+'/来源绑定与当前文本.json'),'f09cf7a5e4f515d89860cf5f05cfd89eb3f2f42b7b19294c906740f6910f6341');assert.equal(sha(input+'/参考资料/当前10槽保护快照.json'),'e68afdd8f5b82dea441ac6fed6d2ecd912fc70d0a7b05812a22b695fffb73956');assert.equal(sha(input+'/主负责人源值核对说明.md'),'3839875a178be5932150348757b8cbe3e6d9187041e2c98384ab0cc7acee7bc2');
const apply=process.argv.includes('--apply');assert(process.argv.slice(2).every(a=>a==='--apply'));if(apply)assert.equal(process.env.HERO29_APPLY_CONFIRM,'CONFIRM_HERO29_COMPONENT_POSTS');
const kinds=[['parameters','parameterKey','parameters'],['formulas','formulaKey','formulas'],['effects','effectKey','effects'],['processes','processKey','processes'],['internalStates','stateKey','internal-states'],['triggerRules','ruleKey','trigger-rules']],skills=['ornn','shen'].flatMap(h=>['p','q','w','e','r'].map(s=>h+'_'+s)),candidateEntries=[],knownKinds=new Map(kinds.map(x=>[x[0],x])),collectionRoutes=new Map();
const strip=v=>Array.isArray(v)?v.map(strip):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)).map(([k,x])=>[k,strip(x)])):v;
for(const sk of skills)for(const[k,id,api]of kinds){const route='/skills/'+sk+'/'+api;collectionRoutes.set(route,{sk,k,id});for(const b of candidate.skills[sk].write[k])candidateEntries.push({sk,k,id:b[id],route,detail:route+'/'+b[id],body:b});}
assert.equal(candidateEntries.length,108);assert.equal(plan.count,97);assert.equal(plan.intents.length,97);assert.equal(new Set(plan.intents.map(x=>x.route+'/'+x.stableKey)).size,97);assert.equal(baseline.requests.length,99);
for(const intent of plan.intents){assert.equal(intent.method,'POST');assert(skills.includes(intent.skillKey));assert(knownKinds.has(intent.kind));const [k,id,api]=knownKinds.get(intent.kind);assert.equal(intent.route,'/skills/'+intent.skillKey+'/'+api);assert.equal(intent.stableKey,intent.body[id]);const c=candidateEntries.find(x=>x.sk===intent.skillKey&&x.k===k&&x.id===intent.stableKey);assert(c);assert.deepEqual(c.body,intent.body);}
function scan(n,sk){if(n.nodeType==='ATTRIBUTE'){assert(['SOURCE','TARGET'].includes(n.attributeOwner));assert(['BASE','BONUS','TOTAL','CURRENT','MISSING','CURRENT_RATIO','MISSING_RATIO'].includes(n.attributeValueKind));return;}if(n.nodeType==='PARAMETER'){assert(candidate.skills[sk].write.parameters.some(p=>p.parameterKey===n.parameterKey));return;}assert.equal(n.nodeType,'OPERATION');assert.equal(n.operands.length,2);assert(['ADD','SUBTRACT','MULTIPLY','DIVIDE','MIN','MAX'].includes(n.operation));n.operands.forEach(x=>scan(x,sk));}
for(const c of candidateEntries){if(c.k==='formulas')scan(c.body.expression,c.sk);if(c.k==='parameters'){const p=c.body;if(p.valueMode==='RUNTIME_INPUT'){assert.equal(p.fixedValue,null);assert.equal(p.levelValues,null);}if(p.parameterKey.endsWith('_ms'))assert.equal(p.valueType,'INTEGER');if(p.valueType==='INTEGER')for(const v of [p.fixedValue,...Object.values(p.levelValues??{})].filter(x=>x!==null&&x!==undefined))assert(Number.isInteger(v));}}
const runId=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(here,apply?'实际写入':'只读预检',runId);fs.mkdirSync(out,{recursive:true});const logfile=out+'/全部请求流水.jsonl';function journal(x){const fd=fs.openSync(logfile,'a');try{fs.writeSync(fd,JSON.stringify(x)+'\n');fs.fsyncSync(fd);}finally{fs.closeSync(fd);}}
const globalLock=here+'/实际写入锁.json';const execution={runId,mode:apply?'apply':'readonly',candidateSha256:wanted.candidate,planSha256:wanted.plan,writerSha256:sha(fileURLToPath(import.meta.url)),apiWrites:0,confirmed:0,calls:[],preflight:null,final:null,success:false};
function lock(status){fs.writeFileSync(globalLock,JSON.stringify({runId,status,apiWrites:execution.apiWrites,confirmed:execution.confirmed,reportPath:out+'/执行结果.json'},null,2)+'\n');}
if(apply){fs.writeFileSync(globalLock,JSON.stringify({runId,status:'STARTED',apiWrites:0,confirmed:0})+'\n',{flag:'wx'});fs.mkdirSync(out+'/写前意图');}
async function req(route,method='GET',body){assert(route.startsWith('/')&&!route.includes('://')&&!route.includes('..'));if(method!=='GET'){assert(apply&&method==='POST');assert(plan.intents.some(x=>x.route===route&&equal(x.body,body)));}const seq=execution.calls.length+1;journal({at:new Date().toISOString(),phase:'BEFORE',seq,method,route,body});let response;
try{const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer local-entry','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const data=await r.json();response={seq,method,route,status:r.status,data};}catch(e){response={seq,method,route,status:null,error:e.message};journal({...response,phase:'AFTER'});execution.calls.push(response);throw e;}journal({...response,phase:'AFTER'});execution.calls.push(response);if(method==='POST'&&response.status===201)execution.apiWrites++;return response;}
async function protection(after){let lists=0,checked=0;for(const old of baseline.requests){const r=await req(old.route);assert.equal(r.status,old.status,old.route);const coll=collectionRoutes.get(old.route);if(!coll){assert.deepEqual(r.data,old.data,old.route);}else{lists++;assert(Array.isArray(r.data)&&Array.isArray(old.data));const allowed=new Map(old.data.map(x=>[x[coll.id],x]));for(const i of plan.intents.filter(x=>x.route===old.route))if(after)allowed.set(i.stableKey,i.body);assert.equal(r.data.length,allowed.size,old.route);for(const prev of old.data)assert.deepEqual(r.data.find(x=>x[coll.id]===prev[coll.id]),prev,old.route);for(const cur of r.data)assert(allowed.has(cur[coll.id]),old.route);}checked++;}assert.equal(lists,60);return {checked,lists,passed:true};}
async function details(after){let old=0,newEntries=0;for(const c of candidateEntries){const r=await req(c.detail),planned=plan.intents.some(i=>i.route===c.route&&i.stableKey===c.id);if(!after&&planned){assert.equal(r.status,404,c.detail);newEntries++;}else{assert.equal(r.status,200,c.detail);assert.deepEqual(strip(r.data),strip(c.body),c.detail);old++;}}return {matched:old,missingBefore:newEntries,passed:true};}
try{execution.preflight={protection:await protection(false),details:await details(false)};assert.equal(execution.preflight.details.missingBefore,97);assert.equal(execution.preflight.details.matched,11);
if(apply){const review=fs.readFileSync(here+'/独立来源评审.md','utf8');assert(/READY|可录|通过/.test(review)&&!/VERDICT:\s*(BLOCK|REVISE)/.test(review),'独立来源评审未通过');for(let i=0;i<plan.intents.length;i++){const x=plan.intents[i],detail=x.route+'/'+x.stableKey;const before=await req(detail);assert.equal(before.status,404,detail);fs.writeFileSync(out+'/写前意图/'+String(i+1).padStart(3,'0')+'.json',JSON.stringify({i,intent:x},null,2)+'\n',{flag:'wx'});const r=await req(x.route,'POST',x.body);assert.equal(r.status,201,x.route);const got=await req(detail);assert.equal(got.status,200,detail);assert.deepEqual(strip(got.data),strip(x.body),detail);execution.confirmed++;lock('RUNNING');}execution.final={protection:await protection(true),details:await details(true)};assert.equal(execution.final.details.matched,108);lock('COMPLETED');}execution.success=true;
}catch(e){execution.error=e.stack;if(apply)lock('STOPPED');process.exitCode=1;}finally{execution.finishedAt=new Date().toISOString();execution.counts={GET:execution.calls.filter(x=>x.method==='GET').length,POST:execution.calls.filter(x=>x.method==='POST').length};fs.writeFileSync(out+'/执行结果.json',JSON.stringify(execution,null,2)+'\n');console.log(JSON.stringify({runId,mode:execution.mode,success:execution.success,apiWrites:execution.apiWrites,confirmed:execution.confirmed,counts:execution.counts,preflight:execution.preflight,final:execution.final,error:execution.error,output:out},null,2));}
