import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
assert.deepEqual(process.argv.slice(2),['--browser-verified']);
const d='C:/project/damage_web_dev/.agents/artifacts/hero29-luna-candidate/修订二',calls=[],cases=[],p={},f={};
assert.equal(JSON.parse(fs.readFileSync(d+'/实际写入锁.json')).status,'COMPLETED');
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer local-entry'},signal:AbortSignal.timeout(30000)});assert.equal(r.status,200,route);const data=await r.json();calls.push({route,status:200,data});return data;}
for(const k of ['ornn_w','shen_q','shen_e']){await get('/skills/'+k);assert((await get('/skills/'+k+'/representative-image')).image);p[k]=await get('/skills/'+k+'/parameters');}
for(const[k,keys]of Object.entries({ornn_w:['damage_per_tick','five_tick_damage_total'],shen_q:['normal_enhanced_attack_magic_damage','enhanced_attack_magic_damage','enhanced_attack_magic_damage_total'],shen_e:['physical_damage']}))for(const key of keys)f[k+'/'+key]=await get('/skills/'+k+'/formulas/'+key);
const qe=await get('/skills/shen_q/effects/energy_cost'),ec=await get('/skills/shen_e/effects/energy_cost'),er=await get('/skills/shen_e/effects/energy_refund');
function value(k,key,l,cl){const x=p[k].find(x=>x.parameterKey===key);assert(x,key);let v;if(x.valueMode==='FIXED')v=x.fixedValue;else if(x.valueMode==='SKILL_LEVEL')v=x.levelValues?.[l];else if(x.valueMode==='CHARACTER_LEVEL')v=x.levelValues?.[cl];else throw Error('缺实际输入 '+key);assert(Number.isFinite(v));if(x.valueType==='INTEGER')assert(Number.isInteger(v));return v;}
function ev(n,k,l,cl,attrs){if(n.nodeType==='PARAMETER')return value(k,n.parameterKey,l,cl);if(n.nodeType==='ATTRIBUTE'){const v=attrs[n.attributeOwner+'/'+n.attributeKey+'/'+n.attributeValueKind];assert(Number.isFinite(v));return v;}assert(n.nodeType==='OPERATION'&&n.operands.length===2);const[a,b]=n.operands.map(x=>ev(x,k,l,cl,attrs));assert(['ADD','MULTIPLY','MAX'].includes(n.operation));return n.operation==='ADD'?a+b:n.operation==='MULTIPLY'?a*b:Math.max(a,b);}
function check(k,key,l,cl,attrs,expected){const actual=ev(f[k+'/'+key].expression,k,l,cl,attrs);assert(Math.abs(actual-expected)<1e-8,`${key}: ${actual} != ${expected}`);cases.push({skillKey:k,formulaKey:key,skillLevel:l,characterLevel:cl,attrs,actual,expected,passed:true});}
for(const[l,hp,one,total]of [[1,200,16,80],[5,4000,128,640]]){check('ornn_w','damage_per_tick',l,18,{'TARGET/hp/TOTAL':hp},one);check('ornn_w','five_tick_damage_total',l,18,{'TARGET/hp/TOTAL':hp},total);}
for(const[l,cl,ap,hp,ordinary,enhanced,total]of [[1,1,100,2000,80,150,450],[5,18,200,4000,320,480,1440]]){const attrs={'SOURCE/ability_power/TOTAL':ap,'TARGET/hp/TOTAL':hp};check('shen_q','normal_enhanced_attack_magic_damage',l,cl,attrs,ordinary);check('shen_q','enhanced_attack_magic_damage',l,cl,attrs,enhanced);check('shen_q','enhanced_attack_magic_damage_total',l,cl,attrs,total);}
for(const[l,hp,expected]of [[1,700,137],[5,1800,358]])check('shen_e','physical_damage',l,18,{'SOURCE/hp/BONUS':hp},expected);
assert.deepEqual([1,3,4,6,7,9,10,12,13,15,16,18].map(cl=>value('shen_q','actual_base_flat_damage',1,cl)),[10,10,16,16,22,22,28,28,34,34,40,40]);
assert.deepEqual([1,3,4,11,12,18].map(cl=>value('shen_e','actual_energy_refund_on_damage',1,cl)),[30,30,40,40,50,50]);
assert.equal(value('ornn_w','tick_count',1,1),5);assert.equal(value('ornn_w','breath_duration_ms',1,1),750);assert.equal(value('shen_q','enhanced_attack_window_ms',1,1),8000);assert.equal(value('shen_e','taunt_duration_ms',1,1),1500);
for(const[e,key,operation,param]of [[qe,'energy_cost','CONSUME','energy_cost'],[ec,'energy_cost','CONSUME','energy_cost'],[er,'energy_refund','RESTORE','actual_energy_refund_on_damage']]){assert.equal(e.effectKey,key);const r=e.results?.[0];assert.equal(r?.resultType,'RESOURCE_CHANGE');assert.equal(r.target,'SOURCE');assert.equal(r.detail.attributeKey,'energy');assert.equal(r.detail.operation,operation);assert.equal(r.valueRule.value.parameterKey,param);}
assert.equal(calls.length,18);assert.equal(cases.length,12);
fs.writeFileSync(d+'/页面验收.json',JSON.stringify({at:new Date().toISOString(),passed:true,browser:'Codex内置浏览器既有tab2，http://127.0.0.1:5173/#/skills，真实查询并打开参数、公式及能量效果详情',representativePages:3,observations:[{skillKey:'ornn_w',ui:'五次伤害分别取最低值与目标最大生命比例伤害的较大值，总量乘五；750毫秒窗口。'},{skillKey:'shen_q',ui:'固定附加伤害按角色等级离散断点显示；普通及强化完整百分比根系数0.01，三次强化总量单独保存。'},{skillKey:'shen_e',ui:'伤害取额外生命值，能量消耗与回复都指向energy，回复按角色等级4和12切换。'}],GETs:18,mathCases:12,calls,cases,apiWrites:0,notes:['首次补核从效果列表读取results失败，列表仅摘要；最终改为3个效果详情端点。未因此改动业务数据，原补核脚本保留。'],runtimeValidation:'未执行',scriptSha256:crypto.createHash('sha256').update(fs.readFileSync(new URL(import.meta.url))).digest('hex')},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({passed:true,GETs:18,mathCases:12,pages:3}));
