import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),load=n=>JSON.parse(fs.readFileSync(path.join(dir,n))),plan=load('可审查请求.json'),before=load('写前现值.json'),expected='685ec3c446fbb5d5c80098ac335e9fa4279f1ac62960c6fbb785ee07d8035106',token=process.env.HP12_API_TOKEN;
assert.equal(hash(fs.readFileSync(path.join(dir,'可审查请求.json'))),expected);assert.equal(hash(fs.readFileSync(path.join(dir,'写前现值.json'))),plan.actualGetSnapshotSha256);assert.equal(load('主审核对.json').verdict,'READY');assert.deepEqual(process.argv.slice(2),['--apply']);assert(token);const journal=path.join(dir,'实际流水.jsonl');assert(!fs.existsSync(journal),'已有流水，先对账禁止重放');fs.writeFileSync(path.join(dir,'写入启动锁.json'),JSON.stringify({at:new Date().toISOString(),planSha256:expected})+'\n',{flag:'wx'});
const reads=[],writes=[],zeroRefs=[],input='actual_mstat12_formula0',sk='item_3181_passive',root='/skills/'+sk,put=plan.requests.filter(x=>x.method==='PUT');const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!['createdAt','updatedAt'].includes(k)).sort().map(k=>[k,stable(v[k])])):v;
async function request(route,method='GET',body){if(method!=='GET'){const allowed=plan.requests.find(x=>x.route===route&&x.method===method);assert(allowed);assert.deepEqual(body,allowed.body);}const start={at:new Date().toISOString(),phase:'before',route,method,...(body?{body}:{})};fs.appendFileSync(journal,JSON.stringify(start)+'\n');let row;try{const a=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)}),text=await a.text();row={at:new Date().toISOString(),route,method,status:a.status,data:text?JSON.parse(text):null};}catch(e){row={at:new Date().toISOString(),route,method,status:null,error:String(e)};}fs.appendFileSync(journal,JSON.stringify({phase:'after',...row})+'\n');(method==='GET'?reads:writes).push(row);return row;}
async function detail(route){const x=await request(route);assert.equal(x.status,200,route);return x.data;}
function nextValue(route,value){const exact=put.find(x=>x.route===route);if(exact)return{...value,...exact.body};for(const[k,pk]of [['parameters','parameterKey'],['formulas','formulaKey']])if(route===root+'/'+k){const change=a=>a.filter(x=>x[pk]!==input).map(x=>({...x,...(put.find(q=>q.route===root+'/'+k+'/'+x[pk])?.body??{})}));return Array.isArray(value)?change(value):{...value,items:change(value.items),...(Object.hasOwn(value,'total')?{total:change(value.items).length}:{})};}return value;}
let passed=false;try{
for(const x of before.reads)assert.deepEqual(await detail(x.route),x.actual,'写前完整现值漂移 '+x.route);
for(const x of put){const response=await request(x.route,'PUT',x.body),actual=await detail(x.route);assert.deepEqual(stable(actual),stable({...x.before,...x.body}),'写后异值 '+x.route);assert(response.status>=200&&response.status<300,'写入响应失败但已回读，停止且不重放');}
for(const[k,pk]of [['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey'],['processes','processKey'],['internal-states','stateKey'],['trigger-rules','ruleKey']]){const list=await detail(root+'/'+k),items=Array.isArray(list)?list:list.items;assert(Array.isArray(items));for(const x of items){if(k==='parameters'&&x[pk]===input)continue;const data=await detail(root+'/'+k+'/'+x[pk]),matches=[];function scan(v,p=''){if(v&&typeof v==='object')for(const[key,val]of Object.entries(v)){if(val===input)matches.push(p+'/'+key);else scan(val,p+'/'+key);}}scan(data);assert.equal(matches.length,0,'删除前仍有引用');zeroRefs.push({kind:k,key:x[pk],matches});}}
const deletion=plan.requests.at(-1),response=await request(deletion.route,'DELETE'),after=await request(deletion.route);assert.equal(after.status,404);assert(response.status>=200&&response.status<300,'删除响应失败但已回读，停止且不重放');
for(const x of before.reads){const actual=await request(x.route);if(x.route===deletion.route){assert.equal(actual.status,404);continue;}assert.equal(actual.status,200);assert.deepEqual(stable(actual.data),stable(nextValue(x.route,x.actual)),'最终保护不符 '+x.route);}passed=true;
}finally{const report={at:new Date().toISOString(),passed,planSha256:expected,updated:writes.filter(x=>x.method==='PUT'&&x.status>=200&&x.status<300).length,deleted:writes.filter(x=>x.method==='DELETE'&&x.status>=200&&x.status<300).length,zeroRefs,reads,writes,expectedRemaining:{parameters:4,formulas:2,effects:0,processes:0,internalStates:0,triggerRules:0},runtimeValidation:'未执行'};fs.writeFileSync(path.join(dir,'实际回补结果.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed,updated:report.updated,deleted:report.deleted,gets:reads.length,zeroReferenceObjects:zeroRefs.length}));}
