// 离线模拟；不连接业务接口、不创建业务对象。
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {business,diff,compareComponent,createMissing,request,here} from './录入工具.mjs';
const checks=[];async function check(name,fn){await fn();checks.push({name,match:true});}
const body={parameterKey:'x',name:'数值',description:'原说明',sortOrder:10,valueType:'INTEGER',valueMode:'FIXED',fixedValue:1,levelValues:null};
const make=(skill,id='x')=>({skillKey:skill,kind:'parameters',idField:'parameterKey',id,base:'/skills/'+skill+'/parameters',route:'/skills/'+skill+'/parameters/'+id,body:{...body,parameterKey:id}});
const okay=data=>({ok:true,status:200,data}),missing={ok:false,status:404,data:{}};
await check('系统时间字段可忽略，名称说明排序等业务字段不可忽略',()=>{assert.equal(compareComponent('sett_q','parameterKey','x',body,{...body,gameId:'lol',skillKey:'sett_q',createdAt:'now'}),null);assert.notEqual(compareComponent('sett_q','parameterKey','x',body,{...body,description:'别人修改'}),null);assert.notEqual(compareComponent('sett_q','parameterKey','x',body,{...body,extraBusiness:true}),null);});
await check('响应补齐useKind空值不改变业务，显式ACTIVE仍为差异',()=>{const a={eventSource:{eventType:'SKILL_HIT',detail:{sourceSkillKey:'sett_e'}}},b={eventSource:{eventType:'SKILL_HIT',detail:{sourceSkillKey:'sett_e',useKind:null}}};assert.equal(diff(business(a),business(b)),null);b.eventSource.detail.useKind='ACTIVE';assert.notEqual(diff(business(a),business(b)),null);});
await check('组成独立子项按排序和键比较，公式操作数顺序不重排',()=>{assert.equal(diff(business({results:[{resultKey:'b',sortOrder:10},{resultKey:'a',sortOrder:10}]}),business({results:[{resultKey:'a',sortOrder:10},{resultKey:'b',sortOrder:10}]})),null);assert.notEqual(diff(business({operands:[1,2]}),business({operands:[2,1]})),null);});
await check('全量冲突在任何请求前阻止写入',async()=>{let calls=0;await assert.rejects(createMissing({}, {conflicts:[{}],missing:[make('sett_q')]},{requestFn:async()=>{calls++;}}));assert.equal(calls,0);});
await check('写前同键同值跳过，写前异值停止且零POST',async()=>{let posts=0;const f=async(_r,o={})=>{if(o.method==='POST')posts++;return okay(body);};const r=await createMissing({}, {conflicts:[],missing:[make('sett_q')]},{requestFn:f});assert.equal(posts,0);assert.equal(r.events[0].action,'并发同值，跳过');await assert.rejects(createMissing({}, {conflicts:[],missing:[make('sett_q')]},{requestFn:async()=>okay({...body,fixedValue:2})}));});
await check('POST断线后独立GET确认已落地，不重放POST',async()=>{let posted=false,posts=0,gets=0;const r=await createMissing({}, {conflicts:[],missing:[make('sett_q')]},{requestFn:async(_route,o={})=>{if(o.method==='POST'){posted=true;posts++;throw Error('模拟响应断线');}gets++;return posted?okay(body):missing;}});assert.equal(posts,1);assert.equal(gets,2);assert.equal(r.failedSkills.length,0);assert.equal(r.events.at(-1).match,true);});
await check('校验拒绝且未落地时停止当前技能依赖，继续另一技能',async()=>{const done=new Map(),posts=[];const candidates=[make('sett_q'),make('sett_q','later'),make('trundle_q')];const r=await createMissing({}, {conflicts:[],missing:candidates},{requestFn:async(route,o={})=>{if(o.method==='POST'){posts.push(route);if(route.includes('sett_q'))return {ok:false,status:400,data:{code:'模拟拒绝'}};done.set(route+'/'+o.body.parameterKey,o.body);return {ok:true,status:201,data:o.body};}return done.has(route)?okay(done.get(route)):missing;}});assert.deepEqual(r.failedSkills,['sett_q']);assert.equal(posts.length,2);assert.equal(r.events.at(-1).match,true);});
await check('候选发生变化时在业务请求前停止',async()=>{let requests=0;await assert.rejects(createMissing({}, {conflicts:[],missing:[make('sett_q')]},{assertFrozen:async()=>{throw Error('模拟候选变化');},requestFn:async()=>{requests++;}}));assert.equal(requests,0);});
await check('拒绝覆盖删除与批次外创建，不发网络请求',async()=>{await assert.rejects(request('/skills/sett_q/parameters/x',{method:'PUT',body}));await assert.rejects(request('/skills/sett_q/parameters/x',{method:'DELETE'}));await assert.rejects(request('/skills/ahri_q/parameters',{method:'POST',body}));});
await writeFile(new URL('录入入口安全核对.json',here),JSON.stringify({at:new Date().toISOString(),boundary:'离线模拟，业务网络请求0次',checks},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,failures:0,businessRequests:0}));
