import {begin,plan,data,literal,formula,pn,attr,add,mul,op,val,fval,damage,pending,exclude,common,processStart,interp,coeff,runtime,heal,statEffect,rule} from './英雄工具.mjs';
{
 const x=begin('warwick_p');interp(x,'on_hit_base','普攻附带基础魔法伤害',x.p.mSpellCalculations.OnHitDamage.mFormulaParts[0]);data(x,'ADRatio','bonus_ad_ratio','被动额外攻击力倍率');data(x,'APRatio','ap_ratio','被动法术强度倍率');
 formula(x,'on_hit_damage','血之饥渴附带魔法伤害',add(pn('on_hit_base'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS')),mul(pn('ap_ratio'),attr('ability_power'))),'当前完整树：角色1至18级6至55 + 0.15额外攻击力 + 0.1法强；不含普通攻击本体。');
 damage(x,'on_hit_damage','血之饥渴普通攻击独立附伤','on_hit_damage','magic',{delivery:'BASIC_ATTACK',block:null});rule(x,'basic_attack_hit','普通攻击实际命中附带血之饥渴',{eventType:'BASIC_ATTACK_HIT',detail:{}},['on_hit_damage']);
 data(x,'HealingThreshold','healing_hp_threshold','触发治疗的生命比例上界');data(x,'EmpoweredHealingThreshold','empowered_healing_hp_threshold','强化治疗的生命比例上界');data(x,'HealingRatio','healing_ratio','通常实际伤害治疗倍率');data(x,'EmpoweredHealingRatio','empowered_healing_ratio','低生命实际伤害治疗倍率');runtime(x,'passive_actual_damage','本次被动实际伤害','只接收本次血之饥渴已结算的实际伤害，不采用普攻总伤害或减伤前公式值；缺失不可补零。');
 formula(x,'normal_heal','生命低于50%通常治疗',mul(pn('passive_actual_damage'),pn('healing_ratio')),'适用于生命比例[25%,50%)；不是任意攻击的伤害。');formula(x,'empowered_heal','生命低于25%强化治疗',mul(pn('passive_actual_damage'),pn('empowered_healing_ratio')),'当前根与主说明是2.5倍，旧摘要三倍不采用；与通常治疗互斥。');heal(x,'normal_heal','血之饥渴通常治疗','normal_heal');heal(x,'empowered_heal','血之饥渴低生命强化治疗','empowered_heal');
 pending(x,'实际伤害到治疗输入及互斥生命门槛','普攻独立伤害已接实际普攻命中。治疗须读取本次被动结算结果，按低于25%、25%至不足50%互斥；生命比例读取时点与实际伤害是否包含被护盾吸收部分须补证后接线。','来源');pending(x,'Q和R施加攻击特效时触发被动','Q一次和R三次的攻击特效交付应接入同一被动结算，不能靠生成伪普通攻击命中造成其他普攻规则误触发。');
 x.c.proofs.push({source:'当前主说明与旧摘要差异',current:2.5,oldSummary:3,disposition:'采用当前主说明及EmpoweredHealingRatio；旧摘要保留证据'});
}
{
 const x=begin('warwick_q');common(x);data(x,'ADRatio','total_ad_ratio','撕咬总攻击力倍率');coeff(x,'BaseBiteDamage',1,'ap_ratio','撕咬法术强度倍率');data(x,'TargetPercentHPDamage','target_max_hp_ratio','目标最大生命伤害比例',{scale:.01});data(x,'LifestealPercent','actual_damage_heal_ratio','实际伤害治疗比例',{scale:.01});
 formula(x,'bite_damage','野兽之口对英雄伤害',add(mul(pn('total_ad_ratio'),attr('attack_damage')),mul(pn('ap_ratio'),attr('ability_power')),mul(pn('target_max_hp_ratio'),attr('hp','TARGET','TOTAL'))),'1.2总攻击力+1法强+6/7/8/9/10%目标最大生命；不会暴击，秒放与蓄力释放伤害相同。');damage(x,'bite','野兽之口实际撕咬','bite_damage');
 runtime(x,'bite_actual_damage','本次撕咬实际伤害','接收本次Q伤害结果，不能把减伤前伤害公式当实际伤害；攻击特效是否计入Q治疗口径须核对。');formula(x,'bite_heal','野兽之口按实际伤害治疗',mul(pn('bite_actual_damage'),pn('actual_damage_heal_ratio')),'25/37.5/50/62.5/75%本次Q实际伤害。');heal(x,'bite_heal','野兽之口自身治疗','bite_heal');processStart(x);
 pending(x,'秒放、蓄力释放与一次性实际撕咬','已配置成本冷却候选，未生成命中；紧咬结束/放开时的伤害与治疗须唯一交付，不能开始和放开各打一次。Q明确施加攻击特效和攻击附伤且不能暴击。');pending(x,'撕咬治疗实际伤害口径','直接伤害、附带特效、护盾吸收与过量伤害的计入基准需补证，现只保留真实输入公式，不猜绑定。','来源');pending(x,'紧咬期间强制位移免疫','此防御行为在1V1内保留；需区分强制位移免疫与所有控制免疫，不能直接套全控制免疫。');exclude(x,'野怪伤害上限与跟随路径计算','英雄伤害不使用HPDamageCap；位移跟随路径按既定空间后置。');
}
{
 const x=begin('warwick_w');common(x);data(x,'PassiveASBonus','attack_speed_ratio','血猎通常额外攻速比例',{scale:.01});data(x,'PassiveMSBonus','toward_target_move_speed_ratio','朝血猎目标通常移速比例',{scale:.01});data(x,'FirstHPThreshold','target_hp_threshold','通常血猎目标生命比例上界');data(x,'SecondHPThreshold','empowered_target_hp_threshold','强化血猎目标生命比例上界');data(x,'Duration','active_hunt_duration_ms','主动指定血猎持续（毫秒）',{scale:1000});data(x,'PassiveASDuration','attack_speed_duration_ms','攻速增益持续原值（毫秒）',{scale:1000});literal(x,'low_hp_multiplier','低生命血猎加成倍率',3,'当前主说明提升200%，即原加成三倍。','Spell_WarwickW_Tooltip');literal(x,'no_target_refund_ratio','未感知英雄时冷却缩短比例',.3,'当前主说明冷却缩短30%；NoTargetCDReduction=0.7为剩余比例，不能当减少70%。','Spell_WarwickW_Tooltip');
 formula(x,'empowered_attack_speed','低生命血猎额外攻速',mul(pn('attack_speed_ratio'),pn('low_hp_multiplier')),'通常70%至110%的三倍即210%至330%。');formula(x,'empowered_move_speed','低生命血猎朝目标移速',mul(pn('toward_target_move_speed_ratio'),pn('low_hp_multiplier')),'通常35%至65%的三倍即105%至195%。');formula(x,'no_target_cooldown_refund','未感知到英雄时冷却减少量',mul(pn('cooldown_ms'),pn('no_target_refund_ratio')),'基础80/70/60/50/40秒的30%，实际减冷却操作尚待确认触发时点。');
 statEffect(x,'normal_attack_speed','血猎通常条件攻速',val('attack_speed_ratio'),'bonus_attack_speed_percent',{duration:val('attack_speed_duration_ms')});statEffect(x,'empowered_attack_speed','血猎强化条件攻速',fval('empowered_attack_speed'),'bonus_attack_speed_percent',{duration:val('attack_speed_duration_ms')});statEffect(x,'normal_move_speed','朝血猎目标通常移速',val('toward_target_move_speed_ratio'),'move_speed_percent');statEffect(x,'empowered_move_speed','朝血猎目标强化移速',fval('empowered_move_speed'),'move_speed_percent');processStart(x);
 pending(x,'攻速刷新、互斥档位及朝目标移速','四个独立条件效果尚未挂接；通常/强化档互斥，不能同时相加。攻速1.25秒原值的技能/攻击触发与刷新时点还需核对；方向移速在停止朝目标移动后须取消。','来源');pending(x,'主动目标和未找到英雄冷却返还','主动最近英雄选择虽与感知有关，但授予自身战斗增益，不能整个主动跳过；8秒内不按正常生命门槛排除目标。未找到英雄才能返还30%。');pending(x,'施法时间字段冲突','当前spellCastTime=0.25秒而mCastTime=0.5秒；只保留成本冷却，不猜0.25或0.5秒完整施法时间。','来源');exclude(x,'纯感知和小地图提示','仅视觉提示排除，不排除其控制自身攻速与移速所需的目标条件。');
}
{
 const x=begin('warwick_e');common(x,{cast:true});data(x,'DRAmount','damage_reduction_ratio','远祖嗥叫伤害减免比例',{scale:.01});data(x,'DRDuration','damage_reduction_duration_ms','当前主说明减伤持续（毫秒）',{scale:1000});data(x,'RecastDelay','recast_delay_ms','允许再次施放等待（毫秒）',{scale:1000});data(x,'FearDuration','fear_duration_ms','嗥叫恐惧持续（毫秒）',{scale:1000});literal(x,'one','完整伤害比例',1,'减免后剩余比例由1减免倍率计算。');formula(x,'remaining_damage_ratio','受到伤害的剩余比例',op('SUBTRACT',pn('one'),pn('damage_reduction_ratio')),'35/40/45/50/55%减伤对应65/60/55/50/45%剩余；不表示真实伤害也受减免。');processStart(x,{delay:true});
 pending(x,'持续减伤效果及提前结束','伤害修正类型可表达减伤，但需匹配伤害乘区目录和真实伤害排除口径；不能使用属性固定加算乘区。二次施放在1秒后提前结束减伤，随后恐惧，不重付初次成本冷却。');pending(x,'恐惧及R联动结束行为','保留来源2.75秒和1秒恐惧；自然结束/主动结束应只嗥叫一次。R期间提前结束E的具体规则仍待来源，不推测。');
 x.c.proofs.push({source:'当前主说明与旧摘要差异',currentDurationMs:2750,oldSummaryAndTooltipOnlyMs:2500,disposition:'采用当前根主说明引用DRDuration，不采用DRDurationTooltipOnly'});
}
{
 const x=begin('warwick_r');common(x);data(x,'RBaseDamage','base_total_damage','完整引导基础总伤害');coeff(x,'DamageCumulative',1,'bonus_ad_ratio','完整引导额外攻击力倍率',{stat:2,kind:2});data(x,'RDuration','channel_duration_ms','压制与引导持续（毫秒）',{scale:1000});literal(x,'attack_count','持续期间攻击与攻击特效次数',3,'当前主说明攻击3次，扩展明确攻击特效和攻击附伤各施加3次。','Spell_WarwickR_Tooltip + Spell_WarwickR_TooltipExtendedBelowLine');literal(x,'actual_damage_heal_ratio','引导期间实际伤害治疗倍率',1,'当前主说明引导期间治疗实际伤害100%。','Spell_WarwickR_Tooltip');formula(x,'channel_total_damage','完整引导总魔法伤害',add(pn('base_total_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'175/350/525+1.67额外攻击力是完整总量；不能每击重复整份，也不按未知跳频均摊。');runtime(x,'channel_actual_damage','引导期间已结算的本次实际伤害','由本次R引导的真实伤害交付；一次结果只治疗一次，不能每击重传完整累计量。');formula(x,'channel_heal','无尽束缚按实际伤害治疗',mul(pn('channel_actual_damage'),pn('actual_damage_heal_ratio')),'引导期间100%实际伤害；具体攻击特效及护盾吸收基准待核对。');heal(x,'channel_heal','无尽束缚自身治疗','channel_heal');processStart(x);
 pending(x,'三次伤害分配、引导中断与治疗口径','确证总伤害、1.5秒和3次攻击，未确证每次分配或具体时点，故不创建冒充单跳或瞬时总伤害的效果。中断须停止后续伤害和治疗。','来源');pending(x,'压制、三次攻击特效与防护交互','必须来源于真正碰撞到第一个敌方英雄后的引导；压制、强制中断位移和法术护盾消费须共同核对，不生成三次伪普攻事件。');pending(x,'施法时间冲突','spellCastTime=0.25秒与mCastTime=0.1秒冲突，当前仅配置成本冷却候选。','来源');exclude(x,'跳跃距离和沿途多目标查找','移动速度影响跳跃距离的空间计算后置；不删除命中后的伤害/治疗组成。');
}
export {plan};
