import {begin,plan,data,literal,formula,pn,attr,add,mul,op,val,fval,damage,pending,exclude,common,processStart,interp,runtime,heal,statEffect} from './英雄工具.mjs';
{
 const x=begin('trundle_p');interp(x,'dead_enemy_hp_heal_ratio','阵亡敌人最大生命治疗比例',x.p.mSpellCalculations.RegenPercent.mFormulaParts[0]);formula(x,'tribute_heal','阵亡敌人贡品治疗',mul(pn('dead_enemy_hp_heal_ratio'),attr('hp','TARGET','TOTAL')),'角色1至18级1.8%至5.5%阵亡敌方最大生命；来源自身为治疗接收者。');heal(x,'kings_tribute','国王的贡品自身治疗','tribute_heal');pending(x,'附近敌人阵亡事件与死者上下文','当前范围包含敌方英雄死亡治疗；事件须保留死者最大生命且验证附近范围。不能要求必须本人击杀，也不能把任意远处死亡都接入。');exclude(x,'小兵和野怪贡品','只保留当前敌方英雄支路。');
}
{
 const x=begin('trundle_q');common(x);data(x,'BonusDamage','base_bonus_damage','撕咬基础额外伤害');data(x,'ADScaling','total_ad_ratio','撕咬完整攻击总攻击力倍率');literal(x,'one','普通攻击本体倍率',1,'完整TotalDamage包含一次普通攻击的1倍总攻击力。','mSpellCalculations.TotalDamage');formula(x,'total_noncritical_damage','撕咬未暴击完整伤害',add(pn('base_bonus_damage'),mul(pn('total_ad_ratio'),attr('attack_damage'))),'10至90 + 1.15/1.25/1.35/1.45/1.55总攻击力；该量已含普通攻击本体。');formula(x,'bonus_noncritical_damage','撕咬未暴击额外部分',add(pn('base_bonus_damage'),mul(op('SUBTRACT',pn('total_ad_ratio'),pn('one')),attr('attack_damage'))),'从完整攻击减去普通攻击1倍总攻击力，不能在普攻之外叠整份。暴击分配仍待证据。');damage(x,'noncritical_bonus','撕咬未暴击额外伤害','bonus_noncritical_damage','physics',{delivery:'BASIC_ATTACK',block:null});
 data(x,'BonusAD','source_attack_damage_gain','撕咬后自身攻击力增加');data(x,'SappedAD','target_attack_damage_loss','撕咬后目标攻击力减少',{scale:-1});data(x,'SapDebuffDuration','sap_duration_ms','攻击力得失持续（毫秒）',{scale:1000});data(x,'SlowAmount','slow_ratio','撕咬减速比例');data(x,'SlowDuration','slow_duration_ms','撕咬减速持续（毫秒）',{scale:1000});data(x,'PrepDuration','empowered_window_ms','等待下次攻击窗口（毫秒）',{scale:1000});data(x,'BonusRange','bonus_attack_range','该次攻击额外距离');
 statEffect(x,'source_attack_damage_gain','撕咬后自身攻击力增加',val('source_attack_damage_gain'),'attack_damage',{duration:val('sap_duration_ms')});statEffect(x,'target_attack_damage_loss','撕咬后目标攻击力减少',val('target_attack_damage_loss'),'attack_damage',{duration:val('sap_duration_ms'),target:'TARGET',operation:'DECREASE'});processStart(x,{empowered:true});
 pending(x,'强化攻击额外伤害、攻击力转移与减速接线','候选已配置7秒等待下次真实攻击命中过程。未暴击伤害只为独立分支；需明确暴击本体组合、法术护盾对技能特效/攻击力削弱的消费边界，再接两方5秒攻击力变化和75%减速0.1秒。攻击力增加发生伤害后，不能提前增益本次撕咬。');
}
{
 const x=begin('trundle_w');common(x,{cast:true});data(x,'MSBonus','move_speed_ratio','领域内移动速度比例');data(x,'ASBonus','attack_speed_ratio','领域内额外攻击速度比例');data(x,'HealingBonus','healing_received_ratio','领域内治疗效果提升比例');data(x,'Duration','zone_duration_ms','领域持续（毫秒）',{scale:1000});
 statEffect(x,'zone_attack_speed','处于冰封领域时攻击速度',val('attack_speed_ratio'),'bonus_attack_speed_percent',{description:'仅在领域内有效；独立效果采用显式取消，尚待区域进入/离开和领域结束接线，不能自动给足8秒。'});statEffect(x,'zone_move_speed','处于冰封领域时移动速度',val('move_speed_ratio'),'move_speed_percent',{description:'仅在领域内有效；显式取消，等待区域进入/离开和领域结束接线。'});processStart(x,{delay:true});pending(x,'区域内持续属性与治疗提升','领域持续8秒不等于来源离开后仍获8秒增益。已有两种独立属性需进入/离开接线；25%治疗提升可由HEALING_MODIFIER表达，但当前仅属性乘区目录，治疗乘区待配置，不能拿护盾治疗强度替代。');
}
{
 const x=begin('trundle_e');common(x,{cast:true});data(x,'PillarDuration','pillar_duration_ms','冰柱持续（毫秒）',{scale:1000});data(x,'SlowAmount','slow_ratio','冰柱附近减速比例',{scale:.01});data(x,'SlowRadius','slow_radius','冰柱减速范围');data(x,'KnockbackRadius','knockback_radius','初始击退范围');data(x,'EnemyDisplacementRange','enemy_displacement_distance','敌方击退距离');processStart(x,{delay:true});pending(x,'初始击退、不可通行地形与邻近减速','冰柱确证无直接伤害；不能造伤害触发。减速只在附近，不能给目标恒定6秒。地形/击退/范围边界仍待配置来源。');exclude(x,'友军挤出位移','本次单敌方英雄场景不配置友军位移。');
}
{
 const x=begin('trundle_r');common(x,{cast:true});data(x,'PercentHPDamage','base_max_hp_damage_ratio','吸取总伤害最大生命基础比例');data(x,'PercentHPDamageAPRatio','ap_to_max_hp_damage_ratio','每点法强增加的最大生命伤害比例');data(x,'ArmorMRShred','resistance_steal_ratio','总计双抗偷取比例');data(x,'PercentOfDamageAndShredUpfront','upfront_ratio','立即伤害和偷取所占比例');data(x,'ActualDurationOfDrainBuff','actual_drain_duration_ms','当前吸取效果持续（毫秒）',{scale:1000});data(x,'DurationOfDrainForTooltip','post_drain_shred_duration_ms','吸取结束后击碎额外持续（毫秒）',{scale:1000});data(x,'NumberOfTicks','raw_tick_count','根周期次数原值');data(x,'ShredDuration','raw_shred_duration_ms','击碎持续旧原值（毫秒）',{scale:1000});
 formula(x,'drain_total_damage','完整吸取总魔法伤害',mul(add(pn('base_max_hp_damage_ratio'),mul(pn('ap_to_max_hp_damage_ratio'),attr('ability_power'))),attr('hp','TARGET','TOTAL')),'当前总量=(20/25/30%+每100法强2%)目标最大生命；只表示完整总量，不冒充每周期量。');formula(x,'initial_drain_damage','立即一半吸取伤害',mul(mul(add(pn('base_max_hp_damage_ratio'),mul(pn('ap_to_max_hp_damage_ratio'),attr('ability_power'))),attr('hp','TARGET','TOTAL')),pn('upfront_ratio')),'当前绑定扩展明确立即一半伤害；另一半在吸取期间持续造成。');damage(x,'initial_drain','强权至上初始一半魔法伤害','initial_drain_damage');processStart(x,{delay:true});
 pending(x,'后半吸取周期和治疗基准','当前主说明用5秒ActualDurationOfDrainBuff，扩展又明确结束后4秒，旧description写4秒且ShredDuration=8秒。NumberOfTicks=4不能推成1秒一次或每次总量。真实周期时点、目标最大生命取值时点与治疗基准须补证。','来源');pending(x,'目标双抗快照、偷取累积和返还','40%总偷取、先一半后另一半已确证；不能在已降低抗性上递算或先减抗再将已降低值给自身，也不能独立降抗和偷取双算。实际目标抗性读取时点、负抗性与最终归还的生命周期须补证。','来源');
}
export {plan};
