import {readFile} from 'node:fs/promises';
import {isDeepStrictEqual} from 'node:util';
import {plan,evidence,clean,val,fval,fixed,pn,attr,op,add,mul,behavior,life,begin,parameter,data,literal,formula,result,effect,damage,manaEffect,hit,pending,exclude} from './候选.mjs';
export {plan,evidence,clean,val,fval,fixed,pn,attr,op,add,mul,behavior,life,begin,parameter,data,literal,formula,result,effect,damage,manaEffect,hit,pending,exclude};
plan.meta.scope='瑟提、特朗德尔、沃里克、赵信20技能的确定组成；仅本批技能内部补缺。控制、跨技能及空间依赖逐项待配，纯视野、友军、多目标和野怪专供支路排除。';
export function common(x,{cast=false}={}){
 const d=x.s.official,n=x.c.maxLevel,cd=x.p.Cooldown?.values?.slice(1,n+1),mana=x.p.manaValues?.values?.slice(0,n);
 if(cd?.length!==n||!cd.every((v,i)=>Math.abs(v-d.cooldown[i])<1e-4))throw Error('冷却不符 '+x.c.skillKey);
 literal(x,'cooldown_ms','基础冷却时间（毫秒）',d.cooldown.map(v=>Math.round(v*1000)),'官方与当前根绑定Cooldown.values索引1起的冷却逐级一致。','official.cooldown + Cooldown.values');
 if(x.c.skillKey.startsWith('sett_')){if(!d.cost.every(v=>v===0))throw Error('无消耗不符');}
 else {if(mana?.length!==n||!mana.every((v,i)=>Math.abs(v-d.cost[i])<1e-4))throw Error('法力不符 '+x.c.skillKey);literal(x,'mana_cost','基础法力消耗',d.cost,'官方cost与当前manaValues逐级一致。','official.cost + manaValues.values');manaEffect(x);if(x.p.mana?.some((v,i)=>i<n&&v!==mana[i]))x.c.proofs.push({source:'mana旧字段未采用',old:x.p.mana,current:mana});}
 if(cast){if(!(x.p.spellCastTime>0)||x.p.mUseAutoattackCastTimeData||(x.p.mCastTime!=null&&Math.abs(x.p.spellCastTime-x.p.mCastTime)>1e-4))throw Error('施法时间冲突 '+x.c.skillKey);literal(x,'cast_time_ms','施法时间（毫秒）',Math.round(x.p.spellCastTime*1000),'根spellCastTime；已排除与mCastTime冲突。','spellCastTime');}
}
export function processStart(x,{delay=false,empowered=false,effects=[]}={}){
 const stepKey=empowered?'next_attack':delay?'cast_time':'start';
 x.c.write.processes.push({processKey:'cast',name:'施放'+x.c.name,activationType:'ACTIVE',description:empowered?'等待7秒内下一次实际普通攻击命中；仅保存等待、成本和冷却，不自动生成普通攻击或伤害。':delay?'只表达已确证的成本、冷却与施法延迟；不生成敌人命中。':'仅表达施放开始的已确证成本与冷却；即时步骤不等于完整施法时长，也不生成命中。',sortOrder:10,cooldown:{durationValue:val('cooldown_ms'),startMoment:{momentType:'PROCESS_START',stepKey:null}},steps:[{stepKey,name:empowered?'等待下一次普通攻击命中':delay?'施法延迟':'施放开始',description:null,sortOrder:10,stepType:empowered?'EMPOWERED_BASIC_ATTACK':delay?'DELAY':'IMMEDIATE',detail:empowered?{windowValue:val('empowered_window_ms'),consumeMoment:'ATTACK_HIT'}:delay?{delayValue:val('cast_time_ms')}:{}}],effectBindings:[...(x.c.write.effects.some(e=>e.effectKey==='mana_cost')?[{bindingKey:'mana_cost',effectKey:'mana_cost',moment:{momentType:'PROCESS_START',stepKey:null},sortOrder:10}]:[]),...effects.map((effectKey,i)=>({bindingKey:effectKey,effectKey,moment:{momentType:'STEP_COMPLETE',stepKey},sortOrder:20+i*10}))],stateOperations:[]});
}
export function interp(x,key,name,part,scale=1){if(part.__type!=='ByCharLevelInterpolationCalculationPart')throw Error('插值类型');const a=Array.from({length:18},(_,i)=>clean((clean(part.mStartValue)+(clean(part.mEndValue)-clean(part.mStartValue))*i/17)*scale));parameter(x,key,name,a,'完整计算树1至18级端点线性插值。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,source:'完整角色等级线性插值',raw:part,values:a,scale});}
export function breaks(x,key,name,part,scale=1){if(part.__type!=='ByCharLevelBreakpointsCalculationPart')throw Error('断点类型');const a=Array.from({length:18},(_,i)=>{let v=clean(part.mLevel1Value);for(const b of part.mBreakpoints??[])if(i+1>=b.mLevel){if(b.mBonusPerLevelAtAndAfter!=null)throw Error('不能省略逐级增量');v+=clean(b.mAdditionalBonusAtThisLevel??0);}return clean(v*scale);});parameter(x,key,name,a,'当前根完整计算树等级断点；1至18级。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,source:'完整角色等级断点',raw:part,values:a,scale});}
export function levelTable(x,key,name,part){if(part.__type!=='ByCharLevelFormulaCalculationPart'||part.values?.length<19)throw Error('角色等级表');const a=part.values.slice(1,19).map(clean);parameter(x,key,name,a,'完整角色等级表索引1至18；索引0不作为角色1级。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,source:'完整角色等级表',raw:part,offset:1,values:a});}
export function coeff(x,calc,index,key,name,{stat,kind}={}){const p=x.p.mSpellCalculations[calc].mFormulaParts[index];if(p.__type!=='StatByCoefficientCalculationPart'||p.mStat!==stat||p.mStatFormula!==kind)throw Error('属性系数不符 '+x.c.skillKey+'/'+calc);literal(x,key,name,clean(p.mCoefficient),'当前完整'+calc+'计算树的属性与总量/额外量已核对。','mSpellCalculations.'+calc+'.mFormulaParts.'+index);}
export function runtime(x,key,name,description,type='DECIMAL'){x.c.write.parameters.push({parameterKey:key,name,valueType:type,valueMode:'RUNTIME_INPUT',fixedValue:null,levelValues:null,description,sortOrder:(x.c.write.parameters.length+1)*10});}
export function heal(x,key,name,formulaKey){effect(x,key,name,[result('heal',name,'DIRECT_HEAL','SOURCE',fval(formulaKey),{})]);}
export const dynamic={moment:'PERSISTENT',valueReadMode:'MOMENT_EVALUATION',stackValueMode:'SHARED',reapplicationValueMode:null,periodicExecutionMode:null};
export function statEffect(x,key,name,value,attributeKey,{duration=null,target='SOURCE',operation='INCREASE',dynamicRead=false,description=null}={}){const lifecycle=life(duration);if(target==='TARGET')lifecycle.instanceScope='SOURCE_TARGET';effect(x,key,name,[result('attribute',name,'ATTRIBUTE_CHANGE',target,value,{attributeKey,operation,modifierZoneKey:'attribute_flat_add'},dynamicRead?dynamic:behavior)],lifecycle,description??'独立持续属性；应用、取消与实际触发分别核对。');}
export function rule(x,key,name,eventSource,effectKeys,conditions=[]){x.c.write.triggerRules.push({ruleKey:key,name,description:'只接受所列真实事件；规则不自行生成命中。',sortOrder:(x.c.write.triggerRules.length+1)*10,eventSource,conditionGroups:conditions.length?[{groupKey:'required',name:'必要条件',sortOrder:10,conditions}]:[],actions:effectKeys.map((effectKey,i)=>({actionKey:effectKey,name:'执行'+effectKey,actionType:'EXECUTE_EFFECT',sortOrder:(i+1)*10,targetContext:'CURRENT_TARGET',detail:{effectKey},runtimeInputBindings:[],resultModifiers:[]})),perTargetCooldown:null,maxTriggersPerProcess:null});}
export function cooldown(x,key,name,keys,value){effect(x,key,name,[result('cooldown',name,'COOLDOWN_CHANGE','SOURCE',value,{affectedSkillScope:{mode:'SKILLS',skillKeys:keys,skillCategoryKeys:[]},operation:'REDUCE'})]);}
export async function finalize(){const before=JSON.parse(await readFile(new URL('./写前现值.json',import.meta.url),'utf8'));for(const s of Object.values(plan.skills)){s.reusedParameters=[];s.write.parameters=s.write.parameters.map(p=>{const prev=before.skills[s.skillKey].components.parameters.find(v=>v.parameterKey===p.parameterKey);if(!prev)return p;if(['valueType','valueMode','fixedValue','levelValues'].some(k=>!isDeepStrictEqual(p[k],prev[k])))throw Error('公共参数冲突 '+s.skillKey+'/'+p.parameterKey);s.reusedParameters.push(p.parameterKey);return Object.fromEntries(Object.entries(prev).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)));});for(const a of Object.values(s.write)){const keys=a.map(v=>v.parameterKey??v.formulaKey??v.effectKey??v.processKey??v.stateKey??v.ruleKey);if(new Set(keys).size!==keys.length)throw Error('重复组成 '+s.skillKey);}s.status='确定组成候选；未保存或未接线不表示整机制完成';}}
