import {begin,plan,data,literal,formula,pn,attr,add,mul,op,val,fval,damage,pending,exclude,common,processStart,breaks,coeff,runtime,heal,statEffect,rule,cooldown} from './英雄工具.mjs';
{
 const x=begin('xinzhao_p');const p=x.p.mSpellCalculations;breaks(x,'total_ad_ratio','果决额外伤害总攻击力倍率',p.TotalDamage.mFormulaParts[0].mSubpart);breaks(x,'damage_ap_ratio','果决额外伤害法术强度倍率',p.TotalDamage.mFormulaParts[1].mSubpart);breaks(x,'max_hp_heal_ratio','果决治疗自身最大生命倍率',p.HealHPRatio.mFormulaParts[0]);breaks(x,'heal_ap_ratio','果决治疗法术强度倍率',p.HealAPRatio.mFormulaParts[0]);literal(x,'required_hits','果决攻击计数门槛',3,'当前主说明每第三次攻击；W参与方式另行核对。','Spell_XinZhaoP_Tooltip');
 formula(x,'bonus_damage','果决一次额外物理伤害',add(mul(pn('total_ad_ratio'),attr('attack_damage')),mul(pn('damage_ap_ratio'),attr('ability_power'))),'等级1/6/11/16分别15/30/45/60%总攻击力，加5/10/15/20%法强。');formula(x,'determination_heal','果决自身治疗',add(mul(pn('max_hp_heal_ratio'),attr('hp','SOURCE','TOTAL')),mul(pn('heal_ap_ratio'),attr('ability_power'))),'等级1/6/11分别2/3.5/5%自身最大生命，加40/50/70%法强；不采用旧固定生命成长。');damage(x,'attack_bonus','果决普通攻击独立额外物理伤害','bonus_damage','physics',{delivery:'BASIC_ATTACK',block:null});damage(x,'wind_becomes_lightning_bonus','果决风斩电刺独立额外物理伤害','bonus_damage','physics');heal(x,'determination_heal','果决自身治疗','determination_heal');
 pending(x,'第三次攻击计数与W参与方式','当前文字同时提到每第三次攻击和W命中；W两段如何参与计数或直接触发需要精确来源。不得把所有普攻或W每段都无条件执行整套。计数跨目标、超时重置、暴击本体组合未核定，未建假计数状态。','来源');pending(x,'果决附伤、治疗的同次触发','保留普攻和W两种交付的独立伤害候选；两者为来源分支，不同时执行。按最终计数规则唯一执行治疗，不能误用实际伤害回血口径。');
}
{
 const x=begin('xinzhao_q');common(x,{cast:true});data(x,'BaseDamage','base_bonus_damage','每次强化攻击基础额外伤害');data(x,'BADRatio','bonus_ad_ratio','每次强化攻击额外攻击力倍率');data(x,'KnockUpDuration','third_attack_knockup_ms','第三次攻击击飞持续（毫秒）',{scale:1000});literal(x,'empowered_attack_count','强化攻击次数',3,'当前主说明下3次普攻。','Spell_XinZhaoQ_Tooltip');literal(x,'other_skills_refund_ms','每次攻击缩短其他技能冷却（毫秒）',1000,'当前主说明每次强化攻击使其他技能冷却缩短1秒；不包含Q本身。','Spell_XinZhaoQ_Tooltip');formula(x,'bonus_damage','三重爪击每次额外伤害',add(pn('base_bonus_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'15/30/45/60/75+0.4额外攻击力，不含普通攻击本体。');damage(x,'empowered_attack_bonus','三重爪击每次独立附伤','bonus_damage','physics',{delivery:'BASIC_ATTACK',block:null});cooldown(x,'refund_other_skills','三重爪击缩短其余主动技能冷却',['xinzhao_w','xinzhao_e','xinzhao_r'],val('other_skills_refund_ms'));processStart(x,{delay:true});
 pending(x,'三次强化攻击消费与第三次击飞','3次共享强化窗口的时长和重置规则未在当前根主说明给出，不能套其他英雄的7秒。每次真实普攻命中才附伤和减其他技能冷却，第三次单独击飞；与P计数需共同接线。');pending(x,'强化附伤暴击分配','普通攻击本体和额外伤害的暴击口径须补证；当前额外分支不把完整攻击重复相加。','来源');
}
{
 const x=begin('xinzhao_w');common(x);data(x,'SlashBaseDamage','slash_base_damage','第一段斩击基础伤害');data(x,'ThrustBaseDamage','thrust_base_damage','第二段刺击基础伤害');coeff(x,'SlashDamage',1,'slash_total_ad_ratio','斩击总攻击力倍率',{stat:2});coeff(x,'ThrustDamage',1,'thrust_total_ad_ratio','刺击总攻击力倍率',{stat:2});coeff(x,'ThrustDamage',2,'thrust_ap_ratio','刺击法术强度倍率');data(x,'CritChanceAmp','crit_chance_amp_ratio','满暴击率刺击伤害提升比例');data(x,'MarkDuration','challenge_duration_ms','刺击被挑战标记持续（毫秒）',{scale:1000});data(x,'BaseSlowDuration','base_slow_duration_ms','刺击基础减速持续（毫秒）',{scale:1000});coeff(x,'TotalSlowDuration',1,'slow_ap_seconds_ratio','每点法术强度增加减速秒数');literal(x,'milliseconds_per_second','每秒毫秒数',1000,'时间从秒转换到毫秒。');literal(x,'zero','比例下界',0,'概率最低为0。');literal(x,'one','完整倍率及暴击率上界',1,'暴击几率按1代表100%，当前说明刺击提升至多33.3%。');
 const slow=x.p.mEffectAmount?.[5]?.value;if(!slow?.length||!slow.every(v=>Math.abs(v+.5)<1e-6))throw Error('赵信W当前绑定Effect6Amount未确证');literal(x,'slow_ratio','刺击减速比例',.5,'当前根主说明显式引用Effect6Amount*-100%，对应mEffectAmount索引5的-0.5；不是命名字段缺失后回退猜值。','Spell_XinZhaoW_Tooltip + mEffectAmount[5].value');literal(x,'life_steal_efficiency','两段生命偷取效能',.33,'当前绑定扩展明确33%效能，不采用33.3%刺击增幅替代。','Spell_XinZhaoW_TooltipExtendedBelowLine');
 formula(x,'slash_damage','风斩第一段物理伤害',add(pn('slash_base_damage'),mul(pn('slash_total_ad_ratio'),attr('attack_damage'))),'30/40/50/60/70+0.3总攻击力。');formula(x,'thrust_damage','电刺第二段物理伤害',mul(add(pn('thrust_base_damage'),mul(pn('thrust_total_ad_ratio'),attr('attack_damage')),mul(pn('thrust_ap_ratio'),attr('ability_power'))),add(pn('one'),mul(pn('crit_chance_amp_ratio'),op('MAX',pn('zero'),op('MIN',pn('one'),attr('critical_strike_chance')))))),'(50/85/120/155/190+0.9总攻击力+0.65法强)×(1+0.333×暴击几率)。这是确定的暴击率增幅，不进行随机暴击。');formula(x,'slow_duration_ms','电刺减速持续（毫秒）',add(pn('base_slow_duration_ms'),mul(mul(pn('slow_ap_seconds_ratio'),attr('ability_power')),pn('milliseconds_per_second'))),'1500毫秒+每点法强5毫秒。');damage(x,'slash_hit','风斩独立命中伤害','slash_damage','physics');damage(x,'thrust_hit','电刺独立命中伤害','thrust_damage','physics');processStart(x);
 pending(x,'两段实际命中、P联动、减速与挑战','一个普通SKILL_HIT事件不能区分斩击和刺击；禁止同一事件把两份伤害都执行。刺击才减速和挂3秒挑战，W参与P规则待核；挑战供E延长距离和R不击退读取，不能因带显形而跳过。');pending(x,'生命偷取基准与施法时间','当前明确33%生命偷取效能，但抗性后伤害或实际生命损失等基准须补证再配vampRules。spellCastTime=0.25秒而mCastTime=0.6秒冲突，不把0.25秒当完整两段施法时间。','来源');exclude(x,'小兵减伤及纯显形','保留英雄伤害和挑战；小兵伤害修正、纯显形后置。');
}
{
 const x=begin('xinzhao_e');common(x);data(x,'BaseDamage','base_damage','冲锋基础魔法伤害');data(x,'APRatio','ap_ratio','冲锋法术强度倍率');data(x,'ASMod','base_attack_speed_ratio','冲锋基础额外攻速比例');data(x,'APToASRatio','ap_attack_speed_ratio','每点法强增加的额外攻速比例');data(x,'PermanentASToASRatio','permanent_attack_speed_divisor','永久额外攻速换算除数');data(x,'ASDuration','attack_speed_duration_ms','冲锋攻速持续（毫秒）',{scale:1000});data(x,'SlowDuration','slow_duration_ms','冲锋减速持续（毫秒）',{scale:1000});data(x,'SlowAmount','slow_ratio','冲锋减速比例',{scale:.01});runtime(x,'permanent_bonus_attack_speed_ratio','自身永久额外攻速比例','按1表示100%；仅永久额外攻速，不包含本次E、临时技能和其他临时增益。不得绑定普通bonus_attack_speed_percent，否则把临时攻速反复计入自身。');
 formula(x,'charge_damage','无畏冲锋魔法伤害',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),'50/75/100/125/150+1.2法强。');formula(x,'attack_speed_bonus','无畏冲锋获得的额外攻速',add(pn('base_attack_speed_ratio'),op('DIVIDE',pn('permanent_bonus_attack_speed_ratio'),pn('permanent_attack_speed_divisor')),mul(pn('ap_attack_speed_ratio'),attr('ability_power'))),'38/46/54/62/70% + 永久额外攻速比例÷5 + 每点法强0.1%；所有项统一比例单位。');damage(x,'charge_hit','无畏冲锋独立命中魔法伤害','charge_damage');statEffect(x,'charge_attack_speed','无畏冲锋自身额外攻速',fval('attack_speed_bonus'),'bonus_attack_speed_percent',{duration:val('attack_speed_duration_ms'),description:'独立5秒攻速候选；仅在永久额外攻速输入正确绑定后应用。当前不从包含临时值的普通额外攻速属性读取。'});processStart(x);rule(x,'actual_charge_hit','无畏冲锋实际命中',{eventType:'SKILL_HIT',detail:{sourceSkillKey:'xinzhao_e'}},['charge_hit']);
 pending(x,'永久额外攻速来源与施加时点','伤害规则只处理实际命中，尚不应用攻速。永久攻速需要来源生产和数值快照；5秒攻速施加时点不能因方便而绑到敌人每次范围命中，否则多目标重复施加。');pending(x,'减速及与挑战共用目标','保留30%减速0.5秒；R与W提供的3秒被挑战印记共享语义待配，不能给两个互不读取的同名私有标记。');exclude(x,'冲锋路径与附近其他目标搜索','当前目标独立伤害保留，空间路径及其他目标搜索后置。');
}
{
 const x=begin('xinzhao_r');common(x,{cast:true});data(x,'BaseDamage','base_damage','新月横扫基础伤害');coeff(x,'TotalDamage',1,'bonus_ad_ratio','新月横扫额外攻击力倍率',{stat:2,kind:2});coeff(x,'TotalDamage',2,'ap_ratio','新月横扫法术强度倍率');data(x,'PercentCurrentHealthDamage','target_current_hp_ratio','目标当前生命伤害比例');data(x,'MissileDefenseBaseDuration','outer_damage_immunity_duration_ms','外侧敌人伤害免疫持续（毫秒）',{scale:1000});data(x,'MissileDefenseRadius','damage_immunity_radius','外侧敌人伤害免疫范围');data(x,'MarkDuration','challenge_duration_ms','被挑战标记持续（毫秒）',{scale:1000});
 formula(x,'sweep_damage','新月护卫横扫物理伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS')),mul(pn('ap_ratio'),attr('ability_power')),mul(pn('target_current_hp_ratio'),attr('hp','TARGET','CURRENT'))),'75/175/275+1额外攻击力+1.1法强+15%目标当前生命；不采用最大生命。');damage(x,'sweep_hit','新月护卫实际横扫伤害','sweep_damage','physics');processStart(x,{delay:true});rule(x,'actual_sweep_hit','新月横扫实际命中',{eventType:'SKILL_HIT',detail:{sourceSkillKey:'xinzhao_r'}},['sweep_hit']);
 pending(x,'被挑战状态、唯一目标替换及免击退','被动保留最后一个被攻击或E伤害命中的英雄3秒，并与W刺击标记共同供E/R读取。目标被挑战只免去击退，不免去R伤害，不能把整个命中规则排除。');pending(x,'按伤害来源位置的4秒免疫','防御行为在1V1内保留。需按伤害来源敌人是否处于450范围外判断，不能只按伤害类型、弹道或受击者当前位置建立全伤害免疫；当前仅参数候选。');exclude(x,'野怪小兵封顶和多目标击退路径','600上限不应用于英雄；附近其他目标和击退轨迹后置，当前敌方英雄的击退控制仍保留待配。');
}
export {plan};
