// 只核对已经完成的本地执行证据；不访问业务接口、不更改历史流水。
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const here=fileURLToPath(new URL('./',import.meta.url)),hash=x=>createHash('sha256').update(x).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(here,f),'utf8'));
const candidate=read('完整候选.json'),version=read('候选版本.json');assert.equal(hash(fs.readFileSync(path.join(here,'完整候选.json'))),version.fileSha256);
assert.equal(hash(fs.readFileSync(path.join(here,'主负责人语义复核.json'))),'c1db4bf02231b60e4b37ff4f1578ed2530bdbadf64ee76b32f540cd7cf3ad4e8');
const runs=fs.readdirSync(path.join(here,'执行记录')).map(id=>({id,file:'执行记录/'+id+'/执行结果.json'})).filter(x=>fs.existsSync(path.join(here,x.file))).map(x=>({...x,data:read(x.file)})),applies=runs.filter(x=>x.data.apply);assert.equal(applies.length,1,'本批必须只有一次实际执行，不接受盲重放');const applied=applies[0];assert.equal(applied.data.apiWrites,213);assert.equal(applied.data.preflight.readbacks.length,27);assert.equal(applied.data.final.readbacks.length,240);assert.equal(applied.data.final.missing.length,0);
const correction=read('列表摘要断言纠错.json');assert.equal(correction.pass,true);assert.equal(correction.originalReportSha256,hash(fs.readFileSync(path.join(here,applied.file))));assert.equal(correction.checks.length,240);assert.ok(correction.checks.every(x=>x.pass));assert.equal(applied.data.final.conflicts.length,70);assert.ok(applied.data.final.conflicts.every(x=>x.listDetailMismatch));assert.ok(applied.data.final.readbacks.every(x=>x.match));
const independentFiles=fs.readdirSync(path.join(here,'独立回读')).map(id=>({id,file:'独立回读/'+id+'/独立全量回读.json'})).filter(x=>fs.existsSync(path.join(here,x.file))).map(x=>({...x,data:read(x.file)}));assert.ok(independentFiles.length);const independent=independentFiles.findLast(x=>x.data.success);assert.ok(independent,'没有成功的独立回读');assert.equal(independent.data.apiWrites,0);assert.equal(independent.data.snapshot.missing.length,0);assert.equal(independent.data.snapshot.conflicts.length,0);assert.equal(independent.data.snapshot.readbacks.length,240);assert.equal(independent.data.verification.saved,true);assert.equal(independent.data.verification.pass,true);
function auditJournal(relative){const bytes=fs.readFileSync(path.join(here,relative),'utf8'),events=bytes.trim().split(/\r?\n/).map(s=>JSON.parse(s)),before=events.filter(x=>x.phase==='请求前'),after=events.filter(x=>x.phase==='请求后');assert.equal(before.length,after.length);assert.equal(events.length,before.length*2);assert.equal(new Set(before.map(x=>x.id)).size,before.length);for(const p of before){const r=after.find(x=>x.id===p.id);assert.ok(r);assert.equal(p.route,r.route);assert.equal(p.method,r.method);assert.ok(events.indexOf(p)<events.indexOf(r));assert.ok(['GET','POST'].includes(p.method));}assert.ok(!/Authorization|Bearer\s+[A-Za-z0-9]/i.test(bytes),'流水不应含鉴权字段');return {file:relative,sha256:hash(bytes),requests:before.length,methods:before.reduce((m,x)=>(m[x.method]=(m[x.method]??0)+1,m),{}),statuses:after.reduce((m,x)=>(m[x.status]=(m[x.status]??0)+1,m),{}),before,after};}
const applyJournal=auditJournal('执行记录/'+applied.id+'/HTTP流水.jsonl'),readJournal=auditJournal('独立回读/'+independent.id+'/HTTP流水.jsonl');assert.equal(applyJournal.methods.POST,213);assert.equal(readJournal.methods.POST,undefined);assert.equal(readJournal.requests,408);assert.equal(readJournal.statuses['200'],408);
const posts=applyJournal.before.filter(x=>x.method==='POST'),postKeys=new Set(),byKind={},byHero={};for(const r of posts){const m=r.route.match(/^\/skills\/((graves|jinx|varus|kogmaw)_[pqwer])\/(parameters|formulas|effects)$/);assert.ok(m);const idField={parameters:'parameterKey',formulas:'formulaKey',effects:'effectKey'}[m[3]],key=m[1]+'/'+m[3]+'/'+r.body[idField];assert.ok(!postKeys.has(key));postKeys.add(key);assert.deepEqual(r.body,candidate.skills[m[1]].write[m[3]].find(x=>x[idField]===r.body[idField]));assert.equal(applyJournal.after.find(x=>x.id===r.id).status,201);byKind[m[3]]=(byKind[m[3]]??0)+1;byHero[m[2]]=(byHero[m[2]]??0)+1;}
assert.deepEqual(byKind,{parameters:143,formulas:49,effects:21});assert.equal(fs.readdirSync(path.join(here,'写前意图')).filter(x=>x.endsWith('.json')).length,213);
const originalHashes=[['根绑定与数值证据.json','e59f40c13d57fcef26ede39ce33fe9c99fc938f46f8666bb5ab10d21752cb1b6'],['补充文本证据.json','95ad677cb6aaca057e67e35641ce23bb1beb6992f2eba977684ee259d54e1f4b'],['写前现值.json','c34a9ffb21b345e4f576c2183019fa391e19cb0ee3f1f8af44a0c24fc862163b']];
for(const[file,expected]of originalHashes)assert.equal(hash(fs.readFileSync(path.join(here,file))),expected);
const summaryJournal=x=>({file:x.file,sha256:x.sha256,requests:x.requests,methods:x.methods,statuses:x.statuses});
const report={at:new Date().toISOString(),success:true,candidateFileSha256:version.fileSha256,candidateObjectSha256:version.planSha256,actual:{new:213,reused:27,total:240,newByKind:byKind,newByHero:byHero,post201:213,unknownResponses:0,replayedPost:0},apply:{runId:applied.id,file:applied.file,sha256:hash(fs.readFileSync(path.join(here,applied.file))),journal:summaryJournal(applyJournal)},independent:{runId:independent.id,file:independent.file,sha256:hash(fs.readFileSync(path.join(here,independent.file))),journal:summaryJournal(readJournal),subjects:20,compositionLists:120,compositionDetails:240,representativeImages:20,characterRelations:4,catalogs:4,fields:independent.data.verification.fields,checks:independent.data.verification.checks.length,sourceCases:independent.data.verification.sourceCases.length,handCases:independent.data.verification.cases.length,actualInputSha256:independent.data.verification.inputSha256,missing:0,conflicts:0},originalHashes,rootReviewSha256:'c1db4bf02231b60e4b37ff4f1578ed2530bdbadf64ee76b32f540cd7cf3ad4e8',boundary:'管理API实际写入及独立实值数学通过；触发、未证输入与完整战斗仍未接线。没有PUT/DELETE、图片或关系写入。'};
report.resolvedHistoricalCheckIssue={file:'列表摘要断言纠错.json',sha256:hash(fs.readFileSync(path.join(here,'列表摘要断言纠错.json'))),originalReportUnchanged:true,previousFalseConflicts:70,description:correction.cause,correction:correction.correction,noReplay:true};
const bytes=JSON.stringify(report,null,2)+'\n';fs.writeFileSync(path.join(here,'最终实录结果.json'),bytes,{flag:'wx'});console.log(JSON.stringify({success:true,finalReportSha256:hash(bytes),actual:report.actual,independent:report.independent}));
