import fs from 'node:fs';
import path from 'node:path';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {isDeepStrictEqual as eq} from 'node:util';
const here=new URL('./',import.meta.url),read=n=>JSON.parse(fs.readFileSync(new URL(n,here),'utf8')),plan=read('完整候选.json'),evidence=read('根绑定与数值证据.json'),text=read('补充文本证据.json'),snapshot=read('写前现值.json');
const checks=[],cases=[],sourceCases=[],failures=[];const check=(name,pass,detail=null)=>{checks.push({name,pass,detail});if(!pass)failures.push({name,detail});};
const hash=b=>createHash('sha256').update(b).digest('hex'),round=n=>Math.round(n*1e6)/1e6;
const dataBase='C:/project/damage_viewer_project_planning/数据参考/全量录入-2026-09/技能公共参数实录';
const sources=[];
for(const h of evidence.heroes){const zipped=fs.readFileSync(path.join(dataBase,h.client.path)),raw=gunzipSync(zipped),officialBytes=fs.readFileSync(path.resolve(dataBase,h.official.path)),client=JSON.parse(raw),official=JSON.parse(officialBytes).data[h.id];
 check(h.id+'客户端压缩及原文哈希',hash(raw)===h.client.sha256&&hash(zipped)===h.client.compressedSha256);check(h.id+'官方哈希',hash(officialBytes)===h.official.sha256);check(h.id+'角色根完整相同',eq(client[h.rootPath],h.rootObject));
 for(const s of h.spells){const index=['Q','W','E','R'].indexOf(s.slot.toUpperCase()),binding=index<0?client[h.rootPath].mCharacterPassiveSpell:client[h.rootPath].spells[index],o=index<0?official.passive:official.spells[index];check(s.skillKey+'当前根绑定及完整对象',binding===s.binding&&eq(client[binding],s.object)&&eq(o,s.official));}
 sources.push({hero:h.id,url:h.client.sourceUrl,clientSha256:hash(raw),compressedSha256:hash(zipped),officialSha256:hash(officialBytes),officialUrl:h.official.url,version:h.client.contentVersion});
}
const locRaw=gunzipSync(fs.readFileSync(text.path)),loc=JSON.parse(locRaw);check('完整当前中文原文哈希',hash(locRaw)===text.sha256);for(const[k,record]of Object.entries(text.skills)){check(k+'绑定中文完整保留',eq(plan.skills[k].source.currentBoundText,record));for(const v of Object.values(record.keys))if(v.key)check(k+'/'+v.key+'原文一致',(loc.entries??loc)[v.key]===v.text);}
const spell=k=>evidence.heroes.flatMap(h=>h.spells).find(s=>s.skillKey===k),parameter=(k,p)=>plan.skills[k].write.parameters.find(v=>v.parameterKey===p);
const kinds={parameters:'parameterKey',formulas:'formulaKey',effects:'effectKey',processes:'processKey',internalStates:'stateKey',triggerRules:'ruleKey'};
const coverage=[];
function validateNode(n,k){check(k+'合法表达式节点',n&&['PARAMETER','ATTRIBUTE','OPERATION'].includes(n.nodeType)&&!('kind'in n));if(!n)return;if(n.nodeType==='PARAMETER')check(k+'参数引用存在',!!parameter(k.split('/')[0],n.parameterKey),n.parameterKey);if(n.nodeType==='OPERATION'){check(k+'二元运算',n.operands?.length===2,n);for(const v of n.operands??[])validateNode(v,k);}}
for(const[k,s]of Object.entries(plan.skills)){
 check(k+'六类组成齐全',eq(Object.keys(s.write),Object.keys(kinds)));for(const[kind,id]of Object.entries(kinds)){check(k+'/'+kind+'唯一稳定键',s.write[kind].every(v=>typeof v[id]==='string')&&new Set(s.write[kind].map(v=>v[id])).size===s.write[kind].length);}
 for(const p of s.write.parameters)if(p.valueMode==='RUNTIME_INPUT')check(k+'/'+p.parameterKey+'无默认输入',p.fixedValue===null&&p.levelValues===null);
 check(k+'没有推测等级曲线',!s.write.parameters.some(p=>p.valueMode==='CHARACTER_LEVEL'));check(k+'没有伤害或瞬时治疗结果',!s.write.effects.some(e=>e.results.some(r=>['DAMAGE','DIRECT_HEAL'].includes(r.resultType))));check(k+'没有触发、过程和状态',!s.write.processes.length&&!s.write.triggerRules.length&&!s.write.internalStates.length);
 for(const f of s.write.formulas)validateNode(f.expression,k+'/'+f.formulaKey);
 for(const p of snapshot.skills[k].components.parameters.items){const expected=Object.fromEntries(Object.entries(p).filter(([a])=>!['gameId','skillKey','createdAt','updatedAt'].includes(a)));check(k+'/'+p.parameterKey+'原公共参数完整保护',eq(expected,parameter(k,p.parameterKey)));}
 for(const proof of s.proofs.filter(p=>p.parameterKey&&p.source?.startsWith('DataValues.'))){const d=spell(k).object.mSpell.DataValues.find(v=>v.name===proof.source.slice(11));check(k+'/'+proof.source+'源数组未改',eq(proof.raw,d?.values));const values=d.values.slice(proof.offset??1,(proof.offset??1)+s.maxLevel).map(v=>round(round(v)*(proof.scale??1))),p=parameter(k,proof.parameterKey),actual=p.valueMode==='FIXED'?Array(values.length).fill(p.fixedValue):Object.values(p.levelValues);check(k+'/'+proof.parameterKey+'索引及单位换算',eq(actual,values),{actual,expected:values});}
 const classified=new Set(s.proofs.filter(v=>v.source?.startsWith('DataValues.')).map(v=>v.source.slice(11))),rawData=spell(k).object.mSpell.DataValues??[];coverage.push({skillKey:k,totalDataFields:rawData.length,classified:rawData.filter(v=>classified.has(v.name)).map(v=>v.name),unclassified:rawData.filter(v=>!classified.has(v.name)).map(v=>v.name)});
}
check('20槽精确覆盖',eq(Object.keys(plan.skills),['graves','jinx','varus','kogmaw'].flatMap(h=>['p','q','w','e','r'].map(s=>h+'_'+s))));check('所有当前DataValues逐项分类',coverage.every(v=>!v.unclassified.length),coverage.filter(v=>v.unclassified.length));

// 独立解释原始树和最终候选；不调用生成器。未知属性/等级值显式外供。
function context(k,rank=1,variant=0){const stats={'0/0':variant?240:100,'2/0':variant?350:200,'2/2':variant?90:50,'12/2':600,'9/0':variant?2.5:2.35,'4/2':variant?1.2:.7},runtime={};
 for(const p of plan.skills[k].write.parameters.filter(p=>p.valueMode==='RUNTIME_INPUT')){const m=p.parameterKey.match(/^source_stat_(\d+)_(\d+)_value$/);if(m)runtime[p.parameterKey]=stats[m[1]+'/'+m[2]];else if(p.parameterKey.includes('single_bullet_damage_level'))runtime[p.parameterKey]=variant?.91:.82;else if(p.parameterKey.includes('ordinary_attack_speed_level'))runtime[p.parameterKey]=variant?.19:.17;else if(p.parameterKey.includes('buff_duration_seconds_level'))runtime[p.parameterKey]=variant?9:7;else if(p.parameterKey.includes('death_explosion_damage_level'))runtime[p.parameterKey]=variant?511:377;else runtime[p.parameterKey]=({current_grit_stacks:3,actual_detonated_stacks:2,affected_skill_base_cooldown_ms:10000,actual_mana_spent:85,actual_prior_cost_stacks:3})[p.parameterKey];if(!Number.isFinite(runtime[p.parameterKey]))throw Error('测试遗漏实际输入 '+k+'/'+p.parameterKey);}
 return {rank,stats,runtime,attributes:{'SOURCE.attack_damage.TOTAL':stats['2/0'],'SOURCE.attack_damage.BONUS':stats['2/2'],'SOURCE.ability_power.TOTAL':stats['0/0'],'SOURCE.hp.BONUS':600,'TARGET.hp.TOTAL':2000,'TARGET.hp.MISSING':1200}};
}
function candidateValue(k,n,c){if(n.nodeType==='PARAMETER'||n.kind==='PARAMETER'){const p=parameter(k,n.parameterKey);if(p.valueMode==='FIXED')return p.fixedValue;if(p.valueMode==='RUNTIME_INPUT'){if(!Object.hasOwn(c.runtime,p.parameterKey))throw Error('缺输入 '+p.parameterKey);return c.runtime[p.parameterKey];}return p.levelValues[String(c.rank)];}if(n.nodeType==='ATTRIBUTE'){if(!Object.hasOwn(c.attributes,n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind))throw Error('缺属性');return c.attributes[n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind];}if(n.kind==='FIXED')return n.value;if(n.kind==='FORMULA')return formulaValue(k,n.formulaKey,c);if(n.nodeType==='OPERATION'){const[a,b]=n.operands.map(v=>candidateValue(k,v,c));switch(n.operation){case'ADD':return a+b;case'SUBTRACT':return a-b;case'MULTIPLY':return a*b;case'DIVIDE':return a/b;case'MIN':return Math.min(a,b);case'MAX':return Math.max(a,b);}}throw Error('非法候选节点');}
function formulaValue(k,f,c){return candidateValue(k,plan.skills[k].write.formulas.find(v=>v.formulaKey===f).expression,c);}
function originalValue(k,n,c,source){const t=n.__type,raw=spell(k).object.mSpell;
 if(t==='NamedDataValueCalculationPart')return raw.DataValues.find(v=>v.name===n.mDataValue).values[c.rank];
 if(t==='NumberCalculationPart')return n.mNumber;
 if(['StatByNamedDataValueCalculationPart','StatByCoefficientCalculationPart','StatBySubPartCalculationPart'].includes(t)){const stat=c.stats[(n.mStat??0)+'/'+(n.mStatFormula??0)];if(!Number.isFinite(stat))throw Error('缺原始属性测试值');return stat*(t==='StatByNamedDataValueCalculationPart'?raw.DataValues.find(v=>v.name===n.mDataValue).values[c.rank]:t==='StatByCoefficientCalculationPart'?n.mCoefficient:originalValue(k,n.mSubpart,c,source+'.mSubpart'));}
 if(t==='ProductOfSubPartsCalculationPart')return originalValue(k,n.mPart1,c,source+'.mPart1')*originalValue(k,n.mPart2,c,source+'.mPart2');
 if(t==='SumOfSubPartsCalculationPart')return n.mSubparts.reduce((sum,v,i)=>sum+originalValue(k,v,c,source+'.mSubparts['+i+']'),0);
 if(t.startsWith('ByCharLevel')){const p=plan.skills[k].proofs.find(p=>p.source===source&&p.sourcePending&&p.parameterKey);if(!p||!eq(p.raw,n))throw Error('未知等级原节点没有完整记录');return c.runtime[p.parameterKey];}
 throw Error('原树类型未核 '+t);
}
function originalCalc(k,key,c){const raw=spell(k).object.mSpell.mSpellCalculations[key],root='mSpellCalculations.'+key;let v=raw.__type==='GameCalculationModified'?originalCalc(k,raw.mModifiedGameCalculation,c):raw.mFormulaParts.reduce((sum,n,i)=>sum+originalValue(k,n,c,root+'.mFormulaParts['+i+']'),0);if(raw.mMultiplier)v*=originalValue(k,raw.mMultiplier,c,root+'.mMultiplier');return v;}
for(const[k,s]of Object.entries(plan.skills))for(const rank of [...new Set([1,s.maxLevel])])for(const variant of [0,1]){const ctx=context(k,rank,variant);for(const p of s.proofs.filter(v=>v.formulaKey&&v.source?.startsWith('mSpellCalculations.'))){const actual=formulaValue(k,p.formulaKey,ctx),expected=originalCalc(k,p.source.slice(19),ctx),pass=Math.abs(actual-expected)<.001;sourceCases.push({skillKey:k,formulaKey:p.formulaKey,rank,variant,actual,expected,pass});check(k+'/'+p.formulaKey+'独立原树算术 rank'+rank+' variant'+variant,pass);}
 for(const f of s.write.formulas)check(k+'/'+f.formulaKey+'完整公式有限',Number.isFinite(formulaValue(k,f.formulaKey,ctx)));
}
function test(k,f,expected,modify=null){const ctx=context(k);if(modify)modify(ctx);const actual=formulaValue(k,f,ctx),pass=Math.abs(actual-expected)<.001;cases.push({skill:k,formula:f,inputs:ctx,actual,expected,pass});check(k+'/'+f+'独立手算',pass,{actual,expected});}
test('graves_p','single_bullet_damage',164);test('graves_p','four_pellets_same_target',327.836);test('graves_p','crit_pellet_increase',.675);test('graves_e','current_grit_armor',21);test('graves_e','current_grit_mr',10.5);
test('jinx_q','rocket_damage',220);test('jinx_r','damage_floor',26);test('jinx_r','max_damage_with_missing_health',560);
test('varus_p','ordinary_ad',7.7);test('varus_p','champion_ad',23.1);test('varus_q','damage_max',140);test('varus_q','damage_max',140,c=>c.attributes['SOURCE.attack_damage.TOTAL']=999);test('varus_q','cancel_mana_refund',42.5);
test('varus_w','on_hit_damage',36.5);test('varus_w','detonation_damage',172);test('varus_w','q_empower_missing_damage',72);test('varus_w','q_empower_max_missing_damage',108);test('varus_w','base_cooldown_refund_ms',2600);
test('kogmaw_p','death_explosion_damage',377);test('kogmaw_q','damage',170);test('kogmaw_w','on_hit_damage',90);test('kogmaw_r','base_damage_value',172.5);test('kogmaw_r','low_health_damage',345);test('kogmaw_r','normal_missing_health_damage',258.749655);for(const[n,cost]of [[0,40],[3,160],[9,400],[12,400]])test('kogmaw_r','actual_mana_cost',cost,c=>c.runtime.actual_prior_cost_stacks=n);
check('KogR阈值严格低于40%',parameter('kogmaw_r','low_health_threshold').fixedValue===.4&&plan.skills.kogmaw_r.write.formulas.find(f=>f.formulaKey==='normal_missing_health_damage').description.includes('>=40%'));
const gravesCD=plan.skills.graves_e.write.effects.find(e=>e.effectKey==='pellet_cooldown_reduction').results[0];check('男枪每弹冷却单位500毫秒',candidateValue('graves_e',gravesCD.valueRule.value,context('graves_e'))*gravesCD.valueRule.fixedMultiplier===500);
check('朝敌人突进2层是总数',parameter('graves_e','toward_enemy_total_stacks').fixedValue===2&&!plan.skills.graves_e.write.parameters.some(p=>p.parameterKey==='dash_toward_enemy_bonus_stacks'));
check('金克丝切换不扣火箭费用',spell('jinx_q').object.mSpell.mDoesNotConsumeMana===true&&!plan.skills.jinx_q.write.parameters.some(p=>p.parameterKey==='mana_cost')&&parameter('jinx_q','rocket_mana_cost').fixedValue===20);
check('KogR消费动态公式而非基础40',plan.skills.kogmaw_r.write.effects.find(e=>e.effectKey==='mana_cost').results[0].valueRule.value.formulaKey==='actual_mana_cost');
for(const k of ['varus_q','varus_w'])check(k+'没有比例直接扣毫秒效果',!plan.skills[k].write.effects.some(e=>e.results.some(r=>r.resultType==='COOLDOWN_CHANGE')));
check('没有借用装备专用乘区',Object.values(plan.skills).every(s=>s.write.effects.every(e=>e.results.every(r=>!r.detail.modifierZoneKey||r.detail.modifierZoneKey==='attribute_flat_add'))));
const runtimeNodes=Object.values(plan.skills).flatMap(s=>s.proofs.filter(p=>p.sourcePending&&p.parameterKey&&p.raw?.__type?.startsWith('ByCharLevel')).map(p=>({skillKey:s.skillKey,key:p.parameterKey,source:p.source,type:p.raw.__type})));check('四个等级节点均明确外供',runtimeNodes.length===4,runtimeNodes);
for(const item of runtimeNodes){const formula=plan.skills[item.skillKey].write.formulas.find(f=>JSON.stringify(f.expression).includes('"'+item.key+'"')),ctx=context(item.skillKey);delete ctx.runtime[item.key];let threw=false;try{formulaValue(item.skillKey,formula.formulaKey,ctx);}catch{threw=true;}check(item.skillKey+'/'+item.key+'缺值拒算',threw);}
const report={at:new Date().toISOString(),pass:!failures.length,apiWrites:0,fileSha256:hash(fs.readFileSync(new URL('完整候选.json',here))),planSha256:hash(JSON.stringify(plan)),sources,textSha256:hash(locRaw),checks,sourceCases,cases,coverage,runtimeNodes,failures,boundary:'静态来源与独立算术；没有业务写入或战斗运行，外供值不证明等级曲线或触发资格。'};fs.writeFileSync(new URL('独立核算.json',here),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pass:report.pass,checks:checks.length,sourceCases:sourceCases.length,handCases:cases.length,failures,runtimeNodes:runtimeNodes.length}));if(failures.length)process.exitCode=1;
