import {readFile} from 'node:fs/promises';
const evidence=JSON.parse(await readFile(new URL('./根绑定与数值证据.json',import.meta.url),'utf8'));
const textEvidence=JSON.parse(await readFile(new URL('./补充文本证据.json',import.meta.url),'utf8'));
const clean=n=>Math.round(n*1e6)/1e6;
const levels=a=>Object.fromEntries(a.map((v,i)=>[String(i+1),v]));
const val=parameterKey=>({kind:'PARAMETER',parameterKey});
const fval=formulaKey=>({kind:'FORMULA',formulaKey});
const fixed=value=>({kind:'FIXED',value});
const pn=parameterKey=>({nodeType:'PARAMETER',parameterKey});
const attr=(key,owner='SOURCE',kind='TOTAL')=>({nodeType:'ATTRIBUTE',attributeOwner:owner,attributeKey:key,attributeValueKind:kind});
const op=(operation,a,b)=>({nodeType:'OPERATION',operation,operands:[a,b]});
const add=(...xs)=>xs.reduce((a,b)=>op('ADD',a,b));
const mul=(a,b)=>op('MULTIPLY',a,b);
const valueRule=value=>({value,fixedMultiplier:1,fixedMinValue:0,fixedMaxValue:null});
const behavior={moment:'PERSISTENT',valueReadMode:'APPLICATION_SNAPSHOT',stackValueMode:'SHARED',reapplicationValueMode:'REPLACE',periodicExecutionMode:null};
const life=duration=>({durationValue:duration,maxStacksValue:fixed(1),applicationStacksValue:fixed(1),instanceScope:'SOURCE',reapplicationStackMode:'KEEP',reapplicationDurationMode:duration?'REFRESH_ALL':null,expiryMode:duration?'ALL_AT_ONCE':'EXPLICIT_ONLY',periodicIntervalValue:null,firstPeriodicExecution:null});
export const plan={meta:{executor:'Codex执行代理接手Cursor中断批次',gameId:'lol',note:'来源冻结与当前录入分开；只计实际GET一致的组成。没有运行Wasm或战斗。本批仅补缺，不更新既有不同内容。',sources:evidence.heroes.map(h=>({id:h.id,client:h.client,official:h.official})),scope:'四英雄20技能；召唤物、纯视野、野怪支路和多对象空间执行按既有约定后置。控制与跨技能接线是待补，不是范围外。'},skills:{}};
function begin(key){const h=evidence.heroes.find(h=>h.spells.some(s=>s.skillKey===key));const s=h.spells.find(s=>s.skillKey===key);const c={skillKey:key,name:s.official.name,maxLevel:s.official.maxrank??1,source:{hero:h.id,rootPath:h.rootPath,spellPath:s.binding,clientSha256:h.client.sha256,officialSha256:h.official.sha256},write:{parameters:[],formulas:[],effects:[],processes:[],internalStates:[],triggerRules:[]},proofs:[],pending:[],excluded:[]};plan.skills[key]=c;return {c,s,p:s.object.mSpell};}
function parameter(x,key,name,values,description,mode){const a=Array.isArray(values)?values:[values];if(!a.length||!a.every(Number.isFinite))throw Error('缺值 '+x.c.skillKey+'/'+key);const variable=mode==='CHARACTER_LEVEL'||new Set(a).size>1;const body={parameterKey:key,name,valueType:a.every(Number.isInteger)?'INTEGER':'DECIMAL',valueMode:mode??(variable?'SKILL_LEVEL':'FIXED'),fixedValue:variable?null:a[0],levelValues:variable?levels(a):null,description,sortOrder:(x.c.write.parameters.length+1)*10};x.c.write.parameters.push(body);return key;}
function data(x,source,key,name,{scale=1,unit='',fixedOnly=false}={}){const d=(x.p.DataValues??x.p.mDataValues??[]).find(d=>(d.name??d.mName)===source);const raw=d?.values??d?.mValues;if(!raw||raw.length<x.c.maxLevel+1)throw Error('数据字段缺失 '+x.c.skillKey+'/'+source);const arr=raw.slice(1,x.c.maxLevel+1).map(v=>clean(v*scale));if(fixedOnly&&new Set(arr).size!==1)throw Error('不是固定值 '+source);x.c.proofs.push({parameterKey:key,source:'DataValues.'+source,raw,offset:1,values:arr,scale});return parameter(x,key,name,arr,`客户端当前根绑定 DataValues.${source} 取索引1至${x.c.maxLevel}${unit?'；单位'+unit:''}。`);}
function literal(x,key,name,value,description,path){x.c.proofs.push({parameterKey:key,source:path??'官方说明或明确计算派生',values:Array.isArray(value)?value:[value]});return parameter(x,key,name,value,description);}
function coefficient(x,calc,index,key,name){const p=x.p.mSpellCalculations[calc].mFormulaParts[index];if(p.__type!=='StatByCoefficientCalculationPart'||p.mStat!=null)throw Error('非默认法强系数 '+calc+'/'+index);return literal(x,key,name,clean(p.mCoefficient),`客户端 ${calc}.mFormulaParts[${index}] 默认法术强度系数；按当前浮点设计值归一。`,'mSpellCalculations.'+calc+'.mFormulaParts.'+index);}
function formula(x,key,name,expression,description){x.c.write.formulas.push({formulaKey:key,name,expression,description,sortOrder:(x.c.write.formulas.length+1)*10});}
function result(key,name,type,target,value,detail,lifecycleBehavior=null,block=null,description=null){return {resultKey:key,name,resultType:type,target,description,sortOrder:10,lifecycleBehavior,spellShieldBlockScope:block,valueRule:value?valueRule(value):null,detail};}
function effect(x,key,name,results,lifecycle=null,description=null){x.c.write.effects.push({effectKey:key,name,description,sortOrder:(x.c.write.effects.length+1)*10,lifecycle,results});}
function damage(x,key,name,formulaKey,type='magic',{delivery='SKILL',origin='DIRECT',crit=null,block='RESULT',description='独立伤害；实际触发另行核对，吸血规则空列表不代表不能吸血。'}={}){effect(x,key,name,[result('damage',name,'DAMAGE','TARGET',fval(formulaKey),{damageTypeKey:type,deliveryKind:delivery,originKind:origin,critical:{mode:crit?'SOURCE_CRIT_CHANCE':'DISALLOWED',multiplierValue:crit},vampRules:[]},null,block)],null,description);}
function manaEffect(x){effect(x,'mana_cost','施放法力消耗',[result('consume_mana','消耗法力','RESOURCE_CHANGE','SOURCE',val('mana_cost'),{attributeKey:'mana',operation:'CONSUME'})],null,'仅施放法力消耗；具体过程单独绑定。');}
function activeCommon(x,{cast=false,allowOfficialCooldown=false}={}){const n=x.c.maxLevel,d=x.s.official,rawCd=x.p.cooldownTime,rawMana=x.p.mana;const cd=rawCd?.slice(1,n+1),mana=rawMana?.slice(0,n);if(cd?.length===n&&cd.every((v,i)=>Math.abs(v-d.cooldown[i])<1e-5)){literal(x,'cooldown_ms','基础冷却时间（毫秒）',d.cooldown.map(v=>Math.round(v*1000)),'官方16.17.1冷却与当前主技能 cooldownTime[1..等级上限]一致；仅基础冷却，不含急速和重置。','official.cooldown + cooldownTime');}else if(allowOfficialCooldown){literal(x,'cooldown_ms','基础冷却时间（毫秒）',d.cooldown.map(v=>Math.round(v*1000)),'当前主技能无 cooldownTime，采用官方16.17.1基础冷却；不借用其他同名旧对象。','official.cooldown');}else{x.c.pending.push({kind:'资料',component:'cooldown_ms',reason:'官方与主对象冷却不一致或缺失，待核对',official:d.cooldown,client:rawCd});}if(mana?.length===n&&mana.every((v,i)=>Math.abs(v-d.cost[i])<1e-5)){literal(x,'mana_cost','法力消耗',d.cost,'官方16.17.1 cost与主技能mana索引0..等级上限-1一致。','official.cost + mana');manaEffect(x);}else{x.c.pending.push({kind:'资料',component:'mana_cost',reason:'官方与客户端消耗不一致，禁止猜值与静默选边',official:d.cost,client:rawMana});}if(cast){if(!(x.p.spellCastTime>0)||x.p.mUseAutoattackCastTimeData||(x.p.mCastTime!=null&&Math.abs(x.p.mCastTime-x.p.spellCastTime)>1e-5))throw Error('施法时长不唯一 '+x.c.skillKey);literal(x,'cast_time_ms','施法时间（毫秒）',Math.round(x.p.spellCastTime*1000),'当前主技能 spellCastTime；仅施法延迟，不代替实际命中。','spellCastTime');}}
function castProcess(x){x.c.write.processes.push({processKey:'cast',name:'施放'+x.c.name,activationType:'ACTIVE',description:'只绑定法力、基础冷却及施法延迟；不在过程结束时自动造成伤害。',sortOrder:10,cooldown:{durationValue:val('cooldown_ms'),startMoment:{momentType:'PROCESS_START',stepKey:null}},steps:[{stepKey:'cast_time',name:'施法延迟',description:'主技能已核对的施法时间。',sortOrder:10,stepType:'DELAY',detail:{delayValue:val('cast_time_ms')}}],effectBindings:[{bindingKey:'mana_cost',effectKey:'mana_cost',moment:{momentType:'PROCESS_START',stepKey:null},sortOrder:10}],stateOperations:[]});}
function hit(x,key){x.c.write.triggerRules.push({ruleKey:'actual_hit',name:x.c.name+'实际命中',description:'接收该技能实际命中，仅执行所述直接伤害；规则本身不生成命中，也不替代控制或跨技能联动。',sortOrder:10,eventSource:{eventType:'SKILL_HIT',detail:{sourceSkillKey:x.c.skillKey}},conditionGroups:[],actions:[{actionKey:'damage',name:'执行命中伤害',actionType:'EXECUTE_EFFECT',sortOrder:10,targetContext:'CURRENT_TARGET',detail:{effectKey:key},runtimeInputBindings:[],resultModifiers:[]}],perTargetCooldown:null,maxTriggersPerProcess:null});}
function pending(x,component,reason,kind='配置'){x.c.pending.push({kind,component,reason});}
function exclude(x,component,reason){x.c.excluded.push({component,reason});}
function apDamage(x,source='BaseDamage',calc='TotalDamage',namedRatio='APRatio'){data(x,source,'base_damage','基础伤害');if(namedRatio)data(x,namedRatio,'ap_ratio','法术强度倍率');else coefficient(x,calc,x.p.mSpellCalculations[calc].mFormulaParts.findIndex(p=>p.__type==='StatByCoefficientCalculationPart'&&p.mStat==null),'ap_ratio','法术强度倍率');formula(x,'damage',x.c.name+'伤害',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),`当前根技能 ${calc}：基础伤害+来源总法术强度×倍率。`);}
function shield(x,key,name,formulaKey,duration){effect(x,key,name,[result('shield','普通护盾','NORMAL_SHIELD','SOURCE',fval(formulaKey),{absorbedDamageTypeKey:null,decayMode:'NONE'},behavior)],life(duration),'自身护盾：结果目标与实例范围均为来源对象。独立组成，施加及刷新条件另行接线。');}
function attributeEffect(x,key,name,parameterKey,attributeKey,duration){effect(x,key,name,[result('attribute',name,'ATTRIBUTE_CHANGE','SOURCE',val(parameterKey),{attributeKey,operation:'INCREASE',modifierZoneKey:'attribute_flat_add'},behavior)],life(duration),'独立持续属性。比例属性按百分点加算，1表示100%；不是把面板最终属性乘此比例。');}
function curve(x,key,name,part,scale=1){if(part.__type!=='ByCharLevelBreakpointsCalculationPart')throw Error('不是断点');const a=Array.from({length:18},(_,i)=>{let v=part.mLevel1Value;for(const b of part.mBreakpoints??[]){if(b.mBonusPerLevelAtAndAfter!=null)throw Error('需要逐级增量，不能只取断点');if(i+1>=b.mLevel)v+=b.mAdditionalBonusAtThisLevel??0;}return clean(v*scale);});parameter(x,key,name,a,'当前计算式的角色等级断点，取1至18级；19级及以后不计本批已覆盖。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,source:'mSpellCalculations角色等级断点',raw:part,values:a,scale});}
function interp(x,key,name,part,scale=1){if(part.__type!=='ByCharLevelInterpolationCalculationPart')throw Error('不是等级插值');const a=Array.from({length:18},(_,i)=>Math.round((clean(part.mStartValue)+(clean(part.mEndValue)-clean(part.mStartValue))*i/17)*scale*1e9)/1e9);parameter(x,key,name,a,'当前计算式角色等级1至18线性插值；比例1表示100%。','CHARACTER_LEVEL');x.c.proofs.push({parameterKey:key,source:'mSpellCalculations角色等级插值',raw:part,values:a,scale});}

{
 const x=begin('malphite_p');literal(x,'shield_hp_ratio','最大生命值护盾倍率',0.1,'官方被动10%最大生命值，与 TotalShield mStat=12、系数0.1一致。','mSpellCalculations.TotalShield');curve(x,'recharge_delay_ms','未受攻击护盾重置等待（毫秒）',x.p.mSpellCalculations.PassiveCooldown.mFormulaParts[0],1000);formula(x,'shield','花岗岩护盾量',mul(pn('shield_hp_ratio'),attr('hp')),'来源总生命值代表最大生命值，不使用当前剩余生命。');shield(x,'granite_shield','花岗岩自护盾','shield',null);pending(x,'护盾重置与W联动','未受攻击等待、受伤重新计时、耗尽及补盾事件需要精确接线；不能把普通冷却完成当作所有条件满足。');
}
{
 const x=begin('malphite_q');activeCommon(x,{cast:true});apDamage(x,'BaseDamage','QDamageCalc',null);data(x,'SpeedSteal','slow_ratio','移动速度窃取比例',{scale:.01});data(x,'SlowDuration','slow_duration_ms','移动速度窃取持续（毫秒）',{scale:1000});damage(x,'shard_hit','碎片命中魔法伤害','damage');castProcess(x);hit(x,'shard_hit');pending(x,'减速与窃取同额移动速度','目标减速后的实际点数需要提供给来源加速，不能把目标与来源都乘20%当同额窃取。');
}
{
 const x=begin('malphite_w');activeCommon(x);data(x,'ThunderclapBaseDamage','base_damage','下一次攻击额外基础伤害');data(x,'ThunderclapBaseDamageAPRatio','ap_ratio','下一次攻击法强倍率');data(x,'ThunderclapBaseDamageArmorRatio','armor_ratio','下一次攻击总护甲倍率');data(x,'ThunderclapSplashDamage','splash_base','余震基础伤害');data(x,'ThunderclapSplashAP','splash_ap_ratio','余震法强倍率');data(x,'ThunderclapSplashArmor','splash_armor_ratio','余震总护甲倍率');data(x,'ThunderclapBuffDuration','buff_duration_ms','余震强化持续（毫秒）',{scale:1000});data(x,'BonusArmorPassive','armor_increase_ratio','常态护甲提升比例');data(x,'BonusArmorPassiveMultiplier','shield_armor_multiplier','花岗岩护盾存在时倍率');formula(x,'next_attack_damage','下一次攻击额外伤害',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power')),mul(pn('armor_ratio'),attr('armor'))),'当前 TotalBonusDamage；只表达额外部分，不重复普通攻击基础伤害。');formula(x,'splash_damage','单次余震伤害',add(pn('splash_base'),mul(pn('splash_ap_ratio'),attr('ability_power')),mul(pn('splash_armor_ratio'),attr('armor'))),'当前 ThunderclapSplash；DataValues旧ThunderclapSlowDamage未被当前说明引用，不录为常规增伤。');damage(x,'empowered_bonus','强化攻击额外物理伤害','next_attack_damage','physics',{delivery:'BASIC_ATTACK',block:null});damage(x,'aftershock_damage','余震物理伤害','splash_damage','physics',{delivery:'BASIC_ATTACK',block:null});pending(x,'强化攻击消费与持续余震','现接口支持强化普攻步骤，但首次强化窗口、消费时点及余震同目标叠加需再核对；不把所有普攻永远加伤害。');pending(x,'常态护甲与P增幅','常态增甲与花岗岩护盾存在条件、刷新顺序及避免最终护甲自引用待接线。');exclude(x,'野怪增伤及扇形多目标','固定1V1英雄目标不执行野怪倍率或空间目标搜索；当前目标余震伤害保留。');
}
{
 const x=begin('malphite_e');activeCommon(x);data(x,'BaseDamage','base_damage','基础魔法伤害');coefficient(x,'EDamageCalc',2,'ap_ratio','法术强度倍率');literal(x,'armor_ratio','总护甲倍率',clean(x.p.mSpellCalculations.EDamageCalc.mFormulaParts[1].mCoefficient),'EDamageCalc mStat=1 总护甲系数0.4。','mSpellCalculations.EDamageCalc.mFormulaParts.1');data(x,'ASReduction','attack_speed_reduction_ratio','攻击速度降低比例',{scale:.01});data(x,'Duration','reduction_duration_ms','攻速降低持续（毫秒）',{scale:1000});formula(x,'damage','大地震颤魔法伤害',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power')),mul(pn('armor_ratio'),attr('armor'))),'来源总护甲×0.4 +总法强×0.6 +基础。');damage(x,'slam_hit','震地命中','damage');hit(x,'slam_hit');pending(x,'施法与攻速削减','mCastTime约0.2419与spellCastTime0.25不同，先不自动选一项；攻速削减是最终攻速减幅，不能等同额外攻速属性减30个百分点。');
}
{
 const x=begin('malphite_r');activeCommon(x);apDamage(x,'BaseDamage','TotalDamage',null);data(x,'KnockupDuration','knockup_duration_ms','击飞持续（毫秒）',{scale:1000});damage(x,'impact_hit','冲撞命中魔法伤害','damage');hit(x,'impact_hit');pending(x,'击飞及不可阻挡','数值已存，控制与突进期间不可阻挡需准确语义，不使用眩晕代替击飞。');exclude(x,'突进路径与区域搜索','空间执行依照当前范围后置，保留当前目标命中伤害。');
}
{
 const x=begin('missfortune_p');curve(x,'total_ad_ratio','新目标额外伤害总攻击力倍率',x.p.mSpellCalculations.TotalDamage.mFormulaParts[0].mSubpart);formula(x,'love_tap_damage','厄运眷顾额外伤害',mul(pn('total_ad_ratio'),attr('attack_damage')),'TotalDamage mStat=2总攻击力，倍率按角色等级断点。');damage(x,'love_tap_damage','新目标额外物理伤害','love_tap_damage','physics',{delivery:'BASIC_ATTACK',block:null});pending(x,'新目标判断及W冷却返还','需要比较上一次普攻目标，并在合法触发时联动W；不能简化成每次普攻触发。');exclude(x,'小兵伤害减半','当前1V1英雄对手不套用MinionDamage。');
}
{
 const x=begin('missfortune_q');activeCommon(x);data(x,'BaseDamage','base_damage','基础物理伤害');data(x,'ADRatio','total_ad_ratio','总攻击力倍率');data(x,'APRatio','ap_ratio','法术强度倍率');formula(x,'damage','第一段射击伤害',add(pn('base_damage'),mul(pn('total_ad_ratio'),attr('attack_damage')),mul(pn('ap_ratio'),attr('ability_power'))),'TotalDamageTooltip：基础+1.0总攻击力+0.35总法强。');damage(x,'primary_hit','第一目标射击伤害','damage','physics');pending(x,'攻击特效、P触发及第一目标事件','第一段独立伤害已存；通用SKILL_HIT不能分辨第一段与第二段，因此不挂全技能命中规则来覆盖弹跳暴击语义。');pending(x,'施法时间','mUseAutoattackCastTimeData存在；spellCastTime=0不代表无普攻前摇，待普攻施法时长映射。','资料');exclude(x,'第二目标弹跳与击杀后必暴','第二对象及身后筛选按本轮多对象范围后置，第一目标独立伤害与P依赖保留。');
}
{
 const x=begin('missfortune_w');activeCommon(x);data(x,'ActiveAS','bonus_attack_speed_ratio','主动额外攻击速度比例');data(x,'ActiveDuration','active_duration_ms','主动攻速持续（毫秒）',{scale:1000});data(x,'PassiveBaseMS','passive_base_move_speed','脱战第一阶段移动速度');data(x,'PassiveMaxMS','passive_max_move_speed','满额移动速度');data(x,'PassiveBaseMSOOC','first_ms_delay_ms','第一阶段未受伤等待（毫秒）',{scale:1000});data(x,'PassiveMaxMSExtraOOC','full_ms_extra_delay_ms','额外等待满额移速（毫秒）',{scale:1000});data(x,'LoveTapBaseRefund','love_tap_base_refund_ms','厄运眷顾基础冷却返还（毫秒）',{scale:1000});attributeEffect(x,'active_attack_speed','主动攻击速度加成','bonus_attack_speed_ratio','bonus_attack_speed_percent',val('active_duration_ms'));pending(x,'主动施放和移速状态','主动攻速4秒独立效果已存；被动两阶段、受伤清除、主动获得满额状态要共用状态，避免另加一次满额导致叠加。');pending(x,'P返还冷却','LoveTapRefund含CooldownMultiplierCalculationPart，不能直接固定减少2000毫秒；需要合法P触发及当前冷却倍率。');
}
{
 const x=begin('missfortune_e');activeCommon(x);data(x,'BaseDamagePerSecond','base_dps','每秒基础魔法伤害');data(x,'APRatioPerSecond','ap_ratio_per_second','每秒法强倍率');data(x,'BaseDuration','duration_ms','弹雨区域持续（毫秒）',{scale:1000});data(x,'TicksPerSecond','ticks_per_second','每秒结算次数');data(x,'CastDelay','cast_delay_ms','弹雨延迟（毫秒）',{scale:1000});data(x,'BaseSlowAmount','base_slow_ratio','基础减速比例');data(x,'SlowPer100AP','slow_ap_ratio','每点法强附加减速比例');literal(x,'duration_seconds','弹雨持续（秒）',2,'BaseDuration=2秒，用于总量公式；毫秒参数供生命周期。','DataValues.BaseDuration');formula(x,'damage_per_second','弹雨每秒伤害',add(pn('base_dps'),mul(pn('ap_ratio_per_second'),attr('ability_power'))),'当前 TotalDamagePerSecond。');formula(x,'damage_per_tick','每次弹雨伤害',op('DIVIDE',add(pn('base_dps'),mul(pn('ap_ratio_per_second'),attr('ability_power'))),pn('ticks_per_second')),'每秒伤害除以每秒4次；不把每秒量用于每次结算。');formula(x,'full_duration_damage','停留完整时长伤害总量',mul(add(pn('base_dps'),mul(pn('ap_ratio_per_second'),attr('ability_power'))),pn('duration_seconds')),'仅总量核对公式，不建立瞬间扣完整2秒伤害的效果。');formula(x,'slow_ratio','减速比例',add(pn('base_slow_ratio'),mul(pn('slow_ap_ratio'),attr('ability_power'))),'SlowPer100AP原值0.0006，实际每点法强系数；100法强贡献0.06，不再除100。');damage(x,'rain_tick','一次弹雨魔法伤害','damage_per_tick');pending(x,'弹雨接线与减速','首个结算时点、实际留在区域和离开停止需补证/接线；不在一次命中后强制打满八次。');exclude(x,'显形与区域目标搜索','纯视野和空间搜索后置；当前目标单次伤害与减速数值保留。');
}
{
 const x=begin('missfortune_r');activeCommon(x);data(x,'BaseDamage','base_damage','每波基础物理伤害');data(x,'tADRatio','total_ad_ratio','每波总攻击力倍率');data(x,'APRatio','ap_ratio','每波法强倍率');data(x,'BaseWaves','wave_count','完整引导波数');data(x,'BaseChannelDuration','channel_duration_ms','完整引导持续（毫秒）',{scale:1000});data(x,'CritDamageMultiplier','crit_bonus_scaling','暴击额外伤害折算系数');if(textEvidence.missFortuneRoot.critDamageMultiplier!==2)throw Error('MF基础暴击变更');literal(x,'base_wave_crit_multiplier','无额外暴伤时每波暴击倍率',1.3,'角色根critDamageMultiplier=2；CritDamagePerWave=1+0.3×(总暴击倍率−1)，无额外暴伤时1.3。','CharacterRecords.Root.critDamageMultiplier + CritDamagePerWave');formula(x,'wave_damage','一波弹幕普通伤害',add(pn('base_damage'),mul(pn('total_ad_ratio'),attr('attack_damage')),mul(pn('ap_ratio'),attr('ability_power'))),'PhysicalDamagePerWave；本版本包含20/30/40基础，不沿用旧版零基础。');formula(x,'wave_crit_multiplier','一波弹幕暴击倍率',add(pn('base_wave_crit_multiplier'),mul(pn('crit_bonus_scaling'),attr('critical_strike_damage_bonus_percent'))),'额外暴伤属性按百分点加算；0时1.3，0.4时1.42。不是使用普通攻击总暴击倍率直接乘。');formula(x,'all_waves_noncritical_damage','完整引导未暴击总伤害',mul(add(pn('base_damage'),mul(pn('total_ad_ratio'),attr('attack_damage')),mul(pn('ap_ratio'),attr('ability_power'))),pn('wave_count')),'只用于全部波命中且未暴击的核对，不创建瞬时全额伤害。');damage(x,'bullet_wave','一波弹幕命中伤害','wave_damage','physics',{crit:fval('wave_crit_multiplier')});pending(x,'引导与逐波命中','每波伤害和可暴击倍率已存；引导打断、每波时点/命中需接线，不能一次施放直接扣完整总量。');exclude(x,'锥形多目标和弹道搜索','空间执行后置，单目标每波伤害保留。');
}
{
 const x=begin('annie_p');data(x,'MaxStacks','max_stacks','满层嗜火层数');curve(x,'stun_duration_ms','嗜火眩晕持续（毫秒）',x.p.mSpellCalculations.StunDuration.mFormulaParts[0],1000);pending(x,'施法累层、伤害技能消费与开局满层','必须跨Q/W/E/R并区分下次伤害技能；开局/复活满层初始化需要相应来源事件。已有眩晕目录不等于接线完成。');
}
for(const key of ['annie_q','annie_w']){const x=begin(key);activeCommon(x,{cast:true});apDamage(x);damage(x,'spell_hit',x.c.name+'命中','damage');castProcess(x);hit(x,'spell_hit');pending(x,'嗜火联动','待P合法累层与满层消费接入。');if(key==='annie_q'){literal(x,'kill_cooldown_refund_ratio','击杀冷却缩短比例',.5,'官方Q说明目标阵亡返还法力并缩短50%冷却。','official.tooltip');effect(x,'kill_mana_refund','Q击杀返还法力',[result('refund_mana','返还施放法力','RESOURCE_CHANGE','SOURCE',val('mana_cost'),{attributeKey:'mana',operation:'REFUND'})],null,'仅Q导致目标阵亡时使用；未挂任意击杀事件。');pending(x,'Q击杀退款与减冷却','需要本次Q伤害导致击杀的因果条件；不能把任意击杀或一般命中当Q击杀。');}}
{
 const x=begin('annie_e');activeCommon(x,{allowOfficialCooldown:true});data(x,'ShieldAmount','base_shield','基础护盾');data(x,'ShieldDuration','shield_duration_ms','护盾持续（毫秒）',{scale:1000});data(x,'DamageReflection','base_return_damage','基础伤害回敬');coefficient(x,'ShieldBlockTotal',1,'shield_ap_ratio','护盾法强倍率');coefficient(x,'DamageReturn',1,'return_ap_ratio','回敬法强倍率');data(x,'MovementSpeedDuration','move_speed_duration_ms','移速衰减持续（毫秒）',{scale:1000});interp(x,'move_speed_ratio','初始移动速度提升比例',x.p.mSpellCalculations.MoveSpeedCalc.mFormulaParts[0]);formula(x,'shield','熔岩自护盾',add(pn('base_shield'),mul(pn('shield_ap_ratio'),attr('ability_power'))),'ShieldBlockTotal：60/95/130/165/200+0.4总法强。');formula(x,'return_damage','熔岩伤害回敬',add(pn('base_return_damage'),mul(pn('return_ap_ratio'),attr('ability_power'))),'DamageReturn：25/35/45/55/65+0.4总法强。');shield(x,'molten_shield','熔岩自护盾','shield',val('shield_duration_ms'));damage(x,'return_damage','护盾伤害回敬','return_damage','magic',{origin:'REFLECTED',block:null});pending(x,'护盾施加和伤害回敬','回敬仅限护盾激活期间被攻击/技能损伤，且每名攻击者每盾一次，不能监听所有受伤无限反伤；先记录独立组成。');pending(x,'移速与历史字段','现说明使用MoveSpeedCalc等级20%至50%衰减；旧MovementSpeed和DamageReduction没有当前引用，不录为额外减伤或固定移速。');exclude(x,'友军与提伯斯护盾','本轮保留安妮自身；队友和独立提伯斯不录。');
}
{
 const x=begin('annie_r');activeCommon(x,{cast:true});apDamage(x,'InitialDamage','InitialBurstDamage',null);data(x,'RPercentPenBuff','magic_penetration_ratio','被动百分比法术穿透');damage(x,'summon_impact','召唤瞬间直接伤害','damage');castProcess(x);hit(x,'summon_impact');pending(x,'百分比法穿来源组合','10/15/20%参数已有当前说明与客户端引用。40%既有穿透与10%来源应按剩余抗性连乘为46%；现有固定加算会得50%。先不保存错误乘区效果，待公共表达最小修正后回填。','系统');pending(x,'被动初始化与嗜火联动','需要学会R时启用本体法穿及P合法眩晕联动；不在每次施放叠加永久穿透。');exclude(x,'提伯斯独立对象','生命、攻击、灼烧、暴怒、控制召唤物全部沿已约定独立召唤物范围后置；本体法穿和召唤瞬间伤害保留。');
}
{
 const x=begin('brand_p');data(x,'PercentHealthDamage','burn_total_max_hp_ratio','每层完整灼烧最大生命比例',{scale:.01});literal(x,'burn_duration_ms','灼烧持续（毫秒）',4000,'冻结当前Spell_BrandPassive_Tooltip明确每层4秒总2%最大生命。','spell_brandpassive_tooltip');literal(x,'max_stacks','炽热之焰最大层数',3,'官方被动及当前客户端文本均最多3层。','spell_brandpassive_tooltip');literal(x,'explosion_delay_ms','满层爆炸延迟（毫秒）',2000,'当前文本明确达到3层后2秒爆炸。','spell_brandpassive_tooltip');curve(x,'kill_mana_restore','击杀灼烧目标法力回复',x.p.mSpellCalculations.ManaRestore.mFormulaParts[0]);interp(x,'explosion_base_max_hp_ratio','爆炸基础最大生命比例',x.p.mSpellCalculations.ExplosionDamage.mFormulaParts[0],.01);literal(x,'explosion_ap_ratio','每点法强爆炸最大生命比例',.0002,'ExplosionDamage先取6..12加AP×0.02，再乘0.01；每点AP贡献0.0002最大生命比例。','mSpellCalculations.ExplosionDamage');formula(x,'burn_total','一层4秒灼烧总量',mul(pn('burn_total_max_hp_ratio'),attr('hp','TARGET')),'目标最大生命×2%；不是每次结算伤害，不绑定瞬时扣血效果。');formula(x,'explosion','满层爆炸伤害',mul(add(pn('explosion_base_max_hp_ratio'),mul(pn('explosion_ap_ratio'),attr('ability_power'))),attr('hp','TARGET')),'当前文本证明目标最大生命魔法伤害；等级基础6%..12%加每100法强2%。');damage(x,'blaze_explosion','满层爆炸魔法伤害','explosion');effect(x,'burn_kill_mana','击杀灼烧目标回复法力',[result('restore_mana','回复法力','RESOURCE_CHANGE','SOURCE',val('kill_mana_restore'),{attributeKey:'mana',operation:'RESTORE'})],null,'只保留回复量；需要本人击杀且目标已有灼烧的合法条件。');pending(x,'灼烧、满层爆炸及Q/W/R联动','灼烧应用、周期时点、叠层、满层延迟、爆炸后的重叠限制及控制/增伤判断顺序需完整接线。不能用EARLY_REMOVE冒充爆炸。');exclude(x,'野怪与周围多目标','野怪倍率/上限与范围目标搜索后置，当前英雄目标爆炸保留。');
}
{
 const x=begin('brand_q');activeCommon(x,{cast:true});apDamage(x,'SpellBaseDamage','TotalDamage',null);data(x,'StunDuration','stun_duration_ms','已有灼烧时眩晕持续（毫秒）',{scale:1000});damage(x,'fireball_hit','火球命中魔法伤害','damage');castProcess(x);hit(x,'fireball_hit');pending(x,'灼烧时眩晕','命中前已灼烧条件与P新层应用顺序必须分清，不能每次Q都因自己刚施加的P而眩晕。');
}
{
 const x=begin('brand_w');activeCommon(x,{cast:true});apDamage(x);literal(x,'empowered_multiplier','已灼烧目标伤害倍率',1.25,'当前EmpoweredDamage=TotalDamage×1.25，官方说明额外25%。','mSpellCalculations.EmpoweredDamage');formula(x,'empowered_damage','已灼烧目标烈焰之柱伤害',mul(add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),pn('empowered_multiplier')),'替换普通伤害，不是在普通伤害外再加整份强化伤害。');damage(x,'normal_pillar','未灼烧烈焰之柱伤害','damage');damage(x,'empowered_pillar','已灼烧烈焰之柱伤害','empowered_damage');castProcess(x);pending(x,'火柱延迟与灼烧条件分支','两份独立效果需按命中前是否已灼烧互斥选择；不能两份都执行，也不能永远使用基础伤害。火柱生成延迟需要补证，不把施法结束当命中。');
}
{
 const x=begin('brand_e');activeCommon(x,{cast:true});apDamage(x,'BaseDamage','EDamageCalc');damage(x,'conflagration_hit','烈火燃烧直接伤害','damage');hit(x,'conflagration_hit');pending(x,'施放过程与P联动','法力来源冲突未解决，不创建消耗错误的施放过程；P应用仍待统一接线。');exclude(x,'扩散至周围敌人与扩散距离翻倍','多对象空间搜索按本轮范围后置，当前目标伤害保留。');
}
{
 const x=begin('brand_r');activeCommon(x,{cast:true});apDamage(x);data(x,'SlowAmount','slow_ratio','已有灼烧目标减速比例',{scale:.01});data(x,'SlowDuration','slow_duration_ms','减速持续（毫秒）',{scale:1000});damage(x,'pyroclasm_hit','一次烈焰风暴伤害','damage');castProcess(x);hit(x,'pyroclasm_hit');pending(x,'P联动与既有灼烧减速','实际每次命中伤害已接入；满层优先规则、每次P叠层及减速条件仍需接线。');exclude(x,'弹跳路径与空间目标搜索','按既有空间执行边界后置；来源可提供多次实际命中，每次只执行本次伤害，不把5跳固定套给同一目标。');
}

for(const x of Object.values(plan.skills)){for(const kind of Object.values(x.write)){const keys=kind.map(v=>v.parameterKey??v.formulaKey??v.effectKey??v.processKey??v.stateKey??v.ruleKey);if(new Set(keys).size!==keys.length)throw Error('重复稳定键 '+x.skillKey);}x.status='部分组成候选，须以独立GET确认保存，不是完整机制';}
