// 仅 GET；拒绝 --apply 及所有参数。技能目录允许其他批次并行增加。
import {readFile,writeFile,access} from 'node:fs/promises';
import assert from 'node:assert/strict';
if(process.argv.length>2)throw Error('第十七批当前仅允许无参数只读前检，未授权业务写入');
const here=new URL('./',import.meta.url),source=JSON.parse(await readFile(new URL('冻结来源.json',here),'utf8'));
const out={at:new Date().toISOString(),boundary:'仅 GET；不创建技能、装备关联、图片或组成。',catalogs:{},skillInventory:[],objects:[],references:[]};
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer local-entry',Accept:'application/json'},signal:AbortSignal.timeout(15000)});return {route,status:r.status,data:await r.json()};}
const items=r=>Array.isArray(r.data)?r.data:r.data?.items;
async function inventory(){for(let attempt=0;attempt<3;attempt++){const map=new Map();let total=0;for(let page=1;;page++){const r=await get('/skills?page='+page+'&pageSize=200');assert.equal(r.status,200);const a=items(r);assert.ok(Array.isArray(a));total=r.data.total??a.length;for(const s of a)map.set(s.skillKey,{skillKey:s.skillKey,name:s.name});if(a.length<200||page*200>=total)break;}const r=await get('/skills?page=1&pageSize=200');assert.equal(r.status,200);if(map.size===(r.data.total??map.size))return [...map.values()];}throw Error('并行技能目录持续变化，未完成只读快照；请稍后再运行');}
out.skillInventory=await inventory();
for(const key of ['attributes','modifier-zones','statuses','skill-categories','damage-types']){const r=await get('/'+key+'?page=1&pageSize=200');assert.equal(r.status,200,key);assert.ok(Array.isArray(items(r)));if(r.data.total!=null)assert.equal(items(r).length,r.data.total,key+'必须完整');out.catalogs[key]=r;}
const kinds=[['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey'],['processes','processKey'],['internal-states','stateKey'],['trigger-rules','ruleKey']];
async function skill(key){const records=[],root=await get('/skills/'+key);assert.ok([200,404].includes(root.status));records.push(root);if(root.status===200){for(const [part,field]of kinds){const r=await get('/skills/'+key+'/'+part);assert.equal(r.status,200);records.push(r);for(const row of items(r)){const d=await get('/skills/'+key+'/'+part+'/'+row[field]);assert.equal(d.status,200);records.push(d);}}const image=await get('/skills/'+key+'/representative-image');assert.ok([200,404].includes(image.status));records.push(image);}return {skillKey:key,records};}
for(const o of source.objects){const skillKeys=[o.equipmentKey+(o.id===3152?'_active':'_passive')],records=[];for(const route of ['/equipment/'+o.equipmentKey,'/equipment/'+o.equipmentKey+'/attributes','/equipment/'+o.equipmentKey+'/representative-image','/equipment-skill-relations?equipmentKey='+o.equipmentKey]){const r=await get(route);assert.equal(r.status,200,route);records.push(r);}const skills=[];for(const key of skillKeys)skills.push(await skill(key));out.objects.push({equipmentKey:o.equipmentKey,name:o.name,skillKeys,possibleAliases:out.skillInventory.filter(s=>!skillKeys.includes(s.skillKey)&&(s.skillKey.startsWith(o.equipmentKey+'_')||s.skillKey===o.equipmentKey||s.name===o.name||s.name.startsWith(o.name+'·'))),records,skills});}
for(const key of ['item_3004_passive','item_3041_passive']){const r=await skill(key);assert.equal(r.records[0].status,200,key+'成熟参考必须存在');out.references.push(r);}
const original=new URL('写前现值.json',here);if(!await access(original).then(()=>true,()=>false))await writeFile(original,JSON.stringify(out,null,2)+'\n',{flag:'wx'});await writeFile(new URL('当前只读核对.json',here),JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify({skills:out.skillInventory.length,equipment:out.objects.length,plannedSkills:out.objects.flatMap(o=>o.skillKeys).length,existing:out.objects.flatMap(o=>o.skills).filter(s=>s.records[0].status===200).map(s=>s.skillKey),aliases:out.objects.flatMap(o=>o.possibleAliases),references:out.references.length}));
