import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {source,base,param,runtime,formula,parameterNode as P,attributeNode as A,operation as O,note,proof,omitted,pending,output,clean} from './候选工具.mjs';
if(existsSync(new URL('./完整候选.json',import.meta.url)))throw Error('候选已经冻结，修改需保留旧版并明确形成新版');
const objects=[], roots=new Map(source.objects.map(x=>[x.id,x]));
const sum=(...n)=>n.reduce((a,b)=>O('ADD',a,b)),mul=(a,b)=>O('MULTIPLY',a,b);
const ap=A('SOURCE','ability_power','TOTAL'),bad=A('SOURCE','attack_damage','BONUS'),baseAD=A('SOURCE','attack_damage','BASE');
function start(id,title,desc,kind='passive'){const c=base(id,kind,title,desc);objects.push(c);return c;}
function src(c){return roots.get(Number(c.equipmentKey.slice(5)));}
function txt(c,key='keyTooltip',pattern){const b=src(c).bound[key];assert(b?.text);if(pattern)assert.match(b.text,pattern);proof(c,'/mItemDataClient/mTooltipData/mLocKeys/'+key,b.text,b);return b.text;}
function value(c,name){const rows=src(c).object.mDataValues.filter(v=>v.mName===name);assert(rows.length);assert(rows.every(v=>Number.isFinite(v.mValue)));const v=clean(rows[0].mValue);assert(rows.every(x=>clean(x.mValue)===v));proof(c,'/mDataValues/'+name,v,rows);return v;}
function d(c,name,key,title,scale=1,description=''){const v=clean(value(c,name)*scale);param(c,key,title,v,`当前根${name}明确数值${scale===1000?'，秒转成毫秒':scale===.01?'，百分比点转成比例':''}。${description}`);return P(key);}
function n(c,key,title,v,description){param(c,key,title,v,description);return P(key);}
function input(c,key,title,description){runtime(c,key,title,description+' 不提供默认值。');return P(key);}
function calc(c,name){const tree=src(c).object.mItemCalculations?.[name];assert(tree);proof(c,'/mItemCalculations/'+name,'原计算树完整保留',tree);return tree;}
function f(c,key,title,expression,description){formula(c,key,title,description,expression);}
function gap(c,name,reason){note(c,'尚未接线',name,reason);pending(c,name,reason);}
function unknown(c,name,reason){note(c,'来源待核',name,reason);pending(c,name,reason);}
function skip(c,name,reason){note(c,'范围外',name,reason);omitted(c,'来源',name,reason);}
function unbound(c,name,reason){const row=src(c).object.mDataValues.find(v=>v.mName===name);assert(row);proof(c,'/mDataValues/'+name,{usage:'仅来源证据',reason},row);note(c,'来源待核',name,reason);}
function scaleEvidence(c,tree,index,stat,form,coefficient){const p=tree.mFormulaParts[index];assert.equal(p.mStat,stat);assert.equal(p.mStatFormula??0,form);if(coefficient!=null)assert.equal(clean(p.mCoefficient),coefficient);return p;}

{
 const c=start(2522,'法力成真','保留主动持续8秒、额外100%法力成本、基础技能冷却转速加快30%及原增幅公式。原资源属性口径仍待核；冷却转速不能改写成一次性冷却返还。','active');
 txt(c,'keyActive',/基础技能的冷却时间转速加快/);d(c,'Cooldown','cooldown_ms','主动冷却（毫秒）',1000);d(c,'Duration','duration_ms','法力强化持续（毫秒）',1000);d(c,'ManaCostIncrease','extra_mana_cost_ratio','额外法力成本比例');d(c,'CooldownTick','basic_cooldown_speed_bonus','基础技能冷却转速增加比例');
 const t=calc(c,'ManaCalc');assert.equal(clean(t.mMultiplier.mNumber),.01);assert.equal(t.mFormulaParts[0].mNumber,15);assert.equal(t.mFormulaParts[1].mStatFormula,2);assert.equal(clean(t.mFormulaParts[1].mCoefficient),.005);
 const unit=n(c,'percentage_point_to_ratio','百分比点转比例系数',.01,'原ManaCalc最外层乘数0.01。'),b=n(c,'amplification_base_points','增幅基础百分比点',15,'原ManaCalc第一项15。'),r=n(c,'resource_amplification_points_ratio','资源缩放百分比点系数',.005,'原资源节点mCoefficient=0.005。'),v=input(c,'actual_ability_resource_formula2','原资源口径的实际值','AbilityResourceByCoefficient的mStatFormula=2尚未证明对应额外法力，必须外供原节点实际数值。');
 f(c,'amplification_ratio','技能伤害护盾治疗增幅比例',mul(unit,sum(b,mul(r,v))),'原树0.01×(15+0.005×实际资源输入)，输出比例；实际资源范围及读取时点待核。');
 for(const name of ['OverflowAddition','OverflowRevert'])unbound(c,name,'当前主动说明没有消费绑定，保留源字段，不猜转换或恢复步骤。');
 unknown(c,'原资源属性','资源类型与基础/额外口径尚未确证。');gap(c,'增幅与转速','技能伤害、护盾、自身治疗增幅的合法乘区与适用结果，额外法力消费和冷却转速计时尚未接线。');skip(c,'仅第三友方治疗分发','只保留可影响自身的治疗增强数值，不实现队友目标分发。');
}
{
 const c=start(2525,'救主灵刃','保留受到将使生命跌到30%以下的伤害后，5秒最大生命增益、总持续治疗及10%移速、25%韧性。等级值外供，不把总治疗按每跳重复。');
 txt(c,'keyTooltip',/跌到.*以下.*持续治疗/);d(c,'LowHealthThreshold','low_health_threshold','触发生命严格低于阈值');d(c,'Duration','duration_ms','增益与总治疗持续（毫秒）',1000);d(c,'Cooldown','cooldown_ms','救主灵刃冷却（毫秒）',1000);d(c,'MSAmount','move_speed_ratio','回复期间移速增幅比例');d(c,'TenacityAmount','tenacity_ratio','回复期间韧性比例');
 const ht=calc(c,'TotalHealthRegen'),hp=calc(c,'MaxHealthGain');assert.deepEqual([ht.mFormulaParts[0].mStartValue,ht.mFormulaParts[0].mEndValue,hp.mFormulaParts[0].mStartValue,hp.mFormulaParts[0].mEndValue],[100,400,100,300]);scaleEvidence(c,ht,1,1,2,1.75);scaleEvidence(c,ht,2,6,2,1.75);
 const heal=input(c,'heal_base_by_level','当前等级基础总治疗','等级节点100至400只有端点，求值函数未证。'),health=input(c,'health_gain_by_level','当前等级最大生命增益','等级节点100至300只有端点，求值函数未证。'),r=n(c,'bonus_resist_heal_ratio','额外双抗治疗系数',1.75,'原树额外护甲与额外魔抗系数均1.75；同构建余震具名旁证。');
 f(c,'total_healing','5秒持续治疗总量',sum(heal,mul(r,A('SOURCE','armor','BONUS')),mul(r,A('SOURCE','magic_resistance','BONUS'))),'基础等级总治疗+1.75额外护甲+1.75额外魔抗；这是全持续期总量，不是每跳值。');f(c,'max_health_gain','临时最大生命增益',health,'当前等级实际值外供；不能假定生命最大值增加会等额治疗。');
 skip(c,'SizeIncrease','体型仅空间表现，不进入当前数值计算。');unknown(c,'两个等级求值','保留原始100/400与100/300端点，不按1至18级猜线性。');gap(c,'受伤阈值与持续治疗','阈值读取和承伤次序、生命上限增减、治疗首跳与刷新、韧性跨来源口径及共用救主灵刃资格待接。');
}
for(const id of [3119,3121]){
 const c=start(id,id===3119?'敬畏与法力流':'敬畏与永续',id===3119?'保留原资源缩放生命、命中成长、充能时间与360升级门槛。准备阶段对非英雄命中可以影响自身后续状态。':'保留原资源缩放生命和定身、近战减速英雄产生的100+4.5%当前法力护盾。单挑不启用附近多名敌人的强化。');txt(c);
 const t=calc(c,'BonusHPFromMana'),p=t.mFormulaParts[0];assert.equal(p.__type,'AbilityResourceByCoefficientCalculationPart');assert.equal(p.mStatFormula,2);assert.equal(clean(p.mCoefficient),.15);
 const r=n(c,'resource_health_ratio','原资源转生命系数',.15,'原BonusHPFromMana系数0.15。'),resource=input(c,'actual_ability_resource_formula2','原资源口径的实际值','原资源节点类型与mStatFormula=2的属性语义未证，不能借护盾当前法力说明替代该节点。');f(c,'awe_bonus_health','敬畏额外生命',mul(r,resource),'0.15×原资源实际值；原口径无默认。');unknown(c,'敬畏资源口径','AbilityResourceByCoefficient的资源和属性部分未解码。');
 if(id===3119){d(c,'ManaPerCharge','mana_per_charge','每次成长最大法力');d(c,'ManaChargeAmmoCD','charge_interval_ms','成长充能间隔（毫秒）',1000);d(c,'ManaChargeMaxAmmo','max_charge_ammo','最大可用充能');d(c,'MaxMana','upgrade_growth_mana','升级所需已成长最大法力');const twice=n(c,'champion_growth_multiplier','对英雄成长倍数',2,'当前中文明确对英雄翻倍。');f(c,'champion_mana_per_charge','命中英雄每次最大法力成长',mul(P('mana_per_charge'),twice),'3×2=6；实际命中、充能消费和升级由外部事件确认。');unbound(c,'InternalCDPerCastID','原6.5尚无单位与同次施法门控证据，不直接写成6500毫秒。');gap(c,'成长与升级','实际充能、同次技能命中资格、最大360封顶、升级3121和敬畏重算待接；不默认满充能或已升级。');}
 else{const b=calc(c,'ShieldBase');assert.equal(b.mFormulaParts[0].mNumber,100);n(c,'shield_base','护盾基础值',100,'原ShieldBase明确固定100。');d(c,'CurrentManaShieldRatio','current_mana_shield_ratio','当前法力护盾系数');d(c,'ShieldDuration','shield_duration_ms','护盾持续（毫秒）',1000);d(c,'Cooldown','cooldown_ms','永续冷却（毫秒）',1000);f(c,'shield_value','单挑永续护盾值',sum(P('shield_base'),mul(P('current_mana_shield_ratio'),A('SOURCE','mana','CURRENT'))),'当前中文明确100+4.5%当前法力值；不加入多名敌人的80%分支。');skip(c,'Multiplier','附近超过一名敌人的额外护盾属于多目标条件，本次1V1不启用。');gap(c,'永续护盾资格','定身或仅近战的减速触发、触发瞬间法力快照、护盾类型与重用规则仍待接。');}
}
{
 const c=start(3137,'死中焕生','保留命中敌方英雄后3秒内阵亡触发的新星自身治疗100+0.2法强及60秒冷却；当前统计文案明确存在自我治疗，不能整项当作仅队友效果删除。');txt(c);txt(c,'keyInventoryOnlyText',/自我治疗.*友军治疗/);txt(c,'keyTooltipExtendedRules',/不能在你阵亡期间触发/);d(c,'BaseHeal','base_heal','新星基础治疗');d(c,'HealAPRatio','ap_heal_ratio','新星法强治疗系数');d(c,'Cooldown','cooldown_ms','死中焕生冷却（毫秒）',1000);assert.equal(value(c,'ItemCooldown'),60);d(c,'TakedownWindow','takedown_window_ms','伤害后目标阵亡窗口（毫秒）',1000);const t=calc(c,'TotalHealAmount');assert.equal(t.mFormulaParts[1].mDataValue,'HealAPRatio');assert.equal(t.mFormulaParts[1].mStat??0,0);assert.equal(t.mFormulaParts[1].mStatFormula??0,0);f(c,'self_healing','新星对自身治疗值',sum(P('base_heal'),mul(P('ap_heal_ratio'),ap)),'100+0.2法强；当前库存统计明确自我治疗，实际自身在新星内的资格不默认。');skip(c,'友方第三者治疗','新星对其他队友的治疗分发不录；自身治疗保留。');gap(c,'新星到自身的作用','需要目标阵亡、自己存活、新星实际命中自身及触发冷却等条件；不把所有击杀后自动视为自我治疗成功。');
}
{
 const c=start(3181,'船长','保留对当前英雄的每第五次攻击附伤。基础攻击力沿同构建具名补证；第二生命属性节点仍外供。远程分支作用于整项计算，不把额外旧字段混入。');txt(c);const t=calc(c,'MaxStackDamage');assert.equal(t.__type,'{e9a3c91d}');scaleEvidence(c,t,0,2,1);scaleEvidence(c,t,1,12,0);assert.equal(clean(t.mRangedMultiplier.mNumber),.7);const ar=d(c,'SkipperADRatio','base_ad_ratio','船长基础攻击力系数'),hr=d(c,'MaxStackDamageHPRatio','mstat12_formula0_ratio','船长第二属性系数'),h=input(c,'actual_mstat12_formula0','船长第二属性实际值','mStat12且省略mStatFormula默认0，当前不扩展为总生命；需要原节点实际输入。');n(c,'attacks_required','触发所需攻击次数',5,'当前中文明确每第五次攻击。');const ranged=n(c,'ranged_damage_multiplier','远程分支整项伤害倍数',.7,'当前MaxStackDamage.mRangedMultiplier明确0.7；只表示给定远程资格分支。');const expr=sum(mul(ar,baseAD),mul(hr,h));f(c,'melee_bonus_damage','近战第五次攻击额外伤害',expr,'1.2基础攻击力+0.05原第二属性实际值；当前已确认近战条件分支。');f(c,'ranged_bonus_damage','远程第五次攻击额外伤害',mul(ranged,expr),'整项近战计算×0.7；不得用RangedSkipperADRatio作为新的0.7基础攻击力系数。');for(const k of ['SkipperADRatioVSStructures','MaxStackDamageVSStructuresHPRatio','RangedSkipperADRatioVSStructures'])skip(c,k,'只对建筑的独立伤害分支，不作用于当前英雄。');skip(c,'BonusMinionResists','仅作用于攻城兵/超级兵的抗性，不录入。');unbound(c,'RangedSkipperADRatio','当前树仅使用具名近战系数及整项mRangedMultiplier，不重复使用该旧参数。');unbound(c,'SkipperStackDuration','10秒字段当前文字未绑定，实际刷新与失效规则待核。');unknown(c,'第二属性与远近资格','mStat12/formula0口径未证；远近计算分支仅按明确输入选择，不从默认分支推断角色资格。');gap(c,'攻击计数与伤害','第五次攻击计数、准备阶段攻击保留、命中与刷新/消费规则待接。');
}
{
 const c=start(6333,'无视痛苦与蔑视','保留近战30%/远程10%伤害延后至3秒、目标阵亡清除剩余延后伤害，以及2秒共0.75额外攻击力治疗。');txt(c,'keyTooltip',/持续扣除.*剩余伤害.*共/);const heal=calc(c,'HealTotal');scaleEvidence(c,heal,0,2,2);d(c,'BonusADRatio','bonus_ad_heal_ratio','蔑视总治疗额外攻击力系数');d(c,'BleedDurationWorst','deferred_duration_ms','延后伤害持续（毫秒）',1000);d(c,'HealDuration','healing_duration_ms','蔑视总治疗持续（毫秒）',1000);d(c,'TakedownWindow','takedown_window_ms','伤害后目标阵亡窗口（毫秒）',1000);
 for(const [name,key,title,expect]of [['MeleeItemCalcValue','melee_deferred_ratio','近战伤害延后比例',.3],['RangedItemCalcValue','ranged_deferred_ratio','远程伤害延后比例',.1]]){const t=calc(c,name);assert.equal(clean(t.mFormulaParts[0].mNumber),expect);n(c,key,title,expect,'当前具名近战/远程计算值，经绑定动态模板选择；没有默认远近资格。');}calc(c,'ChampRange');
 const damage=input(c,'actual_eligible_incoming_damage','本次符合延后资格的伤害量','必须提供经过正确结算阶段确认可延后的本次伤害，不自动取原始或减免前伤害。');f(c,'melee_deferred_damage','近战本次延后伤害总额',mul(P('melee_deferred_ratio'),damage),'0.3×本次明确符合资格的伤害；3秒总额，不是每跳值。');f(c,'ranged_deferred_damage','远程本次延后伤害总额',mul(P('ranged_deferred_ratio'),damage),'0.1×本次明确符合资格的伤害；远程资格外供。');f(c,'total_healing','蔑视2秒总治疗',mul(P('bonus_ad_heal_ratio'),bad),'0.75额外攻击力为2秒总治疗；不建立即时治疗或将总量重复逐跳。');unbound(c,'MS','原0.4移速未被当前文本或具名计算消费，不增加40%移速。');gap(c,'延后伤害池与净化','原承伤资格和结算阶段、独立流血池、首跳与后续节拍、目标阵亡时净化剩余池及治疗刷新待接。');
}
{
 const c=start(6610,'光盾打击','保留每目标10秒冷却的第一次攻击、常规暴击伤害80%及自身治疗。远程减半只作用于基础攻击力治疗项，已损生命项不随意减半。');txt(c);txt(c,'keyTooltipExtendedRules',/临时的额外生命值/);d(c,'Cooldown','per_target_cooldown_ms','每目标冷却（毫秒）',1000);d(c,'CritModifier','normal_crit_damage_ratio','常规暴击伤害倍数');d(c,'HealBaseADRatio','base_ad_heal_ratio','基础攻击力治疗系数');d(c,'MissingHealthHeal','missing_health_heal_ratio','已损生命治疗比例');d(c,'RangedHealMod','ranged_ad_heal_multiplier','远程基础攻击力治疗倍数');const t=calc(c,'{01099b16}');scaleEvidence(c,t,0,2,1);assert.equal(t.mFormulaParts[0].mDataValue,'HealBaseADRatio');assert.equal(t.mRangedMultiplier.mDataValue,'RangedHealMod');
 const ad=mul(P('base_ad_heal_ratio'),baseAD),lost=mul(P('missing_health_heal_ratio'),A('SOURCE','hp','MISSING'));f(c,'melee_self_healing','近战光盾打击自身治疗',sum(ad,lost),'0.9基础攻击力+4%自身已损生命；按当前中文两项相加。');f(c,'ranged_self_healing','远程光盾打击自身治疗',sum(mul(P('ranged_ad_heal_multiplier'),ad),lost),'0.5×(0.9基础攻击力)+4%自身已损生命；原远程乘数仅绑定HealADSplit对应计算。');const crit=input(c,'actual_normal_critical_damage','该次普通常规暴击伤害','取该次攻击完整常规暴击规则下对应的伤害量；不能默认基础暴击倍率2。');f(c,'modified_critical_damage','光盾打击暴击分支伤害',mul(P('normal_crit_damage_ratio'),crit),'0.8×该次常规暴击伤害，最终属性读取及结算阶段由外供确认。');gap(c,'每目标与溢出治疗','每目标首次攻击资格、普通暴击完整口径、溢出实际治疗换临时生命、该生命到期时间及再次触发待核；不默认永久额外生命。');
}
{
 const c=start(4401,'坚定','保留受到8次英雄魔法伤害后的70魔抗和6%移动速度。当前扩展说明明确一次定身视作2次伤害，坚定7秒后重置；不把1秒未绑定字段当刷新规则。');txt(c);txt(c,'keyTooltipExtended',/定身.*次伤害.*秒后重置/);d(c,'MaxStacks','required_magic_hits','需要的英雄魔法伤害计数');d(c,'BonusMagicResist','bonus_magic_resistance','坚定魔抗增益');d(c,'MoveSpeed','bonus_move_speed_ratio','坚定移速增幅比例');d(c,'ImmobilizeStacks','immobilize_hit_count','一次定身计入的伤害次数');d(c,'BuffDuration','reset_duration_ms','坚定重置时长（毫秒）',1000);unbound(c,'StackRefreshTimer','原1秒没有当前消费与刷新语义，不猜去重计时或内置冷却。');const missing=src(c).object.mDataValues.find(v=>v.mName==='DamageReduction');assert(missing&&!Object.hasOwn(missing,'mValue'));proof(c,'/mDataValues/DamageReduction','原值缺失，不填零也不创建额外减伤',missing);gap(c,'坚定计数与重置','实际魔法伤害与定身去重、7秒计时起点与重新计时条件仍待接；不把有重置时长当自动刷新效果。');
}
{
 const c=start(6665,'虚空生物的复原力','保留与英雄战斗5秒后额外双抗提升30%并持续到战斗结束。公式外供不含本装备递归增益的读取基数，避免反复对自己的增益再加30%。');txt(c);d(c,'MaxStacks','champion_combat_duration_ms','激活前英雄战斗时长（毫秒）',1000);d(c,'BonusResistPercentage','bonus_resistance_increase_ratio','额外双抗增加比例');const ar=input(c,'eligible_bonus_armor','本次计算合法额外护甲基数','实际乘区与读取时点未证，不自动读取含自身30%增益的最终额外护甲。'),mr=input(c,'eligible_bonus_magic_resistance','本次计算合法额外魔抗基数','实际乘区与读取时点未证，不自动读取含自身30%增益的最终额外魔抗。');f(c,'additional_armor','贾修新增护甲',mul(P('bonus_resistance_increase_ratio'),ar),'合法额外护甲基数×0.3，读取与重算外供。');f(c,'additional_magic_resistance','贾修新增魔抗',mul(P('bonus_resistance_increase_ratio'),mr),'合法额外魔抗基数×0.3，读取与重算外供。');gap(c,'战斗状态与乘区','英雄战斗开始/结束判定、5秒连续资格、额外双抗乘区和增益重算未接。');
}
{
 const c=start(6695,'掠盾者','保留近战50%/远程35%的现有护盾首次削减与后续获得护盾削减，持续3秒；魔法护盾明确排除。');txt(c);txt(c,'keyTooltipExtendedRules',/魔法护盾不会被削减/);d(c,'DebuffDuration','debuff_duration_ms','掠盾者持续（毫秒）',1000);for(const [name,key,title]of [['ShieldShred','melee_new_shield_reduction','近战新护盾削减比例'],['ShieldWounds','melee_existing_shield_reduction','近战现有护盾削减比例'],['ShieldShredRange','ranged_new_shield_reduction','远程新护盾削减比例'],['ShieldWoundsRange','ranged_existing_shield_reduction','远程现有护盾削减比例']])d(c,name,key,title,.01);const current=input(c,'eligible_existing_shield','首次受掠盾影响时合法现有护盾量','仅实际可削减护盾总量，排除魔法护盾；不是生命或护盾上限。');const newly=input(c,'eligible_new_shield','原始合法新增护盾量','取本次可削减新增护盾原始值，不重复使用已经被减过的量。');for(const ranged of ['melee','ranged']){f(c,ranged+'_existing_shield_removed',(ranged==='melee'?'近战':'远程')+'首次移除护盾量',mul(P(ranged+'_existing_shield_reduction'),current),'仅尚未受掠盾者影响的首次当前护盾削减；不重复削减每次攻击。');f(c,ranged+'_new_shield_removed',(ranged==='melee'?'近战':'远程')+'后续新增护盾削减量',mul(P(ranged+'_new_shield_reduction'),newly),'处于3秒影响期内的合法新增护盾削减；魔法护盾排除。');}skip(c,'LethalityAmount','15穿甲已经在装备直接属性中保存，不在技能再次添加。');gap(c,'护盾类型与同效果去重','远近动态显示字段绑定、合法护盾类型、首次与后续处理、多个掠盾来源的合并及持续刷新仍待核；只保存明确分支数值，不生成默认护盾变更。');
}
{
 const c=start(6696,'涌动','保留伤害后3秒内目标阵亡时返还终极技能总冷却的百分比公式。原mStat29口径未证，不能拿本装备18穿甲替代角色实际属性。');txt(c,'keyTooltip',/终极技能总冷却时间/);d(c,'ResetWindow','takedown_window_ms','伤害后目标阵亡窗口（毫秒）',1000);d(c,'UltimateRefundBase','refund_base_points','返还基础百分比点');const t=calc(c,'UltimateRefund');assert.equal(t.mFormulaParts[1].mStat,29);assert.equal(clean(t.mFormulaParts[1].mCoefficient),.25);n(c,'mstat29_refund_points_ratio','未解码属性增加百分比点系数',.25,'原mStat29计算系数0.25。');n(c,'percentage_point_to_ratio','百分比点转比例系数',.01,'当前中文在@UltimateRefund@后显式百分号，输出百分比点须乘0.01。');const stat=input(c,'actual_mstat29_formula0','原mStat29属性实际值','当前mStat29且默认formula0的枚举未具名证明。'),cd=input(c,'actual_ultimate_total_cooldown_ms','当前终极技能总冷却毫秒','中文明确总冷却，需外部提供对应技能正确结算口径的总冷却，不使用当前剩余值代替。');const ratio=mul(P('percentage_point_to_ratio'),sum(P('refund_base_points'),mul(P('mstat29_refund_points_ratio'),stat)));f(c,'refund_ratio','终极技能总冷却返还比例',ratio,'(10+0.25×实际未解码属性)÷100。');f(c,'refund_cooldown_ms','终极技能冷却返还毫秒',mul(ratio,cd),'返还比例×明确总冷却毫秒；不是将10或0.25直接作为毫秒。');skip(c,'LethalityAmount','18穿甲为已有装备直接属性，不重复施加，也不能证明原mStat29枚举。');unknown(c,'mStat29枚举','保留原节点与显式运行输入，未证不猜穿甲。');gap(c,'击杀窗口与总冷却','伤害归因、目标阵亡、终极技能选择及总冷却读取阶段待接；不创建无条件返还。');
}
for(const c of objects){proof(c,'/当前根与全部绑定说明','包含当前说明、扩展规则及库存统计，范围判定不局限于主Tooltip',src(c));gap(c,'验证边界','当前参数、公式和关系可保存；未建立伤害、治疗、护盾事件结果，也未运行战斗引擎。');}
const p=await output(objects);console.log(JSON.stringify(p.totals));
