import {readFile,writeFile,appendFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {plan} from './英雄候选.mjs';
export const here=path.dirname(fileURLToPath(import.meta.url));
export const apiBase='http://127.0.0.1:8080/api/admin/games/lol';
export const kinds=[['parameters','parameterKey','parameters'],['formulas','formulaKey','formulas'],['effects','effectKey','effects'],['processes','processKey','processes'],['internalStates','stateKey','internal-states'],['triggerRules','ruleKey','trigger-rules']];
export async function request(route,{method='GET',body}={}){const r=await fetch(apiBase+route,{method,headers:{Authorization:'Bearer local-entry',Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data={invalidJson:true};}return {ok:r.ok,status:r.status,data};}
export function diff(expected,actual,p=''){if(expected===actual)return null;if(expected===null||typeof expected!=='object')return {path:p,expected,actual};if(actual===null||typeof actual!=='object')return {path:p,expected,actual};if(Array.isArray(expected)){if(!Array.isArray(actual)||expected.length!==actual.length)return {path:p,expected,actual};for(let i=0;i<expected.length;i++){const d=diff(expected[i],actual[i],p+'['+i+']');if(d)return d;}return null;}for(const k of Object.keys(expected)){const d=diff(expected[k],actual[k],p?(p+'.'+k):k);if(d)return d;}return null;}
export async function verifySources(){const sourceBase='C:/project/damage_viewer_project_planning/数据参考/全量录入-2026-09/技能公共参数实录';for(const s of plan.meta.sources){const client=gunzipSync(await readFile(path.join(sourceBase,s.client.path)));const official=await readFile(path.resolve(sourceBase,s.official.path));for(const [raw,sha]of [[client,s.client.sha256],[official,s.official.sha256]])if(createHash('sha256').update(raw).digest('hex')!==sha)throw Error('冻结来源摘要不符 '+s.id);}const supplemental=JSON.parse(await readFile(path.join(here,'补充文本证据.json'),'utf8'));const textRaw=gunzipSync(await readFile(supplemental.path));if(createHash('sha256').update(textRaw).digest('hex')!==supplemental.sha256)throw Error('补充文本来源摘要不符');const textJson=JSON.parse(textRaw),entries=textJson.entries??textJson;for(const[k,v]of Object.entries(supplemental.entries))if(entries[k]!==v)throw Error('补充文本内容不符 '+k);}
async function main(){await verifySources();const apply=process.argv.includes('--apply');const selected=process.argv.find(v=>v.startsWith('--skill='))?.slice(8);if(selected&&!plan.skills[selected])throw Error('不在授权批次');const skills=Object.values(plan.skills).filter(s=>!selected||s.skillKey===selected);const report={startedAt:new Date().toISOString(),mode:apply?'explicit-apply-missing-only':'read-only',skills:skills.map(s=>s.skillKey),preflight:[],writes:[],conflicts:[],failures:[]};await writeFile(path.join(here,'录入候选.json'),JSON.stringify(plan,null,2)+'\n');const toWrite=[];
 for(const skill of skills){const sd=await request('/skills/'+skill.skillKey);if(!sd.ok||sd.data.maxLevel!==skill.maxLevel)throw Error('技能身份或等级不符 '+skill.skillKey);for(const [kind,idField,apiKind]of kinds){const base='/skills/'+skill.skillKey+'/'+apiKind;const listed=await request(base);if(!listed.ok||!Array.isArray(listed.data))throw Error('清单读取失败 '+base);const keys=listed.data.map(v=>v[idField]);if(new Set(keys).size!==keys.length)throw Error('重复现值 '+base);for(const body of skill.write[kind]){const id=body[idField],route=base+'/'+encodeURIComponent(id);if(keys.includes(id)){const got=await request(route);const d=got.ok?diff(body,got.data):{status:got.status};report.preflight.push({skillKey:skill.skillKey,kind,id,action:d?'conflict':'same-skip'});if(d)report.conflicts.push({skillKey:skill.skillKey,kind,id,diff:d});}else{report.preflight.push({skillKey:skill.skillKey,kind,id,action:'missing'});toWrite.push({skillKey:skill.skillKey,kind,id,base,route,body});}}}}
 await writeFile(path.join(here,apply?'写入前检查.json':'只读检查.json'),JSON.stringify(report,null,2)+'\n');if(report.conflicts.length)throw Error('现值冲突，保留全部现值，不写入');
 if(apply){for(const x of toWrite){if(x.skillKey==='sivir_e'&&[['effects','spell_shield'],['processes','cast'],['triggerRules','successful_spell_block']].some(([k,id])=>x.kind===k&&x.id===id)){report.writes.push({skillKey:x.skillKey,kind:x.kind,id:x.id,action:'reserved-for-parent-browser'});continue;}try{const before=await request(x.route);if(before.status!==404){if(before.ok&&!diff(x.body,before.data)){report.writes.push({skillKey:x.skillKey,kind:x.kind,id:x.id,action:'concurrent-same-skip'});continue;}throw Error('写前同键发生变化，停止而不覆盖 '+x.route);}const saved=await request(x.base,{method:'POST',body:x.body});if(!saved.ok)throw Error('POST失败 '+saved.status+' '+JSON.stringify(saved.data));const got=await request(x.route);const mismatch=got.ok?diff(x.body,got.data):{status:got.status};const record={at:new Date().toISOString(),skillKey:x.skillKey,kind:x.kind,id:x.id,status:saved.status,readbackStatus:got.status,match:!mismatch,diff:mismatch};await appendFile(path.join(here,'写入流水.jsonl'),JSON.stringify(record)+'\n');report.writes.push(record);if(mismatch)throw Error('独立GET不同 '+x.route);}catch(e){report.failures.push({skillKey:x.skillKey,kind:x.kind,id:x.id,message:String(e)});break;}}}
 report.finishedAt=new Date().toISOString();await writeFile(path.join(here,apply?'写入结果.json':'只读检查.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({mode:report.mode,skills:skills.length,missing:toWrite.length,written:report.writes.filter(w=>w.status>=200&&w.status<300).length,reserved:report.writes.filter(w=>w.action==='reserved-for-parent-browser').length,conflicts:report.conflicts.length,failures:report.failures}));if(report.failures.length)process.exitCode=1;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))await main();
