import {plan,evidence,clean,val,fval,pn,attr,op,add,mul,behavior,life,begin,parameter,data,literal,coefficient,formula,result,effect,damage,manaEffect,castProcess,hit,pending,exclude,attributeEffect,curve} from './候选.mjs';
export {plan};
plan.meta.scope='卢锡安、希维尔、崔丝塔娜、图奇20技能；仅本批内部组成。纯队友、视野、多对象路径排除；跨技能、控制和时点缺口列待补。';
function common(x,{cast=false,officialZeroMana=false}={}){
 const d=x.s.official,n=x.c.maxLevel,cd=x.p.cooldownTime?.slice(1,n+1),mv=x.p.manaValues?.values?.slice(0,n),old=x.p.mana?.slice(0,n),mana=mv??old;
 if(cd?.length!==n||!cd.every((v,i)=>Math.abs(v-d.cooldown[i])<1e-4))throw Error('冷却冲突 '+x.c.skillKey);
 literal(x,'cooldown_ms','基础冷却时间（毫秒）',d.cooldown.map(v=>Math.round(v*1000)),'官方16.17.1与当前根对象cooldownTime索引1起一致。','official.cooldown + cooldownTime');
 if(mana?.length===n&&mana.every((v,i)=>Math.abs(v-d.cost[i])<1e-4)){
  literal(x,'mana_cost','法力消耗',d.cost,`官方cost与当前${mv?'manaValues.values':'mana'}索引0起一致；明确0消耗保留。`,'official.cost + '+(mv?'manaValues.values':'mana'));manaEffect(x);
  if(mv&&old?.some((v,i)=>Math.abs(v-mv[i])>1e-4))x.c.proofs.push({source:'mana旧字段处置',old,current:mv,disposition:'当前manaValues与官方一致；旧字段不录'});
 }else if(officialZeroMana&&d.cost.every(v=>v===0)){literal(x,'mana_cost','法力消耗',0,'官方明确0；主对象没有法力消耗字段。','official.cost');}
 else throw Error('法力消耗未核对 '+x.c.skillKey);
 if(cast){if(!(x.p.spellCastTime>0)||x.p.mUseAutoattackCastTimeData||(x.p.mCastTime!=null&&Math.abs(x.p.mCastTime-x.p.spellCastTime)>1e-4))throw Error('施法不唯一 '+x.c.skillKey);literal(x,'cast_time_ms','施法时间（毫秒）',Math.round(x.p.spellCastTime*1000),'当前spellCastTime与已有mCastTime一致；不代替命中。','spellCastTime');}
}
function runtime(x,key,name,description){x.c.write.parameters.push({parameterKey:key,name,valueType:'INTEGER',valueMode:'RUNTIME_INPUT',fixedValue:null,levelValues:null,description,sortOrder:(x.c.write.parameters.length+1)*10});}
function activeBuff(x,effectKeys,{delay=false}={}){const stepKey=delay?'cast_time':'activate';x.c.write.processes.push({processKey:'cast',name:'施放'+x.c.name,activationType:'ACTIVE',description:'法力和冷却始于主动施放；效果只作用自身，不将过程结束当作敌人命中。',sortOrder:10,cooldown:{durationValue:val('cooldown_ms'),startMoment:{momentType:'PROCESS_START',stepKey:null}},steps:[{stepKey,name:delay?'施法延迟':'启用自身效果',description:null,sortOrder:10,stepType:delay?'DELAY':'IMMEDIATE',detail:delay?{delayValue:val('cast_time_ms')}:{}}],effectBindings:[...(x.c.write.effects.some(e=>e.effectKey==='mana_cost')?[{bindingKey:'mana_cost',effectKey:'mana_cost',moment:{momentType:'PROCESS_START',stepKey:null},sortOrder:10}]:[]),...effectKeys.map((effectKey,i)=>({bindingKey:effectKey,effectKey,moment:{momentType:delay?'STEP_COMPLETE':'STEP_EXECUTION',stepKey},sortOrder:20+i*10}))],stateOperations:[]});}
function rule(x,key,name,eventSource,effectKeys,conditions=[]){x.c.write.triggerRules.push({ruleKey:key,name,description:'只接收指定真实事件；不自行生成命中或补造事件。',sortOrder:(x.c.write.triggerRules.length+1)*10,eventSource,conditionGroups:conditions.length?[{groupKey:'required',name:'必要条件',sortOrder:10,conditions}]:[],actions:effectKeys.map((effectKey,i)=>({actionKey:effectKey,name:'执行'+effectKey,actionType:'EXECUTE_EFFECT',sortOrder:(i+1)*10,targetContext:'CURRENT_TARGET',detail:{effectKey},runtimeInputBindings:[],resultModifiers:[]})),perTargetCooldown:null,maxTriggersPerProcess:null});}
const champion={conditionKey:'champion',conditionType:'TARGET_CATEGORY_CHECK',sortOrder:10,detail:{categories:['CHAMPION']}};
function cooldown(x,key,name,keys,operation,value=null){effect(x,key,name,[result('cooldown',name,'COOLDOWN_CHANGE','SOURCE',value,{affectedSkillScope:{mode:'SKILLS',skillKeys:keys,skillCategoryKeys:[]},operation})]);}
function adAp(x,{base='BaseDamage',ad='ADRatio',ap='APRatio',adKind='BONUS',calc='TotalDamage',coefficientAD=null,coefficientAP=null}={}){
 data(x,base,'base_damage','基础伤害');
 if(coefficientAD!=null)literal(x,'ad_ratio','攻击力倍率',coefficientAD,'完整'+calc+'中明确攻击力系数。','mSpellCalculations.'+calc);else data(x,ad,'ad_ratio','攻击力倍率');
 if(coefficientAP!=null)literal(x,'ap_ratio','法术强度倍率',coefficientAP,'完整'+calc+'中默认法强系数。','mSpellCalculations.'+calc);else data(x,ap,'ap_ratio','法术强度倍率');
 return add(pn('base_damage'),mul(pn('ad_ratio'),attr('attack_damage','SOURCE',adKind)),mul(pn('ap_ratio'),attr('ability_power')));
}
function critAmp(x,source){data(x,source,'crit_scaling','暴击属性折算系数');const h=evidence.heroes.find(h=>h.id===x.c.source.hero);if(h.baseCriticalMultiplier!==2)throw Error('基础暴伤变更');literal(x,'one','倍率单位值',1,'当前完整暴击计算树有1与−1常数；角色根暴击倍率2减1为1。','mSpellCalculations + root.critDamageMultiplier');return add(pn('one'),mul(mul(attr('critical_strike_chance'),pn('crit_scaling')),add(pn('one'),attr('critical_strike_damage_bonus_percent'))));}

{
 const x=begin('lucian_p');data(x,'PassiveDuration','empowered_window_ms','双发攻击等待窗口（毫秒）',{scale:1000});curve(x,'second_shot_ad_ratio','第二发总攻击力倍率',x.p.mSpellCalculations.TotalDamage.mFormulaParts[0].mSubpart);literal(x,'base_second_shot_crit','第二发基础暴击倍率',1.75,'CritDamage完整修改树：1.75+额外暴击伤害属性；不套角色普通攻击基础2。','mSpellCalculations.CritDamage.mMultiplier');
 formula(x,'second_shot_damage','第二发基础物理伤害',mul(pn('second_shot_ad_ratio'),attr('attack_damage')),'完整TotalDamage角色等级断点：1至6级0.5，7至12级0.55，13至18级0.6。');formula(x,'second_shot_crit_multiplier','第二发暴击倍率',add(pn('base_second_shot_crit'),attr('critical_strike_damage_bonus_percent')),'完整CritDamage = TotalDamage×(1.75+额外暴击伤害比例)。');
 damage(x,'second_shot','第二发射击伤害','second_shot_damage','physics',{delivery:'BASIC_ATTACK',crit:fval('second_shot_crit_multiplier'),block:null});
 data(x,'PassiveDamageBase','vigilance_base_damage','警惕额外基础伤害');literal(x,'vigilance_total_ad_ratio','警惕总攻击力倍率',clean(x.p.mSpellCalculations.PassiveTotalDamage.mFormulaParts[1].mCoefficient),'完整PassiveTotalDamage mStat=2总攻击力系数。','mSpellCalculations.PassiveTotalDamage');data(x,'OnhitPassiveDuration','vigilance_duration_ms','警惕可用持续（毫秒）',{scale:1000});data(x,'NumAuto','vigilance_granted_attacks','每次触发警惕获得攻击次数');data(x,'MaxAutos','vigilance_max_attacks','最多警惕攻击次数');formula(x,'vigilance_damage','警惕额外魔法伤害',add(pn('vigilance_base_damage'),mul(pn('vigilance_total_ad_ratio'),attr('attack_damage'))),'完整PassiveTotalDamage：15+0.2总AD；只有合法警惕攻击使用。');damage(x,'vigilance_bonus','警惕一次额外伤害','vigilance_damage','magic',{delivery:'BASIC_ATTACK',block:null});
 pending(x,'双发攻击过程及E返还','接口有强化普攻窗口，可用于消费；仍需核对第二发独立暴击判定、两发实际命中和攻击特效链，不能把第二发直接叠到首次命中。已存独立暴击伤害组成，暂不启动。');
 exclude(x,'警惕的友军治疗与护盾分支','纯队友来源按当前范围排除。附近敌方定身分支包含空间检测，需确认物品等自身来源可触发后回填，不据本体无控制认定永久排除。');pending(x,'警惕的自身控制来源','当前文本定身不限友军；若自身物品使对手定身仍可能影响1V1。15+0.2总AD、2次/最多4次/6秒组成已保留；待核近距条件与事件，再接合法状态与消费。');exclude(x,'小兵伤害分支','当前对手为英雄。');
}
{
 const x=begin('lucian_q');common(x);data(x,'BaseDamage','base_damage','基础物理伤害');data(x,'BonusADRatio','bonus_ad_ratio','额外攻击力倍率');formula(x,'damage','透体圣光伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'TotalDamage明确额外攻击力1.0。');damage(x,'beam_hit','圣光命中','damage','physics');hit(x,'beam_hit');pending(x,'动态施法与P联动','当前文本明确随角色等级缩短施法；mCastTime0.35、spellCastTime0.25不能固定选一。P施法后双发待统一接线。');exclude(x,'光束多对象路径','保留当前目标每次实际命中。');
}
{
 const x=begin('lucian_w');common(x,{cast:true});data(x,'BaseDamage','base_damage','基础魔法伤害');coefficient(x,'TotalDamage',1,'ap_ratio','法强倍率');formula(x,'damage','热诚烈弹伤害',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),'TotalDamage为基础+0.9法强。');data(x,'MoveSpeedAmount','move_speed','触发标记后的移动速度');data(x,'BuffDuration','speed_duration_ms','移动速度持续（毫秒）',{scale:1000});data(x,'DebuffDuration','mark_duration_ms','目标标记持续（毫秒）',{scale:1000});attributeEffect(x,'mark_speed','标记触发自身加速','move_speed','move_speed',val('speed_duration_ms'));damage(x,'flare_hit','热诚烈弹命中','damage');castProcess(x);hit(x,'flare_hit');pending(x,'标记与P联动','合法标记施加后本人伤害可触发1秒加速；标记存在判定、施加与命中先后、跨技能P待接线。');exclude(x,'友军触发警惕与显形','保留本人触发移速；纯队友和视野不录。');
}
{
 const x=begin('lucian_e');common(x,{cast:true});data(x,'CDRefundChampion','champion_refund_ms','圣光银弹命中英雄返还冷却（毫秒）',{scale:1000});cooldown(x,'lightslinger_refund','圣光银弹命中英雄冷却返还',['lucian_e'],'REDUCE',val('champion_refund_ms'));castProcess(x);pending(x,'P命中退款','需要圣光银弹两发合法命中，不挂任意普攻。E5级消耗真实0已保留。');exclude(x,'冲刺空间路径与非英雄1秒退款','1V1只留英雄2秒返还，路径后置。');
}
{
 const x=begin('lucian_r');common(x);const bullet=adAp(x,{ad:'DamageADRatio',ap:'DamageAPRatio',adKind:'TOTAL',calc:'DamagePerBullet'});data(x,'NumShots','base_shots','基础子弹数量');data(x,'Duration','channel_duration_ms','引导时长（毫秒）',{scale:1000});data(x,'RecastLockout','recast_lockout_ms','再次施放锁定（毫秒）',{scale:1000});const amp=critAmp(x,'CritValueMod');formula(x,'bullet_damage','单颗子弹伤害',bullet,'DamagePerBullet基础+0.25总AD+0.15AP。');formula(x,'continuous_shot_count','客户端说明子弹数量计算值',mul(pn('base_shots'),amp),'TotalNumShots完整树；本公式可能为小数，实际发射整数取整未核，不用于次数步骤。');formula(x,'tooltip_total_damage','客户端说明完整引导总量',mul(bullet,mul(pn('base_shots'),amp)),'完整TotalDamage修改树；仅说明总量核对，不创建瞬间全额伤害。');damage(x,'bullet_hit','单颗子弹实际命中','bullet_damage','physics');hit(x,'bullet_hit');pending(x,'引导/取消/整数发数与P','单发命中接入；小数发数如何取整、首发时点、再次施放中断及P待接。暴击属性改变数量，不额外对单发重掷暴击。');exclude(x,'小兵增伤、显形和空间路径','当前英雄目标单发保留。');
}
{
 const x=begin('sivir_p');data(x,'HasteDuration','speed_decay_duration_ms','移动速度衰减时长（毫秒）',{scale:1000});curve(x,'initial_move_speed','初始移动速度加成',x.p.mSpellCalculations.FlatMS.mFormulaParts[0]);pending(x,'持续衰减移速及真实伤害触发','当前冻结spell_sivirpassive_tooltip明确用攻击或技能对英雄造成伤害，1.5秒持续衰减；当前持续属性不能直接配置按已过时间衰减，不能存恒定55..75或只监听攻击。E成功护盾也需触发同一机制。','系统');
}
{
 const x=begin('sivir_q');common(x);const base=adAp(x);const amp=critAmp(x,'CritRatio');formula(x,'precrit_damage','暴击属性折算前单次伤害',base,'PreCritDamage：基础+0.7额外AD+0.6AP。');formula(x,'damage','回旋之刃单次伤害',mul(base,amp),'TotalDamage完整乘区=基础量×[1+暴击率×0.4×(总暴击倍率−1)]，不是随机暴击。');data(x,'QBaseCastTime','base_cast_time_ms','基础施法时长（毫秒）',{scale:1000});data(x,'QAttackSpeedCastReductionPercent','cast_speed_ratio','额外攻速施法缩短系数');data(x,'QAttackSpeedCastReductionMax','cast_reduction_cap','施法缩短上限比例');damage(x,'boomerang_hit','回旋之刃单次命中','damage','physics');hit(x,'boomerang_hit');pending(x,'攻速施法时间与P','说明明确额外攻速缩短施法，计算组合需核；每次真实往返命中独立结算，P衰减移速待接。');exclude(x,'非英雄穿透衰减与路径搜索','单英雄无其他单位阻挡，不套后续目标衰减；回程当前目标命中仍保留。');
}
{
 const x=begin('sivir_w');common(x);data(x,'RicochetAttackSpeed','bonus_attack_speed_ratio','额外攻击速度比例');data(x,'BuffDuration','buff_duration_ms','强化持续（毫秒）',{scale:1000});attributeEffect(x,'ricochet_attack_speed','弹射主动攻击速度','bonus_attack_speed_ratio','bonus_attack_speed_percent',val('buff_duration_ms'));activeBuff(x,['ricochet_attack_speed']);exclude(x,'额外对象弹射、优先级及小兵处决','当前1V1无第二敌人；保留主动攻速。原始BounceAttacks=3未被当前4秒说明引用，不误用3次限制。');pending(x,'弹射复用原攻击暴击判定','若后续加入多对象，全部弹射沿用触发普攻暴击；不可重新掷骰。此项随多对象范围后置。');
}
{
 const x=begin('sivir_e');common(x,{officialZeroMana:true});data(x,'SpellShieldDuration','shield_duration_ms','法术护盾持续（毫秒）',{scale:1000});data(x,'HealRatio','heal_total_ad_ratio','治疗总攻击力倍率');data(x,'HealAPRatio','heal_ap_ratio','治疗法术强度倍率');formula(x,'block_heal','成功格挡回复生命',add(mul(pn('heal_total_ad_ratio'),attr('attack_damage')),mul(pn('heal_ap_ratio'),attr('ability_power'))),'TotalHeal完整计算：总AD×0.6/0.65/0.7/0.75/0.8+AP×0.5。');
 effect(x,'block_heal','成功格挡治疗',[result('heal','回复生命','DIRECT_HEAL','SOURCE',fval('block_heal'),{})],null,'仅成功格挡敌方技能后执行；不是施放或护盾自然结束时治疗。');
 effect(x,'spell_shield','希维尔法术护盾',[result('shield','格挡下一次敌方技能','SPELL_SHIELD','SOURCE',null,{},{moment:'PERSISTENT',valueReadMode:null,stackValueMode:null,reapplicationValueMode:null,periodicExecutionMode:null})],life(val('shield_duration_ms')),'来源自身单层法术护盾，持续1500毫秒，成功阻挡消耗。阻挡粒度沿来袭技能结果的spellShieldBlockScope，不把盾当伤害吸收数值。');
 activeBuff(x,['spell_shield']);rule(x,'successful_spell_block','法术护盾成功格挡后治疗',{eventType:'SPELL_SHIELD_BLOCKED',detail:{shieldEffectKey:'spell_shield'}},['block_heal']);x.c.write.triggerRules.at(-1).actions[0].actionKey='action_1';pending(x,'格挡后敏锐疾行','治疗与护盾组合交由主负责人真实页面试录；P持续衰减移速补齐后接同一事件。');
}
{
 const x=begin('sivir_r');common(x,{cast:true});data(x,'MaxMS','move_speed_ratio','主动移动速度加成比例');data(x,'UltDuration','buff_duration_ms','狩猎持续（毫秒）',{scale:1000});data(x,'AttackCooldownRefund','attack_refund_ms','攻击英雄基础技能冷却返还（毫秒）',{scale:1000});data(x,'DamagedMarkerDuration','recent_damage_ms','近期伤害参与击杀窗口（毫秒）',{scale:1000});attributeEffect(x,'on_the_hunt','狩猎自身移速','move_speed_ratio','move_speed_percent',val('buff_duration_ms'));cooldown(x,'attack_basic_refund','狩猎攻击基础技能冷却返还',['sivir_q','sivir_w','sivir_e'],'REDUCE',val('attack_refund_ms'));activeBuff(x,['on_the_hunt'],{delay:true});rule(x,'active_attack_refund','狩猎期间攻击英雄返还基础技能冷却',{eventType:'BASIC_ATTACK_HIT',detail:{}},['attack_basic_refund'],[champion,{conditionKey:'hunt_active',conditionType:'LIFECYCLE_CHECK',sortOrder:20,detail:{effectKey:'on_the_hunt',subject:null,checkKind:'PRESENT',comparator:null,comparisonValue:null}}]);pending(x,'参与击杀刷新狩猎','需要最近3秒本人对目标伤害与参与击杀因果条件；不能任意死亡都刷新。');exclude(x,'友军移速及未引用的旧攻速','当前主说明只用MaxMS/UltDuration/AttackCooldownRefund；HuntAttackSpeed等旧字段不录。');
}
{
 const x=begin('tristana_p');pending(x,'角色等级攻击与技能距离','完整BonusPassiveRange插值仅mEndValue150，mStartValue缺省；未证明序列化默认值前不补0或生成猜测曲线。攻击距离确定后可用SOURCE_INITIALIZED接属性；E/R施法距离还需字段表达。','资料');
}
{
 const x=begin('tristana_q');common(x);data(x,'AttackSpeedMod','bonus_attack_speed_ratio','额外攻击速度比例');data(x,'BuffDuration','buff_duration_ms','急速射击持续（毫秒）',{scale:1000});attributeEffect(x,'rapid_fire','急速射击攻速','bonus_attack_speed_ratio','bonus_attack_speed_percent',val('buff_duration_ms'));activeBuff(x,['rapid_fire']);
}
{
 const x=begin('tristana_w');common(x,{cast:true});const d=adAp(x,{calc:'LandingDamage'});formula(x,'damage','火箭跳跃落地伤害',d,'当前LandingDamage明确魔法伤害，基础+1额外AD+0.5AP。');data(x,'SlowMod','slow_ratio','减速比例',{scale:-1});data(x,'SlowDuration','slow_duration_ms','减速持续（毫秒）',{scale:1000});damage(x,'landing_hit','落地命中伤害','damage');castProcess(x);hit(x,'landing_hit');cooldown(x,'reset_jump','参与击杀或满层炸弹重置跳跃',['tristana_w'],'RESET');pending(x,'减速与E满层/参与击杀重置','眩晕等现状态不能代替40%减速。满层E因R击退后才爆炸例外也需统一爆炸事件，不以EARLY_REMOVE代替。本人击杀需要KILL配英雄类别，参与击杀仍待因果来源。');pending(x,'击杀英雄类别条件','真实API拒绝KILL加TARGET_CATEGORY_CHECK：目标类别只支持SKILL_HIT/BASIC_ATTACK_HIT。需允许KILL按死者类别判断后再保存，不能取消英雄门槛。','系统');exclude(x,'跳跃路径与附近目标搜索','保留当前敌方英雄实际落地命中。');
}
{
 const x=begin('tristana_e');common(x);const base=adAp(x,{base:'ActiveBaseDamage',ad:'ActiveBADRatio',calc:'ActiveDamage'});const amp=critAmp(x,'CritChanceModifier');data(x,'ActivePerStackAmp','per_stack_amp','每层伤害增幅比例');data(x,'ActiveMaxStacks','max_stacks','引爆满层数');data(x,'ActiveDuration','bomb_duration_ms','炸弹自然引爆等待（毫秒）',{scale:1000});runtime(x,'bomb_stacks','本次引爆实际炸弹层数','必须来自该目标该来源炸弹，合法整数0至4；不默认满层。当前独立公式保留，合法取层事件待接。');const zero=mul(base,amp),scaled=stacks=>mul(zero,add(pn('one'),mul(pn('per_stack_amp'),stacks)));formula(x,'unstacked_damage','未增层炸弹伤害',zero,'完整ActiveDamage含暴击属性固定折算。');formula(x,'bomb_damage','按实际层数引爆伤害',scaled(pn('bomb_stacks')),'完整ActiveMaxDamage的每层0.25线性增幅拓展到来源明确的实际0至4层；只在合法爆炸时执行。');formula(x,'max_damage','满层炸弹伤害核对',scaled(pn('max_stacks')),'4层是未增层伤害2倍；不额外重掷暴击。');damage(x,'bomb_explosion','炸弹实际爆炸伤害','bomb_damage','physics');pending(x,'附着、叠层、引爆与取层','普攻/技能加层，4秒自然结束或4层立即爆炸；R施加最后层时延后至击退后爆炸。需来源目标绑定及取层、互斥爆炸和W返还时序；不把附着命中当爆炸，不创建假引爆状态。');pending(x,'动态施法时间','mUseAutoattackCastTimeData明确沿用普攻施法时长，不编0毫秒。','资料');exclude(x,'被动击杀溅射、防御塔与半径','被动伤害只给死者周围其他对象，本轮单对手没有额外敌人；主动当前目标伤害保留。');
}
{
 const x=begin('tristana_r');common(x,{cast:true});const d=adAp(x,{coefficientAD:clean(x.p.mSpellCalculations.DamageCalc.mFormulaParts[1].mCoefficient),calc:'DamageCalc'});formula(x,'damage','毁灭射击魔法伤害',d,'当前DamageCalc基础225/275/325+0.7额外AD+1AP。');data(x,'StunDuration','stun_duration_ms','命中眩晕时长（毫秒）',{scale:1000});data(x,'KnockbackDistance','knockback_distance','击退距离');damage(x,'cannon_hit','加农炮弹命中','damage');castProcess(x);hit(x,'cannon_hit');pending(x,'击退、眩晕与E最后一层','0.4/0.55/0.7秒眩晕与击退共同存在；不能只用眩晕代替击退。末层E需等击退结束后爆炸，跨技能合法事件待补。');exclude(x,'周围多对象与爆炸半径','保留当前目标伤害和控制数值。');
}
{
 const x=begin('twitch_p');data(x,'Duration','poison_duration_ms','毒液持续（毫秒）',{scale:1000});data(x,'MaxStacks','max_stacks','毒液最大层数');data(x,'APRatio','ap_ratio','每层每秒法强倍率');curve(x,'base_dps','每层每秒基础真实伤害',x.p.mSpellCalculations.DamagePerSecond.mFormulaParts[0]);literal(x,'duration_seconds','完整毒液持续（秒）',6,'DataValues.Duration=6，仅用于总量核对。','DataValues.Duration');runtime(x,'poison_stacks','本次周期实际毒液层数','实际来源目标毒液层数1至6，非固定最大层数；当前独立周期伤害组成，合法周期取层待接。');const one=add(pn('base_dps'),mul(pn('ap_ratio'),attr('ability_power')));formula(x,'damage_per_stack_second','每层每秒毒液伤害',one,'DamagePerSecond角色等级断点1/2/3/4/5，加0.03AP。');formula(x,'damage_per_second','当前层数每秒毒液伤害',mul(one,pn('poison_stacks')),'每层每秒量乘实际层数；不一次扣完整6秒。');formula(x,'max_full_duration_damage','满层完整6秒总量核对',mul(mul(one,pn('max_stacks')),pn('duration_seconds')),'DamageMaxTotal完整修改树，只作总量核对。');damage(x,'poison_tick','一次每秒毒液伤害','damage_per_second','real',{block:null});pending(x,'毒液应用、周期、刷新与跨技能取层','普通攻击攻击特效及W应用毒液；6秒最多6层。首个周期/刷新是否重置周期相位需来源核对，目标来源作用域及E实际层数读取待统一，不在普攻命中时直接扣一次每秒伤害。');
}
{
 const x=begin('twitch_q');common(x,{cast:true});data(x,'AttackSpeedMod','bonus_attack_speed_ratio','离开伪装额外攻速比例');data(x,'AttackSpeedDuration','attack_speed_duration_ms','离开伪装攻速持续（毫秒）',{scale:1000});data(x,'StealthDuration','camouflage_duration_ms','伪装时长（毫秒）',{scale:1000});data(x,'MaxFadeTime','fade_delay_ms','进入伪装等待（毫秒）',{scale:1000});data(x,'MoveSpeedMod','camouflage_speed_ratio','伪装常态移动速度比例',{scale:.01});attributeEffect(x,'exit_camouflage_speed','离开伪装后的攻击速度','bonus_attack_speed_ratio','bonus_attack_speed_percent',val('attack_speed_duration_ms'));cooldown(x,'poisoned_death_reset','中毒英雄死亡重置埋伏',['twitch_q'],'RESET');castProcess(x);pending(x,'伪装及解除后攻速和毒目标死亡','伪装影响可选取，需要真语义；1秒等待的受伤延迟条件、进入/解除/自然到期、毒目标死亡重置需事件绑定。不能施放时立即获得攻速，也不能任意敌人死亡重置。');exclude(x,'附近未发现敌人的30%移速空间条件','当前空间与视野搜索后置；基础10%移速数值保留。');
}
{
 const x=begin('twitch_w');common(x,{cast:true});data(x,'BaseSlowAmount','base_slow_ratio','基础减速比例',{scale:.01});data(x,'SlowAPRatio','slow_ap_ratio','每点法强减速比例',{scale:.01});data(x,'Duration','cloud_duration_ms','毒雾存留（毫秒）',{scale:1000});formula(x,'slow_ratio','毒雾减速比例',add(pn('base_slow_ratio'),mul(pn('slow_ap_ratio'),attr('ability_power'))),'TotalSlowAmount原输出百分数；30+0.06AP整体除100，100AP时0.36。');castProcess(x);pending(x,'命中与停留叠毒和减速','桶命中1层，停留每秒额外1层；不能单次命中自动视为完整3秒停留。需真实周期条件和P同源毒层统一。减速倍率与韧性组合由公共结构核对。');exclude(x,'毒雾区域搜索','保留当前对手叠层/减速所需数值，不录其他对象空间搜索。');
}
{
 const x=begin('twitch_e');common(x,{cast:true});data(x,'BaseDamage','base_damage','基础物理伤害');data(x,'BasePhysicalDamagePerStack','physical_per_stack','每层基础物理伤害');data(x,'bADRatioPerStack','bonus_ad_ratio_per_stack','每层额外攻击力倍率');data(x,'APRatioPerStack','ap_ratio_per_stack','每层法强倍率');data(x,'MaxStacks','max_stacks','最大毒层数');runtime(x,'poison_stacks','本次毒性爆发实际毒层数','必须读取当前目标由本来源施加的毒层，合法整数1至6；无毒目标不执行，不默认6层，不伪造消费毒液。');const physicalPer=add(pn('physical_per_stack'),mul(pn('bonus_ad_ratio_per_stack'),attr('attack_damage','SOURCE','BONUS'))),magicPer=mul(pn('ap_ratio_per_stack'),attr('ability_power'));formula(x,'physical_damage','实际毒层物理伤害',add(pn('base_damage'),mul(pn('poison_stacks'),physicalPer)),'基础+层数×(每层基础+0.35额外AD)。');formula(x,'magic_damage','实际毒层魔法伤害',mul(pn('poison_stacks'),magicPer),'层数×0.35AP，不误合并为物理伤害。');formula(x,'max_physical_damage','满层物理伤害核对',add(pn('base_damage'),mul(pn('max_stacks'),physicalPer)),'MaxPhysicalDamage完整树。');formula(x,'max_magic_damage','满层魔法伤害核对',mul(pn('max_stacks'),magicPer),'MaxMagicDamage完整修改树。');
 const parts=['physics','magic'].map((type,i)=>{const r=result(type,type==='physics'?'毒性爆发物理部分':'毒性爆发魔法部分','DAMAGE','TARGET',fval(i?'magic_damage':'physical_damage'),{damageTypeKey:type,deliveryKind:'SKILL',originKind:'DIRECT',critical:{mode:'DISALLOWED',multiplierValue:null},vampRules:[]},null,'EFFECT');r.sortOrder=(i+1)*10;return r;});effect(x,'contaminate_damage','毒性爆发两种伤害',parts,null,'同一次技能的物理和魔法部分按整个效果阻挡，避免法术盾只挡第一部分。需要合法实际毒层输入，不在当前空绑定状态接命中规则。');castProcess(x);pending(x,'毒存在条件与实际层数绑定','P/W目标来源毒层合法读取后，按实际1至6层执行两部分；不能对未中毒对象扣基础伤害，不因“引爆”文案清除毒液。');exclude(x,'附近其他敌人搜索','当前目标独立组成保留。');
}
{
 const x=begin('twitch_r');common(x);data(x,'BonusAD','bonus_attack_damage','额外攻击力');data(x,'BonusRange','bonus_attack_range','额外攻击距离');data(x,'Duration','buff_duration_ms','火力全开持续（毫秒）',{scale:1000});attributeEffect(x,'bonus_ad','火力全开攻击力','bonus_attack_damage','attack_damage',val('buff_duration_ms'));attributeEffect(x,'bonus_range','火力全开攻击距离','bonus_attack_range','attack_range',val('buff_duration_ms'));activeBuff(x,['bonus_ad','bonus_range']);exclude(x,'穿透路径、多目标伤害衰减与越程','保留本人攻击力、攻击距离；不重复创建普通攻击基础伤害。');pending(x,'伪装与攻击投射规则','本技能施放不打破伪装，攻击仍解除；与Q伪装真实状态及穿透攻击事件交接时保留这一区别。');
}

for(const x of Object.values(plan.skills)){
 for(const kind of Object.values(x.write)){const keys=kind.map(v=>v.parameterKey??v.formulaKey??v.effectKey??v.processKey??v.stateKey??v.ruleKey);if(new Set(keys).size!==keys.length)throw Error('重复稳定键 '+x.skillKey);}
 x.status=x.pending.length?'已准备部分组成；须独立GET确认保存；待补不是机制完成':'本轮范围组成候选；须独立GET和页面验收';
}
