import {access,mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const here=new URL('./',import.meta.url);
const artifact='C:/project/damage_web_dev/.agents/artifacts/hero15-20260909/';
const base='http://127.0.0.1:8080/api/admin/games/lol';
const token=process.env.TASK_TOKEN??'local-entry';
const heroes=[{id:'Viktor',key:'viktor'},{id:'Orianna',key:'orianna'},{id:'Syndra',key:'syndra'},{id:'Taliyah',key:'taliyah'}];
const skillKeys=heroes.flatMap(h=>['p','q','w','e','r'].map(slot=>h.key+'_'+slot));
const kinds=[['parameters','parameters','parameterKey'],['formulas','formulas','formulaKey'],['effects','effects','effectKey'],['processes','processes','processKey'],['internalStates','internal-states','stateKey'],['triggerRules','trigger-rules','ruleKey']];
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const requests=[],errors=[],duplicates=[];
async function get(route){const url=base+route;try{const response=await fetch(url,{method:'GET',headers:{Authorization:'Bearer '+token,Accept:'application/json'},signal:AbortSignal.timeout(30000)});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{};const out={route,method:'GET',status:response.status,data};requests.push({route,method:'GET',status:response.status});return out;}catch(error){const out={route,method:'GET',status:null,error:error.name};requests.push({route,method:'GET',status:null});return out;}}
function rows(result){if(result.status!==200)return null;if(Array.isArray(result.data))return result.data;if(Array.isArray(result.data?.items))return result.data.items;return null;}
const out={at:new Date().toISOString(),mode:'全部请求为GET；保留当前20技能主体及六类组成原值；不写业务接口',base,heroes:heroes.map(h=>h.id),skillKeys,kinds:kinds.map(([name,api,id])=>({name,api,id})),skills:{},catalogs:{},duplicateKeys:[],requests:[],errors:[]};
for(const name of ['attributes','modifier-zones','statuses','damage-types']){const result=await get('/'+name);out.catalogs[name]=result;if(result.status!==200)errors.push({route:result.route,status:result.status,reason:'目录GET失败'});}
for(const skillKey of skillKeys){const subject=await get('/skills/'+skillKey);const snapshot={subject,components:{}};if(subject.status!==200)errors.push({route:subject.route,status:subject.status,reason:'技能GET失败'});for(const [name,api,id] of kinds){const list=await get('/skills/'+skillKey+'/'+api);const items=rows(list);const details=[];snapshot.components[name]={list,items:items??[],details};if(!items){errors.push({route:list.route,status:list.status,reason:'组成列表GET失败或响应不是数组'});continue;}const seen=new Set();for(const item of items){const key=item?.[id];if(typeof key!=='string'){duplicates.push({skillKey,kind:name,key:null,reason:'稳定键缺失'});continue;}if(seen.has(key)){duplicates.push({skillKey,kind:name,key,reason:'稳定键重复'});errors.push({route:list.route,status:list.status,reason:'组成稳定键重复'});}seen.add(key);const detail=await get('/skills/'+skillKey+'/'+api+'/'+encodeURIComponent(key));details.push({key,item,detail});if(detail.status!==200)errors.push({route:detail.route,status:detail.status,reason:'组成详情GET失败'});}}
out.skills[skillKey]=snapshot;}
out.requests=requests;out.errors=errors;out.duplicateKeys=duplicates;const compositionCount=Object.values(out.skills).reduce((n,s)=>n+Object.values(s.components).reduce((m,c)=>m+c.items.length,0),0);const detailCount=Object.values(out.skills).reduce((n,s)=>n+Object.values(s.components).reduce((m,c)=>m+c.details.length,0),0);out.summary={skillCount:Object.keys(out.skills).length,expectedSkillCount:20,compositionCount,detailCount,duplicateCount:duplicates.length,errorCount:errors.length,requestCount:requests.length};const report={at:out.at,mode:out.mode,summary:out.summary,duplicates,errors,statusCounts:requests.reduce((m,r)=>(m[String(r.status)]=(m[String(r.status)]??0)+1,m),{}),snapshotSha256:hash(Buffer.from(JSON.stringify(out,null,2)+'\n'))};
if(errors.length){await mkdir(artifact,{recursive:true});await writeFile(artifact+'当前20技能GET失败.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({success:false,...out.summary,statusCounts:report.statusCounts}));process.exitCode=1;}else{const bytes=Buffer.from(JSON.stringify(out,null,2)+'\n');const target=new URL('./写前现值.json',here);if(await access(target).then(()=>true,()=>false))throw Error('写前现值.json已存在，拒绝覆盖原始GET证据');await writeFile(target,bytes,{flag:'wx'});await writeFile(new URL('./当前20技能组成核对.json',here),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({success:true,...out.summary,snapshotSha256:report.snapshotSha256,statusCounts:report.statusCounts}));}
