import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const dir=path.dirname(fileURLToPath(import.meta.url)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),raw=fs.readFileSync(path.join(dir,'可审查请求.json')),plan=JSON.parse(raw),expected='e7016af1c4ef98e846b90e32720047fb34f92e6e8015d65c8f77158e8389630b';
assert.equal(sha(raw),expected);assert.equal(process.argv[2],'--apply');assert.equal(process.argv.length,3);assert(process.env.BASE_AD_API_TOKEN);
const before=JSON.parse(fs.readFileSync(path.join(dir,'写前现值.json')));assert.equal(sha(fs.readFileSync(path.join(dir,'写前现值.json'))),plan.beforeFileSha256);const journal=path.join(dir,'实际流水.jsonl');assert(!fs.existsSync(journal),'已有执行流水，先人工对账，不重放');
const reads=[],writes=[],input='spellblade_damage_mstat2_formula1_input',sk='item_2510_passive';
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).filter(k=>!['createdAt','updatedAt'].includes(k)).sort().map(k=>[k,stable(v[k])]));return v;}
function subset(a,b){if(b&&typeof b==='object'){assert(a&&typeof a==='object');if(Array.isArray(b))assert.equal(a.length,b.length);for(const[k,v]of Object.entries(b))subset(a[k],v);}else assert.deepEqual(a,b);}
async function request(route,method='GET',body){if(method!=='GET')assert(plan.requests.some(x=>x.route===route&&x.method===method),'写入越界');fs.appendFileSync(journal,JSON.stringify({at:new Date().toISOString(),phase:'before',method,route,...(body?{body}:{})})+'\n');const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer '+process.env.BASE_AD_API_TOKEN,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const text=await r.text(),data=text?JSON.parse(text):null;const row={at:new Date().toISOString(),method,route,status:r.status,data};fs.appendFileSync(journal,JSON.stringify({phase:'after',...row})+'\n');(method==='GET'?reads:writes).push(row);return row;}
async function detail(route){const r=await request(route);assert.equal(r.status,200,route);return r.data;}
const currentBefore=[];for(const r of plan.requests){const d=await detail(r.route);assert.deepEqual(stable(d),stable(r.before),'写前漂移 '+r.route);currentBefore.push(d);}
for(const r of plan.requests.filter(r=>r.method==='PUT')){const response=await request(r.route,r.method,r.body);assert(response.status>=200&&response.status<300,'更新失败，先对账不重放 '+r.route);subset(await detail(r.route),r.body);}
const zeroRef=[];for(const[k,pk]of [['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey'],['processes','processKey'],['internal-states','stateKey'],['trigger-rules','ruleKey']]){const l=await detail(`/skills/${sk}/${k}`),items=Array.isArray(l)?l:l.items;assert(Array.isArray(items));for(const p of items){if(k==='parameters'&&p[pk]===input)continue;const d=await detail(`/skills/${sk}/${k}/${p[pk]}`);const matches=[];function walk(v,p){if(!v||typeof v!=='object')return;for(const [key,val]of Object.entries(v)){if(val===input)matches.push(p+'/'+key);else if(val&&typeof val==='object')walk(val,p+'/'+key);}}walk(d,k+'/'+p[pk]);assert.equal(matches.length,0,'仍有引用不得删除');zeroRef.push({kind:k,key:p[pk],matches});}}
const deletion=plan.requests.find(r=>r.method==='DELETE'),deleted=await request(deletion.route,'DELETE');assert(deleted.status>=200&&deleted.status<300);assert.equal((await request(deletion.route)).status,404);
const final={subject:await detail('/skills/'+sk),parameters:[],formulas:[]};for(const k of ['parameters','formulas']){const pk=k==='parameters'?'parameterKey':'formulaKey',l=await detail(`/skills/${sk}/${k}`);for(const p of Array.isArray(l)?l:l.items)final[k].push(await detail(`/skills/${sk}/${k}/${p[pk]}`));}
assert.equal(final.parameters.length,5);assert.equal(final.formulas.length,2);const old=before.objects.find(x=>x.id===2510);for(const p of final.parameters){const change=plan.requests.find(r=>r.route.endsWith('/parameters/'+p.parameterKey));if(change)subset(p,change.body);else assert.deepEqual(stable(p),stable(old.components.parameters.details.find(x=>x.parameterKey===p.parameterKey)));}for(const f of final.formulas){const change=plan.requests.find(r=>r.route.endsWith('/formulas/'+f.formulaKey));if(change)subset(f,change.body);else assert.deepEqual(stable(f),stable(old.components.formulas.details.find(x=>x.formulaKey===f.formulaKey)));}
for(const r of [old.images,old.relations])assert.deepEqual(stable(await detail(r.route??(r===old.images?`/skills/${sk}/representative-image`:'/equipment-skill-relations?equipmentKey=item_2510'))),stable(r.data));
const cases=[];const formula=final.formulas.find(f=>f.formulaKey==='spellblade_damage_value');function calculate(n,attrs){if(n.nodeType==='PARAMETER'){const p=final.parameters.find(p=>p.parameterKey===n.parameterKey);assert(p);return p.fixedValue;}if(n.nodeType==='ATTRIBUTE')return attrs[n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind];const [a,b]=n.operands.map(n=>calculate(n,attrs));return n.operation==='ADD'?a+b:n.operation==='MULTIPLY'?a*b:NaN;}
for(const[base,total,bonus,ap,want]of [[100,300,200,200,95],[80,1000,920,0,60],[120,120,0,300,120]]){const attrs={'SOURCE.attack_damage.BASE':base,'SOURCE.attack_damage.TOTAL':total,'SOURCE.attack_damage.BONUS':bonus,'SOURCE.ability_power.TOTAL':ap},actual=calculate(formula.expression,attrs);assert.equal(actual,want);cases.push({attrs,actual,expected:want});}
const out={at:new Date().toISOString(),planSha256:expected,created:0,updated:3,deleted:1,zeroReferenceGuard:zeroRef,reads,writes,actual:final,mathCases:cases,passed:true,runtimeValidation:'仅实际管理数据和本地公式，未执行战斗引擎'};fs.writeFileSync(path.join(dir,'实际回补结果.json'),JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({updated:3,deleted:1,reads:reads.length,cases:cases.length,passed:true,finalParameters:5}));
