import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const dir=path.dirname(fileURLToPath(import.meta.url)),p=JSON.parse(fs.readFileSync(path.join(dir,'可审查请求.json'))),b=JSON.parse(fs.readFileSync(path.join(dir,'写前现值.json'))).objects.find(x=>x.id===2510),reads=[],sk='item_2510_passive';assert(process.env.BASE_AD_API_TOKEN);
const canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).filter(k=>!['createdAt','updatedAt'].includes(k)).sort().map(k=>[k,canonical(x[k])])):x;
function subset(a,b){if(b&&typeof b==='object'){assert(a&&typeof a==='object');if(Array.isArray(b))assert.equal(a.length,b.length);for(const[k,v]of Object.entries(b))subset(a[k],v);}else assert.deepEqual(a,b);}
async function get(route,status=200){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer '+process.env.BASE_AD_API_TOKEN},signal:AbortSignal.timeout(15000)}),data=await r.json();reads.push({route,status:r.status,data});assert.equal(r.status,status,route);return data;}
const final={subject:await get('/skills/'+sk),components:{}};subset(final.subject,p.requests.find(r=>r.route==='/skills/'+sk).body);
for(const[k,pk]of [['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey'],['processes','processKey'],['internal-states','stateKey'],['trigger-rules','ruleKey']]){const list=await get(`/skills/${sk}/${k}`),rows=Array.isArray(list)?list:list.items;assert(Array.isArray(rows));const expected=b.components[k].details.filter(x=>x[pk]!=='spellblade_damage_mstat2_formula1_input');assert.deepEqual(rows.map(x=>x[pk]).sort(),expected.map(x=>x[pk]).sort());final.components[k]=[];for(const row of rows){const route=`/skills/${sk}/${k}/${row[pk]}`,data=await get(route),change=p.requests.find(r=>r.route===route);if(change)subset(data,change.body);else assert.deepEqual(canonical(data),canonical(expected.find(x=>x[pk]===row[pk])));final.components[k].push(data);}}
await get('/skills/'+sk+'/parameters/spellblade_damage_mstat2_formula1_input',404);
assert.deepEqual(canonical(await get('/skills/'+sk+'/representative-image')),canonical(b.images.data));assert.deepEqual(canonical(await get('/equipment-skill-relations?equipmentKey=item_2510')),canonical(b.relations.data));
const actualFormula=final.components.formulas.find(f=>f.formulaKey==='spellblade_damage_value');assert.deepEqual(actualFormula.expression.operands[0].operands[1],{attributeKey:'attack_damage',attributeOwner:'SOURCE',attributeValueKind:'BASE',nodeType:'ATTRIBUTE'});
function evaluate(n,attrs){if(n.nodeType==='PARAMETER')return final.components.parameters.find(p=>p.parameterKey===n.parameterKey).fixedValue;if(n.nodeType==='ATTRIBUTE')return attrs[n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind];const [a,b]=n.operands.map(x=>evaluate(x,attrs));return n.operation==='ADD'?a+b:n.operation==='MULTIPLY'?a*b:NaN;}
const cases=[];for(const[base,total,bonus,ap,want]of [[100,300,200,200,95],[80,1000,920,0,60],[120,120,0,300,120]]){const attrs={'SOURCE.attack_damage.BASE':base,'SOURCE.attack_damage.TOTAL':total,'SOURCE.attack_damage.BONUS':bonus,'SOURCE.ability_power.TOTAL':ap},actual=evaluate(actualFormula.expression,attrs);assert.equal(actual,want);cases.push({attrs,actual,expected:want});}
const out={at:new Date().toISOString(),reads,actual:final,mathCases:cases,businessWrites:0,passed:true};fs.writeFileSync(path.join(dir,'独立回读结果.json'),JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({independentGets:reads.length,mathCases:cases.length,passed:true,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,'独立回读结果.json'))).digest('hex')}));
