import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const ROOT = path.dirname(fileURLToPath(import.meta.url));
const sha = (v) => crypto.createHash('sha256').update(v).digest('hex');
const json = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const save = (p, x) => fs.writeFileSync(path.join(ROOT, p), `${JSON.stringify(x, null, 2)}\n`, 'utf8');
const candidate = json('完整候选.json');
const math = json('独立源值数学报告.json');
if (math.status !== 'PASS' || math.apiWrites !== 0 || math.apiCalls !== 0 || math.noApiCalls !== true) throw new Error('严格数学未通过或存在接口调用记录，拒绝冻结');
candidate.meta.status = '候选已冻结，严格数学通过，未调用业务接口';
candidate.meta.businessWrites = 0;
candidate.meta.apiCalls = 0;
candidate.meta.candidateSha256 = null;
const candidateSha256 = sha(JSON.stringify(candidate, null, 2));
candidate.meta.candidateSha256 = candidateSha256;
save('完整候选.json', candidate);
const plan = json('写前请求计划.json');
plan.status = '候选已冻结，严格数学通过；仅写入意图，未调用业务接口';
plan.candidateSha256 = candidateSha256;
plan.noApiCalls = true;
save('写前请求计划.json', plan);
const planSha256 = sha(JSON.stringify(plan, null, 2));
math.candidateSha256 = candidateSha256;
math.status = 'PASS';
math.finalCandidateSha256 = candidateSha256;
save('独立源值数学报告.json', math);
const mathSha256 = sha(JSON.stringify(math, null, 2));
const files = ['完整候选.json','写前请求计划.json','源值解析.json','来源哈希汇总.json','来源与范围.json','候选版本.json','冻结候选锁.json','候选交付索引.json','独立源值数学报告.json'];
const fileHashes = Object.fromEntries(files.map((p) => [p, sha(fs.readFileSync(path.join(ROOT, p)))]));
const version = json('候选版本.json');
Object.assign(version, { status: 'frozen-candidate', candidateSha256, planSha256, mathSha256, apiWrites: 0 });
save('候选版本.json', version);
const lock = json('冻结候选锁.json');
Object.assign(lock, { status: '候选已冻结，严格数学通过，未调用业务接口', candidateSha256, planSha256, mathSha256, apiWrites: 0, noApiCalls: true });
save('冻结候选锁.json', lock);
const index = json('候选交付索引.json');
Object.assign(index, { status: '候选已冻结，严格数学通过，未调用业务接口', candidateSha256, planSha256, mathSha256, apiWrites: 0 });
save('候选交付索引.json', index);
const scope = json('来源与范围.json');
scope.status = '候选已冻结，严格数学通过，未调用业务接口';
scope.candidateSha256 = candidateSha256;
scope.mathSha256 = mathSha256;
save('来源与范围.json', scope);
const sourceHashes = json('来源哈希汇总.json');
Object.assign(sourceHashes, { candidateSha256, planSha256, mathSha256 });
save('来源哈希汇总.json', sourceHashes);
const finalFiles = [...files, '候选版本.json','冻结候选锁.json','候选交付索引.json','来源与范围.json','来源哈希汇总.json'];
const finalFileHashes = Object.fromEntries(finalFiles.map((p) => [p, sha(fs.readFileSync(path.join(ROOT, p)))]));
const final = { generatedAt: new Date().toISOString(), batch: '英雄机制第三十三批', revision: candidate.revision, status: '候选已冻结，严格数学通过，未调用业务接口', sourceVersion: candidate.meta.sourceVersion, candidateSha256, planSha256, mathSha256, sourceIndexSha256: candidate.meta.sourceIndexSha256, currentSnapshotSha256: candidate.meta.currentSnapshotSha256, requestCount: plan.requestCount, requestCounts: plan.requestCounts, counts: candidate.counts, protectedCounts: candidate.protectedObjects.protectedReferenceCounts, apiWrites: 0, apiCalls: 0, noApiCalls: true, fileHashes: finalFileHashes };
save('最终哈希汇总.json', final);
console.log(JSON.stringify({ status: final.status, candidateSha256, planSha256, mathSha256, requestCount: final.requestCount, requestCounts: final.requestCounts, apiWrites: 0, fileCount: finalFiles.length }, null, 2));
