import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
const argv=process.argv.slice(2);if(argv.length>1||argv.some(x=>x!=='--apply'&&x!=='--verify'))throw Error('默认只读预检；--apply只补缺；--verify独立回读');
const mode=argv[0]??'--preview',here=path.dirname(fileURLToPath(import.meta.url)),base='http://127.0.0.1:8080/api/admin/games/lol';
const hash=b=>createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const raw=fs.readFileSync(path.join(here,'可审查请求.json'));assert.equal(hash(raw),'45942778a468d2b1c9557ecd3c052ff9c54c514087b7659ae801c71b1d780095');
const plan=JSON.parse(raw);assert.equal(plan.requests.length,99);assert.equal(plan.scope.length,12);
const inventoryDir=path.resolve(here,'../符文机制盘点'),sources=read(path.join(inventoryDir,'冻结来源.json'));
for(const input of sources.inputs){const file=path.resolve(here,'../../装备符文',input.file);assert.equal(hash(fs.readFileSync(file)),input.sha256);}
assert.equal(hash(fs.readFileSync(path.join(inventoryDir,'下一批最多12项.json'))),plan.sourceCandidateSha256);
const extra=read(path.join(inventoryDir,'关联装备来源.json'));
const officialItems=path.resolve(here,'../../装备符文/官方原始资料/item-16.17.1-zh_CN.json');assert.equal(hash(fs.readFileSync(officialItems)),'aff335136e1dc3429655efc763460b9a55630ce8ba27522654070a6beb239973');
const id=new Date().toISOString().replace(/[-:.TZ]/g,''),reportFile=path.join(here,`${mode.slice(2)}-${id}.json`),journal=path.join(here,`流水-${id}.jsonl`);
const report={startedAt:new Date().toISOString(),mode,requestSha256:hash(raw),preflight:[],writes:[],imagePreflight:[],imageWrites:[],finalReads:[],summary:null};
const redact=x=>Array.isArray(x)?x.map(redact):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).filter(([k])=>!['imageBase64','authorization','cookie','token'].includes(k)).map(([k,v])=>[k,redact(v)])):x;
const record=x=>fs.appendFileSync(journal,JSON.stringify(redact({at:new Date().toISOString(),...x}))+'\n');
const save=()=>fs.writeFileSync(reportFile,JSON.stringify(redact(report),null,2)+'\n');
const match=(a,b)=>b===null||typeof b!=='object'?Object.is(a,b):Array.isArray(b)?Array.isArray(a)&&a.length===b.length&&b.every((v,i)=>match(a[i],v)):a&&Object.entries(b).every(([k,v])=>match(a[k],v));
async function request(method,route,body){if(method!=='GET'&&mode!=='--apply')throw Error('只读模式禁止写入');record({phase:'before',method,route,body});try{const r=await fetch(base+route,{method,headers:{Authorization:'Bearer local-entry',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});const text=await r.text();let data;try{data=text?JSON.parse(text):null;}catch{throw Error('响应不是JSON');}const result={status:r.status,data};record({phase:'after',method,route,...result});return result;}catch(e){record({phase:'unknown',method,route,error:e.name});throw Error(`${method} ${route}结果未知：${e.name}`);}}
async function inspect(p){const r=await request('GET',p.readRoute);if(r.status===404){if(p.kind!=='relation')return{state:'missing',...r};const parent=await request('GET','/skills/'+p.skillKey);if(parent.status===404)return{state:'missing',...r};}if(r.status!==200)throw Error(p.readRoute+'读取失败HTTP'+r.status);let value=r.data;if(p.kind==='relation'){if(!Array.isArray(value.items))throw Error('关系返回结构变化');if(value.items.length===0)return{state:'missing',...r};if(value.items.length!==1)throw Error('目标关系数量异常');value=value.items[0];}return{state:match(value,p.body)?'same':'conflict',...r};}
async function mutateAndConfirm(method,route,body,confirm){let result=null,error=null;try{result=await request(method,route,body);}catch(e){error=e.message;}const readback=await confirm();if(!readback.ok)throw Error(`${method} ${route}写后回读不符；停止，不自动重发`);return{method,route,responseStatus:result?.status??null,recoveredAfterUnknown:Boolean(error),readback};}
try{
 for(const row of plan.scope){const rune=await request('GET','/runes/'+row.runeKey);assert.equal(rune.status,200);assert.equal(rune.data.runeKey,row.runeKey);const source=await request('GET','/runes/'+row.runeKey+'/representative-image');assert.equal(source.status,200);assert(source.data.image&&source.data.image.enabled===true);const skillImage=await request('GET','/skills/'+row.skillKey+'/representative-image');assert([200,404].includes(skillImage.status));const existing=skillImage.status===200?skillImage.data.image:null;if(existing&&existing.imageKey!==source.data.image.imageKey)throw Error(row.skillKey+'已有不同代表图');report.imagePreflight.push({runeKey:row.runeKey,skillKey:row.skillKey,imageKey:source.data.image.imageKey,state:existing?'same':'missing'});}
 for(const p of plan.requests){const r=await inspect(p);report.preflight.push({route:p.readRoute,kind:p.kind,state:r.state});if(r.state==='conflict')throw Error(p.readRoute+'现值不同，拒绝覆盖');}
 save();
 if(mode==='--apply'){
  for(const p of plan.requests){const current=await inspect(p);if(current.state==='same')continue;if(current.state!=='missing')throw Error(p.readRoute+'执行前现值变化');const w=await mutateAndConfirm('POST',p.route,p.body,async()=>{const r=await inspect(p);return{ok:r.state==='same',status:r.status,actual:r.data};});report.writes.push(w);save();}
  for(const p of report.imagePreflight){const route='/skills/'+p.skillKey+'/representative-image',r=await request('GET',route);assert.equal(r.status,200);if(r.data.image){assert.equal(r.data.image.imageKey,p.imageKey);continue;}const w=await mutateAndConfirm('PUT',route,{imageKey:p.imageKey},async()=>{const a=await request('GET',route);return{ok:a.status===200&&a.data.image?.imageKey===p.imageKey,status:a.status,imageKey:a.data.image?.imageKey};});report.imageWrites.push(w);save();}
 }
 if(mode!=='--preview'){
  for(const p of plan.requests){const r=await inspect(p);assert.equal(r.state,'same',p.readRoute);report.finalReads.push({id:p.id,kind:p.kind,route:p.readRoute,matched:true,actual:r.data});}
  for(const p of report.imagePreflight){const r=await request('GET','/skills/'+p.skillKey+'/representative-image');assert.equal(r.data.image?.imageKey,p.imageKey);const uses=await request('GET','/images/'+p.imageKey+'/usages');assert.equal(uses.status,200);assert(uses.data.runes.some(x=>x.runeKey===p.runeKey));assert(uses.data.skills.some(x=>x.skillKey===p.skillKey));report.finalReads.push({kind:'image',skillKey:p.skillKey,imageKey:p.imageKey,matched:true,usages:uses.data});}
 }
 report.summary={passed:true,preflight:report.preflight.length,same:report.preflight.filter(x=>x.state==='same').length,missing:report.preflight.filter(x=>x.state==='missing').length,writes:report.writes.length,imageWrites:report.imageWrites.length,finalReads:report.finalReads.length,completeRuneMechanisms:0};report.completedAt=new Date().toISOString();save();console.log(JSON.stringify({file:reportFile,...report.summary}));
}catch(e){report.failure={name:e.name,message:e.message};save();console.error(JSON.stringify({file:reportFile,error:e.message}));process.exitCode=1;}
