import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const here=new URL('./',import.meta.url),read=n=>JSON.parse(fs.readFileSync(new URL(n,here))),sha=n=>crypto.createHash('sha256').update(fs.readFileSync(new URL(n,here))).digest('hex');const old=read('完整候选.json'),final=read('最终候选.json'),lock=read('最终候选锁.json'),oldRequests=read('写前计划.json'),newRequests=read('最终写前计划.json'),before=read('写前现值.json'),originalMath=read('独立源值与算例.json');assert.equal(sha('最终候选.json'),lock.candidateSha256);assert.equal(sha('完整候选.json'),lock.originalCandidateSha256);
const oldEffect=old.skills.kennen_e.write.effects.find(e=>e.effectKey==='after_attack_speed'),effect=final.skills.kennen_e.write.effects.find(e=>e.effectKey==='after_attack_speed'),normalized=structuredClone(final);normalized.skills.kennen_e.write.effects[normalized.skills.kennen_e.write.effects.findIndex(e=>e.effectKey==='after_attack_speed')]=oldEffect;assert.deepEqual(normalized,old,'其余完整候选对象必须一字不改');
const normalizedEffect=structuredClone(effect);normalizedEffect.description=oldEffect.description;normalizedEffect.lifecycle.durationValue=oldEffect.lifecycle.durationValue;assert.deepEqual(normalizedEffect,oldEffect,'效果其余字段不得变化');assert.deepEqual(effect.lifecycle.durationValue,{kind:'PARAMETER',parameterKey:'after_duration_ms'});assert.equal(final.skills.kennen_e.write.parameters.find(p=>p.parameterKey==='after_duration_ms').fixedValue,4000);assert.equal(effect.lifecycle.reapplicationDurationMode,'REFRESH_ALL');
const counts={};for(const s of Object.values(final.skills))for(const[k,items]of Object.entries(s.write))counts[k]=(counts[k]??0)+items.length;assert.deepEqual(counts,{parameters:154,formulas:34,effects:25,processes:0,internalStates:0,triggerRules:0});assert.equal(newRequests.requests.length,189);assert.deepEqual(newRequests.reuse,oldRequests.reuse);assert.equal(newRequests.reuse.length,24);for(const r of newRequests.reuse){const detail=before.skills[r.skillKey].components.parameters.details.find(p=>p.key===r.key).detail.data;assert.deepEqual(r.fullBefore,detail);}
const diffs=[];for(let i=0;i<newRequests.requests.length;i++){const a=oldRequests.requests[i],b=newRequests.requests[i];try{assert.deepEqual(a,b);}catch{diffs.push({index:i,skillKey:b.skillKey,kind:b.kind,key:b.key,before:a.body,after:b.body});}}assert.equal(diffs.length,1);assert.equal(diffs[0].skillKey,'kennen_e');assert.equal(diffs[0].key,'after_attack_speed');
for(const s of Object.values(final.skills))for(const e of s.write.effects)for(const r of e.results)assert.notEqual(r.lifecycleBehavior?.valueReadMode,'MOMENT_EVALUATION');assert.deepEqual(final.skills.kennen_e.write.formulas,old.skills.kennen_e.write.formulas);assert.equal(originalMath.failures.length,0);
const s=final.skills.kennen_e,evalNode=(n,inputs)=>{if(n.nodeType==='PARAMETER'){const p=s.write.parameters.find(p=>p.parameterKey===n.parameterKey);if(p.valueMode==='FIXED')return p.fixedValue;if(p.valueMode==='RUNTIME_INPUT'){assert(Object.hasOwn(inputs,p.parameterKey),'不能默认未提供次数');return inputs[p.parameterKey];}throw Error('本式不应依赖技能等级');}const [a,b]=n.operands.map(c=>evalNode(c,inputs));return ({ADD:()=>a+b,MULTIPLY:()=>a*b,MIN:()=>Math.min(a,b),MAX:()=>Math.max(a,b)})[n.operation]();};const cap=s.write.formulas.find(f=>f.formulaKey==='capped_after_duration_ms').expression;
const arithmetic=[];for(const n of [0,1,4,8]){const actual=evalNode(cap,{confirmed_critical_extension_count:n}),expected=4000+Math.min(Math.max(n,0)*1000,4000);assert.equal(actual,expected);arithmetic.push({criticalCount:n,totalDurationMs:actual,meaning:'只验证总时长上限算术，不是事件发生时剩余时长'});}
const counterexamples=[{elapsedMs:1000,remainingBeforeMs:3000,priorCriticalCount:0,expectedRemainingAfterMs:4000},{elapsedMs:3500,remainingBeforeMs:500,priorCriticalCount:0,expectedRemainingAfterMs:1500}].map(c=>{const incorrectRefreshMs=evalNode(cap,{confirmed_critical_extension_count:c.priorCriticalCount+1}),permittedExtensionMs=1000,correctRemaining=c.remainingBeforeMs+permittedExtensionMs;assert.equal(correctRemaining,c.expectedRemainingAfterMs);assert.notEqual(incorrectRefreshMs,correctRemaining);return {...c,permittedExtensionMs,incorrectRefreshMs,overstatedRemainingMs:incorrectRefreshMs-correctRemaining,passed:true};});
let missingRejected=false;try{evalNode(cap,{});}catch{missingRejected=true;}assert(missingRejected);
const report={at:new Date().toISOString(),status:'READY_FOR_PARENT_REVIEW',candidateSha256:lock.candidateSha256,originalCandidateSha256:lock.originalCandidateSha256,writePlanSha256:sha('最终写前计划.json'),scope:'仅确定初始4秒持续时间和说明修改；原34公式完全未变，原102源树/52手算证据继续适用于相同数值。新增长度语义反例，未业务写或战斗运行。',counts,totalComposition:213,newComponents:189,reusedPublicParameters:24,changedRequests:diffs,arithmetic,counterexamples,initialEffectDurationMs:4000,initialEffectNeedsCriticalCount:false,totalDurationFormulaPreserved:true,totalDurationFormulaBoundToEffect:false,noMomentEvaluationEffects:true,missingInputRejected:missingRejected,originalProofSha256:sha('独立源值与算例.json'),originalFrozenLockUnchanged:sha('冻结候选锁.json')===lock.originalLockSha256,apiWrites:0};assert(report.originalFrozenLockUnchanged);fs.writeFileSync(new URL('初始攻速时长差异核算.json',here),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:report.status,candidateSha256:report.candidateSha256,changedRequests:1,counts,newComponents:189,reused:24,counterexamples:counterexamples.length,reportSha256:sha('初始攻速时长差异核算.json')}));
