import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const here=path.dirname(fileURLToPath(import.meta.url)),sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),read=file=>JSON.parse(fs.readFileSync(file));
const [applyDir,independentDir,mathDir]=process.argv.slice(2).map(p=>path.resolve(p));for(const p of [applyDir,independentDir,mathDir])assert(p.startsWith(here+path.sep),'只能读取本批报告');
const candidate=read(here+'/最终候选.json'),plan=read(here+'/最终写前计划.json'),marker=read(here+'/当前实录状态.json'),apply=read(applyDir+'/执行结果.json'),independent=read(independentDir+'/执行结果.json'),snapshot=read(independentDir+'/写前组件现值.json'),protection=read(independentDir+'/写前保护.json'),original=read(here+'/写前现值.json'),media=read(here+'/关联与图片保护快照.json'),math=read(mathDir+'/实际读取.json'),numbers=read(mathDir+'/独立数学结果.json'),writes=read(applyDir+'/实际写入结果.json');
assert.equal(sha(here+'/最终候选.json'),'373595ebf5ec8f385e813972b8b6a013af64a0228c89ff3b4c870fea23e677d9');assert.equal(sha(here+'/最终写前计划.json'),'efbe71e316fdf71b7ee2250a9357a906501072abe0fd94a9e7a9fe6d95da7382');assert(marker.apiWritesComplete&&marker.validationComplete);assert(apply.success&&apply.final.pass&&apply.apiWrites===189&&writes.postCount===189&&writes.confirmed===189);assert.equal(writes.failedSkills.length,0);assert(independent.success&&independent.apiWrites===0&&independent.independentReadback.complete);assert.equal(snapshot.details.length,213);assert.equal(snapshot.missing.length,0);assert.equal(snapshot.conflicts.length,0);assert(math.success&&math.requests.length===188&&numbers.failures.length===0);
assert.equal(sha(here+'/完整候选.json'),'c65e0a8866d7658a4646241d6a96f94da3f1ad75496914e23cfdd61c3ec86e24');assert.equal(sha(here+'/冻结候选锁.json'),'c24ce856e120ec139547661633ab0a4394861ab6c0b47012438901846d80614a');
const strip=o=>Object.fromEntries(Object.entries(o).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k))),ids={parameters:'parameterKey',formulas:'formulaKey',effects:'effectKey',processes:'processKey',internalStates:'stateKey',triggerRules:'ruleKey'};
let preserved=0,leafFields=0;const leaves=x=>x&&typeof x==='object'?Array.isArray(x)?x.reduce((n,v)=>n+leaves(v),0):Object.values(x).reduce((n,v)=>n+leaves(v),0):1;
for(const d of snapshot.details){assert.equal(d.status,200);const wanted=candidate.skills[d.skillKey].write[d.kind].find(x=>x[ids[d.kind]]===d.id);assert.deepEqual(strip(d.data),wanted,d.skillKey+'/'+d.id);leafFields+=leaves(wanted);const old=original.skills[d.skillKey].components[d.kind].details.find(x=>x.key===d.id);if(old){assert.deepEqual(d.data,old.detail.data);preserved++;}}
assert.equal(preserved,24);
for(const[skillKey,s]of Object.entries(original.skills))assert.deepEqual(protection.subjects[skillKey].data,s.subject.data);
for(const r of media.requests){let actual;if(r.route.startsWith('/characters/'))actual=protection.characters[r.route.split('champion_')[1]];else if(r.route.startsWith('/character-skill-relations'))actual=protection.relations[r.route.split('champion_')[1]];else actual=protection.images[r.route.split('/')[2]];assert.equal(actual.status,200);assert.deepEqual(actual.data,r.data);}
for(const[name,old]of Object.entries(original.catalogs)){const oldItems=old.data.items??old.data,items=protection.catalogs[name].data.items??protection.catalogs[name].data,key=({attributes:'attributeKey','modifier-zones':'modifierZoneKey','damage-types':'damageTypeKey',statuses:'statusKey'})[name];for(const row of oldItems)assert.deepEqual(items.find(v=>v[key]===row[key]),row);}
const confirmed=writes.events.filter(e=>e.action==='创建后独立回读确认');assert.equal(confirmed.length,189);assert(confirmed.every(e=>e.match&&e.readbackStatus===200&&e.postStatus===201));const writtenCounts=Object.fromEntries(['parameters','formulas','effects'].map(k=>[k,confirmed.filter(e=>e.kind===k).length]));assert.deepEqual(writtenCounts,{parameters:130,formulas:34,effects:25});
const formulaKeys=new Set(snapshot.details.filter(d=>d.kind==='formulas').map(d=>d.skillKey+'/'+d.id)),tested=new Set(numbers.manualCases.map(c=>c.skillKey+'/'+c.formulaKey));assert.equal(formulaKeys.size,34);for(const k of formulaKeys)assert(tested.has(k),'缺实际公式算例 '+k);
// 无认证的安全负向检查：完成锁应在任何HTTP之前拒绝，不会进入实际请求。
const env={...process.env};delete env.HERO14_API_TOKEN;const dirsBefore=fs.readdirSync(here+'/执行记录').sort(),guard=spawnSync(process.execPath,[here+'/实际录入.mjs','--apply'],{env,encoding:'utf8',windowsHide:true});assert.notEqual(guard.status,0);assert(guard.stderr.includes('补录已完成；禁止重放--apply'));assert.deepEqual(fs.readdirSync(here+'/执行记录').sort(),dirsBefore);fs.writeFileSync(here+'/完成锁核对.json',JSON.stringify({at:new Date().toISOString(),passed:true,authenticationProvided:false,HTTPCalls:0,businessWrites:0,noNewExecutionDirectory:true,expectedError:'补录已完成；禁止重放--apply'},null,2)+'\n',{flag:'wx'});
const summary={at:new Date().toISOString(),success:true,candidateSha256:sha(here+'/最终候选.json'),writePlanSha256:sha(here+'/最终写前计划.json'),actualPostCount:189,writtenCounts,reusedFullParameters:24,totalComposition:213,allPost201:true,allWriteAfterGET200:true,independentFullRead:{runId:independent.runId,HTTPMethods:independent.calls.methods,actualGETs:independent.calls.total,detailObjects:213,businessLeafFields:leafFields,conflicts:0,missing:0,allProtectedOriginalsUnchanged:true},independentActualMath:{actualGETs:188,parameters:154,formulas:34,sourceCases:numbers.sourceCases.length,manualCases:numbers.manualCases.length,checks:numbers.checks,failures:0},applyHTTP:apply.calls,guards:{finalCandidateFrozen:true,oldCandidateAndLockPreserved:true,completedApplyRejectedBeforeHTTP:true},experience:['接口按25个独立效果保存；没有伤害结果、过程或自动触发。','凯南E初始攻速固定4秒，延长总时长公式未绑定为剩余时间；未知等级/属性/充能及其他资格仍未补默认值。','四角色主体、20技能主体、20技能代表图、4挂载列表、原24完整参数及原字典行均保护。','本次写入结果全部201并逐GET确认；没有重试或重放未知写。'],scope:'本批实际确定组成录入与独立API/数学验收；不含浏览器或完整战斗运行。',evidence:{applyDirectory:applyDir,applyReportSha256:sha(applyDir+'/执行结果.json'),independentDirectory:independentDir,independentReportSha256:sha(independentDir+'/执行结果.json'),fullSnapshotSha256:sha(independentDir+'/写前组件现值.json'),mathDirectory:mathDir,mathReportSha256:sha(mathDir+'/实际读取.json'),mathResultsSha256:sha(mathDir+'/独立数学结果.json'),guardSha256:sha(here+'/完成锁核对.json')}};
fs.writeFileSync(here+'/最终实录结果.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});fs.writeFileSync(here+'/当前实录状态.json',JSON.stringify({...marker,independentReadComplete:true,independentMathComplete:true,finalReportSha256:sha(here+'/最终实录结果.json')},null,2)+'\n');console.log(JSON.stringify({success:true,post:189,reused:24,fullGETs:summary.independentFullRead.actualGETs,mathGETs:188,formulaCount:34,finalReportSha256:sha(here+'/最终实录结果.json')}));
