import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
assert.deepEqual(process.argv.slice(2),['--browser-verified']);
const d='C:/project/damage_web_dev/.agents/artifacts/hero30-luna-candidate',calls=[],cases=[],p={},f={};assert.equal(JSON.parse(fs.readFileSync(d+'/实际写入锁.json')).status,'COMPLETED');
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer local-entry'},signal:AbortSignal.timeout(30000)});assert.equal(r.status,200,route);const data=await r.json();calls.push({route,status:200,data});return data;}
for(const k of ['yasuo_q','yone_w','yone_e']){await get('/skills/'+k);assert((await get('/skills/'+k+'/representative-image')).image);p[k]=await get('/skills/'+k+'/parameters');}
for(const[k,keys]of Object.entries({yasuo_q:['physical_damage','critical_physical_damage'],yone_w:['physical_damage','magic_damage','shield_value','first_champion_shield_value'],yone_e:['return_additional_damage']}))for(const key of keys)f[k+'/'+key]=await get('/skills/'+k+'/formulas/'+key);
const ys=await get('/skills/yasuo_p/effects/self_shield'),yw=await get('/skills/yone_w/effects/first_champion_self_shield');
function val(k,key,l,runtime){const x=p[k].find(x=>x.parameterKey===key);assert(x,key);let v;if(x.valueMode==='FIXED')v=x.fixedValue;else if(x.valueMode==='SKILL_LEVEL')v=x.levelValues?.[l];else if(x.valueMode==='RUNTIME_INPUT'){assert.equal(x.fixedValue,null);assert.equal(x.levelValues,null);v=runtime[key];}else throw Error('未处理参数模式');assert(Number.isFinite(v),'缺值 '+key);if(x.valueType==='INTEGER')assert(Number.isInteger(v));return v;}
function ev(n,k,l,attrs,runtime){if(n.nodeType==='PARAMETER')return val(k,n.parameterKey,l,runtime);if(n.nodeType==='ATTRIBUTE'){const v=attrs[n.attributeOwner+'/'+n.attributeKey+'/'+n.attributeValueKind];assert(Number.isFinite(v));return v;}assert(n.nodeType==='OPERATION'&&n.operands.length===2);const[a,b]=n.operands.map(x=>ev(x,k,l,attrs,runtime));assert(['ADD','MULTIPLY'].includes(n.operation));return n.operation==='ADD'?a+b:a*b;}
function check(k,key,l,attrs,runtime,expected){const actual=ev(f[k+'/'+key].expression,k,l,attrs,runtime);assert(Math.abs(actual-expected)<1e-8,`${key}: ${actual} != ${expected}`);cases.push({skillKey:k,formulaKey:key,skillLevel:l,attrs,runtime,actual,expected,passed:true});}
for(const[l,ad,crit,plain,critical]of [[1,80,1.75,104,167],[5,260,2.25,393,734.25]]){const attrs={'SOURCE/attack_damage/TOTAL':ad},runtime={actual_critical_damage_ratio:crit};check('yasuo_q','physical_damage',l,attrs,runtime,plain);check('yasuo_q','critical_physical_damage',l,attrs,runtime,critical);}
for(const[l,hp,bad,base,half,shield,double]of [[1,1800,35,45,77,67.75,135.5],[5,4200,180,85,277,202,404]]){const attrs={'TARGET/hp/TOTAL':hp,'SOURCE/attack_damage/BONUS':bad},runtime={shield_level_base_value:base};check('yone_w','physical_damage',l,attrs,runtime,half);check('yone_w','magic_damage',l,attrs,runtime,half);check('yone_w','shield_value',l,attrs,runtime,shield);check('yone_w','first_champion_shield_value',l,attrs,runtime,double);}
for(const[l,stored,expected]of [[1,300,75],[5,1200,420]])check('yone_e','return_additional_damage',l,{}, {return_damage_stored:stored},expected);
assert.equal(val('yone_w','shield_duration_ms',1,{}),1500);assert.equal(val('yone_e','return_duration_ms',1,{}),5000);assert.equal(val('yone_e','movement_speed_start_ratio',1,{}),.1);assert.equal(val('yone_e','movement_speed_end_ratio',1,{}),.3);assert.equal(val('yasuo_q','stack_threshold',1,{}),2);
assert(p.yone_e.find(x=>x.parameterKey==='return_damage_stored').description.includes('攻击与技能'));for(const e of [ys,yw]){assert.equal(e.results[0].resultType,'NORMAL_SHIELD');assert.equal(e.results[0].target,'SOURCE');assert.equal(e.lifecycle.durationValue.parameterKey,'shield_duration_ms');}assert.equal(yw.results[0].valueRule.value.formulaKey,'first_champion_shield_value');
assert.equal(calls.length,18);assert.equal(cases.length,14);
fs.writeFileSync(d+'/页面验收.json',JSON.stringify({at:new Date().toISOString(),passed:true,browser:'Codex内置浏览器既有tab2，实际查询并打开参数和公式详情，http://127.0.0.1:5173/#/skills',representativePages:3,observations:[{skillKey:'yasuo_q',ui:'20/45/70/95/120基础值，暴击倍率只乘1.05总攻击力项，倍率计算时传入。'},{skillKey:'yone_w',ui:'物理和魔法两半；完整护盾包含0.65额外攻击力，首个敌方英雄使完整护盾翻倍，持续1500毫秒。'},{skillKey:'yone_e',ui:'5秒灵体窗口；存储值限定对英雄的攻击及技能实际伤害，乘25%至35%，初始10%和最高30%移速分别记录。'}],GETs:18,mathCases:14,calls,cases,apiWrites:0,runtimeValidation:'未执行',scriptSha256:crypto.createHash('sha256').update(fs.readFileSync(new URL(import.meta.url))).digest('hex')},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,GETs:18,mathCases:14,pages:3}));
