import fs from 'node:fs';
import path from 'node:path';
if (!process.argv.includes('--apply')) throw new Error('只在明确执行本地录入时追加 --apply；先核对候选、目标与实录记录。');
const BASE='http://127.0.0.1:8080/api/admin/games/lol';
const HEADERS={Authorization:'Bearer local-entry',Accept:'application/json','Content-Type':'application/json'};
const ROOT='C:/project/damage_viewer_project_planning/数据参考/全量录入-2026-09';
const CANDIDATE=path.join(ROOT,'装备效果候选/装备效果候选.json');
const OUT=path.join(ROOT,'API实录/装备');
const candidates=JSON.parse(fs.readFileSync(CANDIDATE,'utf8')).items;
const target=process.argv[2]??'item_3107';
const all=process.argv[3]==='--all';
async function api(p,opts={}){const r=await fetch(BASE+p,{...opts,headers:{...HEADERS,...(opts.headers||{})}});const t=await r.text();let body=null;try{body=t?JSON.parse(t):null}catch{body=t}return {status:r.status,body};}
function keyOf(c){return c.itemId==='1056'?'duolanjie':c.equipmentKey;}
function descOf(c){return `来源：官方16.17.1装备${c.itemId}。 原始说明：${c.sourceDescriptionText} 被动与主动效果尚待配置。`;}
function planned(c){const x={};for(const a of (c.directAttributes??[])){if(a.suggestedAttributeKey && a.valueForFractionConvention!==null && a.valueForFractionConvention!==undefined)x[a.suggestedAttributeKey]=a.valueForFractionConvention;}return x;}
function eq(a,b){const norm=x=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,norm(x[k])])):x;return JSON.stringify(norm(a))===JSON.stringify(norm(b))}
async function processOne(c, catalog){const key=keyOf(c), plannedAttrs=planned(c), ev={itemId:c.itemId,equipmentKey:key,name:c.name,plannedDirectAttributes:plannedAttrs,sourceVersion:c.sourceVersion,sourceDescriptionText:c.sourceDescriptionText,startedAt:new Date().toISOString()};
const missing=Object.keys(plannedAttrs).filter(k=>!catalog.has(k)); if(missing.length){ev.status='blocked_attribute_catalog';ev.missingAttributeKeys=missing;fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;}
let g=await api(`/equipment/${encodeURIComponent(key)}`); if(g.status===404){const p=await api('/equipment',{method:'POST',body:JSON.stringify({equipmentKey:key,name:c.name,description:descOf(c)})});ev.createStatus=p.status; if(p.status===201||p.status===200){ev.action='created';g=await api(`/equipment/${encodeURIComponent(key)}`);}else if(p.status===409){ev.createConflict=true;g=await api(`/equipment/${encodeURIComponent(key)}`);}else{ev.status='create_failed';ev.error=p.body;fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;}}else if(g.status===200){ev.action='reused';}else{ev.status='equipment_get_failed';ev.error=g.body;fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;}
const eqBody=g.body;ev.actualEquipment={equipmentKey:eqBody?.equipmentKey,name:eqBody?.name,description:eqBody?.description}; if(eqBody?.name!==c.name||eqBody?.description!==descOf(c)){ev.planDifference={expected:{name:c.name,description:descOf(c)},actual:{name:eqBody?.name,description:eqBody?.description}};}
let a=await api(`/equipment/${encodeURIComponent(key)}/attributes`); if(a.status!==200){ev.status='attributes_get_failed';ev.error=a.body;fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;} const before=a.body?.attributeValues??{};ev.beforeAttributeValues=before;const conflicts=Object.entries(plannedAttrs).filter(([k,v])=>Object.hasOwn(before,k)&&before[k]!==v); if(conflicts.length){ev.status="source_value_conflict";ev.conflicts=conflicts.map(([k,v])=>({attributeKey:k,before:before[k],planned:v}));fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;} const merged={...before,...plannedAttrs};ev.expectedAttributeValues=merged; if(!eq(before,merged)){const u=await api(`/equipment/${encodeURIComponent(key)}/attributes`,{method:'PUT',body:JSON.stringify({attributeValues:merged})});ev.attributePutStatus=u.status;if(u.status!==200){ev.status='attributes_put_failed';ev.error=u.body;fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;}}else ev.attributePutStatus='not_needed';
const rb=await api(`/equipment/${encodeURIComponent(key)}/attributes`);ev.readbackStatus=rb.status;ev.readbackAttributeValues=rb.body?.attributeValues??null;ev.readbackMatches=rb.status===200&&eq(ev.readbackAttributeValues,merged);ev.status=ev.readbackMatches?'completed':'readback_mismatch';ev.completedAt=new Date().toISOString();fs.writeFileSync(path.join(OUT,`item_${c.itemId}.json`),JSON.stringify(ev,null,2));return ev;}
const catRes=await api('/attributes');if(catRes.status!==200)throw new Error('attribute catalog '+catRes.status);const catalog=new Set((catRes.body?.items??[]).map(x=>x.attributeKey));const listRes=await api('/equipment');if(listRes.status!==200)throw new Error('equipment list '+listRes.status);
const todo=all?candidates:candidates.filter(c=>keyOf(c)===target);if(!todo.length)throw new Error('target not found '+target);const results=[];for(const c of todo){const e=await processOne(c,catalog);results.push(e);console.log(JSON.stringify({itemId:c.itemId,key:keyOf(c),status:e.status,action:e.action,attrs:Object.keys(e.plannedDirectAttributes??{}).length,readbackMatches:e.readbackMatches}));}
const summaryPath=path.join(OUT,all?'summary.json':`summary-${target}.json`);fs.writeFileSync(summaryPath,JSON.stringify({generatedAt:new Date().toISOString(),count:results.length,results},null,2));
