import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDeepStrictEqual } from 'node:util';
import { expectedCurrent, targetConfigs } from './批次配置.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const baseUrl = (process.env.DAMAGE_API_BASE_URL || 'http://127.0.0.1:8080/api/admin/games/lol').replace(/\/+$/, '');
const token = String(process.env.DAMAGE_ENTRY_TOKEN || '').trim();
if (!token) throw new Error('缺少非空 DAMAGE_ENTRY_TOKEN；独立回读只发送 GET。');
const reportPath = path.join(here, '09-独立GET回读.json');
if (fs.existsSync(reportPath)) throw new Error('已存在09-独立GET回读.json，拒绝覆盖。');

const componentKinds = [['parameters', 'parameterKey'], ['formulas', 'formulaKey'], ['effects', 'effectKey'], ['processes', 'processKey'], ['internal-states', 'stateKey'], ['trigger-rules', 'ruleKey']];
const sha256 = (bytes) => crypto.createHash('sha256').update(bytes).digest('hex');
const stable = (value) => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])) : value;
const shaValue = (value) => sha256(Buffer.from(JSON.stringify(stable(value)), 'utf8'));
const readJson = (name) => JSON.parse(fs.readFileSync(path.join(here, name), 'utf8'));
const fileSha = (name) => sha256(fs.readFileSync(path.join(here, name)));
const equal = (actual, expected) => isDeepStrictEqual(stable(actual), stable(expected));
const normalizeStoredRule = (value) => {
  const normalized = structuredClone(value);
  if (normalized?.eventSource?.eventType === 'SKILL_HIT'
    && normalized.eventSource.detail?.useKind === null) {
    delete normalized.eventSource.detail.useKind;
  }
  return normalized;
};
const assertCondition = (condition, message) => assert.equal(Boolean(condition), true, message);
const ruleId = (skillKey, ruleKey) => skillKey + '/' + ruleKey;
const report = { schemaVersion: 2, revision: 'rev4', startedAt: new Date().toISOString(), status: 'RUNNING', methodPolicy: 'GET_ONLY', authorizationValueRecorded: false, businessWrites: 0, getCount: 0, methods: { GET: 0 }, targets: [], global: null, error: null };
const save = () => fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n', 'utf8');
const requireStatus = (response, expected, context) => { assert.equal(response.status, expected, context + ' 预期' + expected + '，实际' + response.status); return response; };
const arrayData = (response, context) => { requireStatus(response, 200, context); if (Array.isArray(response.data)) return response.data; if (Array.isArray(response.data?.items)) return response.data.items; throw new Error(context + ' 没有数组结果'); };
const sortedUnique = (values, context) => { assertCondition(values.every((value) => typeof value === 'string' && value.length > 0), context + ' 存在空键'); const sorted = [...values].sort(); assert.equal(new Set(sorted).size, sorted.length, context + ' 存在重复键'); return sorted; };
async function get(route) { report.getCount += 1; report.methods.GET += 1; const response = await fetch(baseUrl + route, { method: 'GET', headers: { Authorization: 'Bearer ' + token, Accept: 'application/json' }, signal: AbortSignal.timeout(30_000) }); const raw = await response.text(); let data = null; if (raw) { try { data = JSON.parse(raw); } catch { data = { parseError: true, responseBytes: Buffer.byteLength(raw) }; } } return { method: 'GET', route, status: response.status, data }; }
async function getMany(routes, concurrency = 24) { const result = new Array(routes.length); let cursor = 0; async function worker() { while (true) { const index = cursor++; if (index >= routes.length) return; result[index] = await get(routes[index]); } } await Promise.all(Array.from({ length: Math.min(concurrency, routes.length || 1) }, () => worker())); return result; }
function targetRoutes(config) { const skill = '/skills/' + encodeURIComponent(config.skillKey); const owner = config.ownerKind === 'equipment' ? '/equipment/' + encodeURIComponent(config.ownerKey) : '/characters/' + encodeURIComponent(config.ownerKey); const relation = config.ownerKind === 'equipment' ? 'equipment-skill-relations' : 'character-skill-relations'; const ownerKeyName = config.ownerKind === 'equipment' ? 'equipmentKey' : 'characterKey'; return { skill, owner, ownerKeyName, static: { subject: skill, owner, ownerAttributes: owner + '/attributes', ownerRepresentativeImage: owner + '/representative-image', relation: '/' + relation + '?' + ownerKeyName + '=' + encodeURIComponent(config.ownerKey), relationFiltered: '/' + relation + '?skillKey=' + encodeURIComponent(config.skillKey), skillRepresentativeImage: skill + '/representative-image' } }; }
async function readTarget(config) {
  const info = targetRoutes(config); const staticResponses = {}; for (const [key, route] of Object.entries(info.static)) staticResponses[key] = requireStatus(await get(route), 200, config.name + ' ' + route);
  assert.equal(staticResponses.subject.data?.skillKey, config.skillKey, config.name + ' 技能主体键不符'); assert.equal(staticResponses.owner.data?.[info.ownerKeyName], config.ownerKey, config.name + ' 所有者主体键不符'); const match = (item) => item.skillKey === config.skillKey && item[info.ownerKeyName] === config.ownerKey; assertCondition(arrayData(staticResponses.relation, config.name + ' 全量关系').some(match), config.name + ' 全量关系缺少目标'); assertCondition(arrayData(staticResponses.relationFiltered, config.name + ' 反向关系').some(match), config.name + ' 反向关系缺少目标');
  for (const key of ['ownerRepresentativeImage', 'skillRepresentativeImage']) { const image = staticResponses[key].data?.image; assertCondition(image?.enabled === true && typeof image.imageKey === 'string' && image.imageKey.length > 0, config.name + ' 图片不可用'); }
  const components = {}; for (const [apiName, keyName] of componentKinds) { const listRoute = info.skill + '/' + apiName; const list = await get(listRoute); const items = arrayData(list, config.name + ' ' + listRoute); const keys = sortedUnique(items.map((item) => item[keyName]), config.name + ' ' + listRoute); const details = await getMany(keys.map((key) => listRoute + '/' + encodeURIComponent(key))); details.forEach((response, index) => requireStatus(response, 200, config.name + ' 组成详情 ' + keys[index])); components[apiName] = { list, items, keys, details: details.map((response, index) => ({ key: keys[index], response })) }; }
  const candidateRoute = info.skill + '/trigger-rules/' + encodeURIComponent(config.ruleKey); const candidateDetail = requireStatus(await get(candidateRoute), 200, config.name + ' 新规则详情');
  for (const check of config.effectChecks) {
    const effect = components.effects.details.find(({ key }) => key === check.effectKey)?.response.data;
    assertCondition(effect, config.name + ' 缺少效果：' + check.effectKey);
    const result = effect.results?.find((item) => item.resultKey === check.resultKey);
    assertCondition(result, config.name + ' 缺少结果：' + check.resultKey);
    assert.equal(result.target, check.resultTarget, config.name + ' 结果目标不符：' + check.effectKey);
    assert.equal(result.valueRule?.value?.kind, check.valueKind, config.name + ' 结果取值种类不符：' + check.effectKey);
    const actualValueKey = check.valueKind === 'FORMULA' ? result.valueRule?.value?.formulaKey : result.valueRule?.value?.parameterKey;
    assert.equal(actualValueKey, check.valueKey, config.name + ' 结果取值键不符：' + check.effectKey);
    if (check.valueKind === 'FORMULA') assertCondition(components.formulas.keys.includes(check.valueKey), config.name + ' 缺少公式：' + check.valueKey);
    if (check.valueKind === 'PARAMETER') assertCondition(components.parameters.keys.includes(check.valueKey), config.name + ' 缺少参数：' + check.valueKey);
    if (check.durationParameterKey) assert.deepEqual(effect.lifecycle?.durationValue, { kind: 'PARAMETER', parameterKey: check.durationParameterKey }, config.name + ' 持续时间不符：' + check.effectKey);
    if (check.absorbedDamageTypeKey) assert.equal(result.detail?.absorbedDamageTypeKey, check.absorbedDamageTypeKey, config.name + ' 护盾吸收类型不符：' + check.effectKey);
  }
  return { id: config.id, skillKey: config.skillKey, ownerKey: config.ownerKey, candidateRuleKey: config.ruleKey, staticResponses, components, candidateDetail, nonRule: { static: Object.fromEntries(Object.entries(staticResponses).map(([key, response]) => [key, response.data])), components: Object.fromEntries(componentKinds.filter(([apiName]) => apiName !== 'trigger-rules').map(([apiName]) => [apiName, { list: components[apiName].list.data, details: components[apiName].details.map(({ key, response }) => ({ key, data: response.data })) }])) } };
}
async function scanRules() { const skillsResponse = await get('/skills'); const skills = arrayData(skillsResponse, '最终全技能目录'); const skillKeys = sortedUnique(skills.map((skill) => skill.skillKey), '最终全技能目录'); assert.equal(skillKeys.length, expectedCurrent.skillCount, '最终技能数不是1062'); const listsResponses = await getMany(skillKeys.map((skillKey) => '/skills/' + encodeURIComponent(skillKey) + '/trigger-rules')); const lists = listsResponses.map((response, index) => { const rules = arrayData(response, '最终规则列表 ' + skillKeys[index]); const ruleKeys = sortedUnique(rules.map((rule) => rule.ruleKey), '最终规则列表 ' + skillKeys[index]); return { skillKey: skillKeys[index], response, rules, ruleKeys }; }); const refs = lists.flatMap(({ skillKey, ruleKeys }) => ruleKeys.map((ruleKey) => ({ skillKey, ruleKey }))).sort((left, right) => ruleId(left.skillKey, left.ruleKey).localeCompare(ruleId(right.skillKey, right.ruleKey))); const detailsResponses = await getMany(refs.map(({ skillKey, ruleKey }) => '/skills/' + encodeURIComponent(skillKey) + '/trigger-rules/' + encodeURIComponent(ruleKey))); detailsResponses.forEach((response, index) => requireStatus(response, 200, '最终规则详情 ' + ruleId(refs[index].skillKey, refs[index].ruleKey))); const details = detailsResponses.map((response, index) => ({ ...refs[index], response })); const eventTypeCounts = details.reduce((counts, item) => { const eventType = item.response.data?.eventSource?.eventType; if (eventType) counts[eventType] = (counts[eventType] || 0) + 1; return counts; }, {}); return { skillsResponse, skills, skillKeys, lists, refs, details, eventTypeCounts, ruleCount: refs.length }; }
const oldRuleDetails = () => baseline.preservation?.existingRuleDetails || baseline.globalBaseline?.first?.ruleDetails || [];
const oldRuleLists = () => baseline.preservation?.existingRuleLists || baseline.globalBaseline?.first?.ruleLists || [];
function compareOld(scan) { const oldDetails = oldRuleDetails(); assert.equal(oldDetails.length, expectedCurrent.ruleCount, '旧规则详情不是104条'); const oldMap = new Map(oldDetails.map((item) => [ruleId(item.skillKey, item.ruleKey), item.response?.data])); const currentOldIds = scan.refs.map((item) => ruleId(item.skillKey, item.ruleKey)).filter((id) => oldMap.has(id)).sort(); assert.deepEqual(currentOldIds, [...oldMap.keys()].sort(), '旧104条规则键集合变化'); for (const item of scan.details) { const id = ruleId(item.skillKey, item.ruleKey); if (oldMap.has(id)) assert.equal(equal(item.response.data, oldMap.get(id)), true, '旧规则详情变化：' + id); } const expectedBySkill = new Map(oldRuleLists().map((item) => [item.skillKey, item])); for (const list of scan.lists) { const expected = expectedBySkill.get(list.skillKey); assertCondition(expected, '旧规则列表缺少技能：' + list.skillKey); const currentOld = list.rules.filter((item) => oldMap.has(ruleId(list.skillKey, item.ruleKey))); const expectedOld = expected.rules.filter((item) => oldMap.has(ruleId(expected.skillKey, item.ruleKey))); assert.equal(equal(currentOld, expectedOld), true, '旧规则列表摘要变化：' + list.skillKey); } }

const frozen = readJson('02-合并冻结请求.json');
const baseline = readJson('04-共享写前现值.json');
try {
  assert.equal(frozen.revision, 'rev4', '冻结请求不是rev4'); assert.equal(frozen.requests?.length, targetConfigs.length, '冻结请求数量不符'); assert.equal(baseline.status, 'CAPTURED', '写前现值尚未取得'); assert.equal(baseline.revision, 'rev4', '写前现值不是rev4'); assert.equal(baseline.semanticReviewSha256, fileSha('00-独立语义评审.json'), '独立语义评审散列不符'); assert.equal(baseline.sourceSnapshotSha256, fileSha('03-来源散列快照.json'), '来源快照散列不符'); assert.equal(baseline.frozenRequestSha256, fileSha('02-合并冻结请求.json'), '冻结请求散列不符'); assert.equal(baseline.businessWrites, 0, '写前现值包含业务写入'); assert.deepEqual(baseline.expectedCurrent, expectedCurrent, '写前基线计数不符'); assert.equal(oldRuleDetails().length, expectedCurrent.ruleCount, '写前未保存旧104条详情'); assert.equal(oldRuleLists().length, expectedCurrent.skillCount, '写前未保存1062个规则列表');
  const targets = []; for (const config of targetConfigs) targets.push(await readTarget(config)); const expectedSnapshots = baseline.preservation?.targetNonRuleSnapshots || {}; for (const target of targets) { assertCondition(expectedSnapshots[target.id], '缺少目标非规则基线：' + target.id); assert.equal(equal(target.nonRule, expectedSnapshots[target.id]), true, '非规则组成变化：' + target.id); const entry = frozen.requests.find((item) => item.id === target.id); assertCondition(entry, '冻结请求缺少目标：' + target.id); assert.equal(entry.bodySha256, shaValue(entry.body), '冻结请求体散列不符：' + target.id); assert.equal(target.candidateDetail.status, 200, '新增规则详情不是200：' + target.id); assert.equal(equal(normalizeStoredRule(target.candidateDetail.data), entry.body), true, '新增规则详情与冻结请求不符：' + target.id); report.targets.push({ id: target.id, skillKey: target.skillKey, candidateDetailStatus: target.candidateDetail.status, candidateBodySha256: shaValue(normalizeStoredRule(target.candidateDetail.data)), frozenBodySha256: entry.bodySha256, normalizedStoredSkillHitUseKindNull: target.candidateDetail.data?.eventSource?.eventType === 'SKILL_HIT' && target.candidateDetail.data?.eventSource?.detail?.useKind === null, nonRuleSnapshotSha256: shaValue(target.nonRule) }); }
  const finalScan = await scanRules(); assert.equal(finalScan.ruleCount, expectedCurrent.finalRuleCount, '最终规则总数不符'); assert.equal(finalScan.eventTypeCounts.SOURCE_INITIALIZED || 0, expectedCurrent.sourceInitializedCount, '最终SOURCE_INITIALIZED不是24'); compareOld(finalScan); const oldMap = new Map(oldRuleDetails().map((item) => [ruleId(item.skillKey, item.ruleKey), item.response?.data])); const expectedIds = [...oldMap.keys(), ...frozen.requests.map((entry) => ruleId(entry.skillKey, entry.ruleKey))].sort(); const actualIds = finalScan.refs.map((item) => ruleId(item.skillKey, item.ruleKey)).sort(); assert.deepEqual(actualIds, expectedIds, '最终规则集合不是旧规则加本批新增规则'); for (const entry of frozen.requests) { const actual = finalScan.details.find((item) => item.skillKey === entry.skillKey && item.ruleKey === entry.ruleKey); assertCondition(actual, '缺少新增规则：' + entry.id); assert.equal(entry.bodySha256, shaValue(entry.body), '终审bodySha256不符：' + entry.id); assert.equal(equal(normalizeStoredRule(actual.response.data), entry.body), true, '新增规则最终回读不符：' + entry.id); }
  report.global = { skillCount: finalScan.skillKeys.length, ruleCount: finalScan.ruleCount, sourceInitializedCount: finalScan.eventTypeCounts.SOURCE_INITIALIZED || 0, eventTypeCounts: finalScan.eventTypeCounts, ruleKeysSha256: shaValue(finalScan.refs), oldRuleDetailsExact: true, newRulesExact: true }; report.status = 'PASS'; report.completedAt = new Date().toISOString(); save(); process.stdout.write(JSON.stringify({ status: report.status, revision: report.revision, getCount: report.getCount, methods: report.methods, businessWrites: report.businessWrites, skillCount: report.global.skillCount, ruleCount: report.global.ruleCount, sourceInitializedCount: report.global.sourceInitializedCount }, null, 2));
} catch (error) { report.status = 'FAILED'; report.completedAt = new Date().toISOString(); report.error = { message: error instanceof Error ? error.message : String(error) }; save(); throw error; }
