import fs from 'node:fs';
import path from 'node:path';
if (!process.argv.includes('--apply')) throw new Error('只在明确执行本地录入时追加 --apply；先核对候选、目标与实录记录。');
const BASE='http://127.0.0.1:8080/api/admin/games/lol';
const H={Authorization:'Bearer local-entry',Accept:'application/json','Content-Type':'application/json'};
const ROOT='C:/project/damage_viewer_project_planning/数据参考/全量录入-2026-09';
const SRC=path.join(ROOT,'英雄/等级属性候选'); const OUT=path.join(ROOT,'API实录/英雄补录');
const names=process.argv[2]==='--all'?['Nidalee','Nilah','Ornn','Pyke','Qiyana','Renekton','Rengar']:[process.argv[2]||'Nidalee'];
const map={hp:'hp',hpregen:'hp_regen',spellblock:'magic_resistance',attackdamage:'attack_damage',movespeed:'move_speed',attackrange:'attack_range',attackspeed:'attack_speed',mp:'mana',mpregen:'mana_regen',armor:'armor'};
async function api(p,o={}){const r=await fetch(BASE+p,{...o,headers:{...H,...(o.headers||{})}});const t=await r.text();let b=null;try{b=t?JSON.parse(t):null}catch{b=t}return {status:r.status,body:b};}
const norm=x=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,norm(x[k])])):x;
const same=(a,b)=>JSON.stringify(norm(a))===JSON.stringify(norm(b));
function load(n){return JSON.parse(fs.readFileSync(path.join(SRC,n+'.json'),'utf8'));}
function desc(c){return `来源：官方16.17.1及客户端补证，角色${c.sourceChampionId}。仅基础属性；技能机制待录。`}
async function one(c,catalog){const key='champion_'+c.sourceChampionId.toLowerCase(),ev={sourceFile:c.sourceChampionId+'.json',characterKey:key,name:c.name,startedAt:new Date().toISOString(),sourceVersion:c.sourceVersion,attributeCounts:{}};
const planned={};for(const a of c.attributes??[]){const k=map[a.sourceAttributeKey];if(!k)continue;if(!catalog.has(k)){ev.status='blocked_attribute_catalog';ev.missingAttributeKeys=[...(ev.missingAttributeKeys||[]),k];continue}planned[k]=a.levelValues;ev.attributeCounts[k]=Object.keys(a.levelValues||{}).length;}
ev.plannedAttributeKeys=Object.keys(planned);if(ev.status==='blocked_attribute_catalog'){fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(ev,null,2));return ev;}
let g=await api('/characters/'+encodeURIComponent(key));if(g.status===404){const p=await api('/characters',{method:'POST',body:JSON.stringify({characterKey:key,name:c.name,description:desc(c)})});ev.createStatus=p.status;if(p.status===201||p.status===200){ev.action='created';g=await api('/characters/'+encodeURIComponent(key));}else if(p.status===409){ev.createConflict=true;g=await api('/characters/'+encodeURIComponent(key));}else{ev.status='create_failed';ev.error=p.body;fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(ev,null,2));return ev;}}else if(g.status===200)ev.action='reused';else{ev.status='character_get_failed';ev.error=g.body;fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(ev,null,2));return ev;}
const body=g.body;ev.actualCharacter={characterKey:body?.characterKey,name:body?.name,description:body?.description};if(body?.name!==c.name||body?.description!==desc(c))ev.planDifference={expected:{name:c.name,description:desc(c)},actual:{name:body?.name,description:body?.description}};
const ar=await api('/characters/'+encodeURIComponent(key)+'/attributes');if(ar.status!==200){ev.status='attributes_get_failed';ev.error=ar.body;fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(ev,null,2));return ev;}const before=ar.body?.levelValues??{};ev.beforeLevelValues=before;
const merged=JSON.parse(JSON.stringify(before)), conflicts=[];for(const [ak,levels] of Object.entries(planned)){for(const [lv,val] of Object.entries(levels)){const cur=merged[lv]?.[ak];if(cur!==undefined&&cur!==val){conflicts.push({attributeKey:ak,level:lv,existing:cur,planned:val});continue}if(!merged[lv])merged[lv]={};if(merged[lv][ak]===undefined)merged[lv][ak]=val;}}
ev.conflicts=conflicts;ev.expectedLevelValues=merged;const changed=!same(before,merged);if(changed&&!conflicts.length){const u=await api('/characters/'+encodeURIComponent(key)+'/attributes',{method:'PUT',body:JSON.stringify({levelValues:merged})});ev.attributePutStatus=u.status;if(u.status!==200){ev.status='attributes_put_failed';ev.error=u.body;fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(ev,null,2));return ev;}}else ev.attributePutStatus=conflicts.length?'skipped_due_conflict':'not_needed';const rb=await api('/characters/'+encodeURIComponent(key)+'/attributes');ev.readbackStatus=rb.status;ev.readbackLevelValues=rb.body?.levelValues??null;ev.readbackMatches=rb.status===200&&same(ev.readbackLevelValues,merged);ev.status=conflicts.length?'source_value_conflict':(ev.readbackMatches?'completed':'readback_mismatch');ev.completedAt=new Date().toISOString();fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(ev,null,2));return ev;}
const cat=await api('/attributes');if(cat.status!==200)throw new Error('attribute catalog '+cat.status);const catalog=new Set((cat.body?.items??[]).map(x=>x.attributeKey));const list=await api('/characters');if(list.status!==200)throw new Error('characters list '+list.status);const all=list.body?.items??[];const nameConflicts=[];for(const n of names){const c=load(n),key='champion_'+c.sourceChampionId.toLowerCase();const sameName=all.filter(x=>x.name===c.name&&x.characterKey!==key);if(sameName.length)nameConflicts.push({source:n,name:c.name,expected:key,actual:sameName.map(x=>x.characterKey)});}if(nameConflicts.length)console.log(JSON.stringify({nameConflicts}));
const results=[];for(const n of names){const e=await one(load(n),catalog);results.push(e);console.log(JSON.stringify({key:e.characterKey,status:e.status,action:e.action,attributes:e.plannedAttributeKeys?.length,levels:e.plannedAttributeKeys?.map(k=>e.attributeCounts[k]),conflicts:e.conflicts?.length??0,readbackMatches:e.readbackMatches}));}
fs.writeFileSync(path.join(OUT,'summary-'+(names.length===1?names[0]:'all')+'.json'),JSON.stringify({generatedAt:new Date().toISOString(),count:results.length,results},null,2));
