import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify,isDeepStrictEqual as equal} from 'node:util';
if(process.argv.includes('--apply'))throw Error('该工具全部只读');
const dir=path.dirname(fileURLToPath(import.meta.url)),candidateFile=dir+'/完整候选.json',candidateBytes=fs.readFileSync(candidateFile),hash=b=>createHash('sha256').update(b).digest('hex'),frozen='247eeb25c0f1c0b5448fabd16512d9c7b2632660fc08f3cd67bac0d9335c5ff0';
if(hash(candidateBytes)!==frozen)throw Error('冻结候选变化');
const snapshotFile=path.resolve(process.argv[2]??'');if(!snapshotFile.startsWith(path.resolve(dir)+path.sep)||!snapshotFile.endsWith('写前组件现值.json'))throw Error('必须使用本批另一次只读全量GET快照');
const snapshot=JSON.parse(fs.readFileSync(snapshotFile)),snapshotResult=JSON.parse(fs.readFileSync(path.join(path.dirname(snapshotFile),'执行结果.json')));if(!snapshotResult.success||snapshotResult.apiWrites!==0||!snapshotResult.independentReadback?.complete||snapshot.conflicts.length||snapshot.missing.length||snapshot.details.length!==202)throw Error('独立GET未确认202组成');
const token=process.env.HERO13_API_TOKEN;if(!token)throw Error('缺少进程环境认证值');
const original=JSON.parse(candidateBytes),actual=structuredClone(original),outDir=dir+'/实值核算记录/'+new Date().toISOString().replace(/[:.]/g,'-');fs.mkdirSync(outDir,{recursive:true});
const omit=o=>Object.fromEntries(Object.entries(o).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)));
for(const [skillKey,s]of Object.entries(actual.skills))for(const kind of Object.keys(s.write))s.write[kind]=snapshot.details.filter(d=>d.skillKey===skillKey&&d.kind===kind).map(d=>omit(d.data));
const report={at:new Date().toISOString(),mode:'另行实际GET全部145参数和37公式，逐字段核对后独立求值；不重用写流水作GET证据',candidateFileSha256:frozen,independentSnapshot:snapshotFile,independentSnapshotSha256:hash(fs.readFileSync(snapshotFile)),requests:[],apiWrites:0};
const save=()=>fs.writeFileSync(outDir+'/实际读取.json',JSON.stringify(report,null,2)+'\n');
for(const[skillKey,s]of Object.entries(actual.skills))for(const[kind,id]of [['parameters','parameterKey'],['formulas','formulaKey']])for(let i=0;i<s.write[kind].length;i++){
 const prior=s.write[kind][i],route='/skills/'+skillKey+'/'+kind+'/'+prior[id];let response;try{const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method:'GET',headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});response={route,method:'GET',status:r.status,data:await r.json()};}catch(e){response={route,method:'GET',status:null,error:e.name};}report.requests.push(response);save();if(response.status!==200||!equal(omit(response.data),prior))throw Error('公式核算前现值漂移或读取失败 '+route);s.write[kind][i]=omit(response.data);
}
report.inputFile=outDir+'/实际核算输入.json';report.resultFile=outDir+'/独立数学结果.json';fs.writeFileSync(report.inputFile,JSON.stringify(actual,null,2)+'\n');
await promisify(execFile)(process.execPath,[dir+'/接口实值核算核心.mjs'],{env:{...process.env,HERO13_ACTUAL_PLAN:report.inputFile,HERO13_ACTUAL_RESULT:report.resultFile},windowsHide:true,maxBuffer:1024*1024});
const math=JSON.parse(fs.readFileSync(report.resultFile));report.math={checks:math.checks,sourceCases:math.sourceCases.length,manualCases:math.manualCases.length,failures:math.failures};report.success=math.failures.length===0&&report.requests.length===182;report.inputSha256=hash(fs.readFileSync(report.inputFile));report.resultSha256=hash(fs.readFileSync(report.resultFile));report.completedAt=new Date().toISOString();save();console.log(JSON.stringify({success:report.success,gets:report.requests.length,math:report.math,outDir,reportSha256:hash(fs.readFileSync(outDir+'/实际读取.json'))}));if(!report.success)process.exitCode=1;
