import {start,datum,fixed,input,calc,sourceOnly} from './计算树候选.mjs';
import {common,literal,formula,pending,exclude,statEffect,effect,result,pn,attr,op,add,mul,val,fval,life,behavior} from './候选.mjs';
function rows(x,list){for(const[source,key,name,scale]of list)datum(x,source,key,name,scale==null?{}:{scale});}
const damageGap=x=>pending(x,'实际伤害资格','仅保存确定公式；实际命中、暴击、吸血、护盾资格及归属未证明，不创建默认DAMAGE、空过程或规则。','来源');
const only=(x,names,reason,kind='来源')=>names.forEach(n=>sourceOnly(x,'DataValues.'+n,reason,kind));
function resourceEffect(x,key,name,resource,amount,operation='RESTORE',description='独立资源数值；真实触发未连接。'){effect(x,key,name,[result('resource',name,'RESOURCE_CHANGE','SOURCE',amount,{attributeKey:resource,operation})],null,description);}
function energyCost(x){const a=x.s.official.cost,b=x.p.manaValues?.values?.slice(0,x.c.maxLevel);if(JSON.stringify(a)!==JSON.stringify(b)||!a.every(v=>v>0))throw Error('能量成本未逐级对应');literal(x,'energy_cost','基础能量消耗',a,'官方英雄资源类型Energy；当前根manaValues仅为通用成本字段名称，不代表本角色用法力。','official.cost + 当前根manaValues + Akali官方partype');resourceEffect(x,'energy_cost','基础能量消耗','energy',val('energy_cost'),'CONSUME','阿卡丽消耗能量；不创建法力消费。');}
{
 const x=start('akali_p');rows(x,[['PassiveAPRatio','ap_ratio','法强系数'],['PassiveBADRatio','bonus_ad_ratio','额外攻击力系数']]);calc(x,'Damage','empowered_attack_damage','潜龙印额外魔法伤害','原等级断点项外供，额外AD与AP明确');calc(x,'PassiveSpeedBonus','ring_move_speed_ratio','当前等级朝圆环移动速度比例','未命名等级函数保留原节点，不以空数组填零');fixed(x,'ring_duration_ms','圆环存在时间（毫秒）',4000,'当前绑定正文明确圆环持续4秒。','keyTooltip');fixed(x,'empowered_range_multiplier','强化攻击距离倍数',2,'当前绑定正文明确下次攻击拥有双倍距离。','keyTooltip');only(x,['Level1MS','MSBonusPerLevelAtAndAfter','MSAdditionalBonusAtThreshold'],'未命名移动速度等级树消费；其中数组缺失不能推为0，只通过无默认实际等级值保留公式。');sourceOnly(x,'mSpellCalculations.EnergyRestore','当前绑定正文未提及被动返还能量；旧节点含省略字段，不复活旧版恢复。');pending(x,'圆环与强化攻击','技能命中英雄、越过圆环、方向与下次攻击消费仍需真实事件；双倍距离涉及当前攻击距离取样，不能无条件常驻。','配置');damageGap(x);
}
{
 const x=start('akali_q');common(x,{mana:false});energyCost(x);rows(x,[['BaseDamageNamed','base_damage','基础魔法伤害'],['tADRatio','total_ad_ratio','总攻击力系数'],['APRatio','ap_ratio','法强系数'],['SlowDuration','slow_duration_ms','减速持续（毫秒）',1000],['SlowPercentage','slow_ratio','减速比例']]);calc(x,'Damage','damage','苦无魔法伤害','当前根总AD系数与法强系数明确');pending(x,'短摘要与当前绑定计算口径不同','当前keySummary和官方简述写额外AD，但当前keyTooltip绑定Damage，其具名tADRatio节点为已证mStat2/默认formula0总AD；候选按这条明确数值链，保留两份原文差异供主审，不能声称全部文字同口径。','来源');only(x,['BonusDamageToMinions'],'只涉及小兵伤害分支，当前敌方英雄不使用。','范围外');sourceOnly(x,'mSpellCalculations.MinionDamage','等级5覆盖的小兵分支不使用。','范围外');pending(x,'减速与命中','减速资格、弧形命中及P触发未连接；施法字段冲突不推零时点。','配置');damageGap(x);
}
{
 const x=start('akali_w');common(x,{mana:false});rows(x,[['MovementSpeed','initial_move_speed_ratio','初始移动速度增益比例',.01],['EnergyRestore','energy_amount','能量上限增加及回复数值'],['BaseDuration','smoke_duration_ms','当前烟幕持续（毫秒）',1000],['MovementSpeedDuration','move_speed_decay_duration_ms','移动速度衰减持续（毫秒）',1000]]);statEffect(x,'smoke_energy_capacity','烟幕期间额外最大能量',val('energy_amount'),'energy',{duration:val('smoke_duration_ms'),description:'当前正文明确烟幕激活期间最大能量增加100；烟幕结束移除，实际中断或延长尚未连接。'});resourceEffect(x,'smoke_energy_restore','烟幕回复能量','energy',val('energy_amount'),'RESTORE','当前绑定keyCost明确回复100能量；与最大能量增加分别保存，真实施放中应用次序、上限裁剪与结束须接线。');only(x,['MaxDuration'],'原最大时长字段未由当前正文消费，不自行增加2秒或猜刷新规则。');only(x,['CloudRadius'],'纯烟幕空间半径，不删除自身能量、移动速度或隐形资格。','范围外');only(x,['CherryBonusHaste'],'竞技场模式数值不进入本轮普通模式。','范围外');sourceOnly(x,'mSpellCalculations.{955fbaa3}','当前正文未绑定的等级树不作为普通模式烟幕效果。');pending(x,'烟幕与隐形资格','隐形影响可选取性，仍是1V1依赖；移动速度在2秒内衰减但函数未证，不生成恒定移速。当前根mDoesNotConsumeCooldown使冷却起点需另接。','配置');
}
{
 const x=start('akali_e');common(x,{mana:false});energyCost(x);rows(x,[['BaseDamage','base_damage','两段共同基础伤害'],['E1PercentageOfTotal','first_damage_ratio','一段比例'],['E2PercentageOfTotal','second_damage_ratio','二段比例'],['TotalADRatio','total_ad_ratio','总AD系数'],['TotalAPRatio','ap_ratio','法强系数']]);calc(x,'E1Damage','first_damage','手里剑一段伤害','共同伤害基础乘0.3');calc(x,'E2DamageCalc','second_damage','二段突进伤害','共同伤害基础乘0.7；只攻击真实已标记敌人');only(x,['SelfKnockbackRange'],'纯自身后空翻距离，标记与二次施放资格仍保留。','范围外');pending(x,'标记与二段施放','第一命中目标或自身烟幕可被标记；烟幕二段不凭空生成敌人伤害。两段不能默认同时命中，二次成本与重施放窗口未证。','配置');damageGap(x);
}
{
 const x=start('akali_r');common(x,{mana:false});rows(x,[['BaseDamage','first_base_damage','第一段基础伤害'],['R2BaseDamage','second_base_damage','第二段最小基础伤害'],['R1ADRatio','first_bonus_ad_ratio','第一段额外AD系数'],['R1APRatio','first_ap_ratio','第一段法强系数'],['R2APRatio','second_ap_ratio','第二段法强系数'],['CooldownBetweenCasts','recast_delay_ms','两段最小间隔（毫秒）',1000]]);calc(x,'Cast1Damage','first_damage','第一段魔法伤害','额外AD与AP缩放');calc(x,'Cast2DamageMin','second_min_damage','第二段最低伤害','当前源最低值');calc(x,'Cast2DamageMax','second_max_damage','第二段最高伤害','当前树明确最低值乘3；中间已损生命函数不猜线性');rows(x,[['MaxExecuteThreshold','max_damage_current_hp_threshold','进入最高伤害的当前生命比例阈值']]);pending(x,'二段生命曲线和严格边界','当前绑定扩展正文明确低于30%生命值造成最大伤害，因此保留当前生命比例0.3及严格低于条件；恰等于30%和中间已损生命曲线未证，不猜线性。','来源');only(x,['DashDistance'],'纯位移距离；二段伤害和最小间隔保留。','范围外');x.c.proofs.push({source:'official.cost',values:x.s.official.cost,semantic:'明确0成本，保留来源，不创建空资源效果。'});damageGap(x);
}
{
 const x=start('kassadin_p');rows(x,[['DamageReductionPercent','magic_damage_reduction_ratio','所受魔法伤害减免比例']]);pending(x,'减伤合并与幽灵状态','10%魔法减伤确定，合法修正区及跨来源合并未证，不借用其他装备减伤区。幽灵状态涉及单位碰撞，当前无空间计算。','配置');exclude(x,'单位碰撞几何','当前幽灵状态只免单位碰撞，独立魔法减伤仍保留。');
}
{
 const x=start('kassadin_q');common(x);rows(x,[['BaseDamage','base_damage','基础魔法伤害'],['ShieldAmount','base_magic_shield','基础魔法护盾'],['ShieldDuration','shield_duration_ms','魔法护盾持续（毫秒）',1000]]);calc(x,'TotalDamage','damage','虚无法球魔法伤害','基础值加0.7法强');calc(x,'TotalShield','magic_shield_amount','魔法护盾数值','基础值加0.3法强');effect(x,'magic_shield','虚无法球自身魔法护盾',[result('shield','魔法护盾','NORMAL_SHIELD','SOURCE',fval('magic_shield_amount'),{absorbedDamageTypeKey:'magic',decayMode:'NONE'},behavior)],life(val('shield_duration_ms')),'当前正文明确自身1.5秒魔法护盾；施放与目标命中、护盾采样时点未自动连接。');pending(x,'引导打断','只打断合法引导，不默认沉默或打断任意技能。','配置');damageGap(x);
}
{
 const x=start('kassadin_w');common(x);rows(x,[['ActiveBaseDamage','active_base_damage','主动强化基础伤害'],['PassiveBaseDamage','passive_base_damage','被动攻击附伤'],['MissingManaRatio','normal_missing_mana_ratio','普通目标已损法力回复比例',.01],['ChampionMissingManaRatio','champion_missing_mana_ratio','英雄目标已损法力回复比例',.01]]);calc(x,'ActiveDamage','active_damage','主动强化攻击伤害','当前主动额外伤害基础+0.8AP，不默认与被动重复叠加');calc(x,'OnHitDamage','passive_damage','被动攻击附伤','当前被动25+0.1AP');for(const type of ['normal','champion']){formula(x,type+'_mana_restore',(type==='normal'?'非英雄':'英雄')+'目标强化攻击回复法力',mul(attr('mana','SOURCE','MISSING'),pn(type+'_missing_mana_ratio')),'当前具名文本明确自身已损法力，比例点先转比例；两种目标资格互斥，非英雄战前恢复保留。');resourceEffect(x,type+'_mana_restore',(type==='normal'?'非英雄':'英雄')+'目标回复法力','mana',fval(type+'_mana_restore'));}pending(x,'主动攻击与被动附伤','真实强化攻击消费、主动被动是否叠加、回复采样时点及目标类型未连接；1法力基础成本有双来源，不擅自改0。','配置');damageGap(x);
}
{
 const x=start('kassadin_e');common(x);rows(x,[['ReductionPerSpellCast','cooldown_reduction_per_cast_ms','附近一次施法减少冷却（毫秒）',1000],['BaseDamage','base_damage','基础魔法伤害'],['APRatio','ap_ratio','法强系数'],['SlowAmount','slow_ratio','减速比例',.01],['SlowDuration','slow_duration_ms','减速持续（毫秒）',1000]]);calc(x,'TotalDamage','damage','能量脉冲伤害','基础加0.7AP');effect(x,'nearby_cast_cooldown_reduction','附近一次实际施法减少E冷却',[result('reduce','减少E冷却','COOLDOWN_CHANGE','SOURCE',val('cooldown_reduction_per_cast_ms'),{operation:'REDUCE',affectedSkillScope:{mode:'SKILLS',skillKeys:['kassadin_e'],skillCategoryKeys:[]}})],null,'每次合法附近技能施放减少750毫秒；己方或敌方来源资格、重施放判定与附近条件尚未连接。');pending(x,'施法来源与减速','附近每次施法不是仅自己施法；减速和实际命中资格独立维护。','配置');damageGap(x);
}
{
 const x=start('kassadin_r');common(x,{mana:false});rows(x,[['RBaseDamage','base_damage','基础魔法伤害'],['StackDamage','per_stack_base_damage','每层额外基础伤害'],['APRatio','ap_ratio','基础法强系数'],['APStackRatio','per_stack_ap_ratio','每层法强系数'],['RStackDuration','stack_duration_ms','连续施放窗口（毫秒）',1000],['MaxStacks','max_stacks','最多额外层数'],['RBaseCost','base_mana_cost','首发法力成本']]);const base=calc(x,'BaseDamage','base_damage_amount','首发魔法伤害','资源节点口径未具名证明，用无默认实际输入保留0.02资源项'),stack=calc(x,'BonusDamage','per_stack_damage','每层额外魔法伤害','同一未知资源口径，显式0.01系数');input(x,'actual_prior_cast_stacks','本次施放前实际连续层数','只接受已确认的整数0至4，不默认满层或0层。','INTEGER');formula(x,'actual_damage','当前层数完整魔法伤害',add(base,mul(pn('actual_prior_cast_stacks'),stack)),'首发基础加每层额外伤害乘真实此前层数；资源口径未知部分必须供值。');for(const n of [0,1,2,3,4])fixed(x,'integer_'+n,'有限层数算术常数'+n,n,'只用于整数0至4翻倍成本的等价二元运算，不是未知输入默认值。','明确翻倍次数和上限的数学展开');const n=pn('actual_prior_cast_stacks'),relu=i=>op('MAX',op('SUBTRACT',n,pn('integer_'+i)),pn('integer_0')),factor=add(pn('integer_1'),n,relu(1),mul(pn('integer_2'),relu(2)),mul(pn('integer_4'),relu(3)));formula(x,'actual_mana_cost','当前实际层数法力成本',mul(pn('base_mana_cost'),factor),'仅整数层数0/1/2/3/4，分别40/80/160/320/640；当前公式不支持幂，用此有限域严格等价展开。非整数或越界不能传入。');resourceEffect(x,'mana_cost','本次虚空行走实际法力消耗','mana',fval('actual_mana_cost'),'CONSUME','消耗动态公式而非固定40；实际层数及15秒窗口更新尚未接线。');only(x,['BaseCD','RManaRatio','RStackManaRatio','RiftWalkBaseDamage'],'基础冷却已有公共参数；RManaRatio等重复字段保留来源，不由数值2/1猜最大法力口径。');only(x,['CastRange'],'纯位移距离；当前单人着陆伤害仍保留。','范围外');pending(x,'连续施放层数与资源口径','法力节点未明确当前/最大值；准确保持输入。层数必须整数0至4，时间窗及成功施放后增层未连接。','配置');damageGap(x);
}
{
 const x=start('ryze_p');rows(x,[['PercentManaIncrease','mana_gain_tooltip_coefficient','源法力增幅显示系数']]);const displayed=calc(x,'PassiveManaCalcTooltip','mana_gain_percentage_points','法力增幅百分比点','当前树为0.01×AP×10，正文再显示百分号');fixed(x,'percent_points_to_ratio','百分比点转比例',.01,'百分比点除100。','当前keyTooltip的百分号');formula(x,'maximum_mana_bonus_ratio','最大法力值增幅比例',mul(displayed,pn('percent_points_to_ratio')),'AP100时显示10%，实际比例0.1；不能把显示10当比例10。属性基数和反馈合并未连接。');only(x,['APAmount'],'当前原树未消费的100字段不额外再除100。');sourceOnly(x,'mSpellCalculations.{92bc0080}','未绑定旧0.05AP计算不替代当前10%/100AP显示链。');pending(x,'额外法力与最大法力反馈','当前P文本具名证明Q/W/E以额外法力缩放；P本身最大法力增幅的基数、自反馈与其他法力来源合并未证，不生成循环增幅效果。','来源');
}
{
 const x=start('ryze_q');common(x);rows(x,[['BaseDamage','base_damage','基础魔法伤害'],['MovementSpeedAmount','two_rune_move_speed_ratio','双符文移动速度比例',.01],['MovementSpeedDuration','move_speed_duration_ms','移动速度持续（毫秒）',1000],['MaximumRunes','max_runes','最多符文数'],['RuneDuration','rune_duration_ms','符文充能窗口（毫秒）',1000]]);const damage=calc(x,'QDamageCalc','damage','超负荷基础伤害','当前P具名额外法力与本节点mStatFormula2交叉证明0.02额外法力');input(x,'confirmed_flux_damage_amp_ratio','当前R等级对应涌动增幅比例','须从当前RyzeR.OverloadDamageBonus取得实际有效等级值；不默认R已学习、满级或使用Q自身旧DamageAmp。');fixed(x,'one','一倍基础',1,'1+伤害增幅比例。','明确百分比增伤数学');formula(x,'flux_damage','消耗涌动时超负荷伤害',mul(damage,add(pn('one'),pn('confirmed_flux_damage_amp_ratio'))),'只在真实消耗涌动且R等级增幅已确认时使用。');statEffect(x,'two_rune_move_speed','消耗双符文移动速度比例',val('two_rune_move_speed_ratio'),'move_speed_percent',{duration:val('move_speed_duration_ms'),description:'当前正文明确消耗2枚符文提供持续2秒移速；按移动速度比例属性加算，真实充能和消费尚未自动连接。'});only(x,['DamageAmp'],'当前正文明确取RyzeR.OverloadDamageBonus，不使用Q内旧增幅字段。');exclude(x,'Q向附近涌动目标弹射','只排除多目标分发，当前单个涌动目标增伤保留。');pending(x,'W/E重置与跨技能涌动','W/E刷新Q冷却并充能；Q消耗E涌动，增幅读取R等级。来源创建不自动充满符文。','配置');damageGap(x);
}
{
 const x=start('ryze_w');common(x);rows(x,[['BaseDamage','base_damage','基础魔法伤害'],['SlowAmount','slow_ratio','普通减速比例'],['CCDuration','control_duration_ms','控制持续（毫秒）',1000]]);calc(x,'WDamageCalc','damage','符文禁锢伤害','当前P具名额外法力，本W节点为0.03额外法力');pending(x,'普通减速与涌动禁锢互斥','目标有E涌动则消耗它，禁锢替代减速而不是两者并发；W施放重置Q及符文充能未连接。','配置');damageGap(x);
}
{
 const x=start('ryze_e');common(x);rows(x,[['BaseDamage','base_damage','基础魔法伤害'],['DebuffDuration','flux_duration_ms','涌动持续（毫秒）',1000]]);calc(x,'EDamageCalc','damage','法术涌动伤害','当前P具名额外法力，本E节点为0.02额外法力');only(x,['BounceRadius','BounceRadiusLargeUnit','BounceRadiusQSmallUnit','BounceRadiusQLargeUnit'],'纯附近多目标传播半径；当前目标涌动供Q/W消费仍保留。','范围外');only(x,['DamageAmp'],'当前绑定不消费E旧增幅字段，不代替R增幅。');pending(x,'涌动资格跨技能','保留当前目标4秒涌动、Q增伤和W控制替换；传播几何排除不表示删除跨技能状态依赖。','配置');damageGap(x);
}
{
 const x=start('ryze_r');rows(x,[['OverloadDamageBonus','flux_damage_amp_ratio','R等级对应Q涌动增伤比例',.01]]);formula(x,'flux_damage_multiplier','R等级对应涌动伤害倍率',add(fixed(x,'one','一倍基础',1,'明确伤害增加百分比。','当前绑定正文'),pn('flux_damage_amp_ratio')),'R1/2/3分别提高50%/75%/100%，倍率1.5/1.75/2；未学习R的索引0原值另留来源，不补默认等级。');only(x,['OverloadHealPercent','HealPercentMinionMod'],'当前正文没有超负荷恢复机制，旧恢复字段不复活。');only(x,['ChargeTime','TeleportTime','AllyIndicatorBuffDuration','ChargeTimeTooltip','MinimumCastRange'],'主动传送的空间/队友运输不进入本轮数值机制；原R公共成本与冷却只完整复用，不额外创建无关主动过程。','范围外');pending(x,'Q跨技能取R等级','Q必须取得真实R学习等级；原DataValues索引0为25但本R管理等级从1起，未学习分支单独核对。','配置');
}
{
 const x=start('cassiopeia_p');calc(x,'PercentHasteMod','move_speed_bonus_efficiency_ratio','当前等级移动速度加成效率提升比例','当前原树初值0.06与每级0.02仍保留无默认等级输入，不猜断点求值');input(x,'qualified_move_speed_bonus','本次合格移动速度加成数值','只取当前可被提升效率的加成，不能用总移动速度；不同固定/比例来源的取值与合并需另核。');formula(x,'additional_move_speed_bonus','合格移速加成额外数值',mul(pn('qualified_move_speed_bonus'),x.c.write.formulas[0].expression),'仅提升符合条件的加成部分；不直接把总移速乘同一比率。');pending(x,'当前P与旧机制','当前文本是所有移动速度加成效率，不能复活旧禁止买鞋或固定每级加移速。各加成来源与效率修正未连接。','来源');
}
{
 const x=start('cassiopeia_q');common(x);rows(x,[['BaseDamage','base_total_damage','三秒总基础伤害'],['PoisonDuration','poison_duration_ms','中毒持续（毫秒）',1000],['ChampHitMSBonus','initial_move_speed_ratio','命中英雄初始移速比例',.01],['ChampHitMSDuration','move_speed_decay_duration_ms','移速衰减持续（毫秒）',1000],['NumDamageTicks','source_damage_tick_count','源伤害次数字段']]);calc(x,'TooltipTotalDamage','poison_total_damage','三秒中毒总魔法伤害','当前正文和tooltipOnly明确三秒总量，不能当单跳伤害');pending(x,'中毒与周期事件','原7次伤害字段不能证明首跳时点和分配；Q中毒供E资格使用，命中英雄后移速衰减函数未证，不生成恒定移速效果。','配置');damageGap(x);
}
{
 const x=start('cassiopeia_w');common(x);rows(x,[['BaseDamage','base_damage_per_second','每秒基础伤害'],['SlowPercent','slow_ratio','毒云减速比例',.01],['CloudDuration','cloud_duration_ms','毒云持续（毫秒）',1000]]);calc(x,'DamagePerSecond','damage_per_second','毒云每秒魔法伤害','当前正文明确每秒，不是五秒总量或一次命中量');only(x,['PoisonDuration'],'原1秒字段的区域内刷新/离开延续语义未被当前正文证明；中毒供E使用的资格不能丢。');pending(x,'中毒、缚地和减速','在毒云内的中毒和缚地影响当前对手及E分支；离开时点、周期分配、控制资格未连接，不能将区域持续当完整中毒时长。','配置');damageGap(x);
}
{
 const x=start('cassiopeia_e');common(x);rows(x,[['BasicAPRatio','base_ap_ratio','基础伤害法强系数'],['BonusDamage','poison_bonus_base_damage','中毒额外基础伤害'],['BonusAPRatio','poison_bonus_ap_ratio','中毒额外法强系数'],['HealRatio','poison_heal_ap_ratio','对中毒目标恢复法强系数'],['MinionReductionModifier','small_unit_heal_ratio','小兵及小型野怪恢复比例']]);const base=calc(x,'BasicDamage','base_damage','双生毒牙基础魔法伤害','基础等级节点52及斜率4不猜完整求值'),bonus=calc(x,'BonusPoisonedDamage','poison_bonus_damage','对中毒目标额外伤害','只在已确认中毒资格下增加');formula(x,'poison_total_damage','对中毒目标总伤害',add(base,bonus),'基础与中毒额外伤害相加；不中毒时只用基础公式');calc(x,'HealCalc','poison_heal','攻击中毒目标自身恢复量','当前树仅AP乘逐级HealRatio，不凭旧知识添基础恢复');pending(x,'恢复短摘要与当前数值链不同','keySummary称基于实际伤害恢复，但当前keyTooltip明确HealCalc，其树只有AP乘HealRatio；候选保留这条直接绑定数值关系，完整保留摘要冲突，不生成按伤害自疗或直接治疗效果。','来源');calc(x,'HealCalcMinion','small_unit_poison_heal','小兵及小型野怪目标自身恢复','当前明确降低至四分之一；保留战前自身恢复依赖');input(x,'confirmed_kill_mana_refund','已确认击杀时返还法力','当前文本引用动态Cost；基础成本40已确定，但修正后的返还取值需核对，不默认所有状态恒为40或等于已消耗量。');formula(x,'kill_mana_refund','击杀返还法力数值',pn('confirmed_kill_mana_refund'),'只在E实际击杀且当前Cost返还值已确认时使用');only(x,['HealingRatio'],'此原字段没有values，不填0，也不代替当前HealRatio。');pending(x,'中毒资格和恢复事件','Q/W及其他来源的中毒能否满足E、伤害时取样、目标分类、自疗时点和击杀归属均需明确；不造默认中毒。','配置');damageGap(x);
}
{
 const x=start('cassiopeia_r');common(x);rows(x,[['RBaseDamage','base_damage','基础魔法伤害'],['APRatio','ap_ratio','法强系数'],['RCCDuration','control_duration_ms','控制持续（毫秒）',1000],['RSlowPercent','initial_slow_ratio','背向时初始减速比例',.01]]);calc(x,'RDamage','damage','石化凝视魔法伤害','基础加0.5AP');pending(x,'朝向决定互斥控制','面朝施法者晕眩2秒，未面朝则40%减速并在相同时长衰减，二者不是同时应用；方向判定、减速函数、护盾和免控资格未连接。','配置');damageGap(x);
}
