import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const HERE=path.dirname(fileURLToPath(import.meta.url));
const ARTIFACT=path.resolve(HERE,'..','..','..','..','..','damage_web_dev','.agents','artifacts','gear20-finalize');
const DRAFT_PATH=path.join(HERE,'最终候选.json');
const SOURCE_PATH=path.join(HERE,'冻结来源.json');
const SNAPSHOT_PATH=path.join(HERE,'写前保护快照.json');
const OUTPUT_PATH=path.join(HERE,'修正版最终候选.json');
const AUDIT_PATH=path.join(ARTIFACT,'候选修正版独立审查.json');
const EXPECTED_DRAFT_SHA='b918d195d3cbc64710e077c03e208aec693b0414ac9ae611e59463456ae08d82';
const EXPECTED_SOURCE_SHA='3861cdd2d66da43deb99aca9c085c894258f58a21bfdfc967b9feaa71203e649';
function sha(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function read(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function fail(msg){throw new Error(msg);}
function check(x,msg){if(!x)fail(msg);}
function record(checks,name,pass,detail=null){checks.push({name,pass,...(detail===null?{}:{detail})});check(pass,`修正版候选审查失败：${name}`);}
function sourceByKey(source,key){return source.objects.find(o=>o.equipmentKey===key);}
function candidateByKey(candidate,key){return candidate.objects.find(o=>o.equipmentKey===key);}
function attr(snapshot,key){return snapshot.rows.find(r=>r.kind==='equipmentAttributesGET'&&r.equipmentKey===key)?.response?.data?.attributeValues;}
function relation(snapshot,key){return snapshot.rows.find(r=>r.kind==='relationGET'&&r.equipmentKey===key)?.response?.data?.items;}
function image(snapshot,key){return snapshot.rows.find(r=>r.kind==='representativeImageGET'&&r.equipmentKey===key)?.response?.data?.image;}
function walk(node,visit){if(!node||typeof node!=='object')return;visit(node);if(Array.isArray(node))node.forEach(child=>walk(child,visit));else Object.values(node).forEach(child=>walk(child,visit));}
const draftSha=sha(DRAFT_PATH);const sourceSha=sha(SOURCE_PATH);const snapshotSha=sha(SNAPSHOT_PATH);
check(draftSha===EXPECTED_DRAFT_SHA,`32参数草稿哈希变化：${draftSha}`);check(sourceSha===EXPECTED_SOURCE_SHA,`冻结来源哈希变化：${sourceSha}`);
const draft=read(DRAFT_PATH);const source=read(SOURCE_PATH);const snapshot=read(SNAPSHOT_PATH);const candidate=structuredClone(draft);const checks=[];
const selected=['item_3168','item_3170','item_3171','item_3173','item_3174'];
record(checks,'范围五件装备',JSON.stringify(candidate.objects.map(o=>o.equipmentKey))===JSON.stringify(selected));
record(checks,'实时保护快照GET',snapshot.apiWrites===0&&snapshot.noBusinessWrites===true&&snapshot.counts?.totalGets===26);
record(checks,'实时保护状态',snapshot.statusSummary?.equipment200===5&&snapshot.statusSummary?.attributes200===5&&snapshot.statusSummary?.representativeImages200===5&&snapshot.statusSummary?.relationsEmpty===5&&snapshot.statusSummary?.targetSkills404===5&&snapshot.statusSummary?.category200===true);
record(checks,'分类仅有现存被动键',JSON.stringify(snapshot.category?.data?.items?.map(i=>i.skillCategoryKey))===JSON.stringify(['move_skill','common','passive']));
for(const key of selected){const object=candidateByKey(candidate,key);const src=sourceByKey(source,key);record(checks,`${key}来源原对象`,object.source.rawObjectSha256===src.rawSha256);record(checks,`${key}目标技能被动`,JSON.stringify(object.apiPayload.skill.skillCategoryKeys)===JSON.stringify(['passive']));record(checks,`${key}关系为空`,Array.isArray(relation(snapshot,key))&&relation(snapshot,key).length===0);record(checks,`${key}原图同键`,image(snapshot,key)?.imageKey===key&&object.apiPayload.representativeImage.imageKey===key);record(checks,`${key}四类空组成`,['effects','processes','internalStates','triggerRules'].every(kind=>Array.isArray(object.apiPayload[kind])&&object.apiPayload[kind].length===0));}
const p3168=candidateByKey(candidate,'item_3168').apiPayload.parameters.find(p=>p.parameterKey==='actual_stacks');record(checks,'层数输入为整数运行时',p3168?.valueType==='INTEGER'&&p3168?.valueMode==='RUNTIME_INPUT'&&p3168?.fixedValue===null);p3168.valueType='INTEGER';p3168.description='无默认值。战前或对局中已累积层数由运行时提供；层数是整数输入，不因击杀参与事件未接线而丢弃。';
for(const key of ['item_3173','item_3174']){
 const object=candidateByKey(candidate,key);const params=object.apiPayload.parameters;const before=params.map(p=>p.parameterKey);record(checks,`${key}草稿包含待移除断点参数`,before.includes('shield_breakpoint_level')&&before.includes('shield_bonus_per_level'),{parameterKeys:before});record(checks,`${key}草稿保留1级节点与基础输入`,before.includes('shield_level1_value')&&before.includes('actual_level_base_shield'));
 object.apiPayload.parameters=params.filter(p=>!['shield_breakpoint_level','shield_bonus_per_level'].includes(p.parameterKey));const after=object.apiPayload.parameters.map(p=>p.parameterKey);record(checks,`${key}修正版不含两个未解析断点参数`,!after.includes('shield_breakpoint_level')&&!after.includes('shield_bonus_per_level'),{parameterKeys:after});record(checks,`${key}修正版保留1级节点与基础输入`,after.includes('shield_level1_value')&&after.includes('actual_level_base_shield'));
 object.apiPayload.skill.description=key==='item_3173'
  ?'保留冷却15秒、护盾持续5秒，以及护盾计算树的1级节点90和mStat12/formula2×0.08。等级断点求值算法未证，不以未知等级的基础护盾默认值替代；基础段使用无默认的当前等级基础护盾运行时输入。mStat12/formula2不按其他对象的mStat12/0证据映射为SOURCE.hp.TOTAL。魔法护盾类型来源已明确，本批不创建护盾效果。官方说明中的护盾0不是实际值，不录入。'
  :'保留镀板即将到来的攻击伤害降低10%作为减幅参数，合资格攻击分量与减伤乘区待接。保留诺克萨斯的耐久冷却15秒、护盾持续5秒，以及与3173同构的护盾计算树1级节点90和mStat12/formula2×0.08。等级断点求值未证，不以未知等级的基础护盾默认值替代；基础段使用无默认的当前等级基础护盾运行时输入。物理护盾类型来源已明确，本批不创建效果。官方护盾0不录入。';
}
for(const object of candidate.objects){const params=Object.fromEntries(object.apiPayload.parameters.map(p=>[p.parameterKey,p]));for(const parameter of object.apiPayload.parameters.filter(p=>p.valueMode==='RUNTIME_INPUT')){const expected=parameter.parameterKey==='actual_stacks'?'INTEGER':'DECIMAL';record(checks,`${object.skillKey}/${parameter.parameterKey}运行时类型`,parameter.valueType===expected&&parameter.fixedValue===null&&parameter.levelValues===null,{expected});}for(const formula of object.apiPayload.formulas){const refs=[];walk(formula.expression,node=>{if(node.nodeType==='PARAMETER')refs.push(node.parameterKey);if(node.nodeType==='FORMULA')refs.push(`FORMULA:${node.formulaKey}`);if(node.nodeType==='OPERATION')check(['ADD','MULTIPLY','MIN'].includes(node.operation),`${object.skillKey}/${formula.formulaKey}运算不允许`);});record(checks,`${object.skillKey}/${formula.formulaKey}引用已定义参数`,refs.every(ref=>!ref.startsWith('FORMULA:')&&Boolean(params[ref])),refs);}}
record(checks,'两棵护盾公式不引用断点参数',candidate.objects.filter(o=>['item_3173','item_3174'].includes(o.equipmentKey)).every(o=>{const keys=[];o.apiPayload.formulas.forEach(f=>walk(f.expression,n=>{if(n.nodeType==='PARAMETER')keys.push(n.parameterKey);}));return !keys.includes('shield_breakpoint_level')&&!keys.includes('shield_bonus_per_level');}));
const totals={equipment:candidate.objects.length,skills:candidate.objects.length,parameters:candidate.objects.reduce((n,o)=>n+o.apiPayload.parameters.length,0),formulas:candidate.objects.reduce((n,o)=>n+o.apiPayload.formulas.length,0),effects:candidate.objects.reduce((n,o)=>n+o.apiPayload.effects.length,0),processes:candidate.objects.reduce((n,o)=>n+o.apiPayload.processes.length,0),internalStates:candidate.objects.reduce((n,o)=>n+o.apiPayload.internalStates.length,0),triggerRules:candidate.objects.reduce((n,o)=>n+o.apiPayload.triggerRules.length,0),relations:candidate.objects.length,representativeImages:candidate.objects.length};
const expectedTotals={equipment:5,skills:5,parameters:28,formulas:5,effects:0,processes:0,internalStates:0,triggerRules:0,relations:5,representativeImages:5};record(checks,'修正版总计28参数5公式5关联5图',JSON.stringify(totals)===JSON.stringify(expectedTotals),{totals,expectedTotals});candidate.totals=expectedTotals;candidate.generatedAt=new Date().toISOString();candidate.stage='实时保护读取与独立候选审查后修正版最终版，未写业务';candidate.sourceFreezePath='冻结来源.json';candidate.currentSnapshotSha256=snapshotSha;candidate.currentSnapshotPath='写前保护快照.json';candidate.currentSnapshotAt=snapshot.finishedAt;candidate.apiWrites=0;candidate.revision={basedOnDraftCandidateSha256:draftSha,reason:'删除两个护盾断点说明参数；断点数值只留在来源报告，实际可操作载荷保留1级节点、无默认基础护盾输入和0.08系数。',changes:[{path:'objects[item_3173].apiPayload.parameters[shield_breakpoint_level]',action:'removed'},{path:'objects[item_3173].apiPayload.parameters[shield_bonus_per_level]',action:'removed'},{path:'objects[item_3174].apiPayload.parameters[shield_breakpoint_level]',action:'removed'},{path:'objects[item_3174].apiPayload.parameters[shield_bonus_per_level]',action:'removed'},{path:'objects[item_3168].apiPayload.parameters[actual_stacks].valueType',from:'DECIMAL',to:'INTEGER'}],sourceOnlyNote:'item_3173与item_3174的断点等级9和每级加成10只见冻结来源核对报告，不进入技能参数或公式。',realtimeProtection:{snapshotSha256:snapshotSha,totalGets:snapshot.counts.totalGets,apiWrites:snapshot.apiWrites}};
check(checks.every(x=>x.pass),'审查存在失败项');check(!fs.existsSync(OUTPUT_PATH),`输出已存在：${OUTPUT_PATH}`);fs.writeFileSync(OUTPUT_PATH,JSON.stringify(candidate,null,2)+'\n','utf8');const correctedSha=sha(OUTPUT_PATH);const audit={generatedAt:new Date().toISOString(),mode:'独立候选修正版审查',noBusinessWrites:true,apiWrites:0,draftCandidateSha256:draftSha,correctedCandidateSha256:correctedSha,sourceSha256:sourceSha,snapshotSha256:snapshotSha,removedOperationalParameters:[{equipmentKey:'item_3173',parameterKeys:['shield_breakpoint_level','shield_bonus_per_level']},{equipmentKey:'item_3174',parameterKeys:['shield_breakpoint_level','shield_bonus_per_level']}],checks,allPass:true};fs.mkdirSync(ARTIFACT,{recursive:true});fs.writeFileSync(AUDIT_PATH,JSON.stringify(audit,null,2)+'\n','utf8');console.log(JSON.stringify({outputPath:OUTPUT_PATH,auditPath:AUDIT_PATH,draftCandidateSha256:draftSha,correctedCandidateSha256:correctedSha,sourceSha256:sourceSha,snapshotSha256:snapshotSha,parameterCount:totals.parameters,formulaCount:totals.formulas,checkCount:checks.length,allPass:true,apiWrites:0}));
