import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),planBytes=fs.readFileSync(path.join(here,'可审查最终请求.json'));assert.equal(hash(planBytes),'d9d238981202cf8a8cb57c50592568b01fc6659f510e4f7db86ca07d4a72e17e');const plan=JSON.parse(planBytes),beforeBytes=fs.readFileSync(path.join(here,'修正准备/完整写前快照.json'));assert.equal(hash(beforeBytes),plan.beforeSnapshotSha256);const before=JSON.parse(beforeBytes);assert.equal(plan.requests.length,16);assert.equal(before.requests.length,148);
const apply=process.argv[2]==='--apply';assert.equal(process.argv.length,apply?3:2);const token=process.env.CURVE_FIX_API_TOKEN;assert(token);const journal=path.join(here,'实际流水.jsonl'),reportFile=path.join(here,'实际修正结果.json');if(apply){assert(!fs.existsSync(journal)&&!fs.existsSync(reportFile),'已有实际流水；须先只读对账，禁止重放');const review=JSON.parse(fs.readFileSync(path.join(here,'独立审查结论.json')));assert.equal(review.planSha256,hash(planBytes));assert.equal(review.verdict,'READY');}
const report={at:new Date().toISOString(),planSha256:hash(planBytes),beforeSnapshotSha256:hash(beforeBytes),writes:[],reads:[],protected:[],errors:[]},newParameters=new Map(),deleted=new Set();
const save=()=>{if(apply)fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n');};
async function call(method,route,body){if(method!=='GET'){assert(apply);const allowed=plan.requests.find(r=>r.route===route&&r.method===method);assert(allowed);assert.deepEqual(body,allowed.body);}if(apply)fs.appendFileSync(journal,JSON.stringify({at:new Date().toISOString(),phase:'before',method,route,body})+'\n');try{const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const text=await r.text(),data=text?JSON.parse(text):null,value={method,route,status:r.status,data};if(apply)fs.appendFileSync(journal,JSON.stringify({at:new Date().toISOString(),phase:'after',...value})+'\n');if(method==='GET')report.reads.push(value);return value;}catch(e){if(apply)fs.appendFileSync(journal,JSON.stringify({at:new Date().toISOString(),phase:'unknown',method,route,error:e.name})+'\n');throw e;}}
function parameterAfter(p,current){for(const[k,v]of Object.entries(p.body))assert.deepEqual(current[k],v,p.route+'/'+k);for(const[k,v]of Object.entries(p.before))if(k!=='updatedAt'&&!Object.hasOwn(p.body,k))assert.deepEqual(current[k],v,p.route+'/'+k);assert.equal(current.valueMode,'RUNTIME_INPUT');assert.equal(current.fixedValue,null);assert.equal(current.levelValues,null);}
async function allProtected(final){let i=0;await Promise.all(Array.from({length:4},async()=>{while(i<before.requests.length){const previous=before.requests[i++],current=await call('GET',previous.route);if(final&&deleted.has(previous.route)){assert.equal(current.status,404);report.protected.push({route:previous.route,expectedDeleted:true});continue;}assert.equal(current.status,200,previous.route);let expected=previous.data;if(final&&newParameters.has(previous.route))expected=newParameters.get(previous.route);else if(final&&previous.route.endsWith('/parameters'))expected=previous.data.map(row=>newParameters.get(previous.route+'/'+row.parameterKey)??row);else if(final&&previous.route.endsWith('/trigger-rules'))expected=previous.data.filter(row=>!deleted.has(previous.route+'/'+row.ruleKey));assert.deepEqual(current.data,expected,previous.route);if(final)report.protected.push({route:previous.route,matched:true});}}));}
try{
 await allProtected(false);for(const p of plan.requests){const actual=report.reads.find(r=>r.route===p.route);assert(actual,p.route);assert.deepEqual(actual.data,p.before,p.route+'目标旧值');}
 if(!apply){console.log(JSON.stringify({preview:true,gets:report.reads.length,planned:16,writes:0}));process.exit(0);}
 save();for(const p of plan.requests){const latest=await call('GET',p.route);assert.equal(latest.status,200);assert.deepEqual(latest.data,p.before,p.route+'写前未变');let response=null,unknown=null;try{response=await call(p.method,p.route,p.body);}catch(e){unknown=e.name;}const after=await call('GET',p.route);if(p.method==='DELETE'){assert.equal(after.status,404,p.route+'删除后');deleted.add(p.route);}else{assert.equal(after.status,200);parameterAfter(p,after.data);newParameters.set(p.route,after.data);}report.writes.push({method:p.method,route:p.route,responseStatus:response?.status??null,unknownResponse:unknown,confirmed:true,after});save();if(response)assert([200,204].includes(response.status),p.route+'写响应');}
 await allProtected(true);assert.equal(deleted.size,6);assert.equal(newParameters.size,10);report.summary={success:true,updates:10,removedUnprovenRules:6,gets:report.reads.length,protectedReads:report.protected.length,componentsBefore:76,componentsAfter:70,otherComponentsUnchanged:60,completeBattleMechanisms:0};report.finishedAt=new Date().toISOString();save();console.log(JSON.stringify(report.summary));
}catch(e){report.errors.push({name:e.name,message:e.message});report.summary={success:false,confirmedWrites:report.writes.length,gets:report.reads.length};save();console.error(JSON.stringify(report.summary));process.exitCode=1;}
