import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {load,snapshot,verifySources,get} from './接口工具.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),live=process.argv.includes('--live');assert(process.argv.slice(2).every(x=>x==='--live'));const loaded=await load(),plan=loaded.plan,old=JSON.parse(fs.readFileSync(path.join(here,'完整候选-主审前.json'))),originalCases=JSON.parse(fs.readFileSync(path.join(here,'独立数值核对.json'))).cases;
const report={at:new Date().toISOString(),mode:live?'GET实际保存值':'候选静态数值',candidateSha256:loaded.hash,checks:[],cases:[],businessWrites:0};let rows;
if(live){report.sources=await verifySources(loaded.source);let requests=0;report.snapshot=await snapshot(plan,loaded.before,{request:async(...args)=>{requests++;return get(...args)}});report.requests=requests;assert.equal(report.snapshot.missing.length,0);assert.equal(report.snapshot.conflicts.length,0);assert.equal(report.snapshot.sameCount,132);assert(report.snapshot.objects.every(o=>o.componentLists.length===6&&o.componentLists.every(x=>x.keySetMatch)&&o.protection.routes.every(r=>r.match)));rows=new Map(report.snapshot.objects.map(o=>[o.equipmentKey,{parameters:o.components.filter(x=>x.kind==='parameters').map(x=>x.data),formulas:o.components.filter(x=>x.kind==='formulas').map(x=>x.data)}]));}else rows=new Map(plan.objects.map(o=>[o.equipmentKey,o.apiPayload]));
function evaluate(id,key,inputs,attributes){const o=rows.get(id),params=new Map(o.parameters.map(p=>[p.parameterKey,p]));function calc(n){if(n.nodeType==='PARAMETER'){const p=params.get(n.parameterKey);assert(p);if(p.valueMode==='FIXED')return p.fixedValue;assert.equal(p.valueMode,'RUNTIME_INPUT');assert.equal(p.fixedValue,null);assert(Object.hasOwn(inputs,n.parameterKey));return inputs[n.parameterKey];}if(n.nodeType==='ATTRIBUTE'){const k=[n.attributeOwner,n.attributeKey,n.attributeValueKind].join(':');assert(Object.hasOwn(attributes,k));return attributes[k];}assert.equal(n.nodeType,'OPERATION');assert.equal(n.operands.length,2);const[a,b]=n.operands.map(calc);switch(n.operation){case'ADD':return a+b;case'SUBTRACT':return a-b;case'MULTIPLY':return a*b;case'DIVIDE':return a/b;case'MIN':return Math.min(a,b);case'MAX':return Math.max(a,b);default:throw Error(n.operation)}}return calc(o.formulas.find(x=>x.formulaKey===key).expression);}
function check(id,key,inputs,attributes,expected,reason){const actual=evaluate(id,key,inputs,attributes);assert(Math.abs(actual-expected)<1e-8,`${id}/${key}: ${actual} != ${expected}`);report.cases.push({id,key,inputs,attributes,expected,actual,reason,passed:true});}
for(const test of originalCases){const inputs={...test.inputs.parameters},attributes={...test.inputs.attributes};if(test.equipmentKey==='item_2510'&&test.formulaKey==='spellblade_healing_value'){attributes['SOURCE:hp:BONUS']=inputs.spellblade_healing_mstat12_formula2_input;delete inputs.spellblade_healing_mstat12_formula2_input;}check(test.equipmentKey,test.formulaKey,inputs,attributes,test.expected,'沿已审源数值算例，当前最终公式实际求值。');}
for(const [ap,hp,want]of [[0,0,0],[100,1000,40],[200,3000,110]])check('item_2510','spellblade_healing_value',{}, {'SOURCE:ability_power:TOTAL':ap,'SOURCE:hp:BONUS':hp,'SOURCE:hp:TOTAL':hp+2000},want,'法强与额外生命值；另给不同总生命反例防止误用。');
check('item_2524','melody_ranged_duration_ms',{}, {},4000,'原基础8秒乘远程0.5，再统一毫秒口径。');check('item_2524','melody_self_ranged_attack_speed_ratio',{}, {},.2001,'原0.3乘0.667，不舍入0.2。');
assert.equal(rows.get('item_3083').parameters.find(x=>x.parameterKey==='warmog_nonchampion_damage_lockout_ms').fixedValue,3000);report.checks.push({label:'非英雄伤害恢复禁用3000ms',passed:true});
for(const o of plan.objects){const previous=old.objects.find(x=>x.equipmentKey===o.equipmentKey);for(const f of o.apiPayload.formulas){const oldf=previous.apiPayload.formulas.find(x=>x.formulaKey===f.formulaKey);if(oldf&&!(o.equipmentKey==='item_2510'&&f.formulaKey==='spellblade_healing_value'))assert.deepEqual(f.expression,oldf.expression);}}
report.checks.push({label:'其余已有公式数学表达式未变',passed:true});report.passed=true;report.formulaCases=report.cases.length;fs.writeFileSync(path.join(here,live?'最终独立全量回读.json':'最终候选核算.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({mode:report.mode,passed:report.passed,cases:report.formulaCases,requests:report.requests,components:report.snapshot?.sameCount,writes:0}));
