import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const root='C:/project/damage_web_dev/数据参考/全量录入-2026-09/交叉试录/历史等级曲线修正/',here=new URL('./',import.meta.url),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const originalPlanBytes=fs.readFileSync(root+'可审查最终请求.json'),finalPlanBytes=fs.readFileSync(root+'最终补充7请求.json');assert.equal(sha(originalPlanBytes),'d9d238981202cf8a8cb57c50592568b01fc6659f510e4f7db86ca07d4a72e17e');assert.equal(sha(finalPlanBytes),'fe7f22180b233579c1356b0492d689e344c3e2152cda591db6298250c2254cbe');const originalPlan=JSON.parse(originalPlanBytes),finalPlan=JSON.parse(finalPlanBytes),originalBytes=fs.readFileSync(root+'修正准备/完整写前快照.json');assert.equal(sha(originalBytes),originalPlan.beforeSnapshotSha256);const original=JSON.parse(originalBytes);assert.equal(original.requests.length,148);
const deleted=new Set([...originalPlan.requests,...finalPlan.requests].filter(r=>r.method==='DELETE').map(r=>r.route)),updated=new Map(originalPlan.requests.filter(r=>r.method==='PUT').map(r=>[r.route,r]));assert.equal(deleted.size,9);assert.equal(updated.size,10);for(const r of finalPlan.requests.filter(r=>r.method==='PUT'))assert.deepEqual(r.body,updated.get(r.route).body);
const token=process.env.CURVE_REVIEW_TOKEN;assert(token,'缺少临时开发认证环境');const file=new URL('实际修正后独立回读.json',here),out={at:new Date().toISOString(),mode:'本次重新真实GET；没有导入执行流水或写后回读响应作为当前值',planSha256:sha(finalPlanBytes),originalSnapshotSha256:sha(originalBytes),reads:[],checks:[],errors:[],businessWrites:0};fs.writeFileSync(file,JSON.stringify(out,null,2)+'\n',{flag:'wx'});
const imageRoutes=[...deleted].filter(p=>p.includes('/effects/')).map(p=>p+'/representative-image'),dictionaryRoutes=['/attributes','/modifier-zones','/damage-types','/statuses'],routes=[...original.requests.map(r=>r.route),...imageRoutes,...dictionaryRoutes];assert.equal(new Set(routes).size,155);
let i=0;await Promise.all(Array.from({length:4},async()=>{while(i<routes.length){const route=routes[i++],startedAt=new Date().toISOString();let row;try{const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method:'GET',headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)});row={route,method:'GET',startedAt,finishedAt:new Date().toISOString(),status:r.status,data:await r.json()};}catch(e){row={route,method:'GET',startedAt,status:null,error:e.name};out.errors.push({route,error:e.message});}out.reads.push(row);fs.writeFileSync(file,JSON.stringify(out,null,2)+'\n');}}));
const live=new Map(out.reads.map(r=>[r.route,r])),componentRoute=/^\/skills\/[^/]+\/(parameters|formulas|effects|processes|internal-states|trigger-rules)\/[^/]+$/;
function check(name,fn){try{fn();out.checks.push({name,passed:true});}catch(e){out.checks.push({name,passed:false});out.errors.push({name,message:e.message});}}
for(const[route,p]of updated)check(route+'10参数全部字段及无默认值',()=>{const row=live.get(route);assert.equal(row.status,200);for(const[k,v]of Object.entries(p.body))assert.deepEqual(row.data[k],v,k);for(const[k,v]of Object.entries(p.before))if(k!=='updatedAt'&&!Object.hasOwn(p.body,k))assert.deepEqual(row.data[k],v,k);assert.equal(row.data.valueMode,'RUNTIME_INPUT');assert.equal(row.data.fixedValue,null);assert.equal(row.data.levelValues,null);assert(Number.isFinite(Date.parse(row.data.updatedAt)));assert(Date.parse(row.data.updatedAt)>=Date.parse(p.before.updatedAt));});
let unchangedComponents=0,protectedOtherRoutes=0;
for(const prev of original.requests)check(prev.route+'原对象保护',()=>{const now=live.get(prev.route);if(deleted.has(prev.route)){assert.equal(now.status,404);assert.match(now.data.error.code,/^404\.SKILL_(TRIGGER_RULE|EFFECT)_NOT_FOUND$/);return;}assert.equal(now.status,200);if(updated.has(prev.route))return;let expected=prev.data;
 if(Array.isArray(expected)&&/\/(parameters|effects|trigger-rules)$/.test(prev.route))expected=expected.filter(row=>!deleted.has(prev.route+'/'+(row.parameterKey??row.effectKey??row.ruleKey))).map(row=>{const key=row.parameterKey??row.effectKey??row.ruleKey,route=prev.route+'/'+key;return updated.has(route)?live.get(route).data:row;});
 assert.deepEqual(now.data,expected);if(componentRoute.test(prev.route))unchangedComponents++;else protectedOtherRoutes++;
});
for(const route of imageRoutes)check(route+'空图包装对象',()=>{assert.equal(live.get(route).status,200);assert.deepEqual(live.get(route).data,{image:null});});
for(const route of dictionaryRoutes)check(route+'当前字典',()=>assert.equal(live.get(route).status,200));
check('57其余组成完整不变',()=>assert.equal(unchangedComponents,57));const actualComponents=out.reads.filter(r=>r.status===200&&componentRoute.test(r.route));check('最终67组成',()=>assert.equal(actualComponents.length,67));check('8技能无自动过程或规则',()=>{for(const r of out.reads.filter(r=>/\/(processes|trigger-rules)$/.test(r.route)))assert.deepEqual(r.data,[]);});
out.completedAt=new Date().toISOString();out.summary={success:out.errors.length===0,actualFreshGETs:out.reads.length,originalRoutes:148,deletedDetails404:9,updatedParameters:10,remainingComponents:actualComponents.length,otherComponentsUnchanged:unchangedComponents,protectedOtherRoutes,removedEffectImagesNull:3,currentDictionaries:4,statusCounts:Object.fromEntries([...new Set(out.reads.map(r=>r.status))].map(s=>[s,out.reads.filter(r=>r.status===s).length])),businessWrites:0,runtimeExecution:false};fs.writeFileSync(file,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({...out.summary,sha256:sha(fs.readFileSync(file)),errors:out.errors.length}));if(out.errors.length)process.exitCode=1;
