import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root='C:/project/damage_web_dev/数据参考/全量录入-2026-09/交叉试录/历史等级曲线修正/',here=new URL('./',import.meta.url),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const bytes=fs.readFileSync(root+'最终补充7请求.json'),planSha256=sha(bytes);assert.equal(planSha256,'fe7f22180b233579c1356b0492d689e344c3e2152cda591db6298250c2254cbe');const plan=JSON.parse(bytes),old=read(root+'补充可审查请求.json'),review=read(new URL('独立审查.json',here)),garen=read(new URL('Garen补充删除精确对象.json',here)),numeric=read(new URL('实际后端校验反例.json',here));
assert.equal(sha(fs.readFileSync(root+'补充可审查请求.json')),'50342518c542cc96aac3af2d78e1e27b3c1953a98577d64225562cf154443d45');assert.equal(review.verdict,'REVISE');assert.equal(numeric.correctedSevenFinalComponents,67);assert.equal(numeric.checks.length,15);assert(numeric.checks.every(c=>c.passed));
assert.equal(plan.requests.length,7);assert.deepEqual(plan.requests.map(r=>r.method),['DELETE','DELETE','DELETE','PUT','PUT','PUT','PUT']);assert.equal(new Set(plan.requests.map(r=>r.route)).size,7);
for(const p of old.requests){const now=plan.requests.find(r=>r.route===p.route);assert(now,p.route);assert.deepEqual(now,p,p.route+'原6请求完整对象保持');}
const added=plan.requests.filter(r=>!old.requests.some(p=>p.route===r.route));assert.equal(added.length,1);assert.equal(added[0].method,'DELETE');assert.equal(added[0].route,garen.route);assert.deepEqual(added[0].before,garen.before);assert(!Object.hasOwn(added[0],'body')||added[0].body==null);
const already=plan.alreadyConfirmed??old.alreadyConfirmed;assert.deepEqual(already,old.alreadyConfirmed);assert.equal(already.length,12);for(const r of already)assert(!plan.requests.some(p=>p.route===r.route&&p.method===r.method),'重放已确认 '+r.route);
for(const[source,expected]of Object.entries(review.sourceSha256))assert.equal(sha(fs.readFileSync('C:/project/damage_backend_dev/'+source)),expected,'后端校验源码漂移 '+source);
const latest=read(new URL('独立实时148GET.json',here));assert.equal(latest.errors.length,0);for(const r of plan.requests){const live=latest.reads.find(x=>x.route===r.route);assert.equal(live?.status,200);assert.deepEqual(live.data,r.before);}
const report={at:new Date().toISOString(),verdict:'READY',status:'READY',planSha256,previousSixRequestVerdict:'REVISE',previousSixRequestSha256:review.reviewedPlanSha256,scope:'最终7请求完整文件与已通过生产校验的内存修正方案逐对象比对；本次不发HTTP，不执行写入，不代表写后验收。',requests:7,deleteEffects:3,parameterUpdates:4,alreadyConfirmedNotReplayed:12,beforeObjectsMatchIndependentGET:true,existingSixRequestsUnchanged:true,onlyAddedGarenDelete:true,allDeletesBeforeUpdates:true,productionValidatorSourcesUnchanged:true,productionCounterexampleChecks:15,componentsOriginal:76,componentsFinal:67,otherComponentsUnchanged:57,evidence:{independentReviewSha256:sha(fs.readFileSync(new URL('独立审查.json',here))),productionChecksSha256:sha(fs.readFileSync(new URL('实际后端校验反例.json',here))),current148GETSha256:sha(fs.readFileSync(new URL('独立实时148GET.json',here))),exactGarenObjectSha256:sha(fs.readFileSync(new URL('Garen补充删除精确对象.json',here)))},businessWrites:0,HTTPCallsThisFinalCheck:0,postWriteVerification:'尚未执行；由主负责人写入完成后另行独立GET全量核对。'};
fs.writeFileSync(new URL('最终7请求审查结论.json',here),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({verdict:report.verdict,planSha256,reportSha256:sha(fs.readFileSync(new URL('最终7请求审查结论.json',here))),requests:7,businessWrites:0}));
