// 此入口只有GET；候选缺项只是记录，不会创建或覆盖。
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
const args=process.argv.slice(2);if(args.length!==1||!['--front','--rear','--full'].includes(args[0]))throw Error('请指定--front、--rear或--full；入口不接受--apply');
const prefix={'--front':'前十技能','--rear':'后十技能','--full':'完整'}[args[0]],bytes=await readFile(new URL('./'+prefix+'候选.json',import.meta.url)),plan=JSON.parse(bytes),before=JSON.parse(await readFile(new URL('./写前现值.json',import.meta.url),'utf8'));
const out={at:new Date().toISOString(),mode:'全部请求为GET，原始写前快照不改',planSha256:createHash('sha256').update(bytes).digest('hex'),catalogs:{},subjects:[],relations:[],images:[],collections:[],details:[],missing:[],conflicts:[],references:[]};
const identities=new Set(['gameId','skillKey','createdAt','updatedAt']),arrayKeys={results:'resultKey',steps:'stepKey',effectBindings:'bindingKey',stateOperations:'operationKey',conditionGroups:'groupKey',conditions:'conditionKey',actions:'actionKey'};
function business(n,key='',root=true){if(Array.isArray(n)){const a=n.map(v=>business(v,'',false)),id=arrayKeys[key];if(id&&a.every(v=>typeof v?.[id]==='string'))a.sort((x,y)=>(x.sortOrder??0)-(y.sortOrder??0)||x[id].localeCompare(y[id]));return a;}if(n&&typeof n==='object'){const v=Object.fromEntries(Object.entries(n).filter(([k])=>!root||!identities.has(k)).map(([k,v])=>[k,business(v,k,false)]));if(['SKILL_HIT','SKILL_USED'].includes(v.eventType)&&v.detail&&!('useKind'in v.detail))v.detail.useKind=null;return v;}return n;}
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{headers:{Authorization:'Bearer local-entry',Accept:'application/json'},signal:AbortSignal.timeout(15000)});return {route,status:r.status,data:await r.json()};}
const rows=r=>{if(r.status!==200)throw Error(r.route+' '+r.status);const a=Array.isArray(r.data)?r.data:r.data.items;if(!Array.isArray(a)||r.data.total!=null&&r.data.total!==a.length)throw Error('未读完整 '+r.route);return a;};
const kinds=[['parameters','parameterKey','parameters'],['formulas','formulaKey','formulas'],['effects','effectKey','effects'],['processes','processKey','processes'],['internalStates','stateKey','internal-states'],['triggerRules','ruleKey','trigger-rules']];
for(const name of ['attributes','modifier-zones','statuses','damage-types'])out.catalogs[name]=await get('/'+name);
const cat=Object.fromEntries([['attributes','attributeKey'],['modifier-zones','modifierZoneKey'],['damage-types','damageTypeKey'],['statuses','statusKey']].map(([name,key])=>[key,new Set(rows(out.catalogs[name]).filter(v=>v.status==='ENABLED').map(v=>v[key]))]));
for(const hero of new Set(Object.keys(plan.skills).map(k=>k.split('_')[0]))){const r=await get('/character-skill-relations?characterKey=champion_'+hero),expected=['p','q','w','e','r'].map(s=>hero+'_'+s),actual=rows(r).map(v=>v.skillKey),match=expected.every(k=>actual.includes(k));out.relations.push({...r,match});if(!match)out.conflicts.push({hero,relationMismatch:true});}
for(const s of Object.values(plan.skills)){
 const subject=await get('/skills/'+s.skillKey),match=subject.status===200&&isDeepStrictEqual(subject.data,before.skills[s.skillKey].skill);out.subjects.push({...subject,match});if(!match)out.conflicts.push({skill:s.skillKey,subjectChanged:true});
 const image=await get('/skills/'+s.skillKey+'/representative-image');out.images.push(image);if(image.status!==200||!image.data.image?.enabled)out.conflicts.push({skill:s.skillKey,imageNotAvailable:true});
 for(const[kind,id,api]of kinds){const collection=await get('/skills/'+s.skillKey+'/'+api),items=rows(collection);out.collections.push(collection);const keys=items.map(v=>v[id]);if(new Set(keys).size!==keys.length)out.conflicts.push({skill:s.skillKey,kind,duplicate:true});for(const item of items){const detail=await get('/skills/'+s.skillKey+'/'+api+'/'+item[id]),expected=s.write[kind].find(v=>v[id]===item[id]),same=detail.status===200&&expected&&isDeepStrictEqual(business(detail.data),business(expected));out.details.push({...detail,match:Boolean(same)});if(!same)out.conflicts.push({skill:s.skillKey,kind,key:item[id],unexpectedOrDifferent:true});}for(const expected of s.write[kind])if(!keys.includes(expected[id]))out.missing.push({skill:s.skillKey,kind,key:expected[id]});}
 function walk(n){if(!n||typeof n!=='object')return;for(const[k,v]of Object.entries(n)){if(cat[k]&&v!=null&&!cat[k].has(v))out.references.push({skill:s.skillKey,key:k,value:v});if(v&&typeof v==='object')walk(v);}}walk(s.write);
}
out.conflicts.push(...out.references);out.success=out.conflicts.length===0;out.finishedAt=new Date().toISOString();await writeFile(new URL('./'+prefix+'只读前检.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({success:out.success,planSha256:out.planSha256,subjects:out.subjects.length,collections:out.collections.length,existingDetails:out.details.length,missing:out.missing.length,conflicts:out.conflicts}));if(!out.success)process.exitCode=1;
