import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import path from 'node:path';
import {isDeepStrictEqual as equal} from 'node:util';
const here=new URL('./',import.meta.url),read=n=>readFile(new URL(n,here),'utf8').then(JSON.parse),bytes=await readFile(process.env.HERO7_CANDIDATE_PATH??new URL('后十技能候选.json',here)),p=JSON.parse(bytes),before=await read('写前现值.json'),sources=await read('根绑定与数值证据.json'),texts=await read('补充文本证据.json'),catalogs=(await read('目录现值.json')).catalogs,checks=[],arithmetic=[],hashes=[];
const check=(skillKey,name,match,detail=null)=>checks.push({skillKey,name,match,detail}),near=(a,b)=>Number.isFinite(a)&&Math.abs(a-b)<1e-7,record=(skillKey,name,expected,actual)=>arithmetic.push({skillKey,name,expected,actual,match:near(actual,expected)}),body=k=>p.skills[k].write,pv=(k,key,rank=1)=>{const v=body(k).parameters.find(p=>p.parameterKey===key);return v?.valueMode==='FIXED'?v.fixedValue:v?.levelValues?.[rank];};
function evalNode(k,node,input){if(node.nodeType==='PARAMETER'){const v=body(k).parameters.find(p=>p.parameterKey===node.parameterKey);if(!v)throw Error('缺参数'+k+'/'+node.parameterKey);return v.valueMode==='RUNTIME_INPUT'?input.runtime[node.parameterKey]:pv(k,node.parameterKey,input.rank??1);}if(node.nodeType==='ATTRIBUTE')return input.attributes[[node.attributeOwner,node.attributeKey,node.attributeValueKind].join(':')];if(node.nodeType==='OPERATION'){const a=node.operands.map(n=>evalNode(k,n,input));switch(node.operation){case 'ADD':return a[0]+a[1];case 'SUBTRACT':return a[0]-a[1];case 'MULTIPLY':return a[0]*a[1];case 'MIN':return Math.min(...a);case 'MAX':return Math.max(...a);default:throw Error('未知运算'+node.operation);}}throw Error('未知节点'+node.nodeType);}
const calc=(k,key,{rank=1,totalAD=200,bonusAD=100,ap=100,targetHP=2000,runtime={}}={})=>evalNode(k,body(k).formulas.find(f=>f.formulaKey===key).expression,{rank,runtime,attributes:{'SOURCE:attack_damage:TOTAL':totalAD,'SOURCE:attack_damage:BONUS':bonusAD,'SOURCE:ability_power:TOTAL':ap,'TARGET:hp:TOTAL':targetHP}});
const base='C:/project/damage_viewer_project_planning/数据参考/全量录入-2026-09/技能公共参数实录',sha=b=>createHash('sha256').update(b).digest('hex');for(const h of sources.heroes.filter(h=>['Nocturne','Vayne'].includes(h.id)))for(const[kind,b,expected]of [['client',gunzipSync(await readFile(path.join(base,h.client.path))),h.client.sha256],['official',await readFile(path.resolve(base,h.official.path)),h.official.sha256]])hashes.push({hero:h.id,kind,expected,actual:sha(b),match:sha(b)===expected});const raw=gunzipSync(await readFile(texts.path));hashes.push({kind:'当前字符串表',expected:texts.sha256,actual:sha(raw),match:sha(raw)===texts.sha256});
const expected=['nocturne','vayne'].flatMap(h=>['p','q','w','e','r'].map(s=>h+'_'+s));check('all','只含后十槽',equal(Object.keys(p.skills),expected));let reused=0;
for(const[k,s]of Object.entries(p.skills)){const w=s.write,params=new Map(w.parameters.map(p=>[p.parameterKey,p])),forms=new Map(w.formulas.map(f=>[f.formulaKey,f.expression])),missing=[];function references(n,visited=new Set()){if(!n||typeof n!=='object')return false;let runtime=false;if((n.kind==='PARAMETER'||n.nodeType==='PARAMETER')){if(!params.has(n.parameterKey))missing.push(n.parameterKey);runtime=params.get(n.parameterKey)?.valueMode==='RUNTIME_INPUT';}if(n.kind==='FORMULA'){if(!forms.has(n.formulaKey))missing.push(n.formulaKey);else if(!visited.has(n.formulaKey)){visited.add(n.formulaKey);runtime=references(forms.get(n.formulaKey),visited)||runtime;}}for(const v of Object.values(n))if(v&&typeof v==='object')runtime=references(v,visited)||runtime;return runtime;}
 references(w);check(k,'参数及公式引用完整',!missing.length,missing);for(const[part,arr]of Object.entries(w)){const ids=arr.map(v=>v.parameterKey??v.formulaKey??v.effectKey??v.processKey??v.stateKey??v.ruleKey);check(k,part+'稳定键不重复',new Set(ids).size===ids.length);}for(const e of w.effects)for(const r of e.results){if(r.lifecycleBehavior?.moment==='PERSISTENT'&&r.lifecycleBehavior.valueReadMode==='MOMENT_EVALUATION')check(k,e.effectKey+'动态持续值无运行时输入',!references(r.valueRule));if(r.detail.attributeKey)check(k,e.effectKey+'属性真实目录存在',(catalogs.attributes.items??catalogs.attributes).some(a=>a.attributeKey===r.detail.attributeKey&&a.status==='ENABLED'));if(r.detail.modifierZoneKey)check(k,e.effectKey+'修正区兼容',(catalogs['modifier-zones'].items??catalogs['modifier-zones']).some(z=>z.modifierZoneKey===r.detail.modifierZoneKey&&z.domain==='ATTRIBUTE'&&z.status==='ENABLED'));}for(const proc of w.processes){check(k,proc.processKey+'过程有真实行为',proc.effectBindings.length+proc.stateOperations.length>0);for(const b of proc.effectBindings)check(k,proc.processKey+'效果绑定存在',w.effects.some(e=>e.effectKey===b.effectKey));}for(const r of w.triggerRules)for(const a of r.actions)check(k,r.ruleKey+'动作引用存在',w.effects.some(e=>e.effectKey===a.detail.effectKey));for(const prev of before.skills[k].components.parameters){const want=w.parameters.find(v=>v.parameterKey===prev.parameterKey),old=Object.fromEntries(Object.entries(prev).filter(([key])=>!['gameId','skillKey','createdAt','updatedAt'].includes(key)));check(k,'既有公共参数全部字段保留 '+prev.parameterKey,equal(want,old));reused++;}}
check('all','精确保留13公共参数',reused===13);
for(const[ad,expected]of [[0,0],[100,120],[200,240],[350,420]])record('nocturne_p','非暴击整次伤害TAD='+ad,expected,calc('nocturne_p','noncritical_attack_damage',{totalAD:ad}));record('nocturne_p','暴击分支1.1仅基础算术，不另乘暴击倍率',220,calc('nocturne_p','critical_branch_amount'));record('nocturne_p','基础13+100法强治疗',43,calc('nocturne_p','single_target_heal',{runtime:{decoded_level_base_heal:13}}));record('nocturne_p','基础32+200法强治疗',92,calc('nocturne_p','single_target_heal',{ap:200,runtime:{decoded_level_base_heal:32}}));check('nocturne_p','不将未知曲线展开为1至18线性',body('nocturne_p').parameters.every(p=>p.valueMode!=='CHARACTER_LEVEL'));check('nocturne_p','暴击与盾资格待核不创伤害结果',body('nocturne_p').effects.every(e=>e.results.every(r=>r.resultType!=='DAMAGE')));
for(const[rank,damage]of [[1,150],[2,190],[3,230],[4,270],[5,310]])record('nocturne_q','rank'+rank+' BAD100且TAD900',damage,calc('nocturne_q','damage',{rank,totalAD:900,bonusAD:100}));const trail=body('nocturne_q').effects.find(e=>e.effectKey==='on_trail_attributes');check('nocturne_q','影径增益按条件显式移除，不假定离开后5秒',trail.lifecycle.durationValue===null&&trail.lifecycle.expiryMode==='EXPLICIT_ONLY');check('nocturne_q','实际命中只交付伤害',body('nocturne_q').triggerRules[0].actions.every(a=>a.detail.effectKey==='damage'));
for(const[rank,ratio]of [[1,.3],[2,.35],[3,.4],[4,.45],[5,.5]]){record('nocturne_w','rank'+rank+'被动当前ActiveAS',ratio,pv('nocturne_w','passive_attack_speed_ratio',rank));record('nocturne_w','rank'+rank+'成功格挡合计仅两倍',ratio*2,calc('nocturne_w','total_attack_speed_after_block',{rank}));}const w=body('nocturne_w'),bonus=w.effects.find(e=>e.effectKey==='on_block_additional_attack_speed');check('nocturne_w','成功格挡只追加一倍',bonus.results[0].valueRule.value.parameterKey==='passive_attack_speed_ratio');check('nocturne_w','屏障1.5秒与增攻速5秒分开',pv('nocturne_w','spell_shield_duration_ms')===1500&&pv('nocturne_w','empowered_attack_speed_duration_ms')===5000);check('nocturne_w','成功格挡先消费本盾再加攻速',equal(w.triggerRules[0].actions.map(a=>a.detail.effectKey),['consume_spell_shield','on_block_additional_attack_speed'])&&w.triggerRules[0].eventSource.eventType==='SPELL_SHIELD_BLOCKED'&&w.triggerRules[0].eventSource.detail.shieldEffectKey==='spell_shield');check('nocturne_w','未学被动不以无条件初始化替代',w.triggerRules.every(r=>r.eventSource.eventType!=='SOURCE_INITIALIZED'));
for(const[rank,damage]of [[1,280],[2,325],[3,370],[4,415],[5,460]])record('nocturne_e','rank'+rank+'完整两秒总量，属性输入200',damage,calc('nocturne_e','full_leash_damage',{rank,runtime:{resolved_scaling_attribute:200}}));check('nocturne_e','无假跳频和未证伤害效果',body('nocturne_e').effects.every(e=>e.results.every(r=>r.resultType!=='DAMAGE'))&&body('nocturne_e').processes.every(p=>p.steps.every(s=>s.stepType!=='PERIODIC')));
for(const[rank,d]of [[1,270],[2,395],[3,520]])record('nocturne_r','rank'+rank+'BAD100抵达一次伤害',d,calc('nocturne_r','arrival_damage',{rank}));check('nocturne_r','没有初施再施各执行一次规则',body('nocturne_r').triggerRules.length===0&&body('nocturne_r').effects.filter(e=>e.results.some(r=>r.resultType==='DAMAGE')).length===1);
record('vayne_p','基础固定30移速',30,pv('vayne_p','night_hunter_move_speed'));check('vayne_p','不无条件初始化方向移速',body('vayne_p').triggerRules.length===0);
for(const[rank,d]of [[1,200],[2,220],[3,240],[4,260],[5,280]])record('vayne_q','rank'+rank+'TAD200/AP100的额外量，不含普通攻击本体',d,calc('vayne_q','bonus_attack_damage',{rank}));check('vayne_q','未猜CanBonusDamageCrit为0或创建固定不暴击伤害',body('vayne_q').effects.every(e=>e.results.every(r=>r.resultType!=='DAMAGE')));
for(const[rank,floor,ratio]of [[1,40,.04],[2,55,.055],[3,70,.07],[4,85,.085],[5,100,.1]]){record('vayne_w','rank'+rank+'低生命保底',floor,calc('vayne_w','silver_bolts_damage',{rank,targetHP:500}));record('vayne_w','rank'+rank+'2000目标最大生命比例',ratio*2000,calc('vayne_w','silver_bolts_damage',{rank,targetHP:2000}));record('vayne_w','rank'+rank+'1001目标最大生命小数',ratio*1001,calc('vayne_w','silver_bolts_damage',{rank,targetHP:1001}));}check('vayne_w','没有普通零冷却/零消耗或野怪专用参数',body('vayne_w').parameters.every(p=>!['cooldown_ms','mana_cost','monster_damage'].includes(p.parameterKey)));
for(const[rank,initial,wall,total]of [[1,100,150,250],[5,240,360,600]]){record('vayne_e','rank'+rank+'BAD100首段',initial,calc('vayne_e','initial_damage',{rank}));record('vayne_e','rank'+rank+'BAD100撞墙额外段',wall,calc('vayne_e','wall_bonus_damage',{rank}));record('vayne_e','rank'+rank+'BAD100两段总量',total,calc('vayne_e','with_wall_total_damage',{rank}));}check('vayne_e','实际普通命中未自动追加撞墙',body('vayne_e').triggerRules[0].actions.every(a=>a.detail.effectKey==='initial_damage'));
for(const[rank,ad,duration,qcd]of [[1,35,8000,4200],[2,50,10000,3600],[3,65,12000,3000]]){record('vayne_r','rank'+rank+'固定AD',ad,pv('vayne_r','bonus_attack_damage',rank));record('vayne_r','rank'+rank+'基础时长',duration,pv('vayne_r','base_duration_ms',rank));record('vayne_r','rank'+rank+'Q原6000ms缩短后',qcd,calc('vayne_r','tumble_cooldown_during_final_hour',{rank,runtime:{current_tumble_cooldown_ms:6000}}));}record('vayne_r','P从30替换90的差额为60',60,calc('vayne_r','night_hunter_extra_over_base'));check('vayne_r','不无条件加90且不任意死亡续时',body('vayne_r').effects.every(e=>e.results.every(r=>!['move_speed','move_speed_percent'].includes(r.detail.attributeKey)))&&body('vayne_r').triggerRules.length===0);
const out={at:new Date().toISOString(),candidateSha256:sha(bytes),boundary:'本地已冻结源与候选独立核算，不是API保存、浏览器或战斗证据。条件效果与未绑定输入仍按清单待配。',sourceChecks:hashes,arithmetic,invariants:checks,failures:[...hashes,...arithmetic,...checks].filter(c=>!c.match)};await writeFile(process.env.HERO7_CHECK_OUTPUT_PATH??new URL('后十技能独立核算.json',here),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({candidateSha256:out.candidateSha256,sources:hashes.length,arithmetic:arithmetic.length,invariants:checks.length,failures:out.failures}));if(out.failures.length)process.exitCode=1;
