// 默认只读；显式--apply还必须匹配根任务已授权的冻结摘要。没有PUT/DELETE。
import {mkdir,writeFile,appendFile} from 'node:fs/promises';
import {loadPlan,assertPlanUnchanged,verifySources,fullSnapshot,checkCatalogs,createMissing,verifySaved,independentArithmetic,approvedPlanSha256,here} from './录入工具.mjs';
const args=process.argv.slice(2);if(args.some(v=>v!=='--apply')||args.length>1)throw Error('只接受显式--apply');const apply=args.includes('--apply'),loaded=await loadPlan(),{plan,planSha256}=loaded;
if(apply&&approvedPlanSha256!==planSha256)throw Error('当前完整集合尚未获根任务写入授权，不执行POST');
const runId=new Date().toISOString().replace(/[:.]/g,'-'),runDir=new URL('执行记录/'+runId+'/',here);await mkdir(runDir,{recursive:true});await writeFile(new URL('候选快照.json',runDir),loaded.bytes,{flag:'wx'});
const report={runId,startedAt:new Date().toISOString(),mode:apply?'显式仅创建缺项':'默认只读',planSha256,scope:Object.keys(plan.skills),sources:[],catalogs:null,preflight:null,candidateArithmetic:null,events:[],failedSkills:[],final:null,errors:[]};
async function save(){const bytes=JSON.stringify(report,null,2)+'\n';await writeFile(new URL('执行结果.json',runDir),bytes);await writeFile(new URL(apply?'写入结果.json':'录入只读检查.json',here),bytes);}
try{
 report.sources=await verifySources(plan);report.catalogs=await checkCatalogs(plan);report.preflight=await fullSnapshot(plan);await writeFile(new URL('全量写前现值.json',runDir),JSON.stringify(report.preflight,null,2)+'\n',{flag:'wx'});await save();
 if(report.catalogs.failures.length||report.preflight.conflicts.length)throw Error('完整预检存在目录或现值冲突，不执行写入');report.candidateArithmetic=await independentArithmetic(plan,new URL('候选核算/',runDir));if(report.candidateArithmetic.failures.length)throw Error('候选独算失败');
 console.log(JSON.stringify({stage:'完整预检',same:report.preflight.readbacks.length,missing:report.preflight.missing.length,conflicts:0,sources:report.sources.length,arithmetic:report.candidateArithmetic.arithmetic.length,invariants:report.candidateArithmetic.invariants.length,apply}));
 if(apply){const result=await createMissing(plan,report.preflight,{assertFrozen:()=>assertPlanUnchanged(planSha256),journal:async event=>{report.events.push(event);await appendFile(new URL('写入流水.jsonl',runDir),JSON.stringify(event)+'\n');await appendFile(new URL('写入流水.jsonl',here),JSON.stringify({runId,planSha256,...event})+'\n');if(event.match===false)console.log(JSON.stringify({stage:'当前技能暂停',skill:event.skillKey,kind:event.kind,id:event.id,postStatus:event.postStatus,readbackStatus:event.readbackStatus,diff:event.diff}));}});report.failedSkills=result.failedSkills;report.final=await fullSnapshot(plan);report.verification=await verifySaved(plan,report.final,new URL('实库独算/',runDir));await writeFile(new URL('最终全量回读.json',runDir),JSON.stringify({snapshot:report.final,verification:report.verification},null,2)+'\n');if(report.verification.failures.length)report.errors.push({finalFailures:report.verification.failures.length});}
}catch(error){report.errors.push({message:String(error)});}finally{report.finishedAt=new Date().toISOString();await save();}
console.log(JSON.stringify({mode:report.mode,runId,planSha256,newConfirmed:report.events.filter(e=>e.postStatus>=200&&e.postStatus<300&&e.match).length,reconciledAfterError:report.events.filter(e=>e.action==='创建响应异常后查询落地'&&e.match).length,failedSkills:report.failedSkills,finalMissing:report.final?.missing.length??null,finalConflicts:report.final?.conflicts.length??null,errors:report.errors}));if(report.errors.length)process.exitCode=1;
