import {readFile} from 'node:fs/promises';
import {isDeepStrictEqual} from 'node:util';
import {plan,evidence,clean,val,fval,fixed,pn,attr,op,add,mul,behavior,life,begin,parameter,data,literal,formula,result,effect,damage,manaEffect,hit,pending,exclude} from './候选.mjs';
export {plan,evidence,clean,val,fval,fixed,pn,attr,op,add,mul,behavior,life,begin,parameter,data,literal,formula,result,effect,damage,manaEffect,hit,pending,exclude};
export const textEvidence=JSON.parse(await readFile(new URL('./补充文本证据.json',import.meta.url),'utf8'));
plan.meta.scope='蔚、奥拉夫、魔腾、薇恩20槽确定组成；公共参数精确复用，候选不写API。';
plan.meta.executor='Cursor SDK隔离副本负责蔚与奥拉夫候选；Codex执行代理负责魔腾与薇恩及集成，实际结果分别记账。';
export function runtime(x,key,name,description,type='DECIMAL'){x.c.write.parameters.push({parameterKey:key,name,valueType:type,valueMode:'RUNTIME_INPUT',fixedValue:null,levelValues:null,description,sortOrder:(x.c.write.parameters.length+1)*10});}
export const dynamic={moment:'PERSISTENT',valueReadMode:'MOMENT_EVALUATION',stackValueMode:'SHARED',reapplicationValueMode:null,periodicExecutionMode:null};
export function statEffect(x,key,name,value,attributeKey,{duration=null,target='SOURCE',operation='INCREASE',dynamicRead=false,description=null,zone='attribute_flat_add'}={}){const lifecycle=life(duration);if(target==='TARGET')lifecycle.instanceScope='SOURCE_TARGET';effect(x,key,name,[result('attribute',name,'ATTRIBUTE_CHANGE',target,value,{attributeKey,operation,modifierZoneKey:zone},dynamicRead?dynamic:behavior)],lifecycle,description??'独立持续属性；应用、取消与实际触发分别核对。');}
export function heal(x,key,name,formulaKey){effect(x,key,name,[result('heal',name,'DIRECT_HEAL','SOURCE',fval(formulaKey),{})]);}
export function rule(x,key,name,eventSource,effectKeys,conditions=[]){x.c.write.triggerRules.push({ruleKey:key,name,description:'只接受所列真实事件；不自行生成命中。',sortOrder:(x.c.write.triggerRules.length+1)*10,eventSource,conditionGroups:conditions.length?[{groupKey:'required',name:'必要条件',sortOrder:10,conditions}]:[],actions:effectKeys.map((effectKey,i)=>({actionKey:effectKey,name:'执行'+effectKey,actionType:'EXECUTE_EFFECT',sortOrder:(i+1)*10,targetContext:'CURRENT_TARGET',detail:{effectKey},runtimeInputBindings:[],resultModifiers:[]})),perTargetCooldown:null,maxTriggersPerProcess:null});}
export function cooldown(x,key,name,keys,value){effect(x,key,name,[result('cooldown',name,'COOLDOWN_CHANGE','SOURCE',value,{affectedSkillScope:{mode:'SKILLS',skillKeys:keys,skillCategoryKeys:[]},operation:'REDUCE'})]);}
export function common(x,{mana=true,cooldown=true}={}){const d=x.s.official,n=x.c.maxLevel;if(cooldown){const values=x.p.Cooldown?.values?.slice(1,n+1);if(!values||values.length!==n||!values.every((v,i)=>Math.abs(v-d.cooldown[i])<1e-4))throw Error('需要当前冷却数组来源 '+x.c.skillKey);literal(x,'cooldown_ms','基础冷却时间（毫秒）',values.map(v=>Math.round(v*1000)),'当前根Cooldown.values索引1起，官方逐级相同。','Cooldown.values+official.cooldown');}if(mana){const values=x.p.manaValues?.values?.slice(0,n);if(!values||values.length!==n||!values.every((v,i)=>Math.abs(v-d.cost[i])<1e-4))throw Error('需要当前法力消耗来源 '+x.c.skillKey);literal(x,'mana_cost','基础法力消耗',values,'当前根manaValues.values索引0起，官方逐级相同。','manaValues.values+official.cost');manaEffect(x);}}
export function processStart(x,{effects=[],stepKey='start',stepType='IMMEDIATE',detail={}}={}){const costs=x.c.write.effects.some(e=>e.effectKey==='mana_cost')?['mana_cost']:[],bindings=[...costs.map(effectKey=>({bindingKey:effectKey,effectKey,moment:{momentType:'PROCESS_START',stepKey:null},sortOrder:10})),...effects.map((effectKey,i)=>({bindingKey:effectKey,effectKey,moment:{momentType:'STEP_COMPLETE',stepKey},sortOrder:20+i*10}))];if(!bindings.length)throw Error('禁止无行为空过程');x.c.write.processes.push({processKey:'cast',name:'施放'+x.c.name,activationType:'ACTIVE',description:'仅已确证的施放成本、冷却与独立自益；不生成敌人命中。',sortOrder:10,cooldown:x.c.write.parameters.some(p=>p.parameterKey==='cooldown_ms')?{durationValue:val('cooldown_ms'),startMoment:{momentType:'PROCESS_START',stepKey:null}}:null,steps:[{stepKey,name:'施放开始',description:null,sortOrder:10,stepType,detail}],effectBindings:bindings,stateOperations:[]});}
export async function finalize(){const before=JSON.parse(await readFile(new URL('./写前现值.json',import.meta.url),'utf8'));for(const s of Object.values(plan.skills)){s.reusedParameters=[];s.write.parameters=s.write.parameters.map(p=>{const prev=before.skills[s.skillKey].components.parameters.find(v=>v.parameterKey===p.parameterKey);if(!prev)return p;if(['valueType','valueMode','fixedValue','levelValues'].some(k=>!isDeepStrictEqual(p[k],prev[k])))throw Error('公共参数冲突 '+s.skillKey+'/'+p.parameterKey);s.reusedParameters.push(p.parameterKey);return Object.fromEntries(Object.entries(prev).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k)));});for(const arr of Object.values(s.write)){const keys=arr.map(v=>v.parameterKey??v.formulaKey??v.effectKey??v.processKey??v.stateKey??v.ruleKey);if(new Set(keys).size!==keys.length)throw Error('重复组成 '+s.skillKey);}s.source.currentBoundText=textEvidence.skills[s.skillKey];s.disposition={范围外:s.excluded,来源待核:s.pending.filter(p=>p.kind==='来源'),系统缺口:s.pending.filter(p=>p.kind==='系统'),尚未接线:s.pending.filter(p=>!['来源','系统'].includes(p.kind))};s.status='确定组成候选；未保存或未接线不表示完整机制';}}
