import {begin,common,data,literal,formula,pn,attr,add,mul,op,val,damage,pending,exclude,statEffect,processStart,runtime,hit} from './英雄工具.mjs';
{
 const x=begin('vayne_p');data(x,'MovementSpeed','night_hunter_move_speed','朝附近英雄固定移动速度');statEffect(x,'night_hunter_move_speed','暗夜猎手条件移动速度',val('night_hunter_move_speed'),'move_speed',{description:'朝附近敌方英雄移动时才启用30固定移速，条件失效显式移除；不无条件初始化。R期间改为90的替换关系另配。'});pending(x,'附近英雄与移动朝向条件','当前说明同时限定附近敌方英雄与朝向移动；独立30移速效果没有初始化规则，不能对静止、远离或任意目标全时授予。');pending(x,'终极时刻替换成90移速','R期间暗夜猎手改为90，不是30+90；必须保留相同附近和朝向条件。');exclude(x,'2000距离检测','Range2000仅保留原文与条件依据，实际空间/方向检测后置；本体条件移速保留。');
}
{
 const x=begin('vayne_q');common(x);data(x,'TotalADRatio','bonus_total_ad_ratio','翻滚后额外伤害总攻击力系数');data(x,'APRatio','bonus_ap_ratio','翻滚后额外伤害法强系数');data(x,'Duration','empowered_attack_window_ms','翻滚后强化攻击窗口（毫秒）',{scale:1000});formula(x,'bonus_attack_damage','翻滚后额外物理伤害',add(mul(pn('bonus_total_ad_ratio'),attr('attack_damage')),mul(pn('bonus_ap_ratio'),attr('ability_power'))),'当前主说明明确额外伤害：.75/.85/.95/1.05/1.15总攻击力+.5法强；该公式不再加普通攻击本体。APRatio为明确命名的法强系数。');
 x.c.proofs.push({source:'mSpellCalculations.ADRatioBonus',raw:x.p.mSpellCalculations.ADRatioBonus},{source:'当前CanBonusDamageCrit缺values，不能猜0',raw:x.p.DataValues.find(v=>v.name==='CanBonusDamageCrit')});pending(x,'额外伤害暴击及法术护盾资格','当前CanBonusDamageCrit只有名称没有值，不能猜false；强化攻击额外伤害的暴击和技能交互应分别确认。当前只有完整额外量公式，暂不以DISALLOWED或null默认创建伤害效果。','来源');pending(x,'强化攻击消费、冷却开始与R联动','3秒窗口已确证，但下一次真实攻击消费、强化到期与冷却起始须核对；不直接假设普通施放起始冷却、自动制造命中。R期间Q冷却减少与1秒隐形仍待接线。');exclude(x,'翻滚空间执行','位移轨迹后置；法力、冷却、下次攻击额外伤害和与R的依赖保留。');
}
{
 const x=begin('vayne_w');data(x,'MaxHealthRatio','target_maximum_health_ratio','第三次命中目标最大生命比例');data(x,'DamageFloor','minimum_true_damage','圣银弩箭真实伤害保底');data(x,'DebuffDuration','same_target_window_ms','同目标标记持续时间（毫秒）',{scale:1000});literal(x,'consecutive_hit_threshold','同目标连续命中门槛',3,'当前主说明与摘要明确同一目标每第三次连续攻击或技能。');formula(x,'silver_bolts_damage','圣银弩箭有保底真实伤害',op('MAX',pn('minimum_true_damage'),mul(pn('target_maximum_health_ratio'),attr('hp','TARGET'))),'当前4/5.5/7/8.5/10%目标最大生命，至少40/55/70/85/100；不用2025旧Wiki的6–10%及50–110保底。');
 x.c.proofs.push({source:'当前根DataValues与主/扩展绑定文本',accepted:{ratios:[.04,.055,.07,.085,.1],floors:[40,55,70,85,100]},notAdopted:'旧Wiki2025-08-26及APRatio无values字段'});pending(x,'第三次连续攻击或技能资格与消费','需要同目标计数、3.5秒标记、合法攻击/技能集合、第三次消费与切目标清除；不能只接每次普攻，也不把任意技能施放当实际命中。');pending(x,'真实伤害结果的法术护盾资格','当前第三次触发与攻击/技能结果归属未完全核对；null不是未知占位，先保留确定伤害公式，待实际资格明确后补独立伤害效果。','来源');exclude(x,'野怪专用140–200伤害','本轮一名敌方英雄使用当前最大生命比例与保底；不引入DamageVsMonsters专用量。');
}
{
 const x=begin('vayne_e');common(x);data(x,'Damage','base_damage','恶魔审判直接基础伤害');data(x,'StunDamage','wall_bonus_multiplier','撞墙额外伤害倍率');data(x,'StunDuration','wall_stun_duration_ms','撞墙眩晕时长（毫秒）',{scale:1000});const c=x.p.mSpellCalculations.TotalDamage.mFormulaParts[1];if(c.mStat!==2||c.mStatFormula!==2||c.mCoefficient!==.5)throw Error('VayneE额外AD来源');literal(x,'bonus_ad_ratio','恶魔审判额外攻击力系数',.5,'TotalDamage计算树明确额外攻击力0.5。');formula(x,'initial_damage','恶魔审判直接伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'50/85/120/155/190+.5额外攻击力。');formula(x,'wall_bonus_damage','撞墙追加伤害',mul(add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),pn('wall_bonus_multiplier')),'当前EmpoweredDamageTT=1.5×TotalDamage，当前说明明确这是额外量；没有用它替换首次伤害。');formula(x,'with_wall_total_damage','直接命中并撞墙两次总伤害',add(add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),mul(add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),pn('wall_bonus_multiplier'))),'直接1倍+撞墙额外1.5倍，共2.5倍；该总量公式仅核算，不另建第三次总量伤害效果。');damage(x,'initial_damage','恶魔审判直接物理伤害','initial_damage','physics');damage(x,'wall_bonus_damage','实际撞墙追加物理伤害','wall_bonus_damage','physics');processStart(x);hit(x,'initial_damage');
 pending(x,'实际地形碰撞与追加伤害','直接实际命中规则只执行首次伤害；撞墙追加必须由真实地形碰撞确认，不能每次E自动追加，也不能把规则自身当碰撞事件。');pending(x,'撞墙眩晕与法术护盾期限','眩晕1.5秒参数保留；当前PERSISTENT+TARGET状态不能配置非空法术护盾范围，不用null或APPLICATION绕过期限与阻挡。','系统');exclude(x,'击退距离与地形空间算法','475击退距离和空间检测后置；首次本体伤害、撞墙额外伤害与控制需求保留。');
}
{
 const x=begin('vayne_r');common(x);data(x,'BonusAttackDamage','bonus_attack_damage','终极时刻固定攻击力');data(x,'BaseDuration','base_duration_ms','终极时刻基础持续（毫秒）',{scale:1000});data(x,'MovementSpeed','night_hunter_replacement_move_speed','R期间暗夜猎手替换移速');data(x,'DurationToAdd','duration_extension_ms','符合条件英雄死亡延长（毫秒）',{scale:1000});data(x,'DamagedMarkerDuration','damage_marker_window_ms','本人造成伤害后死亡判定窗口（毫秒）',{scale:1000});data(x,'TumbleCDReduction','tumble_cooldown_reduction_ratio','R期间Q冷却缩短比例',{scale:.01});data(x,'TumbleStealthDuration','tumble_invisibility_ms','R期间Q隐形持续（毫秒）',{scale:1000});literal(x,'ordinary_night_hunter_move_speed','P通常移速参考',30,'当前VayneP根MovementSpeed=30，用于说明R替换90相对普通增量，不再另加一份90。','vayne_p.DataValues.MovementSpeed');literal(x,'one','原始冷却倍率',1,'冷却缩短后倍率为1减缩短比例。');runtime(x,'current_tumble_cooldown_ms','当前Q等级未受本次R缩短的冷却输入','应由当前Q实际技能等级和合法冷却阶段提供；不是R自身冷却，不是Q当前剩余冷却，避免重复乘本次R缩短。当前尚未绑定。');formula(x,'night_hunter_extra_over_base','R期间P相对通常额外移速',op('SUBTRACT',pn('night_hunter_replacement_move_speed'),pn('ordinary_night_hunter_move_speed')),'90-30=60；只有同一P方向条件成立才可替换或加这个差额，不单独无条件加90。');formula(x,'tumble_cooldown_during_final_hour','R期间Q缩短后的冷却量',mul(pn('current_tumble_cooldown_ms'),op('SUBTRACT',pn('one'),pn('tumble_cooldown_reduction_ratio'))),'输入Q冷却×(1-.3/.4/.5)，只为独立数学关系；具体冷却阶段和施加方式未绑定，不把比例当作毫秒减少。');statEffect(x,'bonus_attack_damage','终极时刻自身攻击力',val('bonus_attack_damage'),'attack_damage',{duration:val('base_duration_ms'),description:'普通基础期限内增加35/50/65攻击力，持续8/10/12秒；符合条件死亡延长与最大期限限制另配。'});processStart(x,{effects:['bonus_attack_damage']});
 pending(x,'标记因果、死亡续时与最大期限','必须是被薇恩伤害后3秒内死亡的敌方英雄，才增加4秒。扩展说明限制最大期限，但未明确独立最大数值和与剩余期限的精确组合，不能接任意KILL或无上限续时。','来源');pending(x,'P替换与Q冷却缩短','P只有朝附近敌方英雄时由30改90；Q冷却输入必须是Q当前等级的合法口径而非R冷却或已经缩短过的值。独立公式未绑定，没有无条件90移速效果或比例当毫秒的冷却结果。');pending(x,'Q期间1秒隐形','隐形影响敌方选取与行动资格，不能以普通属性或纯视野说明代替；当前未具备完整隐形结果与动作门槛。','系统');
}
