import {readFile} from 'node:fs/promises';
import {begin,common,data,literal,formula,pn,attr,add,mul,val,fval,damage,pending,exclude,heal,statEffect,processStart,runtime,effect,result,life,rule,cooldown,behavior,hit} from './英雄工具.mjs';
{
 const x=begin('nocturne_p');data(x,'Cooldown','passive_cooldown_ms','暗影之刃基础冷却（毫秒）',{scale:1000});data(x,'AAChampMonsterCDR','champion_attack_cooldown_reduction_ms','攻击英雄减少被动冷却（毫秒）',{scale:1000});data(x,'TotalDamageNoCritADRatio','noncritical_total_ad_ratio','未暴击完整攻击总攻击力系数');data(x,'TotalDamageCritADRatio','critical_branch_total_ad_ratio','当前暴击分支总攻击力系数');data(x,'HealingAPRatio','healing_ap_ratio','单目标治疗法强系数');data(x,'HealLevel1Value','healing_level_one','1级基础治疗端点');data(x,'HealLevel18Value','healing_level_eighteen','18级基础治疗端点');
 runtime(x,'decoded_level_base_heal','当前等级已解码基础治疗','当前TotalHealing的哈希类型节点尚未解码；外部必须提供与当前等级对应的真实基础治疗，不能用端点默认线性插值或未知0。');formula(x,'noncritical_attack_damage','未暴击暗影之刃整次攻击伤害',mul(pn('noncritical_total_ad_ratio'),attr('attack_damage')),'1.2总攻击力为当前说明的整次非暴击攻击量，不另加一次普通攻击。');formula(x,'critical_branch_amount','当前暴击分支基础算术',mul(pn('critical_branch_total_ad_ratio'),attr('attack_damage')),'仅1.1总攻击力分支算术，未证明该分支与普通攻击暴击的组成和倍率，不能直接统一暴击。');formula(x,'single_target_heal','命中一个目标治疗量',add(pn('decoded_level_base_heal'),mul(pn('healing_ap_ratio'),attr('ability_power'))),'已解码等级基础治疗+.3法强；HealingAPRatio明确命名，哈希等级插值输入仍未接入。');heal(x,'single_target_heal','暗影之刃单目标自身治疗','single_target_heal');cooldown(x,'champion_attack_cooldown_reduction','攻击英雄减少被动冷却',['nocturne_p'],val('champion_attack_cooldown_reduction_ms'));
 x.c.proofs.push({source:'mSpellCalculations.TotalHealing',raw:x.p.mSpellCalculations.TotalHealing},{source:'mSpellCalculations.TotalDamageNoCrit/TotalDamageCrit',raw:[x.p.mSpellCalculations.TotalDamageNoCrit,x.p.mSpellCalculations.TotalDamageCrit]});pending(x,'治疗基础值哈希节点','{ee18a47b}节点读取HealLevel1Value13与HealLevel18Value32，但当前资料未给出完整插值函数；端点与外部输入保留，不生成1至18级直线。','来源');pending(x,'非暴击与暴击攻击组成及法术护盾','当前根保留1.2与1.1总攻击力两分支，但暴击倍率分配、攻击本体替换和附伤法术护盾资格未确证，暂只保留公式，不设未知阻挡粒度。','来源');pending(x,'就绪、实际强化攻击和治疗联动','必须在被动就绪后接受下一次真实攻击，按实际命中一个目标治疗一次；治疗基础输入生产、冷却消费和英雄普通攻击减3秒尚未绑定。');exclude(x,'周围其他敌人、小兵与野怪支路','保留一名英雄目标的本体伤害、自身治疗和英雄攻击减冷却；多目标查询、小兵半伤半疗及普通目标1秒减冷却不进入本轮组成。');
}
{
 const x=begin('nocturne_q');common(x);data(x,'BaseDamage','base_damage','梦魇之径基础物理伤害');data(x,'MoveSpeed','trail_move_speed_ratio','影径上移动速度比例',{scale:.01});data(x,'BonusTrailAD','trail_attack_damage','影径上固定攻击力');data(x,'TrailDuration','trail_lifetime_ms','影径存在时间（毫秒）',{scale:1000});const c=x.p.mSpellCalculations.TotalDamage.mFormulaParts[1];if(c.mStat!==2||c.mStatFormula!==2)throw Error('NocturneQ额外攻击力来源');literal(x,'bonus_ad_ratio','梦魇之径额外攻击力系数',Math.round(c.mCoefficient*1e6)/1e6,'当前计算树mStat2/mStatFormula2，额外攻击力系数0.85。');formula(x,'damage','梦魇之径命中伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'65/105/145/185/225+.85额外攻击力。');damage(x,'damage','梦魇之径物理伤害','damage','physics');processStart(x);hit(x,'damage');
 effect(x,'on_trail_attributes','处于影径时自身属性',[result('move_speed','影径移动速度','ATTRIBUTE_CHANGE','SOURCE',val('trail_move_speed_ratio'),{attributeKey:'move_speed_percent',operation:'INCREASE',modifierZoneKey:'attribute_flat_add'},behavior),{...result('attack_damage','影径攻击力','ATTRIBUTE_CHANGE','SOURCE',val('trail_attack_damage'),{attributeKey:'attack_damage',operation:'INCREASE',modifierZoneKey:'attribute_flat_add'},behavior),sortOrder:20}],life(null),'只有身处影径时有效，按显式移除结束；5秒是影径寿命，不是离开影径后仍持续5秒的独立增益。进入/离开条件未接线。');pending(x,'影径进入与离开时自益启停','影径有5秒寿命，在影径上获得20–40%移动速度和15–55攻击力。独立条件属性不自动授予，离开时需按来源移除，不能给所有Q施放固定5秒自益。');exclude(x,'影径空间、多目标留迹和幽灵碰撞','空间查找和碰撞穿越后置；实际本体伤害及自己在合法影径上的收益保留。');
}
{
 const x=begin('nocturne_w');common(x);data(x,'ActiveAS','passive_attack_speed_ratio','黑暗庇护被动额外攻速比例',{scale:.01});data(x,'ShieldDuration','spell_shield_duration_ms','黑暗庇护普通屏障持续（毫秒）',{scale:1000});data(x,'DoubleASDuration','empowered_attack_speed_duration_ms','成功格挡后双倍攻速时长（毫秒）',{scale:1000});literal(x,'on_block_total_multiplier','成功格挡后被动总倍率',2,'当前绑定ActiveAS*2明确提升至两倍，原被动已有一倍，因此额外只加一倍。');formula(x,'total_attack_speed_after_block','格挡后合计被动攻速',mul(pn('passive_attack_speed_ratio'),pn('on_block_total_multiplier')),'30–50%原被动+30–50%临时增量=60–100%；仅合计参考，不将两倍再叠到原被动。');statEffect(x,'passive_attack_speed','黑暗庇护常驻被动攻速',val('passive_attack_speed_ratio'),'bonus_attack_speed_percent');statEffect(x,'on_block_additional_attack_speed','成功格挡额外一倍攻速',val('passive_attack_speed_ratio'),'bonus_attack_speed_percent',{duration:val('empowered_attack_speed_duration_ms'),description:'在原本30–50%被动之上只追加30–50%，5秒后移除增量。'});
 const ref=JSON.parse(await readFile(new URL('./成熟法术护盾参考.json',import.meta.url),'utf8')),get=suffix=>Object.fromEntries(Object.entries(structuredClone(ref.records.find(r=>r.route.endsWith(suffix)).data)).filter(([k])=>!['gameId','skillKey','createdAt','updatedAt'].includes(k))),shield=get('/effects/spell_shield'),consume=get('/effects/consume_spell_shield');shield.name='黑暗庇护法术护盾';shield.description='普通施放产生一层屏障，1.5秒自然结束或成功格挡后显式消费；R飞行保持激活分支另配。';shield.lifecycle={...life(val('spell_shield_duration_ms')),reapplicationStackMode:'REPLACE'};shield.sortOrder=(x.c.write.effects.length+1)*10;consume.name='黑暗庇护成功格挡消费';consume.sortOrder=shield.sortOrder+10;x.c.write.effects.push(shield,consume);processStart(x,{effects:['spell_shield']});rule(x,'consume_and_empower_on_block','本技能屏障成功格挡后消费并增攻速',{eventType:'SPELL_SHIELD_BLOCKED',detail:{shieldEffectKey:'spell_shield'}},['consume_spell_shield','on_block_additional_attack_speed']);
 x.c.proofs.push({source:'当前绑定ActiveAS而非旧PassiveAS',accepted:x.p.DataValues.find(v=>v.name==='ActiveAS'),notAdopted:x.p.DataValues.find(v=>v.name==='PassiveAS')},{source:'成熟法术护盾参考.json',reference:'item_4632_passive：SPELL_SHIELD及成功格挡消费形状，仅复用结构，不继承装备60秒重获'});pending(x,'常驻被动的有效技能等级启用','独立被动属性已配置，仍需由合法的已学习W技能上下文启用与移除；不为尚未学习W的角色自动初始化攻速。');pending(x,'R飞行期间保持屏障激活','当前扩展说明明确R飞行中保持激活；与普通1.5秒屏障期限及成功格挡消费如何组合仍需跨技能阶段接线，不能把飞行过程按固定1.5秒完整宣称。');
}
{
 const x=begin('nocturne_e');common(x);data(x,'DamageToDeal','total_base_damage','完整灵链基础伤害总量');data(x,'CCDuration','fear_duration_ms','不断链恐惧时长（毫秒）',{scale:1000});data(x,'LeashDuration','leash_duration_ms','完整灵链持续（毫秒）',{scale:1000});data(x,'TooltipFearMS','toward_feared_move_speed_ratio','朝恐惧敌人移动速度比例');const c=x.p.mSpellCalculations.TotalDamage.mFormulaParts[1];literal(x,'unresolved_stat_coefficient','完整灵链未定属性系数',c.mCoefficient,'当前StatByCoefficientCalculationPart系数1.0，属性/总量枚举省略，尚未复用可靠默认解码。');runtime(x,'resolved_scaling_attribute','灵链伤害已解码属性输入','当前省略mStat/mStatFormula，待同版本默认解码确定后接入；不能猜AP或未知0。');formula(x,'full_leash_damage','完整两秒灵链伤害总量',add(pn('total_base_damage'),mul(pn('unresolved_stat_coefficient'),pn('resolved_scaling_attribute'))),'80/125/170/215/260 + 1×已解码属性，只是完整2秒总量，不能当每跳伤害。');processStart(x);statEffect(x,'toward_feared_move_speed','朝恐惧敌人条件移动速度',val('toward_feared_move_speed_ratio'),'move_speed_percent',{description:'只在朝受恐惧敌人移动的条件成立期间启用，并在条件失效时显式移除；没有无条件初始化。'});
 pending(x,'伤害属性默认值与逐次执行','当前总量的属性节点未显式枚举；2秒只证明完整总时长，没有确证跳频、首跳或每跳分配，故暂不建伤害效果或周期过程。','来源');pending(x,'恐惧状态与法术护盾期限','当前状态目录没有恐惧；不能用眩晕替代。若目标状态需要持续结束且参与法术护盾，当前持续目标控制组合还有独立缺口。','系统');pending(x,'链持续资格、恐惧与方向移动速度','只有灵链在结束时仍未断才恐惧；朝恐惧敌人的90%移动速度条件未接，不能把2秒计时当实际完整链，也不无条件授予移速。');exclude(x,'灵链空间距离检测','465距离字段保留原文，空间执行后置，不取消本体伤害与恐惧控制的范围内需求。');
}
{
 const x=begin('nocturne_r');common(x);data(x,'BaseDamage','base_damage','再次施放抵达目标基础伤害');data(x,'ParanoiaDuration','recast_window_ms','再次施放允许窗口（毫秒）',{scale:1000});const c=x.p.mSpellCalculations.Damage.mFormulaParts[1];if(c.mStat!==2||c.mStatFormula!==2)throw Error('NocturneR额外攻击力来源');literal(x,'bonus_ad_ratio','鬼影重重额外攻击力系数',Math.round(c.mCoefficient*1e6)/1e6,'当前Damage树明确额外攻击力系数1.2。');formula(x,'arrival_damage','再次施放实际抵达伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'150/275/400+1.2额外攻击力；只在再次施放实际抵达时交付一次。');damage(x,'arrival_damage','鬼影重重抵达物理伤害','arrival_damage','physics');pending(x,'初施与再施分阶段及一次命中','6秒窗口中允许再次施放；法力与基础冷却应归于合法初施，真实抵达才伤害。当前只保留独立成本、冷却和伤害，未把初施与再施都接actual_hit或重复消耗。');pending(x,'黑暗庇护在飞行中保持','NocturneW当前扩展有保持激活提醒；飞行结束、1.5秒普通期限与成功格挡的组合需接线。');exclude(x,'纯视野、飞行空间与全地图目标遍历','视野压缩、移除队友视野及空间导航后置；6秒再次施放依赖和对本次敌方英雄的实际伤害保留。');
}
