package xyz.game.datamanage.model.skilltrigger;

public enum SkillTriggerEventType {
    SOURCE_INITIALIZED,
    SKILL_USED,
    BASIC_ATTACK_START,
    BASIC_ATTACK_HIT,
    SKILL_HIT,
    PROCESS_MOMENT,
    RESULT_AVAILABLE,
    LIFECYCLE_MOMENT,
    DAMAGE_PENDING,
    DAMAGE_DEALT,
    DAMAGE_TAKEN,
    STATUS_CHANGED,
    HEALTH_THRESHOLD_CROSSED,
    INTERNAL_STATE_CHANGED,
    CONTROL_RECEIVED,
    ENTITY_DIED,
    ENTITY_UNTARGETABLE,
    KILL,
    TAKEDOWN,
    PROCESS_CANCEL_REQUESTED,
    SPELL_SHIELD_BLOCKED,
    HIT_LINK_APPLIED,
    ATTACK_LINK_APPLIED
}
