package xyz.game.datamanage.model.skilltrigger;

public enum SkillTriggerEventValueKey {
    STEP_EXECUTION_INDEX,
    CHARGE_DURATION_MS,
    RECAST_COUNT,
    HIT_INDEX,
    LIFECYCLE_STACKS,
    PERIOD_INDEX,
    REMAINING_MS,
    STATE_BEFORE,
    STATE_AFTER,
    ATTRIBUTE_BEFORE,
    ATTRIBUTE_AFTER,
    THRESHOLD_VALUE,
    RAW_DAMAGE,
    POST_DEFENSE_DAMAGE,
    HEALTH_BEFORE,
    PROJECTED_HEALTH_AFTER,
    SHIELD_ABSORBED,
    ACTUAL_HP_LOSS,
    BLOCKED,
    IMMUNE,
    KILLED,
    LINK_INDEX,
    LINK_COUNT
}
