import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import zlib from 'node:zlib';import {fileURLToPath} from 'node:url';
if(process.argv.length!==2)throw Error('只生成候选，没有业务写入口');
const here=path.dirname(fileURLToPath(import.meta.url)),base=path.dirname(here),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),save=(name,x)=>fs.writeFileSync(path.join(here,name),JSON.stringify(x,null,2)+'\n',{flag:'wx'});
assert(!fs.existsSync(path.join(here,'可审查请求.json')),'已有候选不覆盖');
const frozenBytes=fs.readFileSync(path.join(here,'冻结来源.json'));assert.equal(sha(frozenBytes),'878fd1147a277282f6bacd04ecddafe55e980e729a67d4469b31b2ff93d492a7');
const frozen=JSON.parse(frozenBytes),byId=new Map(frozen.entries.map(e=>[e.id,e])),raw=zlib.gunzipSync(fs.readFileSync(path.join(base,'符文客户端数值补证/perks-16.17.cdtb.bin.json.gz')));assert.equal(sha(raw),frozen.rawSha256);const originals=JSON.parse(raw);for(const e of byId.values()){assert.deepEqual(e.object,originals[e.sourcePath]);assert.equal(sha(JSON.stringify(e.object)),e.sourceObjectSha256);}
const P=parameterKey=>({nodeType:'PARAMETER',parameterKey});
const A=(attributeOwner,attributeKey,attributeValueKind)=>({nodeType:'ATTRIBUTE',attributeOwner,attributeKey,attributeValueKind});
const O=(operation,a,b)=>({nodeType:'OPERATION',operation,operands:[a,b]});
const add=(a,b)=>O('ADD',a,b),mul=(a,b)=>O('MULTIPLY',a,b),sub=(a,b)=>O('SUBTRACT',a,b);
const fixed=value=>({kind:'FIXED',value});
const proposals=[];
function proposal(id,scopeText){const e=byId.get(id);const x={id,runeKey:`rune_${id}`,skillKey:`rune_${id}_passive`,name:e.name,scope:scopeText,sourcePath:e.sourcePath,sourceObjectSha256:e.sourceObjectSha256,parameters:[],formulas:[],effects:[],triggerRules:[],processes:[],internalStates:[],parameterEvidence:[],pending:[],excluded:[],qualification:{required:[],notDefaulted:[]}};proposals.push(x);return x;}
function parameter(x,key,name,value,description,{field,scale=1,category='来源确定',runtime=false,type}={}){
 const sourceValues=byId.get(x.id).object.mScript.mSpellScriptData.mEffectAmount;
 if(field){assert.ok(Object.hasOwn(sourceValues,field),`${x.id}/${field}`);assert.ok(Math.abs(sourceValues[field]*scale-value)<Math.max(1e-6,Math.abs(value)*1e-7),`${x.id}/${field} numeric`);}
 x.parameters.push({parameterKey:key,name,valueType:type||(runtime?'DECIMAL':Number.isInteger(value)?'INTEGER':'DECIMAL'),valueMode:runtime?'RUNTIME_INPUT':'FIXED',fixedValue:runtime?null:value,levelValues:null,description,sortOrder:(x.parameters.length+1)*10});
 x.parameterEvidence.push({parameterKey:key,category,sourcePath:field?`${x.sourcePath}/mScript/mSpellScriptData/mEffectAmount/${field}`:null,sourceRawValue:field?sourceValues[field]:null,scale,normalization:field&&sourceValues[field]*scale!==value?'同版本绑定说明的可读数值；仅清除float32尾差，容差1e-7相对值':null,defaultSupplied:!runtime});
}
const runtime=(x,key,name,description,type='DECIMAL')=>parameter(x,key,name,null,description,{runtime:true,type,category:'未接线输入'});
function formula(x,key,name,expression,description){x.formulas.push({formulaKey:key,name,description,sortOrder:(x.formulas.length+1)*10,expression});}
function pending(x,type,reason,needed){x.pending.push({type,reason,needed});}
function fixedAttribute(x,key,name,attr,param,description){
 x.effects.push({effectKey:key,name,description,sortOrder:(x.effects.length+1)*10,lifecycle:{durationValue:null,maxStacksValue:fixed(1),applicationStacksValue:fixed(1),instanceScope:'SOURCE',reapplicationStackMode:'KEEP',reapplicationDurationMode:null,expiryMode:'EXPLICIT_ONLY',periodicIntervalValue:null,firstPeriodicExecution:null},results:[{resultKey:'attribute_bonus',name,description:null,sortOrder:10,resultType:'ATTRIBUTE_CHANGE',target:'SOURCE',lifecycleBehavior:{moment:'PERSISTENT',valueReadMode:'APPLICATION_SNAPSHOT',stackValueMode:'SHARED',reapplicationValueMode:'REPLACE',periodicExecutionMode:null},spellShieldBlockScope:null,valueRule:{value:{kind:'PARAMETER',parameterKey:param},fixedMultiplier:1,fixedMinValue:0,fixedMaxValue:null},detail:{attributeKey:attr,operation:'INCREASE',modifierZoneKey:'attribute_flat_add'}}]});
}
const direct=(x,key,name,value,field,scale=1,description='当前普通模式绑定数值。')=>parameter(x,key,name,value,description,{field,scale});
function curve(x,key,label,start,end,fieldStart,fieldEnd){
 direct(x,key+'_source_start',label+'来源起点',start,fieldStart,1,'仅保留当前来源起点，不凭端点生成1至18级表。');direct(x,key+'_source_end',label+'来源终点',end,fieldEnd,1,'仅保留当前来源终点；等级求值过程待补。');
 runtime(x,key,'已确认'+label,'应由当前等级的已核实来源供值；没有默认值，不按1至18级线性猜算。');pending(x,'来源',label+'曲线起止等级、选项、取整及断点求值未完整证实','同构建的完整求值依据；本批显式外供数值');
}
function damageFormula(x,key,base,apField,adField,apValue,adValue,label='伤害数值'){
 let expression=P(base);if(apField){direct(x,'ability_power_ratio','法术强度系数',apValue,apField);expression=add(expression,mul(A('SOURCE','ability_power','TOTAL'),P('ability_power_ratio')));}
 if(adField){direct(x,'bonus_attack_damage_ratio','额外攻击力系数',adValue,adField);expression=add(expression,mul(A('SOURCE','attack_damage','BONUS'),P('bonus_attack_damage_ratio')));}
 formula(x,key,label,expression,'对应当前绑定计算树；等级基础值须明确外供。法强与额外攻击力直接读取来源属性，不填虚构值。');
}
function qualify(x,required,reason){x.qualification.required=required;x.qualification.notDefaulted=['未满足资格也生效','来源创建后自动触发','未知等级数值默认为0'];pending(x,'未接线',reason,'核实触发资格、取值时点和对象归属后装配');}
function sourceOnly(x,fields,reason,type='来源待核'){x.sourceOnly??=[];for(const field of fields)x.sourceOnly.push({field,raw:byId.get(x.id).object.mScript.mSpellScriptData.mEffectAmount[field],type,reason});}
function time(x,key,name,value,field){direct(x,key,name,value*1000,field,1000,'来源秒转换为毫秒；不表示已经连接事件。');}
function snapshotAttribute(x,key,name,attributeKey,formulaKey,{duration=null,description}={}){fixedAttribute(x,key,name,attributeKey,'__replace__',description);const e=x.effects.at(-1);e.results[0].valueRule.value={kind:'FORMULA',formulaKey};if(duration){e.lifecycle.durationValue={kind:'PARAMETER',parameterKey:duration};e.lifecycle.reapplicationDurationMode='REFRESH_ALL';e.lifecycle.expiryMode='ALL_AT_ONCE';}}
{
 const x=proposal(8005,'强攻第三次连续普攻伤害与8%增伤比例；持续资格为英雄战斗状态');curve(x,'confirmed_level_damage','等级基础伤害',40,160,'MinDamage','MaxDamage');formula(x,'third_attack_damage','第三次攻击额外伤害数值',P('confirmed_level_damage'),'等级伤害显式外供，适应类型及命中资格未连接。');direct(x,'required_hits','连续普攻次数',3,'HitsRequired');direct(x,'damage_amp_ratio','伤害增幅比例',.08,'BonusPercentDamage');time(x,'cooldown_ms','三击冷却时间',6,'Cooldown');
 runtime(x,'qualified_damage_basis','已确认的可增幅伤害基数','由实际结算资格供值，抗性前后阶段与适用结果类型需单独核实，不默认用技能基础伤害。');formula(x,'additional_damage','合格伤害的增幅量',mul(P('qualified_damage_basis'),P('damage_amp_ratio')),'仅数值；增伤状态须持续到离开与英雄战斗，不能固定5秒。');
 sourceOnly(x,['BonusADRatio','APRatio','LethalityRatio','AmpPotencyMaxSelf','AmpDuration','AmpPotencyMaxOthers','AmpPotencyStartSelf','AmpPotencyStartOthers','TimeBetweenHits','OutOfCombatTimer'],'当前正文使用BonusPercentDamage与脱离英雄战斗资格；其余旧/重复字段无当前消费链，不据此生成5秒固定增伤或4秒命中窗。');qualify(x,['连续3次普攻命中同一英雄','三击冷却可用','增幅只在合法英雄战斗状态存在'],'连续命中、战斗状态结束及增幅结算阶段未接线');
}
{
 const x=proposal(8008,'致命节奏近战确定攻速分支、满层伤害与远程来源冲突');time(x,'buff_duration_ms','层数持续时间',6,'Duration');direct(x,'max_stacks','层数上限',6,'MaxStacks');direct(x,'melee_as_per_stack','近战每层额外攻速比例',.06,'TTASPerStackMelee');runtime(x,'actual_stacks','实际层数','仅已确认0至6的整数；不默认满层。','INTEGER');runtime(x,'confirmed_ranged_as_per_stack','已确认远程每层攻速比例','来源冲突：当前ASPerStack计算0.06×0.8=0.048，长说明TTASPerStackRanged=0.04；本批不选择任一值。');
 curve(x,'confirmed_melee_level_damage','近战等级附伤',9,30,'TTMinNoteDamageMelee','TTMaxNoteDamageMelee');runtime(x,'confirmed_ranged_level_damage','已确认远程等级附伤','计算树为近战9至30乘0.667，约6.003至20.01；长说明为6至24。冲突未解决，无默认值。');runtime(x,'confirmed_bonus_attack_speed_ratio','已确认额外攻速比例','当前原树mStat4/formula2未纳入已证属性枚举；长说明明确每1%额外攻速令伤害增加1%，这里显式提供比例而不猜字典映射。');parameter(x,'one','一倍基准',1,'显式计算树乘数1+额外攻速比例。',{category:'当前绑定计算树'});
 formula(x,'melee_attack_speed_amount','近战当前层数额外攻速',mul(P('melee_as_per_stack'),P('actual_stacks')),'仅当前近战分支及已确认层数。');formula(x,'ranged_attack_speed_amount','远程当前层数额外攻速',mul(P('confirmed_ranged_as_per_stack'),P('actual_stacks')),'远程源冲突数值必须由后续已核实来源供值。');for(const type of ['melee','ranged'])formula(x,type+'_full_stack_damage',(type==='melee'?'近战':'远程')+'满层攻击额外伤害',mul(P('confirmed_'+type+'_level_damage'),add(P('one'),P('confirmed_bonus_attack_speed_ratio'))),'只有实际满6层时使用；不以测试输入证明等级曲线或mStat4映射。');
 snapshotAttribute(x,'melee_current_attack_speed','近战当前层数攻速组成','attack_speed','melee_attack_speed_amount',{duration:'buff_duration_ms',description:'仅近战、真实层数已确认时应用一份总攻速快照，6秒后移除；更新时替换总值，不再按生命周期重复叠6层。真实获取/刷新未连接。'});
 sourceOnly(x,['TTASPerStackRanged','TTMinNoteDamageRanged','TTMaxNoteDamageRanged'],'与当前具名计算存在数值冲突，原值完整保留但不进入普通固定参数。','来源冲突');sourceOnly(x,['PerfectlyTimedForgivance'],'只用于统计完美时机普攻比例，不改变本轮伤害或攻速。','范围外');pending(x,'来源冲突','远程攻速4.8%与4%、远程伤害6.003至20.01与6至24不同','同版本实际消费链或明确修订来源');qualify(x,['攻击敌方英雄形成真实层数','真实近远程分类','满层附伤仅实际达到6层','远程冲突先补证'],'层数刷新、适应类型和攻击特效资格未接线');
}
{
 const x=proposal(8010,'征服者真实层数适应之力和满层按实际造成伤害自疗');curve(x,'confirmed_adaptive_per_stack','每层适应之力',1.8,4,'MinAdaptivePerStack','MaxAdaptivePerStack');direct(x,'max_stacks','最大层数',12,'MaxStacks');time(x,'buff_duration_ms','层数持续时间',5,'BuffDuration');direct(x,'melee_heal_ratio','近战伤害转治疗比例',.08,'HealingPercent');direct(x,'ranged_heal_ratio','远程伤害转治疗比例',.05,'RangedHealingPercent');parameter(x,'normal_hit_stacks','普通技能或近战普攻层数',2,'当前正文明确命中提供2层。',{category:'当前绑定正文'});parameter(x,'ranged_attack_stacks','远程普攻层数',1,'当前正文明确远程普攻只提供1层。',{category:'当前绑定正文'});runtime(x,'actual_stacks','实际征服者层数','已确认0至12的整数，不默认满层。','INTEGER');runtime(x,'actual_damage_dealt_to_champion','本次实际对英雄造成的合格伤害','来自实际结算，不能用基础伤害、抗性前理论伤害或未发生的攻击代替。');
 formula(x,'adaptive_force_amount','当前层数适应之力',mul(P('confirmed_adaptive_per_stack'),P('actual_stacks')),'适应属性选择尚未连接，不默认AD=0.6×适应之力。');for(const t of ['melee','ranged'])formula(x,t+'_self_heal',(t==='melee'?'近战':'远程')+'满层自身治疗数值',mul(P('actual_damage_dealt_to_champion'),P(t+'_heal_ratio')),'仅实际满12层且本次伤害资格成立；不自动恢复，不生成瞬时治疗结果。');sourceOnly(x,['TimeUntilNextStackFromSameSpell'],'原4秒字段的同技能重复授予规则未由当前正文证明，待消费链补证。');qualify(x,['实际达到12层才可按伤害自疗','伤害确实对英雄造成','实际近远程分类与适应选择'],'同技能事件去重、层数过期、治疗取样和恢复时点未接线');
}
{
 const x=proposal(8021,'迅捷步法近远程恢复、移动速度与小兵战前恢复分支');curve(x,'confirmed_level_heal','等级基础恢复',15,160,'HealBase','HealMax');direct(x,'bonus_ad_ratio','额外攻击力恢复系数',.1,'HealBonusADRatio');direct(x,'ap_ratio','法强恢复系数',.05,'HealAPRatio');direct(x,'melee_move_speed_ratio','近战移动速度比例',.2,'MSBuff');time(x,'move_speed_duration_ms','移动速度持续',1,'MSDuration');direct(x,'ranged_move_speed_multiplier','远程移动速度效能',.75,'RangedMSMod');direct(x,'ranged_heal_multiplier','远程治疗效能',.6,'RangedHealMod');direct(x,'minion_heal_multiplier','小兵治疗效能',.15,'MinionHealMod');parameter(x,'required_energy','充盈所需层数',100,'当前正文明确100层。',{category:'当前绑定正文'});
 const heal=add(add(P('confirmed_level_heal'),mul(A('SOURCE','attack_damage','BONUS'),P('bonus_ad_ratio'))),mul(A('SOURCE','ability_power','TOTAL'),P('ap_ratio')));formula(x,'melee_heal','近战充盈恢复数值',heal,'当前树明确额外AD与法强；等级节点包含mScaleByStatProgressionMultiplier=true，不能线性展开。');formula(x,'ranged_heal','远程充盈恢复数值',mul(heal,P('ranged_heal_multiplier')),'对远程英雄施加0.6效能。');formula(x,'melee_minion_heal','近战攻击小兵自身恢复',mul(heal,P('minion_heal_multiplier')),'小兵不是英雄伤害目标，但这份自身战前恢复依赖保留。');formula(x,'ranged_minion_heal','远程攻击小兵自身恢复',mul(mul(heal,P('ranged_heal_multiplier')),P('minion_heal_multiplier')),'远程0.6与小兵0.15分别适用，两条件同时成立。');formula(x,'ranged_move_speed_ratio','远程移动速度增益比例',mul(P('melee_move_speed_ratio'),P('ranged_move_speed_multiplier')),'0.2×0.75=0.15；不把它直接加到固定移速属性区。');qualify(x,['真实积攒100层并由下一次合法攻击消费','真实近远程分类','按被攻击对象判断小兵恢复效能'],'能量生成与消费、治疗时点及百分比移速合并未连接');pending(x,'来源','未命名恢复计算{ad820ad4}的5至100未被当前正文引用','不以未绑定树替换当前HealAmount15至160');
}
{
 const x=proposal(8230,'当前风暴掠袭者狂涌的伤害阈值、近远程移动速度和减速抗性');time(x,'damage_window_ms','累计伤害窗口',3,'Window');time(x,'buff_duration_ms','增益持续',4,'Duration');direct(x,'target_max_health_threshold_ratio','目标最大生命伤害阈值比例',.25,'DamageThreshold');direct(x,'melee_move_speed_ratio','近战移动速度增益比例',.48,'HasteMax');direct(x,'ranged_move_speed_multiplier','远程移动速度效能',.75,'RangedEffectiveness');direct(x,'slow_resistance_ratio','减速抗性比例',.5,'SlowResist');curve(x,'confirmed_cooldown_seconds','等级冷却秒数',20,10,'MaxCooldown','MinCooldown');parameter(x,'seconds_to_ms','秒转毫秒系数',1000,'单位换算常数。',{category:'单位換算'});formula(x,'target_damage_threshold','累计伤害门槛数值',mul(A('TARGET','hp','TOTAL'),P('target_max_health_threshold_ratio')),'目标最大生命乘0.25，采样时点待连接；不是三次独立命中。');formula(x,'ranged_move_speed_ratio','远程移动速度增益比例',mul(P('melee_move_speed_ratio'),P('ranged_move_speed_multiplier')),'0.48×0.75=0.36。');formula(x,'cooldown_ms','已确认等级冷却毫秒',mul(P('confirmed_cooldown_seconds'),P('seconds_to_ms')),'只转换已确认等级数值，不从20至10猜线性。');qualify(x,['3秒内对同一英雄累计造成其25%最大生命伤害','冷却可用','按真实近远程分类'],'伤害累计、门槛属性采样和两种百分比效果的合并规则未接线');
}
{
 const x=proposal(8299,'坚毅不倒生命门槛和增伤端点，不生成中间插值');direct(x,'health_threshold_start','自身生命上门槛',.6,'HealthThresholdStart');direct(x,'health_threshold_end','自身生命最大增幅门槛',.3,'HealthThresholdEnd');direct(x,'min_damage_amp_ratio','来源最小增幅比例',.05,'MinBonusDamagePercent');direct(x,'max_damage_amp_ratio','来源最大增幅比例',.11,'MaxBonusDamagePercent');runtime(x,'confirmed_damage_amp_ratio','已确认当前生命比例增幅','60%至30%之间求值未证；30%边界正文与规则措辞不同，不能猜线性或相等边界。');runtime(x,'qualified_damage_basis','已确认合格伤害基数','结算阶段和结果资格需外供，不默认技能基础伤害。');formula(x,'additional_damage','当前已确认增幅伤害',mul(P('qualified_damage_basis'),P('confirmed_damage_amp_ratio')),'仅外供比例，实际低生命资格单独连接。');formula(x,'maximum_branch_additional_damage','严格低于30%时最大增幅伤害',mul(P('qualified_damage_basis'),P('max_damage_amp_ratio')),'两段当前文本均支持严格低于30%时11%；不替代未证中间函数。');qualify(x,['自身当前生命低于60%','合格英雄伤害','实际生命比例对应增幅已确认'],'生命采样与增伤结算阶段未连接');pending(x,'来源','30%恰好相等时，长文“在30%”与规则“低于30%”存在边界措辞差异','相等边界及中间完整求值');
}
{
 const x=proposal(8401,'护盾猛击等级基础伤害、2.5%额外生命与15%新护盾值');curve(x,'confirmed_level_damage','等级基础伤害',5,30,'ProcBaseMin','ProcBaseMax');direct(x,'bonus_health_ratio','额外生命伤害比例',.025,'BonusHealthRatio',.01);direct(x,'new_shield_ratio','新护盾伤害比例',.15,'ShieldRatio',.01);time(x,'after_shield_expiry_window_ms','护盾消散后可用窗口',2,'ProcDuration');runtime(x,'new_shield_value','本次新获得护盾值','只取新护盾的已确认值，不用剩余总护盾、历史累计护盾或治疗值。');formula(x,'damage_amount','下一次攻击额外伤害',add(add(P('confirmed_level_damage'),mul(A('SOURCE','hp','BONUS'),P('bonus_health_ratio'))),mul(P('new_shield_value'),P('new_shield_ratio'))),'比例点先转换0.025和0.15；护盾消散后的2秒不是整个护盾持续时间。');sourceOnly(x,['BonusShieldMult'],'当前正文未消费0.1字段，不创建旧防御或增强护盾机制。');qualify(x,['获得新的护盾','下一次对英雄普攻','护盾消散后最多2秒仍可消费','自适应类型确定'],'新护盾取样、增益消费及适应伤害资格未连接');
}
{
 const x=proposal(8473,'骸骨镀层后续三次攻击或技能的独立减免数值');curve(x,'confirmed_level_block','等级每次减免量',30,60,'BlockBase','BlockMax');direct(x,'block_count','后续可减免次数',3,'BlockCount');time(x,'block_duration_ms','后续减免持续',1.5,'BlockDuration');time(x,'cooldown_ms','冷却时间',55,'Cooldown');formula(x,'block_amount','每次合格事件减免量',P('confirmed_level_block'),'只保留减免数值，不把它当护盾、护甲或触发那次伤害本身的减免。');qualify(x,['先受到英雄伤害触发','随后1.5秒内的下3次合格技能或攻击','冷却可用'],'触发次序、计次和减免所在结算阶段尚未连接');
}
{
 const x=proposal(8369,'先攻保留7%额外伤害与进入英雄战斗窗口，排除金币');direct(x,'damage_amp_ratio','额外伤害比例',.07,'DamageAmp');time(x,'buff_duration_ms','先攻持续',3,'Duration');time(x,'combat_grace_window_ms','进入英雄战斗允许窗口',.25,'GraceWindow');curve(x,'confirmed_cooldown_seconds','等级冷却秒数',25,15,'TooltipOnlyCooldownStartAmount','TooltipOnlyCooldownEndAmount');parameter(x,'seconds_to_ms','秒转毫秒系数',1000,'单位换算常数。',{category:'单位换算'});direct(x,'ordinary_cooldown_multiplier','普通模式冷却乘数',1,'ModesCooldownReduction');runtime(x,'qualified_damage_basis','先攻合格伤害基数','实际可增加7%的结算基数由后续资格供值，不默认技能基础伤害或重复包含先攻自身伤害。');formula(x,'additional_damage','先攻额外伤害数值',mul(P('qualified_damage_basis'),P('damage_amp_ratio')),'伤害支路保留；当前文本标注额外真实伤害，具体结果和资格尚未落库。');formula(x,'cooldown_ms','普通模式等级冷却毫秒',mul(mul(P('confirmed_cooldown_seconds'),P('ordinary_cooldown_multiplier')),P('seconds_to_ms')),'原树等级值乘当前普通模式1后转换毫秒。');sourceOnly(x,['GoldProcBonus','GoldPercentBonus','GoldPercentBonusRanged'],'直接金币与金币换算分支，不影响本轮1V1伤害。','范围外');sourceOnly(x,['OOCTimer','MissileNoiseNumberLimiter','MissileNoiseRangeLimiter','{b50bc5ec}','{7563bf99}'],'未取得普通伤害支路消费证明，不以旧脱战、特效限制或未命名字段生成机制。');qualify(x,['率先进入英雄战斗0.25秒内攻击或施法伤害','冷却可用','3秒合格伤害窗口'],'先手判定、伤害基数及额外伤害排重未连接');
}
{
 const x=proposal(8224,'公理秘术终极技能伤害/自身恢复/自身护盾与当前冷却返还');direct(x,'single_damage_amp_ratio','终极单体伤害及治疗护盾增幅',.12,'DamageAmp');direct(x,'aoe_damage_amp_ratio','终极群体伤害增幅',.08,'AOEAmp');direct(x,'current_ultimate_cooldown_refund_ratio','当前终极冷却返还比例',.07,'UltimateRefundBase',.01);runtime(x,'current_ultimate_cooldown_ms','参与击杀时终极当前剩余冷却','必须读取该终极当前剩余冷却，不使用基础或总冷却，更不能复用装备6696总冷却口径。');runtime(x,'qualified_ultimate_damage','已确认终极伤害基数','群体伤害分类即使只命中当前一个英雄也仍用8%；结算阶段单独核实。');runtime(x,'qualified_self_healing_or_shield','已确认终极自身治疗或护盾基数','只保留当前自身收益，第三者友军专用收益不在本轮；不把数值自动当瞬时治疗。');formula(x,'ultimate_current_cooldown_refund_ms','当前终极剩余冷却返还',mul(P('current_ultimate_cooldown_ms'),P('current_ultimate_cooldown_refund_ratio')),'参与击杀后返还当前剩余冷却7%，不是7毫秒或总冷却7%。');formula(x,'single_target_additional_damage','终极单体分类额外伤害',mul(P('qualified_ultimate_damage'),P('single_damage_amp_ratio')),'仅合法单体伤害分类。');formula(x,'aoe_additional_damage','终极群体分类额外伤害',mul(P('qualified_ultimate_damage'),P('aoe_damage_amp_ratio')),'群体分类对当前单一目标仍成立，不作为多目标范围外删掉。');formula(x,'additional_self_healing_or_shield','终极自身治疗或护盾增加量',mul(P('qualified_self_healing_or_shield'),P('single_damage_amp_ratio')),'基数与自身资格必须确认后选用，治疗和护盾不同时重复发放。');qualify(x,['实际终极技能分类','按实际伤害类型选12%或8%','真实自身恢复/护盾资格','参与击杀才返还当前终极冷却'],'终极技能范围、不同结果基数与触发均待接线');x.excluded.push({branch:'第三者友军专用终极治疗/护盾',reason:'只排除第三者收益，自身和当前敌方英雄伤害分支完整保留'});
}
{
 const x=proposal(8992,'冥火每秒魔法伤害、三秒后仍着火增幅与三种技能分类持续时间');runtime(x,'confirmed_level_damage_per_second','已确认等级每秒基础伤害','当前DamageCalc为3至12插值节点；起止与求值未证，不按1至18级线性生成。');parameter(x,'level_damage_source_start','原计算等级起点',3,'当前DamageCalc首节点mStartValue=3，仅来源端点。',{category:'当前绑定计算树'});parameter(x,'level_damage_source_end','原计算等级终点',12,'当前DamageCalc首节点mEndValue=12；未知hash字段不用于猜语义。',{category:'当前绑定计算树'});direct(x,'bonus_ad_ratio','每秒额外攻击力系数',.07,'ADRatio');direct(x,'ap_ratio','每秒法强系数',.025,'APRatio');time(x,'single_duration_ms','单体技能分类灼烧时长',4,'Duration');time(x,'aoe_duration_ms','群体技能分类灼烧时长',2,'AoEDuration');time(x,'dot_duration_ms','持续伤害技能分类灼烧时长',1,'DotDuration');time(x,'amplification_threshold_ms','仍着火增幅门槛',3,'TimeToAmp');direct(x,'damage_increase_ratio','三秒后伤害提升比例',.75,'DamageMultiplier');direct(x,'source_ticks_per_second','来源每秒跳数',2,'TicksPerSecond',1,'只保留原字段；首跳时点、刷新与截止未知，不生成周期结果或直接除2造每跳。');parameter(x,'one','一倍基准',1,'提升75%意味着乘1.75。',{category:'明确百分比算术'});
 const dps=add(add(P('confirmed_level_damage_per_second'),mul(A('SOURCE','ability_power','TOTAL'),P('ap_ratio'))),mul(A('SOURCE','attack_damage','BONUS'),P('bonus_ad_ratio')));formula(x,'damage_per_second','普通灼烧每秒伤害',dps,'当前原树是每秒伤害，不是每跳或完整持续总伤害。');formula(x,'amplified_damage_per_second','仍着火三秒后的每秒伤害',mul(dps,add(P('one'),P('damage_increase_ratio'))),'仅灼烧3秒后仍着火的后续伤害乘1.75，不回溯放大前三秒。');sourceOnly(x,['Level1DamageTOOLTIP','{2156e250}','APRatioTT','ADRatioTT'],'保留展示或未命名字段原值；正常计算采用当前DamageCalc及APRatio/ADRatio。');qualify(x,['技能实际伤害当前英雄','依据单体/群体/持续伤害分类选持续时间','3秒后仍着火才增强后续伤害'],'首跳、续燃计时、刷新覆盖、伤害资格及周期结果未接线');pending(x,'来源','每秒2跳不能证明首跳在0或0.5秒，也不能证明截止与延长规则','当前周期调度执行链');
}
{
 const x=proposal(8236,'风暴聚集普通模式10分钟档与六个明确法强展示值；攻击力冲突不猜换算');direct(x,'checkpoint_interval_ms','普通模式增长间隔',600000,'UpdateAfterMinutes',60000,'普通模式10分钟乘60000为600000毫秒；其他模式覆盖不使用。');
 const ap=[8,24,48,80,120,168],ad=[5,14,29,48,72,101];x.checkpointEvidence={minutes:[10,20,30,40,50,60],abilityPower:ap,attackDamageDisplay:ad,source:'当前绑定长说明；AD展示存在取整且AdaptiveAD=6与首档5冲突'};for(let i=0;i<ap.length;i++)parameter(x,'ap_at_'+(i+1)*10+'_minutes',(i+1)*10+'分钟已展示法强',ap[i],'当前普通模式长说明逐项明确，仅该档已证，不外推无限时间公式。',{category:'当前绑定正文'});
 runtime(x,'confirmed_current_ability_power','已确认当前档法强','目前只支持明确核对的10/20/30/40/50/60分钟档8/24/48/80/120/168。实际进度和自适应选择外供，不默认0，不外推60分钟之后。');runtime(x,'confirmed_current_attack_damage','已确认当前档攻击力','原AdaptiveAD=6与10分钟展示5冲突，其他展示还有取整；不默认0.6换算或三角数无限公式。');formula(x,'ability_power_amount','已确认当前法强档数值',P('confirmed_current_ability_power'),'仅已确定选择法强分支时使用。');formula(x,'attack_damage_amount','已确认当前攻击力档数值',P('confirmed_current_attack_damage'),'AD来源冲突由已核实输入解决；不把展示整数当未经舍入的实时值。');snapshotAttribute(x,'confirmed_ability_power','已确认法强档组成','ability_power','ability_power_amount',{description:'只在真实进度档及法强分支已确认时授予一份总量快照；换档或属性选择变化须替换/移除，不能按次数重复叠加总值。无自动时钟或适应选择规则。'});sourceOnly(x,['AdaptiveAP','AdaptiveAD','{c5d14564}'],'AP8仅证明第一展示档；AD6与显示5有冲突，未知字段不拿来推无限增长。');pending(x,'来源冲突','攻击力原值6、首档展示5及后续舍入序列不一致','当前实际增益、舍入与适应选择执行链');qualify(x,['普通模式实际进度档明确','仅选择一个适应属性分支','该档实际收益已核实'],'时间进度、适应选择与总值替换未接线');
}
const requests=[];for(const x of proposals){const entry=byId.get(x.id);x.sourceCalculations=entry.summary.calculations;x.currentBoundText=entry.bound;x.skillBody={skillKey:x.skillKey,name:'符文·'+x.name,description:'本批仅录入：'+x.scope+'。未证条件和输入不默认，不表示完整战斗机制。',maxLevel:1,status:'ENABLED',sortOrder:0,skillCategoryKeys:['passive']};x.relationBody={runeKey:x.runeKey,skillKey:x.skillKey,sortOrder:0};const root='/skills/'+x.skillKey,push=(kind,route,readRoute,body)=>requests.push({id:x.id,skillKey:x.skillKey,kind,method:'POST',route,readRoute,body});push('skill','/skills',root,x.skillBody);for(const[kind,list,child,key]of [['parameter',x.parameters,'parameters','parameterKey'],['formula',x.formulas,'formulas','formulaKey'],['effect',x.effects,'effects','effectKey']])for(const body of list)push(kind,root+'/'+child,root+'/'+child+'/'+body[key],body);push('relation','/rune-skill-relations','/rune-skill-relations?runeKey='+x.runeKey+'&skillKey='+x.skillKey,x.relationBody);}
assert.deepEqual(proposals.map(x=>x.id),[8005,8008,8010,8021,8230,8299,8401,8473,8369,8224,8992,8236]);const counts=Object.fromEntries(['skill','parameter','formula','effect','relation','rule','process','internalState'].map(kind=>[kind,requests.filter(x=>x.kind===kind).length]));
save('可审查候选.json',{at:new Date().toISOString(),executor:'Codex执行代理；主负责人指定本12项范围，业务写入未执行',sourceFrozenSha256:sha(frozenBytes),sourceRawSha256:sha(raw),boundary:'普通模式16.17客户端；官方身份16.17.1；只有候选与只读核对',counts,proposals});save('可审查请求.json',{at:new Date().toISOString(),sourceFrozenSha256:sha(frozenBytes),candidateSha256:sha(fs.readFileSync(path.join(here,'可审查候选.json'))),counts,requests});save('生成摘要.json',{at:new Date().toISOString(),counts,totalRequests:requests.length,candidateSha256:sha(fs.readFileSync(path.join(here,'可审查候选.json'))),requestsSha256:sha(fs.readFileSync(path.join(here,'可审查请求.json'))),apiWrites:0});console.log(JSON.stringify({counts,totalRequests:requests.length,apiWrites:0}));
