// 独立读取冻结来源和候选，不导入准备候选工具；不访问业务接口。
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import zlib from 'node:zlib';import {isDeepStrictEqual as eq} from 'node:util';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),read=f=>JSON.parse(fs.readFileSync(path.join(here,f))),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),frozenBytes=fs.readFileSync(path.join(here,'冻结来源.json')),source=JSON.parse(frozenBytes),candidate=read('可审查候选.json'),requests=read('可审查请求.json'),baseline=read('保护基线.json'),images=read('代表图复用候选.json'),checks=[],cases=[],failures=[];
const check=(name,pass,detail=null)=>{checks.push({name,pass,detail});if(!pass)failures.push({name,detail});},byId=new Map(candidate.proposals.map(p=>[p.id,p])),entry=id=>source.entries.find(e=>e.id===id),raw=zlib.gunzipSync(fs.readFileSync(path.join(here,'../符文客户端数值补证/perks-16.17.cdtb.bin.json.gz'))),original=JSON.parse(raw);
check('冻结来源文件散列',sha(frozenBytes)==='878fd1147a277282f6bacd04ecddafe55e980e729a67d4469b31b2ff93d492a7');check('原始16.17客户端解压字节',sha(raw)===source.rawSha256);check('精确12项范围',eq(candidate.proposals.map(x=>x.id),[8005,8008,8010,8021,8230,8299,8401,8473,8369,8224,8992,8236]));check('请求绑定本候选散列',requests.candidateSha256===sha(fs.readFileSync(path.join(here,'可审查候选.json'))));
const list=x=>Array.isArray(x.data)?x.data:x.data.items;
for(const p of candidate.proposals){const e=entry(p.id),values=e.object.mScript.mSpellScriptData.mEffectAmount;check(p.id+'完整原始对象',eq(e.object,original[e.sourcePath])&&sha(JSON.stringify(e.object))===e.sourceObjectSha256);check(p.id+'当前原树和中文完整保留',eq(p.sourceCalculations,e.summary.calculations)&&eq(p.currentBoundText,e.bound));
 for(const[k,id]of [['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey']])check(p.id+'/'+k+'稳定键唯一',new Set(p[k].map(x=>x[id])).size===p[k].length);
 for(const q of p.parameters){check(p.id+'/'+q.parameterKey+'只用固定或无默认输入',['FIXED','RUNTIME_INPUT'].includes(q.valueMode)&&q.levelValues===null&&(q.valueMode==='FIXED'?Number.isFinite(q.fixedValue):q.fixedValue===null));const proof=p.parameterEvidence.find(x=>x.parameterKey===q.parameterKey);check(p.id+'/'+q.parameterKey+'有来源归属',!!proof);if(proof.sourcePath){const field=proof.sourcePath.split('/').at(-1);check(p.id+'/'+q.parameterKey+'原值单位独立核对',eq(proof.sourceRawValue,values[field])&&Math.abs(q.fixedValue-values[field]*proof.scale)<Math.max(1e-6,Math.abs(q.fixedValue)*1e-7),{field,raw:values[field],scale:proof.scale,actual:q.fixedValue});}}
 const used=new Set(p.parameterEvidence.filter(x=>x.sourcePath).map(x=>x.sourcePath.split('/').at(-1)));for(const s of p.sourceOnly??[]){used.add(s.field);check(p.id+'/'+s.field+'来源保留原值',eq(s.raw,values[s.field]));}check(p.id+'全部原数值字段有归属',Object.keys(values).every(k=>used.has(k)),Object.keys(values).filter(k=>!used.has(k)));
 for(const f of p.formulas){function walk(n){check(p.id+'/'+f.formulaKey+'合法表达式节点',n&&['PARAMETER','ATTRIBUTE','OPERATION'].includes(n.nodeType)&&!('kind'in n));if(n.nodeType==='PARAMETER')check(p.id+'/'+f.formulaKey+'参数存在',p.parameters.some(q=>q.parameterKey===n.parameterKey));if(n.nodeType==='ATTRIBUTE')check(p.id+'/'+f.formulaKey+'属性存在',list(baseline.catalogs.attributes).some(q=>q.attributeKey===n.attributeKey&&q.status==='ENABLED'));if(n.nodeType==='OPERATION'){check(p.id+'/'+f.formulaKey+'二元运算',n.operands.length===2);n.operands.forEach(walk);}}walk(f.expression);}
 check(p.id+'无触发过程和周期伤害',!p.triggerRules.length&&!p.processes.length&&!p.internalStates.length&&p.effects.every(e=>e.results.every(r=>!['DAMAGE','DIRECT_HEAL'].includes(r.resultType))&&e.lifecycle.periodicIntervalValue===null));
 for(const e of p.effects){const r=e.results[0];check(p.id+'/'+e.effectKey+'属性与修正区有效',list(baseline.catalogs.attributes).some(a=>a.attributeKey===r.detail.attributeKey&&a.status==='ENABLED')&&list(baseline.catalogs['modifier-zones']).some(a=>a.modifierZoneKey===r.detail.modifierZoneKey&&a.status==='ENABLED'&&a.calculationMode==='FLAT_ADD'));check(p.id+'/'+e.effectKey+'一份总值替换，未叠乘层数',e.lifecycle.maxStacksValue.value===1&&e.lifecycle.applicationStacksValue.value===1&&r.lifecycleBehavior.reapplicationValueMode==='REPLACE');}
 const owner=baseline.owners.find(o=>o.id===p.id);check(p.id+'原身份图片关系保护完整',owner?.rune.runeKey===p.runeKey&&owner.skillStatus===404&&owner.image.width<=64&&owner.image.height<=64&&owner.usage.runes.some(r=>r.runeKey===p.runeKey));check(p.id+'仅复用同一代表图',images.requests.find(r=>r.id===p.id)?.body.imageKey===owner.image.metadata.imageKey);
}
check('被动分类存在',list(baseline.catalogs['skill-categories']).some(x=>x.skillCategoryKey==='passive'&&x.status==='ENABLED'));check('原69身份与6布局只读保留',list(baseline.identities).length===69&&list(baseline.layouts).length===6&&baseline.apiWrites===0);check('候选无身份或原图上传',requests.requests.every(r=>['skill','parameter','formula','effect','relation'].includes(r.kind)&&r.method==='POST'));
const runtime={8005:{confirmed_level_damage:100,qualified_damage_basis:500},8008:{actual_stacks:6,confirmed_ranged_as_per_stack:.05,confirmed_melee_level_damage:18,confirmed_ranged_level_damage:17,confirmed_bonus_attack_speed_ratio:.5},8010:{confirmed_adaptive_per_stack:2.5,actual_stacks:12,actual_damage_dealt_to_champion:400},8021:{confirmed_level_heal:80},8230:{confirmed_cooldown_seconds:13.7},8299:{confirmed_damage_amp_ratio:.09,qualified_damage_basis:500},8401:{confirmed_level_damage:15,new_shield_value:200},8473:{confirmed_level_block:45},8369:{confirmed_cooldown_seconds:20,qualified_damage_basis:500},8224:{current_ultimate_cooldown_ms:20000,qualified_ultimate_damage:500,qualified_self_healing_or_shield:300},8992:{confirmed_level_damage_per_second:6},8236:{confirmed_current_ability_power:48,confirmed_current_attack_damage:29}};
const attributes={'SOURCE.attack_damage.TOTAL':250,'SOURCE.attack_damage.BONUS':100,'SOURCE.ability_power.TOTAL':200,'SOURCE.hp.BONUS':500,'SOURCE.hp.TOTAL':2000,'SOURCE.hp.CURRENT':500,'TARGET.hp.TOTAL':2000};
function evaluate(id,node,inputs=runtime[id],attrs=attributes){if(node.nodeType==='PARAMETER'){const p=byId.get(id).parameters.find(x=>x.parameterKey===node.parameterKey);if(p.valueMode==='RUNTIME_INPUT'){if(!Object.hasOwn(inputs,p.parameterKey))throw Error('缺输入 '+p.parameterKey);return inputs[p.parameterKey];}return p.fixedValue;}if(node.nodeType==='ATTRIBUTE'){const k=node.attributeOwner+'.'+node.attributeKey+'.'+node.attributeValueKind;if(!Object.hasOwn(attrs,k))throw Error('缺属性 '+k);return attrs[k];}const[a,b]=node.operands.map(n=>evaluate(id,n,inputs,attrs));switch(node.operation){case'ADD':return a+b;case'SUBTRACT':return a-b;case'MULTIPLY':return a*b;case'DIVIDE':return a/b;default:throw Error('未审查运算 '+node.operation);}}
function sample(id,key,expected,inputs=runtime[id],attrs=attributes){const f=byId.get(id).formulas.find(x=>x.formulaKey===key),actual=evaluate(id,f.expression,inputs,attrs),pass=Math.abs(actual-expected)<1e-8;cases.push({id,formulaKey:key,inputs,attributes:attrs,actual,expected,pass,boundary:'输入仅为独立算例，不默认真实层数、等级、AD冲突分支或战斗事件'});check(id+'/'+key+'独立算例',pass,{actual,expected});}
sample(8005,'third_attack_damage',100);sample(8005,'additional_damage',40);
sample(8008,'melee_attack_speed_amount',.36);sample(8008,'ranged_attack_speed_amount',.3);sample(8008,'melee_full_stack_damage',27);sample(8008,'ranged_full_stack_damage',25.5);sample(8008,'melee_attack_speed_amount',.24,{...runtime[8008],actual_stacks:4});
sample(8010,'adaptive_force_amount',30);sample(8010,'melee_self_heal',32);sample(8010,'ranged_self_heal',20);sample(8010,'melee_self_heal',8,{...runtime[8010],actual_damage_dealt_to_champion:100});
sample(8021,'melee_heal',100);sample(8021,'ranged_heal',60);sample(8021,'melee_minion_heal',15);sample(8021,'ranged_minion_heal',9);sample(8021,'ranged_move_speed_ratio',.15);sample(8021,'melee_heal',100,runtime[8021],{...attributes,'SOURCE.attack_damage.TOTAL':999});
sample(8230,'target_damage_threshold',500);sample(8230,'ranged_move_speed_ratio',.36);sample(8230,'cooldown_ms',13700);
sample(8299,'additional_damage',45);sample(8299,'maximum_branch_additional_damage',55);
sample(8401,'damage_amount',57.5);sample(8401,'damage_amount',57.5,runtime[8401],{...attributes,'SOURCE.hp.TOTAL':9000});sample(8473,'block_amount',45);
sample(8369,'additional_damage',35);sample(8369,'cooldown_ms',20000);
sample(8224,'ultimate_current_cooldown_refund_ms',1400);sample(8224,'single_target_additional_damage',60);sample(8224,'aoe_additional_damage',40);sample(8224,'additional_self_healing_or_shield',36);
sample(8992,'damage_per_second',18);sample(8992,'amplified_damage_per_second',31.5);sample(8992,'damage_per_second',18,runtime[8992],{...attributes,'SOURCE.attack_damage.TOTAL':999});
sample(8236,'ability_power_amount',48);sample(8236,'attack_damage_amount',29);
for(const p of candidate.proposals)for(const f of p.formulas){check(p.id+'/'+f.formulaKey+'已有独立算例',cases.some(x=>x.id===p.id&&x.formulaKey===f.formulaKey));const ids=[];function collect(n){if(n.nodeType==='PARAMETER'&&p.parameters.find(q=>q.parameterKey===n.parameterKey).valueMode==='RUNTIME_INPUT')ids.push(n.parameterKey);if(n.nodeType==='OPERATION')n.operands.forEach(collect);}collect(f.expression);for(const key of new Set(ids)){const inputs={...runtime[p.id]};delete inputs[key];let threw=false;try{evaluate(p.id,f.expression,inputs);}catch{threw=true;}check(p.id+'/'+f.formulaKey+'缺输入拒算 '+key,threw);}}
const v=id=>entry(id).object.mScript.mSpellScriptData,lt=v(8008),nearAS=lt.mCalculations.ASPerStack.mFormulaParts[0].mNumber,rangeAS=nearAS*lt.mCalculations.ASPerStack.mRangedMultiplier.mNumber,rangeStart=lt.mCalculations.NoteDamage.mFormulaParts[0].mStartValue*lt.mCalculations.NoteDamage.mRangedMultiplier.mNumber,rangeEnd=lt.mCalculations.NoteDamage.mFormulaParts[0].mEndValue*lt.mCalculations.NoteDamage.mRangedMultiplier.mNumber;
const conflicts=[{id:8008,kind:'远程每层攻速',rawCalculation:rangeAS,longText:lt.mEffectAmount.TTASPerStackRanged},{id:8008,kind:'远程等级附伤两端点',rawCalculation:[rangeStart,rangeEnd],longText:[lt.mEffectAmount.TTMinNoteDamageRanged,lt.mEffectAmount.TTMaxNoteDamageRanged]},{id:8236,kind:'首档AD',raw:v(8236).mEffectAmount.AdaptiveAD,longText:5}];
check('8008原树与长说明远程攻速冲突确实存在',Math.abs(rangeAS-.048)<1e-7&&Math.abs(rangeAS-lt.mEffectAmount.TTASPerStackRanged)>.007);check('8008远程附伤上限冲突确实存在',Math.abs(rangeEnd-20.01)<1e-5&&Math.abs(rangeEnd-24)>3);check('8008近战原树与长说明一致',Math.abs(nearAS-.06)<1e-7&&lt.mCalculations.NoteDamage.mFormulaParts[0].mStartValue===9&&lt.mCalculations.NoteDamage.mFormulaParts[0].mEndValue===30);
check('8021原树确为额外AD、法强与远程效能',v(8021).mCalculations.HealAmount.mFormulaParts[1].mStat===2&&v(8021).mCalculations.HealAmount.mFormulaParts[1].mStatFormula===2&&!Object.hasOwn(v(8021).mCalculations.HealAmount.mFormulaParts[2],'mStat')&&v(8021).mCalculations.HealAmount.mRangedMultiplier.mDataValue==='RangedHealMod');
check('8230不用旧三次命中',!byId.get(8230).parameters.some(p=>/hit/i.test(p.parameterKey))&&entry(8230).bound.mTooltipNameLocalizationKey.text.includes('@DamageThreshold*100@%最大生命值'));check('8992原树每秒AD口径',v(8992).mCalculations.DamageCalc.mFormulaParts[2].mStat===2&&v(8992).mCalculations.DamageCalc.mFormulaParts[2].mStatFormula===2);check('8236六档AP与原文逐项同值',byId.get(8236).checkpointEvidence.abilityPower.every(n=>entry(8236).bound.mLongDescLocalizationKey.text.includes('+ '+n+'法术强度')));check('8236分钟正确转换毫秒',byId.get(8236).parameters.find(p=>p.parameterKey==='checkpoint_interval_ms').fixedValue===v(8236).mEffectAmount.UpdateAfterMinutes*60000);
const report={at:new Date().toISOString(),pass:!failures.length,apiWrites:0,sourceFrozenSha256:sha(frozenBytes),sourceRawSha256:sha(raw),candidateSha256:sha(fs.readFileSync(path.join(here,'可审查候选.json'))),requestsSha256:sha(fs.readFileSync(path.join(here,'可审查请求.json'))),checks,cases,conflicts,failures,boundary:'固定来源和候选独立算术；79次GET的保护证据另存。没有业务写入或战斗运行；外供输入不构成曲线/来源冲突/资格已解决的证明。'};fs.writeFileSync(path.join(here,'独立核算.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass:report.pass,checks:checks.length,cases:cases.length,coveredFormulas:new Set(cases.map(x=>x.id+'/'+x.formulaKey)).size,failures}));if(failures.length)process.exitCode=1;
