import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import{fileURLToPath}from'node:url';
const d=path.dirname(fileURLToPath(import.meta.url)),a='C:/project/damage_web_dev/.agents/artifacts',read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),c=read(a+'/hero43-luna-candidate/修订二/完整候选.json'),source=read(a+'/hero43-root-entry-20260910/来源绑定与当前文本.json'),getPath=process.env.HERO43_GET_REPORT;let actualHydrated=0;
if(getPath){const g=read(getPath);assert(g.status==='PASS'&&g.actual.calls===426);assert.equal(g.candidateSha256,sha(a+'/hero43-luna-candidate/修订二/完整候选.json'));const m=new Map(g.rawResponses.map(x=>[x.route,x.data]));for(const[k,s]of Object.entries(c.skills))for(const[kind,id]of [['parameters','parameterKey'],['formulas','formulaKey'],['effects','effectKey']])s.write[kind]=s.write[kind].map(x=>{const p=m.get('/skills/'+k+'/'+kind+'/'+x[id]);assert(p);actualHydrated++;return p;});assert.equal(actualHydrated,206);}
const spell=(h,s)=>source.heroes.find(x=>x.id===h).skills.find(x=>x.slot===s).object.mSpell,params=(h,s)=>c.skills[h.toLowerCase()+'_'+s.toLowerCase()].write.parameters,near=(x,y)=>typeof x==='number'&&typeof y==='number'&&Number.isFinite(x)&&Number.isFinite(y)&&Math.abs(x-y)<1e-6*Math.max(1,Math.abs(x),Math.abs(y)),checks=[];
const bindings=[['Gangplank','Q','base_damage','SpellDamage'],['Gangplank','W','base_heal','BaseHeal'],['Gangplank','R','damage_per_wave','DamagePerWave'],['Gangplank','R','deaths_daughter_base_damage','DeathsDaughterBaseDamage'],['Kindred','Q','base_damage','BaseDamage'],['Kindred','E','base_bite_damage','BaseDamage'],['Kindred','R','ending_heal','HealFlat'],['Naafiri','Q','first_cast_base_damage','BaseDamageFirstCast'],['Naafiri','Q','bleed_base_damage','BleedBaseDamage'],['Naafiri','Q','second_cast_min_base_damage','BaseDamageSecondCast'],['Naafiri','Q','second_cast_heal_base','BaseHealSecondCast'],['Naafiri','W','move_speed_ratio','MoveSpeedAmount'],['Naafiri','E','first_slash_base_damage','BaseDamageFirstSlash'],['Naafiri','E','second_hit_base_damage','BaseDamageSecondHit'],['Naafiri','R','base_damage','BaseDamage'],['Naafiri','R','shield_base','ShieldSize'],['Zed','Q','base_damage','BaseDamage'],['Zed','W','energy_restore_double_hit','EnergyRestoreDoubleHit'],['Zed','E','base_damage','BaseDamage'],['Zed','R','damage_amp','RDamageAmp']];
function checkArray(h,s,key,values,note){const p=params(h,s).find(x=>x.parameterKey===key);assert(p);const actual=Object.values(p.levelValues);assert.equal(actual.length,values.length);for(let i=0;i<values.length;i++)assert(near(actual[i],values[i]),h+'/'+s+'/'+key+'/'+(i+1));checks.push({skillKey:h.toLowerCase()+'_'+s.toLowerCase(),key,source:note,actual,expected:values,passed:true});}
for(const[h,s,key,field]of bindings){const n=c.skills[h.toLowerCase()+'_'+s.toLowerCase()].currentSubject.maxLevel,row=spell(h,s).DataValues.find(x=>x.name===field);assert(row);checkArray(h,s,key,row.values.slice(1,n+1),'DataValues.'+field+'[1..'+n+']');}
for(const s of ['Q','W']){const raw=spell('Zed',s);assert(Array.isArray(raw.mana));checkArray('Zed',s,'energy_cost',raw.mana.slice(0,5),'根mana[0..4]，能量');}
checkArray('Kindred','Q','w_zone_cooldown_ms',spell('Kindred','Q').DataValues.find(x=>x.name==='CDNewValue').values.slice(1,6).map(x=>x*1000),'当前正文5档冷却，零基索引CDNewValue[1..5]秒转毫秒');
checkArray('Zed','P','max_health_damage_ratio',Array.from({length:18},(_,i)=>i<6?.05:i<16?.075:.1),'当前已证明7级和17级纯加法断点');
let fixed=0,integerParameters=0,integerValues=0,milliseconds=0,binaryNodes=0;const modes=[];for(const[k,s]of Object.entries(c.skills)){for(const p of s.write.parameters){const vals=p.valueMode==='FIXED'?[p.fixedValue]:Object.values(p.levelValues??{});if(p.valueMode==='RUNTIME_INPUT'){assert.equal(p.fixedValue,null);assert.equal(p.levelValues,null);}else{assert(vals.length>0);assert(vals.every(x=>typeof x==='number'&&Number.isFinite(x)));}if(p.valueMode==='FIXED')fixed++;if(p.valueMode==='SKILL_LEVEL')assert.deepEqual(Object.keys(p.levelValues),Array.from({length:s.currentSubject.maxLevel},(_,i)=>String(i+1)));if(p.valueMode==='CHARACTER_LEVEL')assert.deepEqual(Object.keys(p.levelValues),Array.from({length:18},(_,i)=>String(i+1)));if(p.valueType==='INTEGER'){integerParameters++;integerValues+=vals.length;assert(vals.every(Number.isInteger));}if(p.parameterKey.endsWith('_ms')){milliseconds++;assert.equal(p.valueType,'INTEGER');assert(vals.every(x=>x>=0));}modes.push({skillKey:k,key:p.parameterKey,mode:p.valueMode,passed:true});}function walk(n){assert(['PARAMETER','ATTRIBUTE','OPERATION'].includes(n.nodeType));if(n.nodeType==='OPERATION'){binaryNodes++;assert.equal(n.operands.length,2);n.operands.forEach(walk);}}s.write.formulas.forEach(f=>walk(f.expression));}
assert.equal(checks.length,c.order.reduce((n,k)=>n+c.skills[k].write.parameters.filter(x=>['SKILL_LEVEL','CHARACTER_LEVEL'].includes(x.valueMode)).length,0));
const swap=params('Zed','W').find(x=>x.parameterKey==='swap_window_ms');assert(near(swap.fixedValue,spell('Zed','W').DataValues.find(x=>x.name==='SwapTimeLimit').values[1]*1000));
const report={at:new Date().toISOString(),candidateSha256:sha(a+'/hero43-luna-candidate/修订二/完整候选.json'),actualHydrated,actualGETSha256:getPath?sha(getPath):null,sourceArrays:checks.length,sourceValues:checks.reduce((n,x)=>n+x.actual.length,0),checks,fixed,integerParameters,integerValues,milliseconds,binaryNodes,modes,passed:true,apiCalls:0,apiWrites:0};fs.writeFileSync(d+'/源数组与边界核对.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:true,sourceArrays:report.sourceArrays,sourceValues:report.sourceValues,fixed,integerParameters,integerValues,milliseconds,binaryNodes,actualHydrated}));
