import fs from 'node:fs';
import path from 'node:path';
const BASE='http://127.0.0.1:8080/api/admin/games/lol';
const H={Authorization:'Bearer local-entry',Accept:'application/json'};
const ROOT='C:/project/damage_viewer_project_planning/数据参考/全量录入-2026-09';
const SRC=path.join(ROOT,'英雄/等级属性候选'); const OUT=path.join(ROOT,'API实录/英雄全量核对');
const EXCLUDE=new Set(['Sylas','Aphelios']);
const MAP={hp:'hp',hpregen:'hp_regen',spellblock:'magic_resistance',attackdamage:'attack_damage',movespeed:'move_speed',attackrange:'attack_range',attackspeed:'attack_speed',mp:'mana',mpregen:'mana_regen',armor:'armor'};
const files=fs.readdirSync(SRC).filter(x=>x.endsWith('.json')).map(x=>x.slice(0,-5)).filter(x=>!EXCLUDE.has(x));
async function api(p){const started=Date.now();try{const r=await fetch(BASE+p,{headers:H});const t=await r.text();let b=null;try{b=t?JSON.parse(t):null}catch{b=t}return {status:r.status,body:b,ms:Date.now()-started};}catch(e){return {status:0,body:String(e),ms:Date.now()-started};}}
const n=(v)=>typeof v==='number'?v:Number(v);const close=(a,b)=>Number.isFinite(n(a))&&Number.isFinite(n(b))&&Math.abs(n(a)-n(b))<=1e-9;
function missingRows(c){const m=c.missing;return Array.isArray(m)?m:[];}
const startedAt=new Date().toISOString();const list=await api('/characters');const actualList=list.body?.items??[];const results=[];for(const file of files){const c=JSON.parse(fs.readFileSync(path.join(SRC,file+'.json'),'utf8'));const key=file==='Ezreal'?'champion_ez':'champion_'+c.sourceChampionId.toLowerCase();const e={sourceFile:file+'.json',characterKey:key,name:c.name,sourceNumericId:c.sourceNumericId,checkedAt:new Date().toISOString(),sourceMissing:missingRows(c),status:'checked',differences:[],missingValues:[],sourceMissingConfigured:[],extraConfigured:[],unknownSourceRows:[]};const g=await api('/characters/'+encodeURIComponent(key));e.characterGet={status:g.status,ms:g.ms};if(g.status!==200){e.status='character_missing_or_error';e.error=g.body;fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(e,null,2));results.push(e);continue;}e.actualCharacter={characterKey:g.body?.characterKey,name:g.body?.name,description:g.body?.description};if(g.body?.name!==c.name)e.differences.push({kind:'basic_name',source:c.name,actual:g.body?.name});const a=await api('/characters/'+encodeURIComponent(key)+'/attributes');e.attributesGet={status:a.status,ms:a.ms};if(a.status!==200){e.status='attributes_missing_or_error';e.error=a.body;fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(e,null,2));results.push(e);continue;}const actual=a.body?.levelValues??{};e.explicitSourceAttributeKeys=[];const expectedByAttr={};for(const row of c.attributes??[]){const sk=row.sourceAttributeKey;const ak=MAP[sk];if(!ak){e.unknownSourceRows.push({sourceAttributeKey:sk,label:row.label,reason:'未定义映射'});continue;}e.explicitSourceAttributeKeys.push(ak);expectedByAttr[ak]=row.levelValues??{};for(const lv of Object.keys(row.levelValues??{})){const sv=row.levelValues[lv];const av=actual[lv]?.[ak];if(av===undefined||av===null)e.missingValues.push({level:lv,attributeKey:ak,source:sv});else if(!close(sv,av))e.differences.push({kind:'value',level:lv,attributeKey:ak,source:sv,actual:av,delta:n(av)-n(sv)});}}
const explicit=new Set(Object.keys(expectedByAttr));for(const row of e.sourceMissing){const sk=typeof row==='string'?row:(row?.sourceAttributeKey??row?.attributeKey??row?.name);const ak=MAP[sk]??sk;if(!ak)continue;for(let lv=1;lv<=18;lv++){const av=actual[String(lv)]?.[ak];if(av!==undefined&&av!==null)e.sourceMissingConfigured.push({sourceMissing:sk,attributeKey:ak,level:String(lv),actual:av});}}
const actualKeys=new Set();for(const vals of Object.values(actual))for(const ak of Object.keys(vals??{}))actualKeys.add(ak);for(const ak of actualKeys)if(!explicit.has(ak)){const levels={};for(const [lv,vals] of Object.entries(actual))if(vals?.[ak]!==undefined)levels[lv]=vals[ak];e.extraConfigured.push({attributeKey:ak,levels});}
e.sourceExplicitAttributeCount=Object.keys(expectedByAttr).length;e.sourceExplicitValueCount=Object.values(expectedByAttr).reduce((s,x)=>s+Object.keys(x).length,0);e.actualAttributeKeyCount=actualKeys.size;e.actualLevelValueCount=Object.values(actual).reduce((s,x)=>s+Object.keys(x??{}).length,0);if(e.differences.length||e.missingValues.length||e.sourceMissingConfigured.length||e.extraConfigured.length||e.unknownSourceRows.length)e.status='differences_found';fs.writeFileSync(path.join(OUT,key+'.json'),JSON.stringify(e,null,2));results.push(e);}
const summary={startedAt,finishedAt:new Date().toISOString(),sourceFilesTotal:files.length,excluded:[...EXCLUDE],characterListGet:{status:list.status,count:actualList.length,ms:list.ms},coverage:{checked:results.length,characterMissing:results.filter(x=>x.status==='character_missing_or_error').length,attributeErrors:results.filter(x=>x.status==='attributes_missing_or_error').length,complete:results.filter(x=>x.status==='checked').length,differencesFound:results.filter(x=>x.status==='differences_found').length},totals:{sourceExplicitAttributes:results.reduce((s,x)=>s+(x.sourceExplicitAttributeCount||0),0),sourceExplicitValues:results.reduce((s,x)=>s+(x.sourceExplicitValueCount||0),0),missingValues:results.reduce((s,x)=>s+x.missingValues.length,0),valueDifferences:results.reduce((s,x)=>s+x.differences.filter(d=>d.kind==='value').length,0),sourceMissingConfigured:results.reduce((s,x)=>s+x.sourceMissingConfigured.length,0),extraConfiguredAttributeEntries:results.reduce((s,x)=>s+x.extraConfigured.length,0),unknownSourceRows:results.reduce((s,x)=>s+x.unknownSourceRows.length,0)},items:results.map(x=>({sourceFile:x.sourceFile,characterKey:x.characterKey,name:x.name,status:x.status,sourceExplicitAttributes:x.sourceExplicitAttributeCount??null,sourceExplicitValues:x.sourceExplicitValueCount??null,missingValues:x.missingValues.length,valueDifferences:x.differences.filter(d=>d.kind==='value').length,sourceMissingConfigured:x.sourceMissingConfigured.length,extraConfigured:x.extraConfigured.length,unknownSourceRows:x.unknownSourceRows.length,checkedAt:x.checkedAt}))};fs.writeFileSync(path.join(OUT,'汇总.json'),JSON.stringify(summary,null,2));
