import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { batchConfig } from './批次配置.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const batchRoot = path.resolve(here, '..');
const revisionOneRoot = path.resolve(here, '..', '修订一');
const webRoot = path.resolve(here, '..', '..', '..', '..', '..');
const planningRoot = path.resolve(webRoot, '..', 'damage_viewer_project_planning');
const mode = process.argv[2];
if (!new Set(['freeze', 'prepare', 'review', 'write', 'readback', 'targets', 'manifest']).has(mode)) throw new Error('用法：node 批次执行.mjs freeze|prepare|review|write|readback|targets|manifest');

const names = { frozen: '02-冻结请求.json', sources: '03-来源散列快照.json', prepare: '04-写入前现值.json', review: '05-独立写前评审.json', journal: '06-写入流水.jsonl', write: '06-写入与即时回读.json', readback: '07-独立GET回读.json', targets: '08-页面目标.json', browser: '09-页面验收.json', experience: '录入体验报告.md', manifest: '10-证据清单.json' };
const files = Object.fromEntries(Object.entries(names).map(([key, name]) => [key, path.join(here, name)]));
const prior = {
  originalPrepare: path.join(batchRoot, '04-写入前现值.json'),
  originalFailure: path.join(batchRoot, '06-首个请求失败后只读回查.json'),
  revisionOnePrepare: path.join(revisionOneRoot, '04-写入前现值.json'),
  revisionOneReview: path.join(revisionOneRoot, '05-独立写前评审.json'),
  revisionOneFailure: path.join(revisionOneRoot, '06-首个请求失败后只读回查.json')
};
const managed = new Set(['gameId', 'skillKey', 'createdAt', 'updatedAt']);

function normalize(value) { if (Array.isArray(value)) return value.map(normalize); if (!value || typeof value !== 'object') return value; return Object.fromEntries(Object.keys(value).sort().map(key => [key, normalize(value[key])])); }
function strip(value) { if (Array.isArray(value)) return value.map(strip); if (!value || typeof value !== 'object') return value; return Object.fromEntries(Object.entries(value).filter(([key]) => !managed.has(key)).map(([key, item]) => [key, strip(item)])); }
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const hash = value => sha(JSON.stringify(normalize(value)));
const fileHash = file => sha(fs.readFileSync(file));
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
function writeJson(file, value) { fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n', { encoding: 'utf8', flag: 'wx' }); }
function missing(...paths) { for (const file of paths) if (fs.existsSync(file)) throw new Error(path.basename(file) + ' 已存在，拒绝覆盖。'); }
async function pool(values, count, worker) { const output = new Array(values.length); let cursor = 0; async function run() { while (cursor < values.length) { const index = cursor++; output[index] = await worker(values[index], index); } } await Promise.all(Array.from({ length: Math.min(values.length, count) }, run)); return output; }

function resolveSource(source) { const root = source.root === 'web' ? webRoot : source.root === 'planning' ? planningRoot : null; if (!root) throw new Error('未知来源根：' + source.root); return path.join(root, ...source.relativePath.split('/')); }
function verifySources() {
  const evidence = batchConfig.sourceFiles.map(source => { const file = resolveSource(source), actual = fileHash(file); assert.equal(actual, source.sha256, '来源散列漂移：' + source.relativePath); return { ...source, actualSha256: actual, byteSize: fs.statSync(file).size }; });
  const zh = read(resolveSource(batchConfig.sourceFiles.find(item => item.id === 'zhonyasReview'))).candidates.find(item => item.skillKey === 'item_3157_active' && item.status === 'DEFERRED');
  const qss = read(resolveSource(batchConfig.sourceFiles.find(item => item.id === 'qssReview'))).candidates.find(item => item.skillKey === 'item_3139_active' && item.status === 'DEFERRED');
  const red = read(resolveSource(batchConfig.sourceFiles.find(item => item.id === 'redemptionSource'))).selectedRawObjects.item_3107;
  assert.equal(zh.current.components.parameters.details.active_cooldown_ms.data.fixedValue, 120000); assert.equal(zh.current.components.parameters.details.stasis_duration_ms.data.fixedValue, 2500);
  assert.equal(qss.current.components.parameters.details.active_cooldown_ms.data.fixedValue, 90000); assert.equal(qss.current.components.parameters.details.move_speed_ratio.data.fixedValue, 0.5); assert.equal(qss.current.components.parameters.details.move_speed_duration_ms.data.fixedValue, 2000);
  assert(Math.abs(red.dataValues.DamageToChampions - 0.1) < 1e-6); assert.equal(red.dataValues.Cooldown, 90); assert.equal(red.dataValues.DiminishedTimer, 8); assert.equal(red.dataValues.DiminishedEffect, 0.5);
  return { status: 'PASS', files: evidence };
}
function correctionEvidence() { return Object.fromEntries(Object.entries(prior).map(([key, file]) => [key + 'Sha256', fileHash(file)])); }
function payload() { return { schemaVersion: batchConfig.schemaVersion, sourceVersion: batchConfig.sourceVersion, scope: batchConfig.scope, expectedCurrent: batchConfig.expectedCurrent, sourceFiles: batchConfig.sourceFiles, targets: batchConfig.targets, correction: batchConfig.correction, correctionEvidence: correctionEvidence(), writeBoundary: batchConfig.writeBoundary, runtimeBoundary: batchConfig.runtimeBoundary }; }
function writeAllowlist() {
  const allowed = new Set();
  for (const target of batchConfig.targets) { const base = '/skills/' + encodeURIComponent(target.skillKey); if (target.formulaUpdate) allowed.add('PUT ' + base + '/formulas/' + encodeURIComponent(target.formulaUpdate.formulaKey)); if (target.deleteParameterKey) allowed.add('DELETE ' + base + '/parameters/' + encodeURIComponent(target.deleteParameterKey)); if (target.process) allowed.add('POST ' + base + '/processes'); allowed.add('POST ' + base + '/trigger-rules'); if (target.updatedSkill) allowed.add('PUT ' + base); }
  return allowed;
}
function frozen() { const value = read(files.frozen), current = payload(); assert.deepEqual(value.payload, current, '冻结请求与当前配置不一致'); assert.equal(value.batchSha256, hash(current)); return value; }

function apiClient({ writes = false } = {}) {
  const token = String(process.env.DAMAGE_ENTRY_TOKEN || '').trim(); if (!token) throw new Error('缺少非空 DAMAGE_ENTRY_TOKEN；令牌不会保存或输出。');
  const base = (process.env.DAMAGE_API_BASE_URL || 'http://127.0.0.1:8080/api/admin/games/lol').replace(/\/+$/, ''), log = [], allowed = writeAllowlist();
  async function request(route, options = {}) { const method = options.method || 'GET'; if (method !== 'GET' && (!writes || !allowed.has(method + ' ' + route))) throw new Error('不允许的业务请求：' + method + ' ' + route); const response = await fetch(base + route, { method, headers: { Authorization: 'Bearer ' + token, Accept: 'application/json', ...(options.body === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) }), signal: AbortSignal.timeout(30_000) }); const raw = await response.text(); let data = null; try { data = raw ? JSON.parse(raw) : null; } catch { throw new Error('接口未返回JSON：' + route); } log.push({ method, path: route, status: response.status }); return { status: response.status, ok: response.ok, data }; }
  async function get(route, status = 200) { const result = await request(route); assert.equal(result.status, status, route + ' 状态应为 ' + status); return result.data; }
  return { request, get, log };
}
function requestAudit(api) { const methodCounts = {}, statusCounts = {}; for (const row of api.log) { methodCounts[row.method] = (methodCounts[row.method] || 0) + 1; statusCounts[row.status] = (statusCounts[row.status] || 0) + 1; } return { total: api.log.length, methodCounts, statusCounts, entries: api.log }; }

async function inventory(api) {
  const response = await api.get('/skills'); assert.equal(response.total, batchConfig.expectedCurrent.skillCount); assert.equal(response.items.length, response.total);
  const rows = await pool(response.items, 16, async skill => { const base = '/skills/' + encodeURIComponent(skill.skillKey); const [rules, processes] = await Promise.all([api.get(base + '/trigger-rules'), api.get(base + '/processes')]); return { skill: { skillKey: skill.skillKey, updatedAt: skill.updatedAt, body: strip(skill) }, rules: rules.map(row => ({ skillKey: skill.skillKey, ruleKey: row.ruleKey, updatedAt: row.updatedAt, eventType: row.eventType })), processes: processes.map(row => ({ skillKey: skill.skillKey, processKey: row.processKey, updatedAt: row.updatedAt })) }; });
  const skills = rows.map(row => row.skill).sort((a, b) => a.skillKey.localeCompare(b.skillKey)); const rules = rows.flatMap(row => row.rules).sort((a, b) => a.skillKey.localeCompare(b.skillKey) || a.ruleKey.localeCompare(b.ruleKey)); const processes = rows.flatMap(row => row.processes).sort((a, b) => a.skillKey.localeCompare(b.skillKey) || a.processKey.localeCompare(b.processKey));
  return { skillCount: skills.length, ruleCount: rules.length, processCount: processes.length, sourceInitializedCount: rules.filter(row => row.eventType === 'SOURCE_INITIALIZED').length, skills, rules, processes, hashes: { skills: hash(skills), rules: hash(rules), processes: hash(processes) } };
}
async function collection(api, key, segment, id) { const base = '/skills/' + encodeURIComponent(key) + '/' + segment, summaries = await api.get(base), details = []; for (const row of summaries) details.push(strip(await api.get(base + '/' + encodeURIComponent(row[id])))); return { keys: summaries.map(row => row[id]).sort(), details }; }
async function targetSnapshot(api, target) { const base = '/skills/' + encodeURIComponent(target.skillKey); const [skill, parameters, formulas, effects, processes, states, rules, relation, image] = await Promise.all([api.get(base), collection(api, target.skillKey, 'parameters', 'parameterKey'), collection(api, target.skillKey, 'formulas', 'formulaKey'), collection(api, target.skillKey, 'effects', 'effectKey'), collection(api, target.skillKey, 'processes', 'processKey'), collection(api, target.skillKey, 'internal-states', 'stateKey'), collection(api, target.skillKey, 'trigger-rules', 'ruleKey'), api.get('/equipment-skill-relations?equipmentKey=' + encodeURIComponent(target.ownerKey)), api.get(base + '/representative-image')]); return { skill, businessSkill: strip(skill), parameters, formulas, effects, processes, states, rules, relation, image }; }
const find = (set, key, value) => set.details.find(row => row[key] === value);
const beforeParameterKeys = target => [...target.expectedParameters, ...(target.deleteParameterKey ? [target.deleteParameterKey] : [])].sort();
function common(target, value) { assert.equal(value.skill.skillKey, target.skillKey); assert.equal(value.skill.name, target.skillName); assert.deepEqual(value.effects.keys, [...target.expectedEffects].sort()); for (const [key, expected] of Object.entries(target.expectedParameterValues)) assert.equal(find(value.parameters, 'parameterKey', key).fixedValue, expected); assert.equal(value.relation.total, 1); assert.equal(value.relation.items[0].equipmentKey, target.ownerKey); assert.equal(value.image.image?.enabled, true); }
function before(target, value) { common(target, value); assert.deepEqual(value.parameters.keys, beforeParameterKeys(target)); assert.deepEqual(value.processes.keys, []); assert.deepEqual(value.rules.keys, []); if (target.expectedCurrentDescription) assert.equal(value.skill.description, target.expectedCurrentDescription); if (target.expectedCurrentFormula) assert.deepEqual(find(value.formulas, 'formulaKey', target.expectedCurrentFormula.formulaKey), target.expectedCurrentFormula); }
function after(target, value) { common(target, value); assert.deepEqual(value.parameters.keys, [...target.expectedParameters].sort()); if (target.formulaUpdate) assert.deepEqual(find(value.formulas, 'formulaKey', target.formulaUpdate.formulaKey), target.formulaUpdate); if (target.updatedSkill) assert.deepEqual(value.businessSkill, target.updatedSkill); if (target.process) { assert.deepEqual(value.processes.keys, [target.process.processKey]); assert.deepEqual(find(value.processes, 'processKey', target.process.processKey), target.process); } else assert.deepEqual(value.processes.keys, []); assert.deepEqual(value.rules.keys, [target.rule.ruleKey]); assert.deepEqual(find(value.rules, 'ruleKey', target.rule.ruleKey), target.rule); }
const protectedSubset = value => ({ effects: value.effects, states: value.states, relation: value.relation, image: value.image });
function baselineSignature(global) { return { skills: global.skills, rules: global.rules.map(({ skillKey, ruleKey, updatedAt, eventType }) => ({ skillKey, ruleKey, updatedAt, eventType: eventType ?? global.rules.find(item => item.skillKey === skillKey && item.ruleKey === ruleKey)?.body?.eventSource?.eventType })), processes: global.processes.map(({ skillKey, processKey, updatedAt }) => ({ skillKey, processKey, updatedAt })) }; }
function initialBaseline() { const value = read(prior.revisionOnePrepare).global; return { skills: value.skills, rules: value.rules.map(row => ({ skillKey: row.skillKey, ruleKey: row.ruleKey, updatedAt: row.updatedAt, eventType: row.body.eventSource.eventType })), processes: value.processes.map(row => ({ skillKey: row.skillKey, processKey: row.processKey, updatedAt: row.updatedAt })) }; }

async function runFreeze() { missing(files.frozen, files.sources); const sources = verifySources(), body = payload(), batchSha256 = hash(body); writeJson(files.frozen, { schemaVersion: 3, frozenAt: new Date().toISOString(), status: 'FROZEN', batchSha256, payload: body, allowedWrites: [...writeAllowlist()].sort(), authorizationValueRecorded: false }); writeJson(files.sources, { schemaVersion: 3, capturedAt: new Date().toISOString(), ...sources, correctionEvidence: correctionEvidence(), batchSha256 }); process.stdout.write(JSON.stringify({ status: 'FROZEN', batchSha256, targetCount: batchConfig.targets.length, allowedWrites: [...writeAllowlist()].sort() }, null, 2)); }
async function runPrepare() { missing(files.prepare); const freeze = frozen(); verifySources(); const api = apiClient(), currentInventory = await inventory(api), baseline = initialBaseline(); assert.deepEqual(baselineSignature(currentInventory), baseline, '前两次零落地后全库基线发生变化'); assert.equal(currentInventory.ruleCount, batchConfig.expectedCurrent.ruleCount); assert.equal(currentInventory.sourceInitializedCount, batchConfig.expectedCurrent.sourceInitializedCount); const targets = []; for (const target of batchConfig.targets) { const value = await targetSnapshot(api, target); before(target, value); targets.push({ skillKey: target.skillKey, current: value, currentSha256: hash(value) }); } assert(api.log.every(row => row.method === 'GET')); const result = { schemaVersion: 3, capturedAt: new Date().toISOString(), status: 'PASS', methodPolicy: 'GET_ONLY', batchSha256: freeze.batchSha256, businessWrites: 0, inventory: currentInventory, targets, requestAudit: requestAudit(api), boundary: batchConfig.writeBoundary }; writeJson(files.prepare, result); process.stdout.write(JSON.stringify({ status: result.status, batchSha256: result.batchSha256, getCount: result.requestAudit.methodCounts.GET, inventory: { skillCount: currentInventory.skillCount, ruleCount: currentInventory.ruleCount, processCount: currentInventory.processCount, sourceInitializedCount: currentInventory.sourceInitializedCount }, targets: targets.map(row => row.skillKey), businessWrites: 0 }, null, 2)); }
async function runReview() { missing(files.review); const freeze = frozen(), prepared = read(files.prepare); verifySources(); const api = apiClient(), currentInventory = await inventory(api); assert.deepEqual(currentInventory, prepared.inventory); const checks = []; for (const target of batchConfig.targets) { const value = await targetSnapshot(api, target); before(target, value); const expected = prepared.targets.find(row => row.skillKey === target.skillKey); assert.equal(hash(value), expected.currentSha256); checks.push({ skillKey: target.skillKey, currentSha256: expected.currentSha256, status: 'APPROVED' }); } assert(api.log.every(row => row.method === 'GET')); const result = { schemaVersion: 3, reviewedAt: new Date().toISOString(), status: 'APPROVED', methodPolicy: 'GET_ONLY', approvedBatchSha256: freeze.batchSha256, approvedPrepareSha256: fileHash(files.prepare), inventory: { skillCount: currentInventory.skillCount, ruleCount: currentInventory.ruleCount, processCount: currentInventory.processCount, sourceInitializedCount: currentInventory.sourceInitializedCount, hashes: currentInventory.hashes }, targetChecks: checks, requestAudit: requestAudit(api), businessWrites: 0 }; writeJson(files.review, result); process.stdout.write(JSON.stringify({ status: result.status, approvedBatchSha256: result.approvedBatchSha256, getCount: result.requestAudit.methodCounts.GET, inventory: result.inventory, targets: checks, businessWrites: 0 }, null, 2)); }

function journal(row) { fs.appendFileSync(files.journal, JSON.stringify({ at: new Date().toISOString(), ...row }) + '\n', 'utf8'); }
async function verifyWrite(api, { method, route, detail = route, body, beforeBody, expectedBody, absentAfter = false, label }) { if (method === 'POST') assert.equal((await api.request(detail)).status, 404); else assert.deepEqual(strip(await api.get(detail)), beforeBody); journal({ label, action: '准备写入', method, path: route }); let response = null, error = null; try { response = await api.request(route, { method, ...(body === undefined ? {} : { body }) }); } catch (caught) { error = String(caught); } const got = await api.request(detail), matched = absentAfter ? got.status === 404 : got.status === 200 && hash(strip(got.data)) === hash(expectedBody); journal({ label, action: '写入后即时回读', responseStatus: response?.status ?? null, responseError: error, responseBodyOnFailure: response?.ok ? null : response?.data ?? null, readbackStatus: got.status, matched }); if (!matched) throw new Error(label + ' 未通过即时回读；禁止重放'); return { label, method, path: route, responseStatus: response?.status ?? null, responseError: error, readbackStatus: got.status, matched, bodySha256: body === undefined ? null : hash(body) }; }
async function runWrite() {
  missing(files.journal, files.write); const freeze = frozen(), prepared = read(files.prepare), review = read(files.review); verifySources(); assert.equal(review.status, 'APPROVED'); assert.equal(review.approvedBatchSha256, freeze.batchSha256); assert.equal(review.approvedPrepareSha256, fileHash(files.prepare)); const approval = String(process.env.DAMAGE_APPROVED_BATCH_SHA || '').trim(); if (!approval || approval !== freeze.batchSha256) throw new Error('批准散列不一致；业务写入尚未开始。');
  const api = apiClient({ writes: true }); assert.equal((await api.get('/skills')).total, batchConfig.expectedCurrent.skillCount); const snapshots = [];
  for (const target of batchConfig.targets) { const value = await targetSnapshot(api, target); before(target, value); assert.equal(hash(value), prepared.targets.find(row => row.skillKey === target.skillKey).currentSha256); snapshots.push({ skillKey: target.skillKey, value }); }
  fs.writeFileSync(files.journal, '', { encoding: 'utf8', flag: 'wx' }); const operations = [];
  for (const target of batchConfig.targets) { verifySources(); const base = '/skills/' + encodeURIComponent(target.skillKey), old = snapshots.find(row => row.skillKey === target.skillKey).value;
    if (target.formulaUpdate) { const { formulaKey, ...body } = target.formulaUpdate, route = base + '/formulas/' + encodeURIComponent(formulaKey); operations.push(await verifyWrite(api, { method: 'PUT', route, body, beforeBody: target.expectedCurrentFormula, expectedBody: target.formulaUpdate, label: target.skillKey + '/公式纠错' })); }
    if (target.deleteParameterKey) { verifySources(); const route = base + '/parameters/' + encodeURIComponent(target.deleteParameterKey); operations.push(await verifyWrite(api, { method: 'DELETE', route, beforeBody: find(old.parameters, 'parameterKey', target.deleteParameterKey), absentAfter: true, label: target.skillKey + '/删除失去引用参数' })); }
    if (target.process) { verifySources(); operations.push(await verifyWrite(api, { method: 'POST', route: base + '/processes', detail: base + '/processes/' + encodeURIComponent(target.process.processKey), body: target.process, expectedBody: target.process, label: target.skillKey + '/过程' })); }
    verifySources(); operations.push(await verifyWrite(api, { method: 'POST', route: base + '/trigger-rules', detail: base + '/trigger-rules/' + encodeURIComponent(target.rule.ruleKey), body: target.rule, expectedBody: target.rule, label: target.skillKey + '/规则' }));
    if (target.updatedSkill) { verifySources(); operations.push(await verifyWrite(api, { method: 'PUT', route: base, body: target.updatedSkill, beforeBody: old.businessSkill, expectedBody: target.updatedSkill, label: target.skillKey + '/说明' })); }
  }
  const immediate = [];
  for (const target of batchConfig.targets) { const value = await targetSnapshot(api, target); after(target, value); const old = snapshots.find(row => row.skillKey === target.skillKey).value; assert.deepEqual(protectedSubset(value), protectedSubset(old)); immediate.push({ skillKey: target.skillKey, current: value, currentSha256: hash(value) }); }
  const requestAudit = requestAudit(api); assert.deepEqual({ POST: requestAudit.methodCounts.POST, PUT: requestAudit.methodCounts.PUT, DELETE: requestAudit.methodCounts.DELETE }, { POST: 5, PUT: 3, DELETE: 1 }); const result = { schemaVersion: 3, writtenAt: new Date().toISOString(), status: 'PASS', batchSha256: freeze.batchSha256, authorizationValueRecorded: false, operations, immediateTargets: immediate, requestAudit, businessWrites: 9, boundary: batchConfig.writeBoundary }; writeJson(files.write, result); process.stdout.write(JSON.stringify({ status: result.status, batchSha256: result.batchSha256, businessWrites: result.businessWrites, methodCounts: requestAudit.methodCounts, operations }, null, 2));
}
function mapBy(values, first, second) { return new Map(values.map(row => [row[first] + '/' + row[second], row])); }
async function runReadback() {
  missing(files.readback); const freeze = frozen(), prepared = read(files.prepare), written = read(files.write); verifySources(); assert.equal(written.status, 'PASS'); assert.equal(written.batchSha256, freeze.batchSha256); const api = apiClient(), currentInventory = await inventory(api); assert.equal(currentInventory.skillCount, batchConfig.expectedCurrent.skillCount); assert.equal(currentInventory.ruleCount, batchConfig.expectedCurrent.finalRuleCount); assert.equal(currentInventory.processCount, prepared.inventory.processCount + batchConfig.expectedCurrent.addedProcessCount); assert.equal(currentInventory.sourceInitializedCount, batchConfig.expectedCurrent.sourceInitializedCount);
  const rules = mapBy(currentInventory.rules, 'skillKey', 'ruleKey'); for (const old of prepared.inventory.rules) assert.deepEqual(rules.get(old.skillKey + '/' + old.ruleKey), old, '旧规则变化：' + old.skillKey + '/' + old.ruleKey); const processes = mapBy(currentInventory.processes, 'skillKey', 'processKey'); for (const old of prepared.inventory.processes) assert.deepEqual(processes.get(old.skillKey + '/' + old.processKey), old, '旧过程变化：' + old.skillKey + '/' + old.processKey);
  const skills = new Map(currentInventory.skills.map(row => [row.skillKey, row])); for (const old of prepared.inventory.skills) { const target = batchConfig.targets.find(item => item.skillKey === old.skillKey), current = skills.get(old.skillKey); if (target?.updatedSkill) assert.deepEqual(current.body, target.updatedSkill); else assert.deepEqual(current, old, '未授权技能元数据变化：' + old.skillKey); }
  const targets = [];
  for (const target of batchConfig.targets) { const value = await targetSnapshot(api, target); after(target, value); const old = prepared.targets.find(row => row.skillKey === target.skillKey).current; assert.deepEqual(protectedSubset(value), protectedSubset(old)); const parameters = old.parameters.details.filter(row => row.parameterKey !== target.deleteParameterKey); assert.deepEqual(value.parameters.details, parameters); const formulas = old.formulas.details.filter(row => row.formulaKey !== target.formulaUpdate?.formulaKey); assert.deepEqual(value.formulas.details.filter(row => row.formulaKey !== target.formulaUpdate?.formulaKey), formulas); targets.push({ skillKey: target.skillKey, current: value, currentSha256: hash(value), conclusion: target.conclusion, completedBranch: target.completedBranch, remaining: target.remaining }); }
  assert(api.log.every(row => row.method === 'GET')); const result = { schemaVersion: 3, capturedAt: new Date().toISOString(), status: 'PASS', methodPolicy: 'GET_ONLY', batchSha256: freeze.batchSha256, businessWrites: 0, inventory: currentInventory, targets, requestAudit: requestAudit(api), boundary: batchConfig.runtimeBoundary }; writeJson(files.readback, result); process.stdout.write(JSON.stringify({ status: result.status, getCount: result.requestAudit.methodCounts.GET, inventory: { skillCount: currentInventory.skillCount, ruleCount: currentInventory.ruleCount, processCount: currentInventory.processCount, sourceInitializedCount: currentInventory.sourceInitializedCount }, targets: targets.map(row => ({ skillKey: row.skillKey, conclusion: row.conclusion, completedBranch: row.completedBranch, remaining: row.remaining })), businessWrites: 0 }, null, 2));
}
async function runTargets() { missing(files.targets); const freeze = frozen(), readback = read(files.readback); assert.equal(readback.status, 'PASS'); const targets = batchConfig.targets.map(target => ({ skillKey: target.skillKey, skillName: target.skillName, ownerKey: target.ownerKey, expectedImageEnabled: true, expectedRule: target.rule, expectedProcess: target.process, expectedFormula: target.formulaUpdate ?? null, deletedParameterKey: target.deleteParameterKey ?? null, expectedUpdatedSkill: target.updatedSkill, completedBranch: target.completedBranch, remaining: target.remaining, readbackSha256: readback.targets.find(row => row.skillKey === target.skillKey).currentSha256 })); const result = { schemaVersion: 3, generatedAt: new Date().toISOString(), status: 'PASS', batchSha256: freeze.batchSha256, source: '07-独立GET回读.json', targetCount: targets.length, targets, boundary: '页面只读核对图片、组成、过程、规则和救赎公式；不点击任何写入动作。' }; writeJson(files.targets, result); process.stdout.write(JSON.stringify({ status: result.status, targetCount: result.targetCount, targets: targets.map(row => ({ skillKey: row.skillKey, processKey: row.expectedProcess?.processKey ?? null, ruleKey: row.expectedRule.ruleKey, formulaKey: row.expectedFormula?.formulaKey ?? null })) }, null, 2)); }
async function runManifest() {
  missing(files.manifest); const freeze = frozen(), prepared = read(files.prepare), review = read(files.review), written = read(files.write), readback = read(files.readback), targets = read(files.targets), browser = read(files.browser); assert.equal(prepared.status, 'PASS'); assert.equal(review.status, 'APPROVED'); assert.equal(written.status, 'PASS'); assert.equal(readback.status, 'PASS'); assert.equal(targets.status, 'PASS'); assert.equal(browser.status, 'PASS'); assert.equal(browser.targetCount, 3); assert.equal(browser.businessWrites, 0); assert.equal(browser.nonGetRequests, 0); assert.equal(browser.consoleErrors, 0); assert.equal(browser.consoleWarnings, 0); assert.equal(browser.pageErrors, 0); assert.equal(browser.failedRequests, 0); assert.equal(browser.requestAudit.postBrowserGetReadback.ruleCount, batchConfig.expectedCurrent.finalRuleCount); assert.equal(browser.requestAudit.postBrowserGetReadback.processCount, readback.inventory.processCount); assert(browser.targets.every(row => row.matched));
  const evidence = ['../01-补录方案.md', '../README.md', '../批次配置.mjs', '../批次执行.mjs', '../02-冻结请求.json', '../03-来源散列快照.json', '../04-写入前现值.json', '../05-独立写前评审.json', '../06-写入流水.jsonl', '../06-首个请求失败后只读回查.json', '../首次写入停止说明.md', '../修订一/README.md', '../修订一/批次配置.mjs', '../修订一/批次执行.mjs', '../修订一/02-冻结请求.json', '../修订一/03-来源散列快照.json', '../修订一/04-写入前现值.json', '../修订一/05-独立写前评审.json', '../修订一/06-写入流水.jsonl', '../修订一/06-首个请求失败后只读回查.json', '../修订一/首次写入停止说明.md', ...Object.values(names).filter(name => name !== names.manifest)]; for (const name of evidence) assert(fs.existsSync(path.resolve(here, name)), '缺少证据：' + name);
  const result = { schemaVersion: 3, capturedAt: new Date().toISOString(), status: 'PASS', scope: batchConfig.scope, batchSha256: freeze.batchSha256, stoppedAttempts: [{ version: '原始', landedWrites: 0, evidence: '../06-首个请求失败后只读回查.json' }, { version: '修订一', landedWrites: 0, evidence: '../修订一/06-首个请求失败后只读回查.json' }], requestAudit: { prepare: prepared.requestAudit, review: review.requestAudit, write: written.requestAudit, readback: readback.requestAudit, browserPostReadback: browser.requestAudit.postBrowserGetReadback }, final: { skillCount: readback.inventory.skillCount, ruleCount: readback.inventory.ruleCount, processCount: readback.inventory.processCount, sourceInitializedCount: readback.inventory.sourceInitializedCount }, conclusions: batchConfig.targets.map(target => ({ skillKey: target.skillKey, conclusion: target.conclusion, completedBranch: target.completedBranch, remaining: target.remaining })), browser: { targetCount: browser.targetCount, screenshots: browser.screenshots.length, consoleErrors: browser.consoleErrors, consoleWarnings: browser.consoleWarnings, pageErrors: browser.pageErrors, failedRequests: browser.failedRequests, businessWrites: browser.businessWrites }, files: evidence.map(name => { const file = path.resolve(here, name); return { name, sha256: fileHash(file), byteSize: fs.statSync(file).size }; }), boundary: batchConfig.runtimeBoundary }; writeJson(files.manifest, result); process.stdout.write(JSON.stringify({ status: result.status, scope: result.scope, batchSha256: result.batchSha256, stoppedAttempts: result.stoppedAttempts, final: result.final, browser: result.browser, conclusions: result.conclusions, fileCount: result.files.length }, null, 2));
}

if (mode === 'freeze') await runFreeze(); else if (mode === 'prepare') await runPrepare(); else if (mode === 'review') await runReview(); else if (mode === 'write') await runWrite(); else if (mode === 'readback') await runReadback(); else if (mode === 'targets') await runTargets(); else await runManifest();
