// 预期独立按冻结来源手算；不从表达式生产预期。
export function verify(plan){
 const arithmetic=[],invariants=[];
 const pv=(s,key,rank=1,level=1,inputs={})=>{const p=s.write.parameters.find(p=>p.parameterKey===key);if(!p)throw Error('缺参数 '+s.skillKey+'/'+key);const n=p.valueMode==='FIXED'?p.fixedValue:p.valueMode==='RUNTIME_INPUT'?inputs[key]:p.levelValues[String(p.valueMode==='CHARACTER_LEVEL'?level:rank)];if(!Number.isFinite(n))throw Error('缺输入 '+key);return n;};
 const ev=(s,n,r,l,a,i)=>{if(n.nodeType==='PARAMETER')return pv(s,n.parameterKey,r,l,i);if(n.nodeType==='ATTRIBUTE'){const key=n.attributeOwner+'.'+n.attributeKey+'.'+n.attributeValueKind;if(!Number.isFinite(a[key]))throw Error('缺属性 '+key);return a[key];}const [x,y]=n.operands.map(v=>ev(s,v,r,l,a,i));return {ADD:()=>x+y,SUBTRACT:()=>x-y,MULTIPLY:()=>x*y,DIVIDE:()=>x/y,MIN:()=>Math.min(x,y),MAX:()=>Math.max(x,y)}[n.operation]();};
 const AD={'SOURCE.attack_damage.TOTAL':200},BAD={'SOURCE.attack_damage.BONUS':100},AP={'SOURCE.ability_power.TOTAL':100},BAP={'SOURCE.ability_power.BONUS':100},THP={'TARGET.hp.TOTAL':2000};
 const cases=[
 ['garen_p','regen_per_5s',1,1,{'SOURCE.hp.TOTAL':2000},30],['garen_p','regen_per_5s',1,6,{'SOURCE.hp.TOTAL':2000},50],['garen_p','regen_per_5s',1,7,{'SOURCE.hp.TOTAL':2000},66],['garen_p','regen_per_5s',1,13,{'SOURCE.hp.TOTAL':2000},162],['garen_p','regen_per_5s',1,14,{'SOURCE.hp.TOTAL':2000},170],['garen_p','regen_per_5s',1,18,{'SOURCE.hp.TOTAL':2000},202],
 ['garen_q','bonus_damage',1,1,AD,130],['garen_q','bonus_damage',5,18,AD,250],['garen_w','shield',1,1,{'SOURCE.hp.BONUS':500},155],['garen_w','shield',5,18,{'SOURCE.hp.BONUS':500},235],['garen_e','damage_per_spin',1,1,AD,84],['garen_e','damage_per_spin',5,18,AD,120],['garen_e','nearest_damage_per_spin',1,1,AD,105],['garen_e','nearest_damage_per_spin',5,18,AD,150],['garen_e','critical_multiplier',1,1,{'SOURCE.critical_strike_damage_bonus_percent.TOTAL':0},1.3],['garen_e','critical_multiplier',5,18,{'SOURCE.critical_strike_damage_bonus_percent.TOTAL':.3},1.39],['garen_r','damage',1,1,{'TARGET.hp.MISSING':1000},375],['garen_r','damage',3,18,{'TARGET.hp.MISSING':1000},625],
 ['jax_p','current_attack_speed',1,1,{},.05,{current_passive_stacks:1}],['jax_p','current_attack_speed',1,3,{},.4,{current_passive_stacks:8}],['jax_p','current_attack_speed',1,4,{},.52,{current_passive_stacks:8}],['jax_p','current_attack_speed',1,13,{},.88,{current_passive_stacks:8}],['jax_p','current_attack_speed',1,18,{},1,{current_passive_stacks:8}],['jax_p','current_attack_speed',1,18,{},1,{current_passive_stacks:9}],['jax_p','current_attack_speed',1,18,{},0,{current_passive_stacks:0}],
 ['jax_q','damage',1,1,BAD,165],['jax_q','damage',5,18,BAD,325],['jax_w','bonus_damage',1,1,AP,110],['jax_w','bonus_damage',5,18,AP,250],
 ['jax_e','counterstrike_damage',1,1,{...BAP,...THP},190,{actual_dodged_attacks:0}],['jax_e','counterstrike_damage',1,1,{...BAP,...THP},228,{actual_dodged_attacks:1}],['jax_e','counterstrike_damage',1,1,{...BAP,...THP},380,{actual_dodged_attacks:5}],['jax_e','counterstrike_damage',5,18,{...BAP,...THP},620,{actual_dodged_attacks:6}],['jax_e','counterstrike_damage',5,18,{...BAP,...THP},310,{actual_dodged_attacks:0}],
 ['jax_r','passive_damage',1,1,AP,135],['jax_r','passive_damage',3,18,AP,245],['jax_r','active_damage',1,1,BAP,200],['jax_r','active_damage',3,18,BAP,350],['jax_r','armor_gain',1,1,BAD,85],['jax_r','armor_gain',3,18,BAD,115],['jax_r','magic_resistance_gain',1,1,BAD,51],['jax_r','magic_resistance_gain',3,18,BAD,69]
 ];
 if(plan.skills.mordekaiser_p)cases.push(
 ['mordekaiser_p','attack_bonus_damage',1,1,AP,40],['mordekaiser_p','aura_damage_per_second',1,1,{...AP,...THP},55,{aura_target_hp_ratio:.01}],['mordekaiser_p','aura_damage_per_second',1,1,{...AP,...THP},135,{aura_target_hp_ratio:.05}],
 ['mordekaiser_q','normal_damage',1,1,{...AP,...BAD},270,{current_character_level_bonus:0}],['mordekaiser_q','normal_damage',5,18,{...AP,...BAD},455,{current_character_level_bonus:45}],['mordekaiser_q','isolated_damage',1,1,{...AP,...BAD},351,{current_character_level_bonus:0}],['mordekaiser_q','isolated_damage',5,18,{...AP,...BAD},682.5,{current_character_level_bonus:45}],
 ['mordekaiser_w','minimum_shield',1,1,{'SOURCE.hp.TOTAL':2000},100],['mordekaiser_w','maximum_shield',1,1,{'SOURCE.hp.TOTAL':2000},600],['mordekaiser_w','initial_shield',1,1,{'SOURCE.hp.TOTAL':1000},600,{actual_released_shield:600}],['mordekaiser_w','recast_heal',1,1,{},70,{actual_remaining_shield:200}],['mordekaiser_w','recast_heal',5,18,{},90,{actual_remaining_shield:200}],['mordekaiser_w','recast_heal',5,18,{},0,{actual_remaining_shield:0}],
 ['mordekaiser_e','damage',1,1,AP,105],['mordekaiser_e','damage',5,18,AP,185],
 ['renekton_p','low_health_attack_fury',1,1,{},7.5],['renekton_q','normal_damage',1,1,BAD,160],['renekton_q','normal_damage',5,18,BAD,280],['renekton_q','empowered_damage',1,1,BAD,230],['renekton_q','empowered_damage',5,18,BAD,410],['renekton_q','normal_champion_heal',1,1,BAD,29],['renekton_q','normal_champion_heal',5,18,BAD,61],['renekton_q','empowered_champion_heal',1,1,BAD,87],['renekton_q','empowered_champion_heal',5,18,BAD,183],['renekton_q','normal_champion_heal',1,1,{'SOURCE.attack_damage.BONUS':300},50],['renekton_q','empowered_champion_heal',1,1,{'SOURCE.attack_damage.BONUS':300},189],['renekton_q','normal_champion_heal',1,1,{'SOURCE.attack_damage.BONUS':2000},50],['renekton_q','empowered_champion_heal',1,1,{'SOURCE.attack_damage.BONUS':2000},200],
 ['renekton_w','damage_per_hit',1,1,AD,155],['renekton_w','damage_per_hit',5,18,AD,215],['renekton_w','normal_total_damage',1,1,AD,310],['renekton_w','normal_total_damage',5,18,AD,430],['renekton_w','empowered_total_damage',1,1,AD,465],['renekton_w','empowered_total_damage',5,18,AD,645],
 ['renekton_e','normal_damage',1,1,BAD,130],['renekton_e','normal_damage',5,18,BAD,250],['renekton_e','empowered_damage',1,1,BAD,205],['renekton_e','empowered_damage',5,18,BAD,385],['renekton_r','aura_damage_per_second',1,1,{...AP,...BAD},80],['renekton_r','aura_damage_per_second',3,18,{...AP,...BAD},260]
 );
 for(const[skey,fkey,r,l,a,expected,inputs={}]of cases){const s=plan.skills[skey],f=s.write.formulas.find(f=>f.formulaKey===fkey);if(!f)throw Error('缺公式 '+skey+'/'+fkey);const actual=ev(s,f.expression,r,l,a,inputs);arithmetic.push({skill:skey,formula:fkey,rank:r,level:l,attributes:a,inputs,expected,actual,match:Math.abs(actual-expected)<1e-8});}
 for(const[skey,key,r,expected]of [['garen_q','move_duration_ms',5,3600],['garen_w','reduction_ratio',1,.25],['garen_w','reduction_ratio',5,.41],['garen_w','upfront_duration_ms',1,750],['jax_q','mana_cost',1,50],['jax_w','cooldown_ms',5,3000],['jax_e','target_max_hp_ratio',1,.04],['jax_e','area_skill_reduction_ratio',1,.25],['jax_e','defensive_duration_ms',1,2000],['jax_r','passive_window_ms',1,2500],['jax_r','resist_duration_ms',1,8000]]){const actual=pv(plan.skills[skey],key,r);arithmetic.push({skill:skey,parameter:key,rank:r,expected,actual,match:Object.is(actual,expected)});}
 for(const s of Object.values(plan.skills)){
  const keys={parameters:new Set(s.write.parameters.map(v=>v.parameterKey)),formulas:new Set(s.write.formulas.map(v=>v.formulaKey)),effects:new Set(s.write.effects.map(v=>v.effectKey))},missing=[];
  function walk(n){if(!n||typeof n!=='object')return;if((n.kind==='PARAMETER'||n.nodeType==='PARAMETER')&&!keys.parameters.has(n.parameterKey))missing.push(n.parameterKey);if(n.kind==='FORMULA'&&!keys.formulas.has(n.formulaKey))missing.push(n.formulaKey);if(n.actionType==='EXECUTE_EFFECT'&&!keys.effects.has(n.detail.effectKey))missing.push(n.detail.effectKey);for(const v of Object.values(n))if(v&&typeof v==='object')walk(v);}
  walk(s.write);invariants.push({skill:s.skillKey,check:'内部引用完整',missing,match:!missing.length});
  invariants.push({skill:s.skillKey,check:'施法过程有实际行为且不生成敌人命中',match:s.write.processes.every(p=>p.effectBindings.length+p.stateOperations.length>0&&p.effectBindings.every(b=>!s.write.effects.find(e=>e.effectKey===b.effectKey)?.results.some(r=>r.resultType==='DAMAGE')))});
  invariants.push({skill:s.skillKey,check:'无目标持续状态法术护盾绕过',match:s.write.effects.every(e=>e.results.every(r=>!(r.target==='TARGET'&&r.lifecycleBehavior?.moment==='PERSISTENT'&&r.resultType==='STATUS_OPERATION')))});
 }
 const w=plan.skills.garen_w.write.effects;invariants.push({skill:'garen_w',check:'护盾和韧性各自独立生命周期',match:w.find(e=>e.effectKey==='upfront_shield')!==w.find(e=>e.effectKey==='upfront_tenacity')&&w.find(e=>e.effectKey==='upfront_shield').results.length===1});
 invariants.push({skill:'jax_p',check:'没有虚构2.5秒整组到期或350毫秒周期',match:plan.skills.jax_p.write.effects.every(e=>e.lifecycle?.durationValue===null&&e.lifecycle?.periodicIntervalValue===null)&&plan.skills.jax_p.write.triggerRules.length===0});
 invariants.push({skill:'jax_w',check:'未在成本过程或任意命中自动附伤',match:plan.skills.jax_w.write.triggerRules.length===0});
 invariants.push({skill:'jax_e',check:'结算需要实际躲闪输入而非假事件',match:plan.skills.jax_e.write.triggerRules.length===0&&plan.skills.jax_e.write.parameters.some(p=>p.parameterKey==='actual_dodged_attacks'&&p.valueMode==='RUNTIME_INPUT')});
 if(plan.skills.mordekaiser_p){
  for(const[skey,key,r,expected]of [['mordekaiser_p','move_speed_ratio',1,.03],['mordekaiser_e','cooldown_ms',1,16000],['mordekaiser_e','cooldown_ms',5,8000],['mordekaiser_r','realm_duration_ms',1,7000],['mordekaiser_r','stat_steal_ratio',1,.1],['renekton_q','empowered_fury_cost',1,50],['renekton_w','extra_fury_vs_champion',1,10],['renekton_e','armor_reduction_ratio',5,.35],['renekton_r','maximum_health_gain',3,700],['renekton_r','fury_on_cast',1,20],['renekton_r','duration_ms',1,15000]]){const actual=pv(plan.skills[skey],key,r);arithmetic.push({skill:skey,parameter:key,rank:r,expected,actual,match:Object.is(actual,expected)});}
  invariants.push({skill:'mordekaiser_w',check:'没有猜定护盾衰减效果',match:plan.skills.mordekaiser_w.write.effects.every(e=>e.results.every(r=>r.resultType!=='NORMAL_SHIELD'))});
  invariants.push({skill:'mordekaiser_r',check:'没有相互持续读取的偷取反馈',match:plan.skills.mordekaiser_r.write.effects.length===0});
  invariants.push({skill:'renekton_p',check:'没有使用法力/能量伪造怒气',match:['p','q','w','e','r'].every(k=>plan.skills['renekton_'+k].write.effects.every(e=>e.results.every(r=>r.resultType!=='RESOURCE_CHANGE')))});
  invariants.push({skill:'renekton_r',check:'最大生命没有重复作为直接治疗',match:plan.skills.renekton_r.write.effects.every(e=>e.results.every(r=>r.resultType!=='DIRECT_HEAL'))});
 }
 return {arithmetic,invariants};
}
