// 只整理本目录已完成的原始证据，不请求业务接口。
import {readFile,writeFile} from 'node:fs/promises';
const read=async n=>JSON.parse(await readFile(new URL(n,import.meta.url),'utf8'));
const plan=await read('./完整候选.json'),before=await read('./写前现值.json'),first=await read('./前十技能写入结果.json'),second=await read('./写入结果.json'),final=await read('./最终独立回读证据.json');
if(!final.success||final.snapshot.missing.length||final.snapshot.conflicts.length)throw Error('独立回读尚未完成，不生成完成说明');
const count=a=>Object.values(a).reduce((n,items)=>n+items.length,0),oldCount=Object.values(before.skills).reduce((n,s)=>n+count(s.components),0),newCount=[first,second].reduce((n,r)=>n+r.events.filter(e=>e.postStatus>=200&&e.postStatus<300&&e.match).length,0),totals=Object.fromEntries(Object.keys(Object.values(plan.skills)[0].write).map(k=>[k,Object.values(plan.skills).reduce((n,s)=>n+s.write[k].length,0)]));
const referenced=s=>new Set([...s.write.processes.flatMap(p=>p.effectBindings.map(b=>b.effectKey)),...s.write.triggerRules.flatMap(r=>r.actions.filter(a=>a.actionType==='EXECUTE_EFFECT').map(a=>a.detail.effectKey))]),wired=Object.values(plan.skills).reduce((n,s)=>n+s.write.effects.filter(e=>referenced(s).has(e.effectKey)).length,0);
if(newCount+oldCount!==final.snapshot.readbacks.length)throw Error('新增与保留计数不闭合');
const summary={at:new Date().toISOString(),skills:20,components:final.snapshot.readbacks.length,newConfirmed:newCount,preservedExisting:oldCount,normalCollectionMissing:0,excludedRejected:1,totals,referencedEffects:wired,standaloneEffects:totals.effects-wired,arithmetic:final.verification.arithmetic.length,invariants:final.verification.invariants.length};
await writeFile(new URL('./实际保存汇总.json',import.meta.url),JSON.stringify(summary,null,2)+'\n');
const lines=['# 盖伦、贾克斯、莫德凯撒、雷克顿机制实录第六批','',`本批正常集合${summary.components}项已完成独立回读：新增${newCount}、精确保留原有${oldCount}，正常集合缺项0。另有1个被真实接口拒绝的动态攻速效果经批准撤出，原候选、POST400及GET404均保留；该项属于明确系统缺口，不计入233项已保存。`,'',`共${totals.parameters}参数、${totals.formulas}公式、${totals.effects}效果、${totals.processes}过程、${totals.internalStates}内部状态、${totals.triggerRules}规则。重新读取20个主体、120类组成列表、${summary.components}个详情，全部业务字段一致；实际保存表达式的${summary.arithmetic}个独立算例与${summary.invariants}个结构约束通过。原技能主体元数据、挂载关系和代表图保持一致。`,'',`其中${wired}个效果由本技能过程或规则直接引用，${totals.effects-wired}个仍是独立组成；已保存不表示完整机制已触发。当前证据是来源、接口和独立GET，没有执行浏览器或Wasm战斗验收。本批由当前执行代理接手已中断的Cursor路线，不冒称Cursor成功。`,'','| 技能 | 参数 | 公式 | 效果 | 过程 | 状态 | 规则 |','| --- | ---: | ---: | ---: | ---: | ---: | ---: |'];
for(const s of Object.values(plan.skills))lines.push(`| ${s.skillKey} ${s.name} | ${Object.values(s.write).map(a=>a.length).join(' | ')} |`);
lines.push('','盖伦原有53项来自规划树盖伦技能候选、盖伦技能实录.json与盖伦效果回读-2026-09-07.md；本次以实库为准找到并复核，保留原键、说明和排序。原有38参数、7公式、8效果没有重复创建。其余原有11项是贾克斯6项、后两位英雄5项公共参数。','','来源固定客户端16.17与官方16.17.1。根绑定与数值证据.json保留当前主技能对象完整计算树，补充文本证据.json保留当前绑定说明，来源冻结目录保留原文件地址和摘要。Mordekaiser E采用当前Cooldown的16/14/12/10/8秒，旧cooldownTime的18/16/14/12/10未采用。','','明确限制见完整审查说明.md：贾克斯P动态持续属性不能使用计算时输入；莫德P插值等级端点、Q省略初值的等级项没有猜零，W没有把不明衰减写成线性护盾，R没有按持续读取目标现值做双向偷取。雷克顿怒气目录缺失，没有用法力/能量代替或整数化7.5增量；Q仍保留单英雄高额攻击力下有效的治疗上限，E仅第二次可怒气强化，R保留自身生命和每秒伤害/怒气数值，不猜首次周期。','','录入.mjs默认全量只读，显式--apply只允许创建后两英雄缺项；前十技能录入.mjs固定前10候选摘要，只允许创建贾克斯缺项。两入口先校验完整冻结版本、来源、目录、所有现有组成及主体/挂载/图片；异值停止且不覆盖。每项POST之后独立GET，错误或断线先查落地，不自动重放POST。执行记录目录保留每轮候选快照、原始全量预检和完整结果，写入流水.jsonl为追加证据。','','独立回读.mjs只请求GET，重新读取全部组成并对实际保存表达式验算；最终独立回读证据.json是当前保存证据。候选文件中的阶段描述及apiWrites=0仅指生成器不写API，生成时点和真实保存结果分别核对；当前状态以本README、实际保存汇总.json及最终独立回读为准。生成候选不等于执行写入，也不会重新执行原失败请求。','','未保存候选/原119候选.json、贾克斯被动动态效果400及404.json和撤出差异核对.json保留唯一撤项。其限制来自当前后端PERSISTENT+MOMENT_EVALUATION禁止直接或递归引用RUNTIME_INPUT，未改成施加快照绕过。当前请求类型核对.json另有20技能的前端请求类型检查；类型通过不代表后端所有语义都接受。','','代表页面及最终提交由主任务后续验收安排；本目录尚未执行浏览器验收。');
await writeFile(new URL('./README.md',import.meta.url),lines.join('\n')+'\n');
await writeFile(new URL('./实际配置体验报告.md',import.meta.url),['# 第六批实际配置体验','',`正常集合${summary.components}项全部回读一致，新增${newCount}，保留${oldCount}。前10实际新增59；后10新增110。每项写后独立GET，再次全量GET20主体/120列表/${summary.components}详情，${summary.arithmetic}独算与${summary.invariants}约束通过。`,'','普通技能伤害、即时治疗、独立限时生命/抗性、法力成本和实际命中规则沿成熟结构保存。被动输入公式能够保存，但贾克斯的持续动态攻速效果被后端明确拒绝，POST400后GET404；已保留事实并撤出该效果，没有把它改成固定快照或假状态。其他对象顺序继续完成。','','盖伦已有53项说明主进度未记录不代表实库为空；本次读取历史实录、原键和全字段后保留，未重新造同名组成。雷克顿大招保存15秒最大生命与主动挂接，但没有额外添加等额直接治疗；其怒气和持续伤害仍需真实资源及事件执行。莫德W治疗读取本次实际剩余护盾，初始护盾快照不会因后来最大生命变化被再次截断；完整衰减护盾没有猜测保存。','','当前9个效果有本技能过程或规则引用，其余24个独立效果有明确后续条件。候选与算例不是浏览器交互或战斗运行证明。建议主任务查看jax_q的法力过程/实际命中规则、mordekaiser_w的剩余护盾输入与治疗、renekton_q的治疗封顶及renekton_r的生命效果/过程，再按真实GET核验页面读取。'].join('\n')+'\n');
console.log(JSON.stringify(summary));
