import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url)),web='C:/project/damage_web_dev/web',require=createRequire(path.join(web,'package.json')),ts=require('typescript');
const plan=JSON.parse(fs.readFileSync(path.join(here,'完整候选.json'),'utf8')),fields={parameters:['skillParameter','CreateSkillParameterRequest'],formulas:['skillFormula','CreateSkillFormulaRequest'],effects:['skillEffect','CreateSkillEffectRequest'],processes:['skillProcess','CreateSkillProcessRequest'],internalStates:['skillInternalState','CreateSkillInternalStateRequest'],triggerRules:['skillTriggerRule','CreateSkillTriggerRuleRequest']};
let code=Object.values(fields).map(([file,type])=>`import type {${type}} from ${JSON.stringify(web+'/src/types/'+file+'.ts')};`).join('\n');for(const s of Object.values(plan.skills))for(const[k,[,type]]of Object.entries(fields))code+=`\nconst ${s.skillKey}_${k}: ${type}[] = ${JSON.stringify(s.write[k])};`;
const virtual=path.join(here,'__only_in_memory__.ts'),options={noEmit:true,strict:true,skipLibCheck:true,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,allowImportingTsExtensions:true,types:[]},host=ts.createCompilerHost(options),original=host.getSourceFile;host.getSourceFile=(file,language,onError,newFile)=>path.resolve(file)===path.resolve(virtual)?ts.createSourceFile(file,code,language,true):original(file,language,onError,newFile);
const diagnostics=ts.getPreEmitDiagnostics(ts.createProgram([virtual],options,host));const out={at:new Date().toISOString(),skills:Object.keys(plan.skills).length,compilerVersion:ts.version,boundary:'只在内存核对当前前端请求类型，不写构建产物；不代替真实后端语义校验',success:diagnostics.length===0,diagnostics:diagnostics.map(d=>ts.flattenDiagnosticMessageText(d.messageText,'\n'))};fs.writeFileSync(path.join(here,'当前请求类型核对.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));if(diagnostics.length)process.exitCode=1;
