import {begin,common,data,breaks,literal,formula,pn,attr,add,mul,op,runtime,statEffect,val,damage,coeff,pending,exclude,hit,rule,heal,plan} from './英雄工具.mjs';
{
 const x=begin('mordekaiser_p');data(x,'CombatTrackingDuration','aura_duration_ms','光环及加速刷新时长（毫秒）',{scale:1000});data(x,'MaximumStacks','activation_hits','激活被动所需攻击或基础技能命中数');data(x,'PercentAPAddedToAutos','attack_ap_ratio','普通攻击附伤法强系数');breaks(x,'move_speed_ratio','被动加速比例',x.p.mSpellCalculations.PassiveMovementSpeed.mFormulaParts[0]);
 literal(x,'aura_base_damage_per_second','光环每秒固定伤害',5,'AuraDamagePerStack第一项Number=5；说明明确每秒。','mSpellCalculations.AuraDamagePerStack');coeff(x,'AuraDamagePerStack',1,'aura_ap_ratio','光环每秒法强系数');runtime(x,'aura_target_hp_ratio','本等级已确证光环最大生命比例','当前PercentHealthForAura插值起值1、终值5，以百分数显示；节点未明确等级端点，需提供经证实的本等级小数比例，不默认按1至18级插值。');
 formula(x,'attack_bonus_damage','被动普通攻击额外魔法伤害',mul(pn('attack_ap_ratio'),attr('ability_power')),'普通攻击额外.4法强，不含普通攻击本体。');formula(x,'aura_damage_per_second','黑暗起兮每秒伤害量',add(pn('aura_base_damage_per_second'),mul(pn('aura_ap_ratio'),attr('ability_power')),mul(pn('aura_target_hp_ratio'),attr('hp','TARGET'))),'5+.3法强+当前已确证等级比例×目标最大生命；仅每秒总量，不冒充单跳伤害。');damage(x,'attack_bonus_damage','黑暗起兮普攻附伤','attack_bonus_damage','magic',{delivery:'BASIC_ATTACK',block:null});rule(x,'basic_attack_hit','真实普攻命中附带黑暗起兮伤害',{eventType:'BASIC_ATTACK_HIT',detail:{}},['attack_bonus_damage']);statEffect(x,'aura_move_speed','黑暗起兮自身加速',val('move_speed_ratio'),'move_speed_percent',{duration:val('aura_duration_ms')});
 x.c.proofs.push({source:'当前PercentHealthForAura完整插值节点',raw:x.p.mSpellCalculations.PercentHealthForAura,disposition:'端点等级未明，比例通过明确输入提供'});pending(x,'光环等级比例端点与实际伤害节拍','每秒量已确认，插值等级端点及单跳间隔/首次执行未明确；不把每秒伤害直接绑每次命中，也不自动每秒触发。','来源');pending(x,'三次合法基础技能/攻击命中激活与刷新','当前根数据FuryForQHit/FuryForAutoHit/FuryForEHit均1；启动须普通技能/攻击对英雄命中，保持4秒并刷新；不得把P光环每跳或R作为无条件新叠层。');exclude(x,'野怪专用上限与空间光环范围','对手伤害和自身移速保留，不新增野怪上限或范围查找。');
}
{
 const x=begin('mordekaiser_q');common(x);data(x,'QBaseDamage','base_damage','破灭之锤基础伤害');data(x,'APRatio','ap_ratio','破灭之锤法强系数');data(x,'ADRatio','bonus_ad_ratio','破灭之锤额外攻击力系数');data(x,'IsolationScalar','isolated_multiplier','只命中单个敌人时伤害倍率');runtime(x,'current_character_level_bonus','当前已确证等级附加伤害','QDamage包含角色等级断点项，10级及以后每级增5；mLevel1Value与初始斜率省略，当前未取得默认值证据，须提供明确等级附加量，缺失不可填零。');
 const normal=add(pn('base_damage'),pn('current_character_level_bonus'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS')),mul(pn('ap_ratio'),attr('ability_power')));formula(x,'normal_damage','破灭之锤通常伤害',normal,'80/115/150/185/220 + 已确证等级附加量 + 1.2额外攻击力 + .7法强。');formula(x,'isolated_damage','破灭之锤仅命中单个敌人的伤害',mul(normal,pn('isolated_multiplier')),'通常伤害整体乘1.3/1.35/1.4/1.45/1.5。');damage(x,'normal_damage','破灭之锤通常命中伤害','normal_damage');damage(x,'isolated_damage','破灭之锤单个敌人命中伤害','isolated_damage');
 x.c.proofs.push({source:'QDamage完整角色等级项',raw:x.p.mSpellCalculations.QDamage.mFormulaParts[1],disposition:'未将省略基础数值猜成零'});pending(x,'角色等级项默认值与施法字段','等级项省略初值/初始斜率，spellCastTime=0但mCastTime=.5秒；分别待核，不建立空过程或猜施法时间。','来源');pending(x,'命中数互斥选择与被动叠层','两伤害效果互斥，既有只有一名对手也必须依据真实命中对象集合，不无条件双结算。当前等级附加输入与实际命中规则尚未绑定。');exclude(x,'矩形范围和权杖起点空间执行','伤害保留，空间形状与查找本轮后置。');
}
{
 const x=begin('mordekaiser_w');common(x);data(x,'DamageConversion','dealt_damage_store_ratio','造成伤害的存储比例');data(x,'DamageTakenConversion','taken_damage_store_ratio','承受伤害的存储比例');data(x,'BaseShield','minimum_shield_hp_ratio','最小护盾相对最大生命比例');data(x,'MaxHealthCap','maximum_shield_hp_ratio','最大护盾相对最大生命比例');data(x,'HealingPercent','remaining_shield_heal_ratio','剩余护盾转换治疗比例');
 runtime(x,'actual_released_shield','本次已消费储量对应的初始护盾','只接收合法释放时已确认的实际初始护盾，最小5%与最大30%在捕获时点验证；不能用后来最大生命重新截断该快照。');runtime(x,'actual_remaining_shield','本次再次施放实际剩余护盾','在本次二次施放真实消费该护盾实例前捕获；扣除已吸收伤害与衰减，不使用初始护盾或全部同名护盾。');
 formula(x,'minimum_shield','释放时最小护盾边界参考',mul(pn('minimum_shield_hp_ratio'),attr('hp')),'5%释放时最大生命；用于捕获边界校验，不重算已消费快照。');formula(x,'maximum_shield','释放时最大护盾上限参考',mul(pn('maximum_shield_hp_ratio'),attr('hp')),'30%释放时最大生命。');formula(x,'initial_shield','本次合法释放初始护盾',pn('actual_released_shield'),'原样读取已消费储量的快照，不按后来生命值二次截断。');formula(x,'recast_heal','消耗本次剩余护盾后的治疗',mul(pn('actual_remaining_shield'),pn('remaining_shield_heal_ratio')),'35/37.5/40/42.5/45%本次实际剩余护盾。');heal(x,'recast_heal','不坏之身二次施放自身治疗','recast_heal');
 x.c.proofs.push({source:'当前W.Duration/TimeBeforeDecay/DecayPerSecond/HealthDecay',duration:x.p.DataValues.find(v=>v.name==='Duration'),delay:x.p.DataValues.find(v=>v.name==='TimeBeforeDecay'),rate:x.p.DataValues.find(v=>v.name==='DecayPerSecond'),calculation:x.p.mSpellCalculations.HealthDecay,disposition:'HealthDecay使用基础生命，不据这些字段把护盾强行写成5秒线性归零或固定周期'});pending(x,'储存与护盾衰减的字段对应关系','当前文本只确认护盾持续衰减；HealthDecay基于基础生命，TimeBeforeDecay/DecayPerSecond可能描述储量。未核各阶段曲线和期限归属，不创建NONE或LINEAR_TO_ZERO护盾效果。','来源');pending(x,'储量输入、两次施放与一次性护盾消费','存储量与护盾实例必须分开；第一次消耗已储量、第二次仅消费本次剩余盾，然后治疗一次；暂不建立独立主动过程使治疗凭空可用。');exclude(x,'非英雄伤害储存率降低75%','英雄造成/受到伤害储存保留；不新增非英雄分支。');
}
{
 const x=begin('mordekaiser_e');common(x);data(x,'Damage','base_damage','断魂一扼基础伤害');coeff(x,'TotalDamage',1,'ap_ratio','断魂一扼法强系数');data(x,'MagicPen','magic_penetration_ratio','被动百分比法术穿透');formula(x,'damage','断魂一扼魔法伤害',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),'60/80/100/120/140 + .45法强。');damage(x,'death_grasp_damage','断魂一扼实际命中伤害','damage');hit(x,'death_grasp_damage');
 x.c.proofs.push({source:'当前Cooldown与旧cooldownTime差异',current:x.p.Cooldown,old:x.p.cooldownTime,disposition:'采用当前Cooldown与官方16/14/12/10/8秒，旧18/16/14/12/10不采用'});pending(x,'百分比法穿的独立来源组合','已有百分比属性加算不能证明多个来源按剩余抗性连乘；仅保留5/7.5/10/12.5/15%参数，待独立乘区/游戏穿透规则核对。','系统');pending(x,'命中与P叠层','本体实际命中伤害候选可配置；P对应叠层消费单列，当前没有假施法到命中事件。');exclude(x,'拉拽方向、距离及区域查找','纯强制位移空间分支本轮后置；保留本体伤害与自身穿透。');
}
{
 const x=begin('mordekaiser_r');common(x);data(x,'SpiritRealmDuration','realm_duration_ms','死者领域基础时长（毫秒）',{scale:1000});data(x,'StatStealPercentScalar','stat_steal_ratio','核心属性偷取比例');
 pending(x,'六项偷取属性的基准与双侧恢复','当前扩展已确证法强/攻击力/攻速/护甲/魔抗/最大生命六项与10%，但未明确取总量或基础量、捕获时点及两侧恢复。不能用持续读取目标当前值的双向百分比效果制造反馈；最大生命变化对当前生命的处理也须单独确认。','来源');pending(x,'领域结束与击杀后的跨死亡保留','7秒内目标被击杀后收益保留至目标复活；属于自身战斗依赖，不能按空间分支整体丢弃，也不能固定7秒删除全部偷取收益。');exclude(x,'异次元场地、视觉与其他对象隔离','空间维度本轮后置，偷取与本体属性收益继续待配。');
}
export {plan};
