import {begin,common,data,breaks,literal,formula,pn,attr,add,mul,op,runtime,statEffect,val,fval,damage,processStart,coeff,pending,exclude,hit,plan} from './英雄工具.mjs';
{
 const x=begin('jax_p');breaks(x,'attack_speed_per_stack','每层额外攻速比例',x.p.mSpellCalculations.AttackSpeedPerStack.mFormulaParts[0]);data(x,'BuffDuration','stack_hold_ms','叠层维持时间（毫秒）',{scale:1000});data(x,'MaxStacks','maximum_stacks','普通被动最大层数');
 runtime(x,'current_passive_stacks','当前有效被动层数','仅接受已核实的当前被动层数；层数增加、2.5秒后的消退与刷新由事件/实例输入提供，缺失不填零。','INTEGER');literal(x,'zero','层数下限',0,'层数非负。');
 formula(x,'current_attack_speed','当前有效层数的额外攻速',mul(pn('attack_speed_per_stack'),op('MIN',pn('maximum_stacks'),op('MAX',pn('zero'),pn('current_passive_stacks')))),'每层5%至12.5%，按当前有效层数相加，最多8层。');
 pending(x,'持续动态属性不允许引用计算时输入','passive_attack_speed真实POST400 RUNTIME_INPUT_FORBIDDEN后GET404，已从正常可保存集合撤出；当前PERSISTENT+MOMENT_EVALUATION禁止公式递归引用RUNTIME_INPUT。保留输入与独立公式，不以施加快照或虚构状态绕过。原请求及响应见未保存候选/。','系统');
 pending(x,'被动层数获得、消退与当前输入绑定','本体攻速保留；攻击事件何时增层、FallOffRate=0.35的单位及2.5秒后逐层或整组消退尚缺当前绑定文本完整依据，故未建立周期、计数状态或触发规则。','来源');
 x.c.proofs.push({source:'当前DataValues.FallOffRate',raw:x.p.DataValues.find(v=>v.name==='FallOffRate'),disposition:'字段保留来源；不猜350毫秒消退步长或整组到期'});exclude(x,'卑尔维斯宿敌任务奖励','依赖本轮未建对局任务与第三方事件，普通8层被动保留；不混入奖励叠层。');
}
{
 const x=begin('jax_q');common(x,{cast:true});data(x,'Damage','base_damage','跳斩基础物理伤害');coeff(x,'TotalDamage',1,'bonus_ad_ratio','跳斩额外攻击力系数',{stat:2,kind:2});formula(x,'damage','跳斩物理伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'65/105/145/185/225 + 1.0额外攻击力。');damage(x,'leap_damage','跳斩实际伤害','damage','physics');processStart(x,{delay:true});hit(x,'leap_damage');
 pending(x,'W与Q的一次性附伤联动','Q实际命中只结算本体；W的下次普攻或Q二选一消费仍需共享实例与合法命中顺序，不能两路各发一份附傷。');exclude(x,'跳跃空间及友方/守卫目标','不建立位移和友军分支，保留对敌伤害。');
}
{
 const x=begin('jax_w');common(x);data(x,'Damage','base_damage','蓄力一击基础附加伤害');coeff(x,'TotalDamage',1,'ap_ratio','蓄力一击法强系数');formula(x,'bonus_damage','蓄力一击魔法附伤',add(pn('base_damage'),mul(pn('ap_ratio'),attr('ability_power'))),'50/85/120/155/190 + .6总法强。');damage(x,'empower_bonus_damage','蓄力一击额外魔法伤害','bonus_damage','magic',{description:'下次普攻或跳斩的独立附伤，尚未接入共享一次消费；不叠加普通攻击本体。'});processStart(x);
 pending(x,'下次普攻或跳斩的互斥消费与普攻重置','当前绑定主说明确认两条消费路径，但未给强化保存时间；不借用Q施法时间或别的英雄7秒窗口。尚未建立强化等待过程和任意SKILL_HIT附伤规则。');pending(x,'强化窗口与完整施法耗时','当前root spellCastTime约0.52175秒不足以证明强化输入窗口或实际施放耗时；保留来源，不把该值当延迟。','来源');exclude(x,'建筑伤害50%分支','1V1本体附伤保留，对建筑不新增。');
}
{
 const x=begin('jax_e');common(x);data(x,'BaseDamage','base_damage','反击风暴基础伤害');data(x,'APRatio','bonus_ap_ratio','额外法强系数');data(x,'PercentHealthDamage','target_max_hp_ratio','目标最大生命系数',{scale:.01});data(x,'PercentIncreasedPerDodge','damage_increase_per_dodge','每躲闪一次伤害提升比例');data(x,'MaxDodgesForDamageIncrease','maximum_damage_dodges','参与增伤的最大躲闪次数');data(x,'DodgeDuration','defensive_duration_ms','防御姿态最长时间（毫秒）',{scale:1000});data(x,'StunDuration','stun_duration_ms','眩晕基础时长（毫秒）',{scale:1000});data(x,'AoEDamageReduction','area_skill_reduction_ratio','群体技能伤害减免比例',{scale:.01});
 literal(x,'one','完整伤害倍率',1,'无躲闪时原始伤害100%。');literal(x,'zero','计数下限',0,'次数非负。');runtime(x,'actual_dodged_attacks','本次防御姿态实际躲闪攻击次数','由本次防御姿态实际成功躲闪记录提供；不可用受到伤害次数、未命中施法次数或普通攻击尝试替代。','INTEGER');
 formula(x,'counterstrike_damage','反击风暴本次魔法伤害',mul(add(pn('base_damage'),mul(pn('bonus_ap_ratio'),attr('ability_power','SOURCE','BONUS')),mul(pn('target_max_hp_ratio'),attr('hp','TARGET'))),add(pn('one'),mul(pn('damage_increase_per_dodge'),op('MIN',pn('maximum_damage_dodges'),op('MAX',pn('zero'),pn('actual_dodged_attacks')))))),'40/70/100/130/160 + .7额外法强 + 4%目标最大生命，整体每次躲闪增20%，5次封顶翻倍。');damage(x,'counterstrike_damage','反击风暴实际结算伤害','counterstrike_damage','magic');processStart(x);
 pending(x,'攻击躲闪与群体技能减伤','普通免伤只减少伤害，不等于成功躲闪及攻击附加效果处理；当前过滤字段不能可靠区分群体技能，不用ANY/SKILL冒充范围技能条件。','系统');pending(x,'防御状态的自然/提前结束与一次反击','当前文本确认最多2秒和再次施放可结束；最早重施门槛、躲闪计数输入与一次性结算未接线。不能按固定2秒造命中，也不能因任意提前移除产生反击。');exclude(x,'周围多目标空间与野怪伤害上限','本次对手的完整伤害保留，不新增空间查找和野怪分支。');
}
{
 const x=begin('jax_r');common(x);data(x,'PassiveBaseDamage','passive_base_damage','第三次攻击基础附伤');coeff(x,'OnHitDamage',1,'passive_ap_ratio','被动法强系数');data(x,'PassiveFallOffTime','passive_window_ms','连续攻击计数窗口（毫秒）',{scale:1000});data(x,'Duration','resist_duration_ms','命中英雄后的防御时长（毫秒）',{scale:1000});data(x,'BaseResists','base_armor','命中首名英雄基础护甲');coeff(x,'BaseArmor',1,'armor_bonus_ad_ratio','护甲额外攻击力系数',{stat:2,kind:2});data(x,'MRMult','mr_multiplier','魔抗相对护甲加成倍率');data(x,'SwingDamageBase','active_base_damage','主动挥击基础伤害');coeff(x,'SwingDamageTotal',1,'active_bonus_ap_ratio','主动额外法强系数',{kind:2});literal(x,'normal_attack_threshold','普通被动触发攻击次数',3,'当前根主说明：2.5秒内每第三次攻击。','Spell_JaxRApexForm_Tooltip');literal(x,'empowered_attack_threshold','主动防御期间被动触发攻击次数',2,'命中英雄取得防御期间改为每第二次攻击。','Spell_JaxRApexForm_Tooltip');
 formula(x,'passive_damage','武器大师被动魔法附伤',add(pn('passive_base_damage'),mul(pn('passive_ap_ratio'),attr('ability_power'))),'75/130/185 + .6总法强。');formula(x,'active_damage','武器大师主动魔法伤害',add(pn('active_base_damage'),mul(pn('active_bonus_ap_ratio'),attr('ability_power','SOURCE','BONUS'))),'100/175/250 + 1.0额外法强。');formula(x,'armor_gain','命中首名英雄获得护甲',add(pn('base_armor'),mul(pn('armor_bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'45/60/75 + .4额外攻击力。');formula(x,'magic_resistance_gain','命中首名英雄获得魔抗',mul(add(pn('base_armor'),mul(pn('armor_bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),pn('mr_multiplier')),'BaseMR=BaseArmor*.6，按当前完整修改计算树。');damage(x,'passive_damage','武器大师被动附伤','passive_damage','magic');damage(x,'active_damage','武器大师主动伤害','active_damage','magic');statEffect(x,'armor_gain','武器大师首名英雄护甲',fval('armor_gain'),'armor',{duration:val('resist_duration_ms')});statEffect(x,'magic_resistance_gain','武器大师首名英雄魔抗',fval('magic_resistance_gain'),'magic_resistance',{duration:val('resist_duration_ms')});processStart(x);hit(x,'active_damage');
 pending(x,'命中英雄防御门槛与二/三次攻击联动','本体伤害实际命中规则已配置候选；防御效果仅供确实命中英雄后挂接。被动2.5秒计数、二/三次阈值切换、进入主动前计数如何继承均未接入，不能任何SKILL_HIT无条件加抗性。');pending(x,'施法时间字段冲突','spellCastTime=0，mCastTime=.25秒；不把0当确证无施法时间，仅保留成本冷却过程。','来源');exclude(x,'额外英雄防御叠加、空间范围和建筑分支','本次只有一名对手；保留首名英雄防御和自身被动，不新增额外目标数、建筑50%伤害及空间查找。');
}
export {plan};
