import {begin,common,data,literal,formula,pn,attr,add,mul,op,val,damage,coeff,pending,exclude,heal,statEffect,processStart,evidence,plan} from './英雄工具.mjs';
const passive=evidence.heroes.find(h=>h.id==='Renekton').spells.find(s=>s.slot==='P');
function furyCost(x,phase){const raw=passive.object.mSpell.DataValues.find(v=>v.name==='FuryCost');literal(x,'empowered_fury_cost','强化'+phase+'消耗怒气',raw.values[1],'由当前被动FuryCost=50确证；'+phase+'的合法强化门槛、捕获与扣除必须由真实资源状态提供。',passive.binding+'/DataValues.FuryCost');pending(x,'怒气资源目录与跨技能共享','当前属性目录没有怒气；不能用法力、能量或整数计数替代。低血量有7.5等小数增量，50点门槛和同一施放消费只可执行一次。','系统');}
{
 const x=begin('renekton_p');data(x,'FuryPerAttack','fury_per_attack','普通攻击基础怒气增量');data(x,'FuryIncreasePercent','low_health_fury_increase_ratio','低生命怒气获取提升比例');data(x,'LowHealthPercentThreshold','low_health_threshold','怒气增益生命比例阈值');data(x,'InCombatDuration','combat_hold_ms','当前战斗保持时间字段（毫秒）',{scale:1000});data(x,'FuryCost','empowered_fury_cost','强化基础技能怒气消耗');literal(x,'one','原始怒气倍率',1,'获取提升倍率从1加额外比例。');formula(x,'low_health_attack_fury','低于50%生命时一次普通攻击怒气增量',mul(pn('fury_per_attack'),add(pn('one'),pn('low_health_fury_increase_ratio'))),'5×1.5=7.5，保持小数，不取整。');
 pending(x,'怒气实际资源与跨技能原子消费','当前目录缺怒气，尚未配置资源变化或共享状态。普通攻击与Q/W/E/R的增量叠加、低生命读取时点、50点临界门槛与唯一消费均需接线。','系统');pending(x,'怒气上限及脱战衰减','当前根资源arIncrements50/arMaxSegments2仅是显示分段，不据此证明上限100；当前文本只说脱战衰减，12秒字段未证明衰减每跳数值与节拍。','来源');
}
{
 const x=begin('renekton_q');common(x,{cast:true});furyCost(x,'Q');data(x,'BaseDamage','base_damage','通常巨鳄狂袭基础伤害');data(x,'BaseADRatio','bonus_ad_ratio','通常伤害额外攻击力系数');data(x,'EmpoweredBaseDamage','empowered_base_damage','强化巨鳄狂袭基础伤害');data(x,'EmpoweredADRatio','empowered_bonus_ad_ratio','强化伤害额外攻击力系数');data(x,'ChampHeal','champion_base_heal','命中一名英雄基础治疗');data(x,'ChampionHealADRatio','heal_bonus_ad_ratio','对英雄治疗额外攻击力系数');data(x,'BasicHealCap','normal_heal_cap','通常施放治疗上限');data(x,'EmpoweredHealCap','empowered_heal_cap','强化施放治疗上限');data(x,'EmpoweredHealMultiplier','empowered_heal_multiplier','强化治疗倍率');data(x,'ChampionFuryGain','champion_base_fury','通常命中一名英雄基础怒气');data(x,'FuryGainCap','fury_gain_cap','单次施放怒气获取上限');
 const h=add(pn('champion_base_heal'),mul(pn('heal_bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS')));
 formula(x,'normal_damage','通常巨鳄狂袭伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'60/90/120/150/180 + 1.0额外攻击力。');formula(x,'empowered_damage','强化巨鳄狂袭伤害',add(pn('empowered_base_damage'),mul(pn('empowered_bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'90/135/180/225/270 + 1.4额外攻击力。');formula(x,'normal_champion_heal','通常命中一名英雄的有上限治疗',op('MIN',pn('normal_heal_cap'),h),'12/20/28/36/44 + .17额外攻击力，仍受本次50/75/100/125/150治疗上限限制。');formula(x,'empowered_champion_heal','强化命中一名英雄的有上限治疗',op('MIN',pn('empowered_heal_cap'),mul(h,pn('empowered_heal_multiplier'))),'通常未封顶英雄治疗量×3，再按强化200/300/400/500/600上限截断，不能先套普通上限。');damage(x,'normal_damage','通常巨鳄狂袭伤害','normal_damage','physics');damage(x,'empowered_damage','强化巨鳄狂袭伤害','empowered_damage','physics');heal(x,'normal_champion_heal','通常命中英雄自身治疗','normal_champion_heal');heal(x,'empowered_champion_heal','强化命中英雄自身治疗','empowered_champion_heal');
 pending(x,'怒气档位互斥与命中后治疗/增怒','通常/强化只取其一，真实命中英雄后治疗一次；强化不生成怒气。没有怒气目录与一次消费前，不建无条件伤害或治疗触发，也不靠空施法延迟过程蒙混保存。');exclude(x,'非英雄治疗/怒气与周围多目标','本体一名英雄伤害及自身治疗保留；即使一名对手仍保留高额攻击力下有效的治疗上限。');
}
{
 const x=begin('renekton_w');common(x);furyCost(x,'W');data(x,'BaseDamagePerHit','base_damage_per_hit','每段完整攻击基础伤害');data(x,'TotalADPerHit','total_ad_ratio_per_hit','每段总攻击力倍率');data(x,'StunDuration','normal_stun_ms','通常眩晕时长（毫秒）',{scale:1000});data(x,'EnragedStunDuration','empowered_stun_ms','强化眩晕时长（毫秒）',{scale:1000});data(x,'BuffDuration','attack_window_ms','强化攻击保留时长（毫秒）',{scale:1000});data(x,'BonusFuryVsChamps','extra_fury_vs_champion','通常命中英雄额外怒气');literal(x,'normal_hit_count','通常攻击段数',2,'当前BasicTotalDamage完整修改计算×2，主说明两次打击。','mSpellCalculations.BasicTotalDamage');literal(x,'empowered_hit_count','强化攻击段数',3,'当前EmpTotalDamage完整修改计算×3，主说明三次打击。','mSpellCalculations.EmpTotalDamage');
 const h=add(pn('base_damage_per_hit'),mul(pn('total_ad_ratio_per_hit'),attr('attack_damage')));formula(x,'damage_per_hit','冷酷捕猎未暴击每段完整伤害',h,'5/20/35/50/65 + .75总攻击力；是替代该段普通攻击的完整量，不再加1.0普通攻击本体。');formula(x,'normal_total_damage','通常两段完整伤害',mul(h,pn('normal_hit_count')),'每段完整量×2，仅总量参考，不作为每段重复执行的效果。');formula(x,'empowered_total_damage','强化三段完整伤害',mul(h,pn('empowered_hit_count')),'每段完整量×3，仅总量参考。');damage(x,'noncritical_hit_damage','冷酷捕猎未暴击单段伤害','damage_per_hit','physics',{delivery:'BASIC_ATTACK',block:null,description:'仅已确证未暴击单段算术，完整攻击替换、每段攻击特效与2/3段交付尚未接线，不额外结算普通攻击本体。'});
 pending(x,'二/三段交付、普通攻击本体替换和怒气','当前扩展确认每段各自施加攻击特效；BonusFuryVsChamps=10是额外怒气，不能当全次总增量，普攻被动是否每段获怒仍需核。强化不生成怒气。','来源');pending(x,'先破盾后伤害与眩晕','强化攻击须先摧毁对手伤害护盾；未知完整护盾集合不能用移除一个猜测效果替代，眩晕和法术护盾阻挡期限另有系统缺口。');pending(x,'强化消费与动作窗口','6秒窗口有当前字段，但缺完整共享怒气消费、攻击替换及动作序列；不为表达冷却而创建空过程或假普攻。');exclude(x,'野怪护盾例外','本轮对英雄破盾保留，野怪分支不新增。');
}
{
 const x=begin('renekton_e');common(x,{cast:true});furyCost(x,'E第二次施放');data(x,'BaseDamage','base_damage','通常冲刺基础伤害');data(x,'BaseADRatio','bonus_ad_ratio','通常冲刺额外攻击力系数');data(x,'EnragedBaseDamage','empowered_base_damage','强化第二次冲刺基础伤害');data(x,'EnragedADRatio','empowered_bonus_ad_ratio','强化第二次冲刺额外攻击力系数');data(x,'ChampionRageGeneration','champion_base_fury','通常命中一名英雄基础怒气');data(x,'FuryMax','fury_gain_cap','单次冲刺怒气获取上限');data(x,'DiceTimer','second_cast_window_ms','命中后第二次施放窗口（毫秒）',{scale:1000});data(x,'EnragedArmorShred','armor_reduction_ratio','强化第二次冲刺护甲削减比例',{scale:.01});data(x,'ShredTimer','armor_reduction_duration_ms','护甲削减持续（毫秒）',{scale:1000});
 formula(x,'normal_damage','通常横冲或直撞伤害',add(pn('base_damage'),mul(pn('bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'40/70/100/130/160 + .9额外攻击力。');formula(x,'empowered_damage','强化第二次直撞伤害',add(pn('empowered_base_damage'),mul(pn('empowered_bonus_ad_ratio'),attr('attack_damage','SOURCE','BONUS'))),'70/115/160/205/250 + 1.35额外攻击力。');damage(x,'normal_damage','通常冲刺实际伤害','normal_damage','physics');damage(x,'empowered_damage','强化第二次冲刺实际伤害','empowered_damage','physics');
 pending(x,'两次施放资格和怒气消费','第一次命中至少一名敌人才允许4秒内第二次；只有再次施放能强化与消耗怒气，强化不生成怒气。不能因怒气充足将第一次E也换成强化伤害；实际命中事件须携带合法施放阶段。');pending(x,'独立百分比削甲合并','25/27.5/30/32.5/35%持续4秒参数已确证，当前不能借黑切专属乘区或属性固定减值冒充该来源的百分比削甲。','系统');exclude(x,'沿途空间、冲刺速度和非英雄怒气','本体伤害、第二次施放资格和自身怒气依赖保留。');
}
{
 const x=begin('renekton_r');common(x);data(x,'HealthGain','maximum_health_gain','终极统治最大生命提升');data(x,'AuraDamagePerSecond','base_damage_per_second','光环每秒基础伤害');coeff(x,'TotalDamagePerSecond',1,'ap_ratio_per_second','光环每秒法强系数');coeff(x,'TotalDamagePerSecond',2,'bonus_ad_ratio_per_second','光环每秒额外攻击力系数',{stat:2,kind:2});data(x,'FuryPerSecond','fury_per_second','激活期间每秒怒气');data(x,'FuryOnCast','fury_on_cast','施放时怒气');data(x,'BuffDuration','duration_ms','终极统治持续（毫秒）',{scale:1000});
 formula(x,'aura_damage_per_second','终极统治每秒魔法伤害',add(pn('base_damage_per_second'),mul(pn('ap_ratio_per_second'),attr('ability_power')),mul(pn('bonus_ad_ratio_per_second'),attr('attack_damage','SOURCE','BONUS'))),'60/150/240 + .1法强 + .1额外攻击力是每秒量；不把完整每秒量当每个0.5秒字段的跳伤害。');statEffect(x,'dominance_health','终极统治自身最大生命',val('maximum_health_gain'),'hp',{duration:val('duration_ms'),description:'自身最大生命增加300/500/700，持续15秒；当前生命如何随最大生命变更由资源契约另核，不另送一份等额直接治疗。'});processStart(x,{effects:['dominance_health']});
 x.c.proofs.push({source:'当前TickRate字段',raw:x.p.DataValues.find(v=>v.name==='TickRate'),disposition:'仅字段0.5，未据此决定首次执行时点或伤害/怒气是否共享节拍'});pending(x,'伤害光环和怒气每秒量的实际执行','当前说明明确每秒伤害与5怒气，TickRate=.5不证明首次执行时刻，也不证明两者共用周期。怒气目录仍缺，保留20施放怒气与每秒5参数，不制造法力变化或额外治疗。','系统');pending(x,'生命变更与技能交互','当前先保存15秒最大生命效果与施放开始挂接；当前生命增减策略、P低生命增怒对R各增量的适用及Q范围变化分别待核。');exclude(x,'外形、碰撞体积与Q范围空间变化','不是完整替换技能组；保留自身最大生命、怒气和光环伤害。');
}
export {plan};
