import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url)),mode=process.argv[2];assert(['--apply','--verify',undefined].includes(mode));const plan=JSON.parse(fs.readFileSync(dir+'/写入计划.json')),before=JSON.parse(fs.readFileSync(dir+'/写前保护.json'));const sha=n=>crypto.createHash('sha256').update(fs.readFileSync(dir+'/'+n)).digest('hex');
assert.equal(sha('写入计划.json'),'a0e659be4e7213185960b6da82303b2ff3c025e20989502c324ee6887b021f93');assert.equal(sha('写前保护.json'),'e4ea68a60bf601c9fc3672ee5d4924aaeed354792499c0144c7512289cc0543b');assert.equal(sha('来源与方案.json'),plan.sourceSha256);
const run=new Date().toISOString().replaceAll(':','-'),file=dir+'/'+(mode==='--apply'?'写入':mode==='--verify'?'独立回读':'只读预检')+'-'+run+'.json',rows=[],writes=[];const api='http://127.0.0.1:8080/api/admin/games/lol';
async function request(method,route,body){let row;try{const res=await fetch(api+route,{method,headers:{Authorization:'Bearer local-entry','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});row={at:new Date().toISOString(),method,route,status:res.status,data:await res.json()};}catch(e){row={at:new Date().toISOString(),method,route,status:'UNKNOWN',error:String(e)};}rows.push(row);fs.appendFileSync(file+'.jsonl',JSON.stringify(row)+'\n');return row;}
const strip=x=>{if(Array.isArray(x))return x.map(strip);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).filter(([k])=>!['createdAt','updatedAt','gameId','skillKey'].includes(k)).map(([k,v])=>[k,strip(v)]));return x;};
const array=x=>Array.isArray(x)?x:x.items;
async function verify(after){for(const old of before){const got=await request('GET',old.route);const change=plan.requests.find(r=>r.readRoute===old.route);if(after&&change){assert.equal(got.status,200,old.route);assert.deepEqual(strip(got.data),strip(change.body),old.route);continue;}assert.equal(got.status,old.status,old.route);if(after&&old.route.endsWith('/parameters')){const additions=plan.requests.filter(r=>r.method==='POST'&&r.route===old.route);const expected=array(old.data),actual=array(got.data);assert.equal(actual.length,expected.length+additions.length);for(const p of expected)assert.deepEqual(strip(actual.find(x=>x.parameterKey===p.parameterKey)),strip(p));const keys=[...expected.map(p=>p.parameterKey),...additions.map(r=>r.body.parameterKey)].sort();assert.deepEqual(actual.map(p=>p.parameterKey).sort(),keys);if(!Array.isArray(got.data)&&got.data.total!=null)assert.equal(got.data.total,actual.length);}else if(after&&old.route.startsWith('/equipment-skill-relations?')){const expected=structuredClone(old.data);for(const row of array(expected)){const update=plan.requests.find(r=>r.method==='PUT'&&r.readRoute==='/skills/'+row.skillKey);if(update)row.skillName=update.body.name;}assert.deepEqual(strip(got.data),strip(expected),old.route);}else assert.deepEqual(strip(got.data),strip(old.data),old.route);}}
const lock=dir+'/补录锁.json';let error=null,ownedLock=false;try{if(mode==='--apply'){fs.writeFileSync(lock,JSON.stringify({state:'STARTED',at:new Date().toISOString(),planSha256:sha('写入计划.json')},null,2)+'\n',{flag:'wx'});ownedLock=true;await verify(false);for(const r of plan.requests){const result=await request(r.method,r.route,r.body);const read=await request('GET',r.readRoute);writes.push({method:r.method,route:r.route,status:result.status,readStatus:read.status});assert.equal(typeof result.status,'number','网络失败后须独立恢复核对，不重放');assert(result.status>=200&&result.status<300,JSON.stringify(writes.at(-1)));assert.equal(read.status,200);assert.deepEqual(strip(read.data),strip(r.body));}fs.writeFileSync(lock,JSON.stringify({state:'COMPLETED',at:new Date().toISOString(),planSha256:sha('写入计划.json'),writes:writes.length},null,2)+'\n');}else await verify(mode==='--verify');}catch(e){error=String(e);if(mode==='--apply'&&ownedLock&&fs.existsSync(lock)){const prior=JSON.parse(fs.readFileSync(lock));if(prior.state==='STARTED')fs.writeFileSync(lock,JSON.stringify({...prior,state:'ABORTED',writes:writes.length,error},null,2)+'\n');}}
const report={at:new Date().toISOString(),mode:mode??'--preflight',passed:error===null,GETs:rows.filter(r=>r.method==='GET').length,writes,requests:rows,error,planSha256:sha('写入计划.json'),sourceSha256:plan.sourceSha256};fs.writeFileSync(file,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({file,passed:report.passed,GETs:report.GETs,writes:writes.length,error}));if(error)process.exitCode=1;
