import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
if(process.argv.length>2)throw Error('仅独立GET核算');
const here=path.dirname(fileURLToPath(import.meta.url)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=f=>JSON.parse(fs.readFileSync(path.join(here,f)));
const raw=fs.readFileSync(path.join(here,'最终请求.json'));assert.equal(sha(raw),'536dc79da589dd4e36a7c229a4c983aecf20c720a8be4947047719855ca13623');
const plan=JSON.parse(raw),checks=read('独立核对结果.json'),candidate=read('可审查候选.json'),token=process.env.RUNE3_API_TOKEN;assert.ok(token);
const requests=[],parameters=new Map(),formulas=new Map(),effects=[];
const compare=(actual,expected)=>{if(expected===null||typeof expected!=='object')assert.deepEqual(actual,expected);else if(Array.isArray(expected)){assert.ok(Array.isArray(actual));assert.equal(actual.length,expected.length);expected.forEach((e,i)=>compare(actual[i],e));}else{for(const[k,v]of Object.entries(expected))compare(actual[k],v);}};
async function get(route){const r=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method:'GET',headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)});assert.equal(r.status,200,route);const data=await r.json();requests.push({route,status:r.status,data});return data;}
for(const scope of plan.scope){const rows=await get('/skills/'+scope.skillKey+'/parameters');assert.ok(Array.isArray(rows));parameters.set(scope.id,new Map(rows.map(p=>[p.parameterKey,p])));const expected=plan.requests.filter(p=>p.id===scope.id&&p.kind==='parameter');assert.equal(rows.length,expected.length);for(const e of expected)compare(rows.find(r=>r.parameterKey===e.body.parameterKey),e.body);}
for(const row of plan.requests.filter(p=>p.kind==='formula')){const data=await get(row.readRoute);compare(data,row.body);formulas.set(row.id+'/'+row.body.formulaKey,data);}
for(const row of plan.requests.filter(p=>p.kind==='effect')){const data=await get(row.readRoute);compare(data,row.body);effects.push({skillKey:row.skillKey,effectKey:row.body.effectKey,actual:data});}
function evaluate(id,key,inputs,attributes){const formula=formulas.get(id+'/'+key);assert.ok(formula);const params=parameters.get(id);function calc(n){if(n.nodeType==='PARAMETER'){const p=params.get(n.parameterKey);assert.ok(p);if(p.valueMode==='FIXED')return p.fixedValue;assert.equal(p.valueMode,'RUNTIME_INPUT');assert.equal(p.fixedValue,null);assert.ok(Object.hasOwn(inputs,n.parameterKey),'不能默认缺失输入');if(p.valueType==='INTEGER')assert.ok(Number.isInteger(inputs[n.parameterKey]));return inputs[n.parameterKey];}if(n.nodeType==='ATTRIBUTE'){const key=`${n.attributeOwner}.${n.attributeKey}.${n.attributeValueKind}`;assert.ok(Object.hasOwn(attributes,key));return attributes[key];}assert.equal(n.nodeType,'OPERATION');const[a,b]=n.operands.map(calc);switch(n.operation){case'ADD':return a+b;case'SUBTRACT':return a-b;case'MULTIPLY':return a*b;case'DIVIDE':return a/b;case'MIN':return Math.min(a,b);case'MAX':return Math.max(a,b);default:throw Error(n.operation);}}return calc(formula.expression);}
const cases=[];for(const c of checks.formulaCases){const actual=evaluate(c.id,c.formulaKey,c.inputs,c.attributes);assert.ok(Math.abs(actual-c.expected)<1e-9);cases.push({id:c.id,formulaKey:c.formulaKey,inputs:c.inputs,attributes:c.attributes,sourceExpected:c.expected,actual,passed:true});}
assert.equal(cases.length,29);assert.equal(formulas.size,14);assert.equal(effects.length,3);assert.equal(parameters.get(8451).has('absorption_range'),false);
const sourceChecks=[];for(const p of candidate.proposals)for(const e of p.parameterEvidence.filter(e=>e.sourcePath&&e.parameterKey!=='absorption_range')){const actual=parameters.get(p.id).get(e.parameterKey);assert.equal(actual.valueMode,'FIXED');assert.ok(Math.abs(actual.fixedValue-e.sourceRawValue*e.scale)<Math.max(1e-6,Math.abs(actual.fixedValue)*1e-7));sourceChecks.push({id:p.id,parameterKey:e.parameterKey,rawSourceValue:e.sourceRawValue,scale:e.scale,actualValue:actual.fixedValue,passed:true});}
const runtime=[...parameters.values()].flatMap(map=>[...map.values()]).filter(p=>p.valueMode==='RUNTIME_INPUT');assert.equal(runtime.length,10);for(const p of runtime){assert.equal(p.fixedValue,null);assert.equal(p.levelValues,null);}
const result={at:new Date().toISOString(),mode:'GET_ONLY',finalSha256:sha(raw),summary:{passed:true,gets:requests.length,skills:12,parameters:36,sourceFixedParameters:sourceChecks.length,runtimeInputsWithoutDefault:runtime.length,formulas:formulas.size,formulaCases:cases.length,effects:effects.length,businessWrites:0},requests,cases,sourceChecks,effects,boundary:'只验证实际已存字段、数值与独立候选算例；无触发/完整符文或战斗运行证明。'};
fs.writeFileSync(path.join(here,'实值独立核算.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));
