import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
export const here=new URL('./',import.meta.url),read=n=>readFile(new URL(n,here),'utf8').then(JSON.parse),source=await read('冻结来源.json'),before=await read('当前只读核对.json');
export const clean=n=>Math.round(n*1e6)/1e6,fixed=value=>({kind:'FIXED',value}),pv=parameterKey=>({kind:'PARAMETER',parameterKey}),pn=parameterKey=>({nodeType:'PARAMETER',parameterKey}),op=(operation,...operands)=>({nodeType:'OPERATION',operation,operands});
export function data(o,key){const n=o.object.mDataValues.find(v=>v.mName===key)?.mValue;assert.ok(Number.isFinite(n),o.path+'/'+key);return clean(n);}
export function numberCalc(o,key){const p=o.object.mItemCalculations[key];assert.equal(p.__type,'GameCalculation');assert.equal(p.mFormulaParts.length,1);assert.equal(p.mFormulaParts[0].__type,'NumberCalculationPart');assert.ok(Number.isFinite(p.mFormulaParts[0].mNumber));return p.mFormulaParts[0].mNumber;}
export function base(id,kind,title,description){const o=source.objects.find(x=>x.id===id),live=before.objects.find(x=>x.equipmentKey===o.equipmentKey),key=o.equipmentKey+'_'+kind,rec=route=>live.records.find(r=>r.route===route),equipment=rec('/equipment/'+o.equipmentKey),attrs=rec('/equipment/'+o.equipmentKey+'/attributes'),image=rec('/equipment/'+o.equipmentKey+'/representative-image'),relations=rec('/equipment-skill-relations?equipmentKey='+o.equipmentKey);
 assert.equal(equipment.status,200);assert.equal(attrs.status,200);assert.ok(image.data?.image?.imageKey);assert.deepEqual(live.possibleAliases,[]);assert.equal((relations.data.items??relations.data).length,0);assert.equal(live.skills.find(s=>s.skillKey===key).records[0].status,404,'候选前发现已有技能，须完整比较，不覆盖');
 return {equipmentKey:o.equipmentKey,equipmentName:o.name,skillKey:key,source:{path:o.path,bindings:o.bound,official:o.official,sourceFiles:source.sources},apiPayload:{skill:{skillKey:key,name:o.name+'·'+title,description,maxLevel:1,status:'ENABLED',sortOrder:kind==='passive'?0:10,skillCategoryKeys:kind==='passive'?['passive']:[]},parameters:[],formulas:[],effects:[],processes:[],internalStates:[],triggerRules:[],relation:{equipmentKey:o.equipmentKey,skillKey:key,sortOrder:kind==='passive'?10:20},representativeImage:{imageKey:image.data.image.imageKey}},disposition:{范围外:[],来源待核:[],系统缺口:[],尚未接线:[]},proofs:[],safeguards:{equipment:equipment.data,attributes:attrs.data,representativeImage:image.data,relations:relations.data}};
}
export function param(x,key,name,value,description){assert.ok(Number.isFinite(value));x.apiPayload.parameters.push({parameterKey:key,name,valueType:Number.isInteger(value)?'INTEGER':'DECIMAL',valueMode:'FIXED',fixedValue:value,levelValues:null,description,sortOrder:(x.apiPayload.parameters.length+1)*10});}
export function runtime(x,key,name,description){x.apiPayload.parameters.push({parameterKey:key,name,valueType:'DECIMAL',valueMode:'RUNTIME_INPUT',fixedValue:null,levelValues:null,description,sortOrder:(x.apiPayload.parameters.length+1)*10});}
export function formula(x,key,name,description,expression){x.apiPayload.formulas.push({formulaKey:key,name,description,expression,sortOrder:(x.apiPayload.formulas.length+1)*10});}
export function note(x,kind,component,reason){x.disposition[kind].push({component,reason});}
export function proof(x,pointer,accepted,raw){x.proofs.push({pointer,accepted,raw});}
export function cloneReference(skillKey,suffix){const raw=before.references.find(x=>x.skillKey===skillKey).records.find(r=>r.route.endsWith(suffix))?.data;assert.ok(raw);return structuredClone(Object.fromEntries(Object.entries(raw).filter(([key])=>!['createdAt','updatedAt','skillKey','gameId'].includes(key))));}
export async function output(objects,full){const keys=['parameters','formulas','effects','processes','internalStates','triggerRules'],totals={equipment:new Set(objects.map(o=>o.equipmentKey)).size,skills:objects.length,...Object.fromEntries(keys.map(k=>[k,objects.reduce((n,o)=>n+o.apiPayload[k].length,0)])),relations:objects.length,representativeImages:objects.length};totals.components=Object.entries(totals).filter(([k])=>k!=='equipment').reduce((n,[,v])=>n+v,0);
 const prefix=full?'完整':'前两件',payload={generatedAt:new Date().toISOString(),stage:'仅候选，未调用业务写接口',clientVersion:'16.17',officialVersion:'16.17.1',objects,totals,entryBoundary:'只读前检.mjs 仅 GET；生成候选.mjs 只写本目录文件，没有业务写入入口。',configurationBoundary:'候选的独立效果、参数和公式不表示合法事件、冷却消费、状态或运行时已接线。'},bytes=JSON.stringify(payload,null,2)+'\n';await writeFile(new URL(prefix+'候选.json',here),bytes);const digest={generatedAt:payload.generatedAt,file:prefix+'候选.json',sha256:createHash('sha256').update(bytes).digest('hex'),totals};await writeFile(new URL(prefix+'版本.json',here),JSON.stringify(digest,null,2)+'\n');
 const lines=['# 第十四批常规效果候选','',`本文件为 ${totals.equipment} 件装备、${totals.skills} 个技能槽候选；未调用业务写接口。组成共 ${totals.components} 项，包含主体、关联和代表图关系。`,'',`数量：${JSON.stringify(totals)}`,'','所有原装备直接属性与代表图仅作为保护证据；不重复施加、不覆盖。幽梦的主动与被动分为两个技能槽，均复用同一原装备图片。',''];for(const o of objects){lines.push('## '+o.apiPayload.skill.name,'',o.apiPayload.skill.description,'');for(const [kind,rows]of Object.entries(o.disposition))lines.push('**'+kind+'**：'+(rows.length?rows.map(r=>r.component+'：'+r.reason).join('；'):'当前没有新增记录。'),'');}await writeFile(new URL(prefix+'审查说明.md',here),lines.join('\n')+'\n');console.log(JSON.stringify(digest));return payload;
}
