import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {arithmetic} from './独立核算.mjs';
export const here=new URL('./',import.meta.url),root=new URL('../../',import.meta.url),allowed=[[3142,'passive'],[3142,'active'],[3144,'passive'],[3802,'passive'],[3070,'passive'],[3077,'active']].map(([id,kind])=>({equipmentKey:'item_'+id,skillKey:'item_'+id+'_'+kind})),kinds=[['parameters','parameterKey','parameters'],['formulas','formulaKey','formulas'],['effects','effectKey','effects'],['processes','processKey','processes'],['internalStates','stateKey','internal-states'],['triggerRules','ruleKey','trigger-rules']];
const sha=b=>createHash('sha256').update(b).digest('hex');
export async function load(){const bytes=await readFile(new URL('完整候选.json',here)),plan=JSON.parse(bytes),before=JSON.parse(await readFile(new URL('写前现值.json',here),'utf8'));assert.equal(sha(bytes),'16d826cd8933acf60bfa399b1196a004db90312ec5272ffbb3d8eda8a8cf354c','必须为主负责人授权的独立审查通过版本');assert.deepEqual(plan.objects.map(o=>({equipmentKey:o.equipmentKey,skillKey:o.skillKey})),allowed,'候选必须为五装备六技能，不能越界');return {bytes,plan,before,hash:sha(bytes)};}
export async function unchanged(hash){if(sha(await readFile(new URL('完整候选.json',here)))!==hash)throw Error('候选变化，停止本轮，不重放历史载荷');}
export async function verifySources(){const s=JSON.parse(await readFile(new URL('冻结来源.json',here),'utf8')),checks=[];for(const record of s.sources){if(record.文件){const compressed=await readFile(new URL('装备效果补证/'+record.文件,root)),raw=gunzipSync(compressed);if(sha(compressed)!==record.压缩SHA256||sha(raw)!==record.原始SHA256)throw Error('冻结原文摘要变化');checks.push({file:record.文件,rawSha256:sha(raw),compressedSha256:sha(compressed)});}else{const raw=await readFile(new URL('装备符文/'+record.file,root));if(sha(raw)!==record.sha256)throw Error('官方冻结原文摘要变化');checks.push({file:record.file,sha256:sha(raw)});}}return checks;}
export function makeRequest(allowWrite=false){return async(route,{method='GET',body}={})=>{
 if(method!=='GET'){
  if(!allowWrite)throw Error('默认只读，禁止业务写入');
  const skill=allowed.find(o=>body?.skillKey===o.skillKey),owner=allowed.find(o=>route.startsWith('/skills/'+o.skillKey+'/'));
  const permitted=method==='POST'&&route==='/skills'&&skill||method==='POST'&&route==='/equipment-skill-relations'&&skill&&body.equipmentKey===skill.equipmentKey||method==='POST'&&owner&&kinds.some(([, ,api])=>route==='/skills/'+owner.skillKey+'/'+api)||method==='PUT'&&owner&&route==='/skills/'+owner.skillKey+'/representative-image'&&Object.keys(body??{}).length===1&&typeof body.imageKey==='string';
  if(!permitted)throw Error('禁止覆盖删除或批次外写入');
 }
 const response=await fetch('http://127.0.0.1:8080/api/admin/games/lol'+route,{method,headers:{Authorization:'Bearer local-entry',Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const raw=await response.text();let data;try{data=raw?JSON.parse(raw):null;}catch{throw Error('非JSON响应 '+route+' HTTP '+response.status);}return {route,status:response.status,ok:response.ok,data};
};}
export const get=makeRequest();
function norm(n,key=''){if(Array.isArray(n)){const a=n.map(v=>norm(v));const k={results:'resultKey',actions:'actionKey',steps:'stepKey',conditionGroups:'groupKey',conditions:'conditionKey',effectBindings:'bindingKey'}[key];if(k&&a.every(v=>typeof v?.[k]==='string'))a.sort((x,y)=>(x.sortOrder??0)-(y.sortOrder??0)||x[k].localeCompare(y[k]));return a;}if(n&&typeof n==='object'){const x=Object.fromEntries(Object.entries(n).map(([k,v])=>[k,norm(v,k)]));if(['SKILL_HIT','SKILL_USED'].includes(x.eventType)&&x.detail&&!('useKind'in x.detail))x.detail.useKind=null;return x;}return n;}
export function differences(expected,actual,path='',rows=[]){if(expected===null||actual===null||typeof expected!=='object'||typeof actual!=='object'){rows.push({path,expected,actual,equal:Object.is(expected,actual)});return rows;}if(Array.isArray(expected)||Array.isArray(actual)){rows.push({path:path+'.length',expected:expected.length,actual:actual.length,equal:Array.isArray(expected)&&Array.isArray(actual)&&expected.length===actual.length});for(let i=0;i<Math.max(expected.length??0,actual.length??0);i++)differences(expected[i],actual[i],path+'['+i+']',rows);return rows;}for(const k of [...new Set([...Object.keys(expected),...Object.keys(actual)])].sort())differences(expected[k],actual[k],path?path+'.'+k:k,rows);return rows;}
export const same=(a,b)=>differences(norm(a),norm(b)).every(f=>f.equal);
const list=r=>{if(!r.ok)throw Error(r.route+' HTTP '+r.status);const a=Array.isArray(r.data)?r.data:r.data?.items;if(!Array.isArray(a))throw Error('列表结构不符 '+r.route);return a;};
export function entries(o){const s='/skills/'+o.skillKey,b=o.apiPayload,a=[{kind:'skill',route:s,createRoute:'/skills',method:'POST',expected:b.skill}];for(const[k,id,api]of kinds)for(const body of b[k])a.push({kind:k,route:s+'/'+api+'/'+body[id],createRoute:s+'/'+api,method:'POST',expected:body,idField:id,id:body[id]});a.push({kind:'relation',route:'/equipment-skill-relations?equipmentKey='+o.equipmentKey,createRoute:'/equipment-skill-relations',method:'POST',expected:b.relation},{kind:'image',route:s+'/representative-image',createRoute:s+'/representative-image',method:'PUT',expected:b.representativeImage});return a.map(e=>({...e,equipmentKey:o.equipmentKey,skillKey:o.skillKey}));}
export function compareEntry(o,e,r){if(r.status===404)return {state:'missing',fields:[]};if(!r.ok)return {state:'conflict',fields:[],error:'GET HTTP '+r.status};let expected=e.expected,actual=r.data;
 if(e.kind==='relation'){const a=list(r),permitted=allowed.filter(v=>v.equipmentKey===o.equipmentKey).map(v=>v.skillKey);if(r.data.total!=null&&r.data.total!==a.length)return {state:'conflict',error:'关系未读完整',fields:[]};if(a.some(v=>!permitted.includes(v.skillKey))||new Set(a.map(v=>v.skillKey)).size!==a.length)return {state:'conflict',error:'已存在批次外关系或重复关系，保留全部',fields:[]};actual=a.find(v=>v.skillKey===o.skillKey);if(!actual)return {state:'missing',fields:[]};expected={...expected,equipmentName:o.equipmentName,skillName:o.apiPayload.skill.name,skillStatus:o.apiPayload.skill.status};}
 else if(e.kind==='image'){if(actual?.image==null)return {state:'missing',fields:[]};expected=o.safeguards.representativeImage;}
 if(e.kind!=='image'){if(actual?.gameId!=null&&actual.gameId!=='lol'||actual?.skillKey!=null&&actual.skillKey!==o.skillKey)return {state:'conflict',error:'返回对象归属不符',fields:[]};actual=Object.fromEntries(Object.entries(actual).filter(([k])=>!['gameId','createdAt','updatedAt'].includes(k)&&!(k==='skillKey'&&!['skill','relation'].includes(e.kind))));}
 const fields=differences(norm(expected),norm(actual));return {state:fields.every(f=>f.equal)?'same':'conflict',fields};
}
async function inventory(request){for(let attempt=0;attempt<3;attempt++){const map=new Map();let target=0;for(let page=1;;page++){const r=await request('/skills?page='+page+'&pageSize=200'),a=list(r);target=Math.max(target,r.data.total??a.length);for(const s of a)map.set(s.skillKey,{skillKey:s.skillKey,name:s.name});if(a.length<200||page*200>=target)break;}const confirm=await request('/skills?page=1&pageSize=200');list(confirm);if(map.size===(confirm.data.total??map.size))return [...map.values()];}throw Error('技能目录持续变化未能完整读取，停止当前预检；不写死历史905数量');}
export async function snapshot(plan,before,{request=get}={}){const out={at:new Date().toISOString(),inventory:await inventory(request),catalogs:[],objects:[],conflicts:[],missing:[],sameCount:0,fieldCount:0};
 for(const name of ['attributes','modifier-zones','skill-categories']){const r=await request('/'+name+'?page=1&pageSize=200'),a=list(r);if(r.data.total!=null&&r.data.total!==a.length)throw Error('目录未完整 '+name);out.catalogs.push(r);}
 for(const o of plan.objects){const permitted=allowed.filter(v=>v.equipmentKey===o.equipmentKey).map(v=>v.skillKey),row={equipmentKey:o.equipmentKey,skillKey:o.skillKey,safeguards:[],components:[],lists:[],aliases:out.inventory.filter(s=>!permitted.includes(s.skillKey)&&(s.skillKey.startsWith(o.equipmentKey+'_')||s.skillKey===o.equipmentKey||s.name===o.equipmentName||s.name.startsWith(o.equipmentName+'·')))};out.objects.push(row);if(row.aliases.length)out.conflicts.push({equipmentKey:o.equipmentKey,aliases:row.aliases});
  const original=before.objects.find(x=>x.equipmentKey===o.equipmentKey);for(const route of ['/equipment/'+o.equipmentKey,'/equipment/'+o.equipmentKey+'/attributes','/equipment/'+o.equipmentKey+'/representative-image']){const r=await request(route),expected=original.records.find(v=>v.route===route).data,fields=differences(norm(expected),norm(r.data));row.safeguards.push({...r,fields});out.fieldCount+=fields.length;if(!r.ok||fields.some(f=>!f.equal))out.conflicts.push({equipmentKey:o.equipmentKey,preservedEquipmentChanged:route});}
  const es=entries(o),subject=await request(es[0].route);if(![200,404].includes(subject.status))throw Error('技能主体查询失败');
  for(const e of es){const r=e.kind==='skill'?subject:subject.status===404&&!['relation'].includes(e.kind)?{route:e.route,status:404,ok:false,data:null,inferredFromMissingSubject:true}:await request(e.route),c=compareEntry(o,e,r);row.components.push({...e,...r,...c});out.fieldCount+=c.fields.length;if(c.state==='conflict')out.conflicts.push({equipmentKey:o.equipmentKey,kind:e.kind,route:e.route,fields:c.fields.filter(f=>!f.equal),error:c.error});else if(c.state==='missing')out.missing.push(e);else out.sameCount++;}
  if(subject.ok)for(const[k,id,api]of kinds){const r=await request('/skills/'+o.skillKey+'/'+api),a=list(r),expected=o.apiPayload[k].map(v=>v[id]).sort(),actual=a.map(v=>v[id]).sort();row.lists.push({...r,expectedKeys:expected,actualKeys:actual});if(new Set(actual).size!==actual.length)out.conflicts.push({equipmentKey:o.equipmentKey,kind:k,duplicateKeys:true});for(const key of actual.filter(key=>!expected.includes(key)))out.conflicts.push({equipmentKey:o.equipmentKey,kind:k,unexpectedKey:key});}
  const attrs=list(out.catalogs.find(c=>c.route.startsWith('/attributes'))),zones=list(out.catalogs.find(c=>c.route.startsWith('/modifier-zones')));for(const effect of o.apiPayload.effects)for(const r of effect.results){if(r.detail.attributeKey&&!attrs.some(a=>a.attributeKey===r.detail.attributeKey&&a.status==='ENABLED'))out.conflicts.push({equipmentKey:o.equipmentKey,missingAttribute:r.detail.attributeKey});if(r.detail.modifierZoneKey&&!zones.some(a=>a.modifierZoneKey===r.detail.modifierZoneKey&&a.status==='ENABLED'))out.conflicts.push({equipmentKey:o.equipmentKey,missingZone:r.detail.modifierZoneKey});}
 }
 return out;
}
export async function applyMissing(plan,preflight,{request,assertUnchanged=async()=>{},journal=async()=>{}}){if(preflight.conflicts.length)throw Error('全局预检存在冲突，禁止写入');const events=[],failed=[];const emit=async e=>{const x={at:new Date().toISOString(),...e};events.push(x);await journal(x);};for(const e of preflight.missing){if(failed.includes(e.equipmentKey)){await emit({...e,action:'当前装备暂停，后续依赖跳过'});continue;}await assertUnchanged();const o=plan.objects.find(o=>o.skillKey===e.skillKey&&o.equipmentKey===e.equipmentKey),before=await request(e.route),check=compareEntry(o,e,before);if(check.state==='same'){await emit({...e,action:'写前同值跳过',before});continue;}if(check.state==='conflict')throw Error('写前现值改变，停止整批且不覆盖 '+e.route);
 await assertUnchanged();await emit({...e,action:'准备写入'});let write=null,error=null;try{write=await request(e.createRoute,{method:e.method,body:e.expected});}catch(ex){error=String(ex);}let after=null,getError=null;try{after=await request(e.route);}catch(ex){getError=String(ex);}const result=after?compareEntry(o,e,after):{state:'conflict',fields:[],error:getError},match=result.state==='same';await emit({...e,action:'写后独立GET',write,error,after,result,match});if(!match)failed.push(e.equipmentKey);}
 return {events,failed};}
export function numericChecks(snap){return arithmetic(snap.objects.map(o=>({skillKey:o.skillKey,apiPayload:Object.fromEntries(['parameters','formulas','effects'].map(kind=>[kind,o.components.filter(c=>c.kind===kind&&c.state==='same').map(c=>c.data)]))})));}
