import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {here,source,base,data,numberCalc,clean,param,runtime,formula,note,proof,pn,op,output} from './候选工具.mjs';
if(process.argv.length>2)throw Error('只生成当前固定五装备六技能候选');
const root=id=>source.objects.find(x=>x.id===id),objects=[];
function d(x,id,key,value){const o=root(id),raw=o.object.mDataValues.filter(v=>v.mName===key);assert.ok(raw.length);assert.ok(raw.every(v=>Number.isFinite(v.mValue)&&clean(v.mValue)===value));proof(x,`/Items~1${id}/mDataValues/${key}`,value,raw);}
const ghost=base(3142,'passive','鬼影萦绕','保留非战斗状态下近战20、远程10点固定移速；是否脱战与近远程选择仍待接线，不创建无条件永久移速效果。');
assert.equal(root(3142).object.mItemCalculations.OOCMS.mFormulaParts[0].mDataValue,'{74ac7847}');
assert.equal(root(3142).object.mItemCalculations.OOCMS.mRangedMultiplier.mNumber,0.5);
param(ghost,'melee_out_of_combat_move_speed','近战非战斗固定移速',data(root(3142),'BaseOOCMS'),'当前OOCMS引用BaseOOCMS哈希；单位为固定移速。');
param(ghost,'ranged_out_of_combat_move_speed','远程非战斗固定移速',data(root(3142),'BaseOOCMS')*0.5,'同一OOCMS计算的远程倍率为0.5，20×0.5=10；不采用未绑定模式覆盖。');
d(ghost,3142,'BaseOOCMS',20);proof(ghost,'/Items~13142/mItemCalculations/OOCMS',{melee:20,ranged:10},root(3142).object.mItemCalculations.OOCMS);
note(ghost,'来源待核','非战斗判定','CombatTimer字段为3，但当前绑定说明没有明确其单位、起算和刷新条件，未猜成3000毫秒规则。');
note(ghost,'尚未接线','近远程及脱战门槛','两组固定移速互斥，只有符合非战斗状态时获得，不与装备已有4%移速重复。');objects.push(ghost);
const step=base(3142,'active','鬼魂步伐','保留近战20%/远程15%主动移速与近战6000毫秒持续时间；远程时长按客户端6×0.667秒的独立公式表达，不凭展示取整写为4000毫秒。');
param(step,'melee_move_speed_ratio','近战主动移动速度比例',data(root(3142),'MeleeItemCalcValueB')/100,'绑定动态近战百分数20转换为0.2。');
param(step,'ranged_move_speed_ratio','远程主动移动速度比例',data(root(3142),'RangedItemCalcValueB')/100,'绑定动态远程百分数15转换为0.15。');
const duration=root(3142).object.mItemCalculations.Duration;assert.equal(duration.mFormulaParts[0].mNumber,6);assert.equal(clean(duration.mRangedMultiplier.mNumber),0.667);
param(step,'melee_duration_ms','近战主动持续时间',duration.mFormulaParts[0].mNumber*1000,'当前Duration计算明确6秒，换算6000毫秒。');
param(step,'ranged_duration_multiplier','远程主动持续时间倍率',clean(duration.mRangedMultiplier.mNumber),'原浮点0.6669999957084656按来源小数精度保留0.667；不能改成2/3以得到4秒。');
param(step,'cooldown_ms','主动冷却',data(root(3142),'Cooldown')*1000,'两个同名Cooldown均为45秒，不择取冲突值。');
formula(step,'ranged_duration_ms','远程主动持续时间','6000×0.667=4002毫秒；仅保存独立时长计算，近远程选择未接线。',op('MULTIPLY',pn('melee_duration_ms'),pn('ranged_duration_multiplier')));
proof(step,'/Items~13142/mItemCalculations/Duration',{meleeMs:6000,rangedMultiplier:0.667,rangedMs:4002},duration);
for(const [key,value]of [['MeleeItemCalcValueB',20],['RangedItemCalcValueB',15],['Cooldown',45]])d(step,3142,key,value);
note(step,'范围外','幽灵碰撞与纯空间','不录忽略单位碰撞或空间执行。');note(step,'尚未接线','近远程选择及施放','在没有互斥选择接线前不创建两份同时生效的移速效果；冷却开始和主动过程待补。');objects.push(step);
const slingshot=base(3144,'passive','靶心','保留对英雄伤害触发的40魔法附伤、40秒冷却与攻击减冷却1秒。法术护盾资格和合法事件未明确，不创建未知阻挡粒度的伤害效果。');
param(slingshot,'magic_damage','额外魔法伤害',numberCalc(root(3144),'DamageAmount'),'当前根DamageAmount明确NumberCalculationPart=40。');
param(slingshot,'cooldown_ms','被动冷却',data(root(3144),'Cooldown')*1000,'当前Cooldown=40秒。');
assert.match(root(3144).bound.keyTooltip.text,/攻击可使这个冷却时间缩减1秒/);
param(slingshot,'cooldown_reduction_ms_per_attack','每次符合条件攻击减冷却',1000,'当前绑定中文明确攻击减冷却1秒，具体攻击时点及目标资格另待核。');
proof(slingshot,'/Items~13144/mItemCalculations/DamageAmount',40,root(3144).object.mItemCalculations.DamageAmount);d(slingshot,3144,'Cooldown',40);
note(slingshot,'来源待核','法术护盾与攻击资格','不将法术护盾null当未知，也不凭广义伤害文字认定任意周期、反射、递归伤害或所有攻击均合法。');note(slingshot,'尚未接线','冷却和减冷却','持有者独立冷却、触发消费、攻击减冷却与避免递归等待完整事件依据。');objects.push(slingshot);
const chapter=base(3802,'passive','启蒙','升级时在3秒内回复共20%最大法力。仅保存确定总量与持续时间；最大法力读取时点和首次/后续回复间隔尚未确定，不伪造即时恢复或周期。');
param(chapter,'max_mana_restore_ratio','升级总回复最大法力比例',data(root(3802),'ManaRestorePercent'),'20%以0.2保存，总量不是每秒或每跳量。');
param(chapter,'restoration_duration_ms','升级回复持续时间',data(root(3802),'RestorationDuration')*1000,'当前明确3秒，换算3000毫秒。');
runtime(chapter,'max_mana_for_restoration','本次升级回复使用的最大法力','非负小数输入；应由已核实的本次升级回复取值时点提供最大法力。该时点尚待核，不默认读取每跳现值或缺失为0。');
formula(chapter,'total_mana_restoration','升级总法力回复量','本次确证取值口径的最大法力×0.2；独立总量公式不决定回复跳频或读取时点。',op('MULTIPLY',pn('max_mana_for_restoration'),pn('max_mana_restore_ratio')));
d(chapter,3802,'ManaRestorePercent',0.2);d(chapter,3802,'RestorationDuration',3);note(chapter,'来源待核','回复时序与取值','最大法力取值阶段、每跳间隔、首次时点与重叠升级的处理未确证。');note(chapter,'尚未接线','升级回复','只记录独立总量，不平均分跳、不建瞬时治疗或伪造固定周期。');objects.push(chapter);
const tear=base(3070,'passive','法力流','当前女神之泪说明只写技能命中：每次3最大法力、对英雄翻倍、累计上限360，8秒恢复一份充能、最多4份。保留数值，不从魔宗扩大为普攻也触发。');
for(const [key,name,sourceKey,mult]of [['max_mana_per_hit','每次合法技能命中增加最大法力','ManaPerCharge',1],['max_accumulated_mana','法力流累计最大法力上限','MaxMana',1],['charge_recovery_ms','法力流充能恢复间隔','ManaChargeAmmoCD',1000],['max_charges','法力流最大充能次数','ManaChargeMaxAmmo',1]]){param(tear,key,name,data(root(3070),sourceKey)*mult,`当前根${sourceKey}，${mult===1000?'秒换算毫秒':'保留原单位'}；充能数和累计法力分别记录。`);d(tear,3070,sourceKey,data(root(3070),sourceKey));}
assert.match(root(3070).bound.keyTooltip.text,/技能在命中时/);assert.match(root(3070).bound.keyTooltip.text,/对英雄时翻倍/);
param(tear,'champion_hit_multiplier','英雄命中收益倍率',2,'当前绑定文字明确对英雄翻倍，不扩大普攻资格。');
formula(tear,'champion_hit_max_mana','合法英雄技能命中增加最大法力','3×2=6；资格、同次施法去重、充能消费和累计封顶尚未接线。',op('MULTIPLY',pn('max_mana_per_hit'),pn('champion_hit_multiplier')));
note(tear,'范围外','帮助之手','仅对小兵的普攻附伤与1V1无关，不录入。');note(tear,'来源待核','同次施法与初始充能','InternalCDPerCastID=6.5与缺值TakedownMana不直接推成时限或零；初始充能、同次施法限制需补证。');note(tear,'尚未接线','升级共享累计法力','升级到魔宗/大天使等应核对累计量保留及共享资格，不重置、不重复加240基础法力、不挂含敬畏的整技能。');objects.push(tear);
const tiamat=base(3077,'active','新月','保留主动对单个对手0.75总攻击力物理伤害的独立公式、10秒冷却。旁溅被动不能加在攻击主目标上，主动法术护盾资格与施放时点仍待核。');
param(tiamat,'total_attack_damage_ratio','主动总攻击力比例',data(root(3077),'ActiveADRatio'),'当前PrimaryDamage使用StatByNamedDataValueCalculationPart、mStat=2和ActiveADRatio。');
param(tiamat,'cooldown_ms','新月主动冷却',data(root(3077),'Cooldown')*1000,'当前根Cooldown=10秒。');
const damage=root(3077).object.mItemCalculations.PrimaryDamage;assert.equal(damage.mFormulaParts.length,1);assert.equal(damage.mFormulaParts[0].mStat,2);assert.equal(damage.mFormulaParts[0].mDataValue,'ActiveADRatio');
formula(tiamat,'active_physical_damage','新月主动物理伤害','0.75×自身总攻击力；公式不包含被动旁溅、不结算基础普攻，也未接入主动命中。',op('MULTIPLY',{nodeType:'ATTRIBUTE',attributeOwner:'SOURCE',attributeKey:'attack_damage',attributeValueKind:'TOTAL'},pn('total_attack_damage_ratio')));
proof(tiamat,'/Items~13077/mItemCalculations/PrimaryDamage',{ratio:0.75,attribute:'TOTAL attack_damage'},damage);d(tiamat,3077,'ActiveADRatio',0.75);d(tiamat,3077,'Cooldown',10);
note(tiamat,'范围外','被动旁溅与多目标','攻击邻近额外目标的旁溅分发不属于本轮1V1，不将40%/20%附加给原攻击目标。');note(tiamat,'来源待核','主动护盾资格与时间','护盾阻挡资格及主动施放时间仍需明确；不借未绑定辅助对象覆盖当前根。');note(tiamat,'尚未接线','主动单目标命中','独立伤害公式可先保存，命中与冷却过程不构造假事件。');objects.push(tiamat);
const payload=await output(objects,true);assert.deepEqual(payload.totals,{equipment:5,skills:6,parameters:20,formulas:4,effects:0,processes:0,internalStates:0,triggerRules:0,relations:6,representativeImages:6,components:42});
await writeFile(new URL('舒瑞娅范围待核.json',here),JSON.stringify({equipmentKey:'item_2065',includedInNormalCandidate:false,source:root(2065),determinedValues:{moveSpeedRatio:0.3,durationMs:4000,cooldownMs:75000},reason:'当前绑定只写附近友军，Self施放类型不能单独证明施法者获得增益。保留来源及原装备，不创建参数或技能占位；待明确1V1自用资格后决定补录或排除。'},null,2)+'\n');
