import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const here = path.dirname(fileURLToPath(import.meta.url));
const previous = path.resolve(here, '../技能公共参数第四批');
const selected = ['Briar','Elise','Gnar','Hwei','Jayce','Karma','Kayn','Kled','KSante','LeeSin','Locke','MonkeyKing','Neeko','Nidalee','Qiyana','RekSai','Rengar','Seraphine','Shaco','Shyvana','Taric','Yorick','Yunara','Yuumi','Zaahen','Zeri','Ziggs','Zilean','Zoe','Zyra','Ashe'];
for (const name of ['生成公共参数候选.mjs','录入公共参数.mjs']) assert.equal(fs.existsSync(path.join(here, name)), false, '已准备，不覆盖后续审查：' + name);
let generator = fs.readFileSync(path.join(previous, '生成公共参数候选.mjs'), 'utf8');
generator = generator.replace(/const selected = \[[^\n]+\];/, 'const selected = ' + JSON.stringify(selected) + ';\nconst selectedSlots = {Ashe:["q"]};\nlet visitedSlots = 0;');
generator = generator.replace(/const skipped = \{[\s\S]*?\n\};/, 'const skipped = {};');
generator = generator.replace(/const reviewedOrdinaryCooldowns = new Set\([^\n]+\);/, 'const reviewedOrdinaryCooldowns = new Set([]);');
generator = generator.replace(/const reviewedMixedZeroCosts = new Set\([^\n]+\);/, 'const reviewedMixedZeroCosts = new Set([]);');
generator = generator.replace(/const scopeNotes = \{[\s\S]*?\n\};/, 'const scopeNotes = {};');
generator = generator.replace(/    if \(skillKey === 'belveth_q'\)[^\n]+\n    else if \(complexCooldown\)/, '    if (complexCooldown)');
generator = generator.replace("    const skillKey = `${id.toLowerCase()}_${slot}`;", "    if (selectedSlots[id] && !selectedSlots[id].includes(slot)) continue;\n    visitedSlots++;\n    const skillKey = `${id.toLowerCase()}_${slot}`;");
generator = generator.replace('selectedHeroes: selected,', 'selectedHeroes: selected, selectedSlots,');
generator = generator.replace('slotsVisited: selected.length * 4', 'slotsVisited: visitedSlots');
assert.ok(generator.includes('visitedSlots++') && !generator.includes('belveth_q'));
fs.writeFileSync(path.join(here, '生成公共参数候选.mjs'), generator);
fs.copyFileSync(path.join(previous, '录入公共参数.mjs'), path.join(here, '录入公共参数.mjs'));
console.log(JSON.stringify({ selected, slots: 121, status: '仅准备，未调用业务接口' }));
