import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const saved=path.join(dir,'修正前证据');
assert.ok(!fs.existsSync(saved),'准备只执行一次；已有备份时不得覆盖');
const originalFiles=['README.md','实际体验报告.md','录入候选.json','录入装备技能.mjs','逐字段回读证据.json','独立最终回读.mjs','独立最终回读.json','写入执行记录.json'];
for(const f of originalFiles)assert.ok(fs.existsSync(path.join(dir,f)),f);
fs.mkdirSync(saved);
for(const f of originalFiles)fs.copyFileSync(path.join(dir,f),path.join(saved,f.endsWith('.mjs')?f+'.txt':f));
const batch=JSON.parse(fs.readFileSync(path.join(dir,'录入候选.json'),'utf8'));
assert.equal(batch.objects.length,6);
const item=id=>batch.objects.find(o=>o.equipmentKey==='item_'+id);
const p=parameterKey=>({kind:'PARAMETER',parameterKey});
const fixed=value=>({kind:'FIXED',value});
const addParameter=(o,parameterKey,name,value,description,sortOrder)=>{assert.ok(!o.parameters.some(p=>p.parameterKey===parameterKey));o.parameters.push({parameterKey,name,valueType:Number.isInteger(value)?'INTEGER':'DECIMAL',valueMode:'FIXED',fixedValue:value,levelValues:null,description,sortOrder});};
const navori=item(6675);
assert.equal(navori.effects[0].effectKey,'basic_skill_cooldown_reduction');
navori.effects=[];
navori.skill.description='保存冻结16.17客户端与官方16.17.1确证的每次攻击缩短各基础技能15%剩余冷却比例。当前冷却变化结果按毫秒解释，错误0.15毫秒效果已撤；已有SOURCE结果可指持有者，尚缺各受影响技能剩余冷却比例操作。装备直接属性不重复施加。';
navori.pendingRules=['普通攻击命中动作可用CURRENT_TARGET，结果SOURCE仍指持有者；待正确比例操作补齐后再接普通攻击及合法攻击特效链。'];
navori.pendingEffects=[{effectKey:'basic_skill_cooldown_reduction',resultType:'COOLDOWN_CHANGE',target:'SOURCE',reason:'现有REDUCE按毫秒，0.15不能代替每个受影响技能的剩余冷却乘15%；需最小比例操作或逐技能剩余冷却供值。'}];
const rod=item(6657);
const growth=rod.effects.find(e=>e.effectKey==='timeless_growth');
growth.name='时无限成长层数';growth.description='由十次成长过程每分钟施加一层，最多十层并永久保留各层属性。';
growth.lifecycle={durationValue:null,maxStacksValue:p('timeless_growth_max_stacks'),applicationStacksValue:fixed(1),instanceScope:'SOURCE',reapplicationStackMode:'INCREASE',reapplicationDurationMode:null,expiryMode:'EXPLICIT_ONLY',periodicIntervalValue:null,firstPeriodicExecution:null};
for(const [i,r] of growth.results.entries()){r.lifecycleBehavior={moment:'PERSISTENT',valueReadMode:'APPLICATION_SNAPSHOT',stackValueMode:'PER_STACK',reapplicationValueMode:null,periodicExecutionMode:null};r.detail.modifierZoneKey='attribute_flat_add';r.sortOrder=(i+1)*10;r.description=r.description.replace('周期成长','显式成长');}
rod.processes=[{processKey:'timeless_growth_process',name:'时无限十次成长',activationType:'PASSIVE',description:'初始化后每60000毫秒施加一层，首次等待完整间隔，共执行10次。',sortOrder:10,cooldown:null,steps:[{stepKey:'growth_tick',name:'每分钟成长一层',stepType:'PERIODIC',description:'第1至第10次分别发生在第1至第10分钟。',sortOrder:10,detail:{repeatCountValue:p('timeless_growth_max_stacks'),intervalValue:p('timeless_growth_interval_ms'),firstExecution:'AFTER_INTERVAL'}}],effectBindings:[{bindingKey:'apply_growth',effectKey:'timeless_growth',moment:{momentType:'STEP_EXECUTION',stepKey:'growth_tick'},sortOrder:10}],stateOperations:[]}];
rod.triggerRules=[{ruleKey:'initialize_timeless_growth',name:'初始化时无限十次成长',description:'来源对象初始化时启动一次有界成长过程，满层升级和永恒另行配置。',sortOrder:10,eventSource:{eventType:'SOURCE_INITIALIZED',detail:{}},conditionGroups:[],actions:[{actionKey:'start_timeless_growth',name:'启动时无限十次成长',actionType:'START_PROCESS',sortOrder:10,targetContext:'EVENT_SOURCE',detail:{processKey:'timeless_growth_process'},runtimeInputBindings:[],resultModifiers:[]}],perTargetCooldown:null,maxTriggersPerProcess:null}];
rod.skill.description='保存冻结16.17客户端与官方16.17.1确证的每60秒增加10生命、30法力和3法强，共10次成长并永久保留。原无限周期已改为有界被动过程与显式逐层属性；直接装备属性不重复施加。满层升1级及永恒的减免前英雄伤害回蓝、实际施法消耗治疗仍待接线。';
rod.parameters.find(x=>x.parameterKey==='eternity_mana_restore_ratio').description='收到来自英雄的减免前伤害，回复其10%的法力；基数按当前根绑定扩展说明，英雄来源及伤害值绑定待配。';
addParameter(rod,'eternity_max_heal_per_cast','永恒每次施放治疗上限',20,'当前根EternityMaxHealPerCast与绑定扩展说明确证，每次施放最多治疗20生命。',90);
addParameter(rod,'eternity_sustained_heal_per_second','永恒维持型技能每秒治疗上限',20,'当前绑定扩展说明明确维持型技能每秒最多治疗20生命；不是每次周期都固定治疗20。',100);
rod.pendingRules=['十次成长过程、显式叠层与初始化已配置；本轮不声称战斗运行验证。','满10层提升1级尚无等级变更结果；永恒英雄来源、减免前伤害和实际法力消耗绑定继续配置。'];
rod.pendingEffects[1].reason='25%实际法力消耗治疗、每次20及维持型每秒20上限已有来源；合法消耗绑定和维持型统计待配。';
const edge=item(3814);
edge.effects.push({effectKey:'consume_spell_shield',name:'成功格挡后消耗法术护盾',description:'仅在法术护盾成功阻挡事件中执行，移除本技能的自身护盾。',sortOrder:20,lifecycle:null,results:[{resultKey:'remove_spell_shield',name:'移除已格挡护盾',resultType:'LIFECYCLE_OPERATION',target:'SOURCE',description:null,sortOrder:10,lifecycleBehavior:null,spellShieldBlockScope:null,valueRule:null,detail:{targetEffectKey:'spell_shield',operation:'REMOVE'}}]});
edge.triggerRules.push({ruleKey:'consume_on_successful_block',name:'成功格挡后消耗护盾',description:'法术护盾不自动消费，成功格挡后显式移除；恢复另配。',sortOrder:20,eventSource:{eventType:'SPELL_SHIELD_BLOCKED',detail:{shieldEffectKey:'spell_shield'}},conditionGroups:[],actions:[{actionKey:'consume_shield',name:'消耗本次格挡护盾',actionType:'EXECUTE_EFFECT',sortOrder:10,targetContext:'CURRENT_TARGET',detail:{effectKey:'consume_spell_shield'},runtimeInputBindings:[],resultModifiers:[]}],perTargetCooldown:null,maxTriggersPerProcess:null});
edge.skill.description='保存冻结16.17客户端与官方16.17.1确证的一层法术护盾、40秒冷却及冷却中受到英雄伤害重新起算。已配置初始化与成功阻挡后显式消费；40秒重获与英雄伤害重置规则待接线，直接装备属性不重复施加。';
edge.pendingRules=['初始化及成功阻挡后的显式消费已配置；40秒恢复和冷却中受到英雄伤害重新起算有绑定扩展说明支持，仍待准确接线。'];
const arch=item(3003);
arch.parameters.find(p=>p.parameterKey==='mana_flow_transform_threshold').name='法力流累计增加法力升级阈值';
arch.parameters.find(p=>p.parameterKey==='mana_flow_transform_threshold').description='法力流累计增加360最大法力后升级；不是角色总最大法力达到360，装备自身600法力不计入进度。';
arch.skill.description=arch.skill.description.replace('360最大法力升级阈值','法力流累计增加360最大法力的升级阈值');
arch.pendingRules=arch.pendingRules.map(x=>x.replace('360最大法力','法力流累计增加360最大法力'));
const rift=item(4633);
addParameter(rift,'void_corrosion_melee_omnivamp','虚空腐蚀满强度近战全能吸血比例',0.1,'当前根VampAmountMelee和绑定扩展说明确证满强度近战10%全能吸血。',50);
addParameter(rift,'void_corrosion_ranged_omnivamp','虚空腐蚀满强度远程全能吸血比例',0.06,'当前根VampAmountRanged和绑定扩展说明确证满强度远程6%全能吸血。',60);
rift.skill.description=rift.skill.description.replace('和满层全能吸血数值留待补配','及满强度近战10%/远程6%全能吸血效果留待补配');
rift.pendingRules=rift.pendingRules.filter(x=>!x.includes('数值未')).concat('满强度近战10%/远程6%全能吸血已有来源参数；攻击类型、满层条件及战斗结束清理仍待配置。');
const blood=item(2501);
addParameter(blood,'revenge_remaining_health_threshold','报复达到最高加成的剩余生命比例',0.3,'当前绑定RemainingHealthThreshold计算为1-0.7=0.3，扩展说明明确低于30%生命达到最高12%；中间增长函数尚待补证。',40);
blood.pendingRules=['报复在低于30%剩余生命达到最高12%攻击力已有当前根计算和扩展说明；中间连续增长函数仍未确证，不猜线性关系。'];
blood.skill.description=blood.skill.description.replace('报复的已损失生命完整函数留待补配','报复低于30%剩余生命达到最高12%的边界已补参数，中间增长函数留待补证');
rift.sourceRefs.push({file:'数据参考/全量录入-2026-09/装备效果补证/客户端原始资料/items-16.17.cdtb.bin.json.gz',pointer:'Items/4633/mDataValues/VampAmountMelee,VampAmountRanged',evidence:'当前绑定值近战0.1、远程0.06，与item_4633_activeinventoryextended一致。'});
blood.sourceRefs.push({file:'数据参考/全量录入-2026-09/装备效果补证/客户端原始资料/items-16.17.cdtb.bin.json.gz',pointer:'Items/2501/mItemCalculations/RemainingHealthThreshold',evidence:'当前绑定计算1-MissingHealthThreshold=1-0.7=0.3；item_2501_tooltipextendedrules明确低于30%生命达到最高12%。'});
rod.sourceRefs.push({file:'数据参考/全量录入-2026-09/装备效果补证/客户端原始资料/lol-16.17-zh_CN.stringtable.json.gz',pointer:'entries/item_6657_tooltipextended',evidence:'减免前英雄伤害按10%回蓝；实际施法消耗25%治疗，每次施放上限20，维持型每秒20。'});
edge.sourceRefs.push({file:'数据参考/全量录入-2026-09/装备效果补证/客户端原始资料/lol-16.17-zh_CN.stringtable.json.gz',pointer:'entries/item_3814_tooltipextended',evidence:'装备尚在冷却时受到英雄伤害，冷却重新开始计算。'});
batch.generatedAt=new Date().toISOString();
fs.writeFileSync(path.join(dir,'录入候选.json'),JSON.stringify(batch,null,2)+'\n');
let runner=fs.readFileSync(path.join(dir,'录入装备技能.mjs'),'utf8');
const start=runner.indexOf('const objects = [');const end=runner.indexOf('const sourceFiles = [',start);
assert.ok(start>0&&end>start);
runner=runner.slice(0,start)+"// 当前候选是业务内容唯一输入；旧定义已留在修正前证据，不重放错误效果。\nconst objects = JSON.parse(await readFile(candidatePath, 'utf8')).objects;\n\n"+runner.slice(end);
const triggerLine="  for (const item of object.triggerRules) await writeResource";
assert.equal(runner.split(triggerLine).length,2);
runner=runner.replace(triggerLine,"  for (const item of object.processes ?? []) await writeResource({ kind: `process:${item.processKey}`, path: `${skillPath}/processes/${encodeURIComponent(item.processKey)}`, createPath: `${skillPath}/processes`, body: item, apply, record: record.components });\n"+triggerLine);
runner=runner.replace("effectCount: count('effect:'), triggerRuleCount:","effectCount: count('effect:'), processCount: count('process:'), triggerRuleCount:");
fs.writeFileSync(path.join(dir,'录入装备技能.mjs'),runner);
let verify=fs.readFileSync(path.join(dir,'独立最终回读.mjs'),'utf8');
const ruleLoop='  for (const item of object.triggerRules) {';
assert.equal(verify.split(ruleLoop).length,2);
verify=verify.replace(ruleLoop,"  for (const item of object.processes ?? []) {\n    const path = `${skillPath}/processes/${encodeURIComponent(item.processKey)}`;\n    const read = await request(path);\n    addCheck(path, item, read.data, read.status, `process:${item.processKey}`);\n  }\n"+ruleLoop);
fs.writeFileSync(path.join(dir,'独立最终回读.mjs'),verify);
fs.writeFileSync(path.join(saved,'README.md'),fs.readFileSync(path.join(saved,'README.md'),'utf8')+'\n以上为纠错前历史；不能作为当前验收，旧脚本只保留文本。\n');
console.log(JSON.stringify({prepared:true,objects:batch.objects.length,parameters:batch.objects.reduce((a,o)=>a+o.parameters.length,0)}));
